-- ============================================================================
-- PIN · 017 applies to a database that already has quotations
-- ============================================================================
--
-- WHAT THIS PINS, AND WHY IT IS A SEPARATE FILE.
--
-- 017's SST section adds `sst_rate` and `sst_reason`, back-fills them from
-- `app.resolve_tax_policy()` for every existing row, and only then makes them
-- NOT NULL. On an EMPTY `core.quotations` the back-fill updates nothing and the
-- whole section is trivially fine — which is the state every pin in this
-- directory runs against, and the reason two separate defects survived review
-- and a full green suite:
--
--   1. The `margin_rate` precision guard tested `scale(margin_rate) > 4`.
--      `margin_rate` is GENERATED by a numeric division, so its scale is 20 for
--      every row regardless of value — a margin of exactly 0.41 is stored as
--      0.41000000000000000000. The guard was therefore TRUE FOR EVERY ROW and
--      refused the apply on any database holding one ordinary quotation, while
--      rounding to numeric(6,4) would have lost nothing at all.
--   2. With that cleared, the back-fill UPDATE queued 007's DEFERRABLE constraint
--      triggers on `core.quotations`. They fire at COMMIT, this file is one
--      transaction, and the `SET NOT NULL` that follows hit
--        55006  cannot ALTER TABLE "quotations" because it has pending trigger events
--
-- Both defects share one shape: they are invisible unless a quotation exists
-- BEFORE 017 runs. `test_017` cannot catch them, because it runs after 017 and
-- creates its fixtures afterwards. This file is the missing case.
--
-- ⚠ HOW TO RUN IT. Unlike every other pin here, this one asserts something about
-- the APPLY, not about the applied state, so the harness has to set the state up:
--
--   1. build a database with 001-016 applied,
--   2. insert at least one `core.quotations` row,
--   3. apply 017,
--   4. run this file.
--
-- It refuses rather than passing vacuously if step 2 or 3 was skipped — a pin
-- that silently no-ops when its subject is absent is the failure mode this
-- repo's postmortem catalog is about.
-- ============================================================================

BEGIN;

SET LOCAL plpgsql.check_asserts = on;

DO $preflight$
BEGIN
  IF pg_catalog.to_regclass('core.tax_policies') IS NULL THEN
    RAISE EXCEPTION
      'test_017_applies_over_existing_quotations SETUP FAILURE: 017 is not '
      'applied, so there is nothing to check. Apply it over a 001-016 database '
      'that already holds a quotation, then run this.';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM core.quotations
     WHERE created_at < (SELECT pg_catalog.min(created_at) FROM core.tax_policies))
  THEN
    RAISE EXCEPTION
      'test_017_applies_over_existing_quotations SETUP FAILURE: no quotation '
      'predates 017''s own seeded tax policies, so nothing here was back-filled '
      'and this pin would pass without testing the case it exists for. Insert a '
      'quotation at 001-016 BEFORE applying 017.';
  END IF;
END;
$preflight$;

-- ─── Q1 · every pre-existing quotation was resolved, not defaulted ──────────
DO $q1$
DECLARE
  v_unresolved integer;
  v_zero       integer;
  v_row        record;
BEGIN
  SELECT pg_catalog.count(*) INTO v_unresolved
    FROM core.quotations
   WHERE sst_rate IS NULL OR sst_reason IS NULL;
  ASSERT v_unresolved = 0,
    pg_catalog.format('Q1a FAIL: %s pre-existing quotation(s) still carry a NULL '
      'SST position. The back-fill is what makes SET NOT NULL possible; a NULL '
      'here means it silently matched nothing.', v_unresolved);

  -- The whole point of removing the column defaults: a rate of zero beside
  -- STANDARD_RATED is a taxable service billed at no tax, and it is the exact
  -- pair the defaults used to produce.
  SELECT pg_catalog.count(*) INTO v_zero
    FROM core.quotations
   WHERE sst_reason = 'STANDARD_RATED' AND sst_rate = 0;
  ASSERT v_zero = 0,
    pg_catalog.format('Q1b FAIL: %s quotation(s) are STANDARD_RATED at a rate of '
      'zero. That is the defaulted pair 017 exists to remove, and it reads as a '
      'deliberate zero-tax position on a taxable service.', v_zero);

  FOR v_row IN SELECT id, sst_rate, sst_reason, sst_policy_id FROM core.quotations LOOP
    ASSERT v_row.sst_policy_id IS NOT NULL,
      pg_catalog.format('Q1c FAIL: quotation %s carries a rate with no '
        'sst_policy_id, so nobody can answer "why this rate" in two years.',
        v_row.id);
  END LOOP;

  RAISE NOTICE
    'Q1 PASS - every pre-existing quotation carries a resolved SST position '
    'traceable to the policy row it came from, and none is STANDARD_RATED at zero.';
END;
$q1$;

-- ─── Q2 · the columns really are NOT NULL, which is the statement that failed ─
DO $q2$
DECLARE v_nullable text;
BEGIN
  SELECT pg_catalog.string_agg(column_name, ', ' ORDER BY column_name)
    INTO v_nullable
    FROM information_schema.columns
   WHERE table_schema='core' AND table_name='quotations'
     AND column_name IN ('sst_rate','sst_reason')
     AND is_nullable = 'YES';
  ASSERT v_nullable IS NULL,
    pg_catalog.format('Q2a FAIL: %s is still nullable. The SET NOT NULL is the '
      'statement that raised 55006 against a database with pending trigger '
      'events; if it was quietly dropped to make the apply pass, the tax position '
      'is optional again.', v_nullable);

  ASSERT NOT EXISTS (
    SELECT 1 FROM information_schema.columns
     WHERE table_schema='core' AND table_name='quotations'
       AND column_name IN ('sst_rate','sst_reason')
       AND column_default IS NOT NULL),
    'Q2b FAIL: a default came back on sst_rate or sst_reason. Ruling R-C: SST is '
    'resolved from policy, never defaulted.';

  RAISE NOTICE 'Q2 PASS - both SST columns are NOT NULL with no default.';
END;
$q2$;

-- ─── Q3 · the precision guard lets a lossless value through ─────────────────
-- The guard refuses a margin_rate that numeric(6,4) cannot hold exactly. It used
-- to test `scale() > 4`, which a generated division makes true for everything.
-- If that regressed, 017 would not have applied at all and the preflight above
-- would have failed — so this asserts the narrower thing: the conversion really
-- happened and really was lossless.
DO $q3$
DECLARE v_bad integer;
BEGIN
  ASSERT EXISTS (
    SELECT 1 FROM information_schema.columns
     WHERE table_schema='core' AND table_name='quotations'
       AND column_name='margin_rate'
       AND numeric_precision=6 AND numeric_scale=4),
    'Q3a FAIL: core.quotations.margin_rate is not numeric(6,4).';

  SELECT pg_catalog.count(*) INTO v_bad
    FROM core.quotations
   WHERE margin_rate IS NOT NULL
     AND margin_rate IS DISTINCT FROM pg_catalog.round(margin_rate, 4);
  ASSERT v_bad = 0,
    pg_catalog.format('Q3b FAIL: %s row(s) hold a margin_rate the new type cannot '
      'represent exactly, which means the conversion rounded somebody''s margin '
      'and may have moved it across its floor.', v_bad);

  RAISE NOTICE
    'Q3 PASS - margin_rate is numeric(6,4) and no row lost value in the conversion.';
END;
$q3$;

ROLLBACK;
