-- Wipe the TrainOS fixture world
--
-- Tenant: akademi-perdana (Akademi Perdana Sdn Bhd), id acade111-0000-4000-8000-000000000001
--
-- Run (from the repo root):
--   psql "$DATABASE_URL" -1 -v ON_ERROR_STOP=1 -f supabase/seeds/fixture_world_wipe.sql
--
-- Targets migrations 001-017: the tenant is provisioned by
-- app.provision_tenant() from 016, so this does NOT run against a database at
-- 013 or earlier. 018 adds trg_tenants_z_seed_pipelines on public.tenants,
-- which seeds two default pipelines and their sixteen steps for every tenant
-- with ON CONFLICT (id) DO NOTHING, using the same md5(...) ids this seed
-- computes. Both writers agree on ids, so this seed's DO UPDATE is what sets
-- the fixture tenant's names, whichever one loads first.
--
-- Idempotent: every statement is an upsert guarded by an IS DISTINCT FROM
-- comparison, so a second run of an unchanged seed performs zero updates and
-- leaves every updated_at where it was. Iterating a fixture never needs a wipe,
-- with two exceptions named in supabase/seeds/README.md.
--
-- Removes every row the four fixture_world parts write, in reverse dependency
-- order, for the one tenant. Reset, not rollback: re-running the seed afterwards
-- rebuilds the world from scratch with the same ids.
--
-- Normal iteration does NOT need this. The seed upserts; wipe only when you want
-- to prove the seed builds from nothing, or to hand the database back empty.
--
-- Generated by packages/fixtures/scripts/emit-seed.ts — edit the fixtures or the
-- generator, never this file. Regenerate with:
--   npx tsx packages/fixtures/scripts/emit-seed.ts
-- and `--check` fails if the committed SQL and the fixtures have drifted apart.

-- Suspend the gates for this load; restored at the foot of this file.
ALTER TABLE core.enquiries DISABLE TRIGGER enquiries_state_gate;
ALTER TABLE core.opportunities DISABLE TRIGGER opportunities_state_gate;
ALTER TABLE core.tnas DISABLE TRIGGER tnas_state_gate;
ALTER TABLE core.proposals DISABLE TRIGGER proposals_state_gate;
ALTER TABLE core.quotations DISABLE TRIGGER quotations_state_gate;
ALTER TABLE core.quotations DISABLE TRIGGER trg_quotations_freeze_applied;
ALTER TABLE core.engagements DISABLE TRIGGER engagements_state_gate;
ALTER TABLE core.attendance_days DISABLE TRIGGER attendance_days_state_gate;
ALTER TABLE core.attendance_entries DISABLE TRIGGER trg_attendance_entries_lock;
ALTER TABLE core.compliance_rules DISABLE TRIGGER compliance_rules_state_gate;
ALTER TABLE core.hrdc_packets DISABLE TRIGGER hrdc_packets_state_gate;
ALTER TABLE core.invoices DISABLE TRIGGER invoices_state_gate;
ALTER TABLE core.invoices DISABLE TRIGGER invoices_sync_gate;
ALTER TABLE core.collections_cases DISABLE TRIGGER collections_cases_state_gate;
ALTER TABLE core.events DISABLE TRIGGER events_append_only;
ALTER TABLE app.key_access_audit DISABLE TRIGGER key_access_audit_append_only;
ALTER TABLE core.payments DISABLE TRIGGER trg_a_payments_immutable;
ALTER TABLE core.proposal_sections DISABLE TRIGGER trg_proposal_sections_freeze;

-- Cut the mutual references first; see UNLINK_BEFORE_DELETE in the generator.
UPDATE core.action_requests SET approval_request_id = NULL
 WHERE tenant_id = 'acade111-0000-4000-8000-000000000001' AND approval_request_id IS NOT NULL;

DELETE FROM core.hours_saved_baselines WHERE tenant_id = 'acade111-0000-4000-8000-000000000001';
DELETE FROM core.hours_saved_baseline_tables WHERE tenant_id = 'acade111-0000-4000-8000-000000000001';
DELETE FROM core.metric_definitions WHERE tenant_id = 'acade111-0000-4000-8000-000000000001';
DELETE FROM core.knowledge_sources WHERE tenant_id = 'acade111-0000-4000-8000-000000000001';
DELETE FROM core.run_checkpoints WHERE tenant_id = 'acade111-0000-4000-8000-000000000001';
DELETE FROM core.run_events WHERE tenant_id = 'acade111-0000-4000-8000-000000000001';
DELETE FROM core.run_state_cards WHERE tenant_id = 'acade111-0000-4000-8000-000000000001';
DELETE FROM core.run_snapshots WHERE tenant_id = 'acade111-0000-4000-8000-000000000001';
DELETE FROM core.run_nodes WHERE tenant_id = 'acade111-0000-4000-8000-000000000001';
DELETE FROM core.runs WHERE tenant_id = 'acade111-0000-4000-8000-000000000001';
DELETE FROM core.approval_requests WHERE tenant_id = 'acade111-0000-4000-8000-000000000001';
DELETE FROM core.action_requests WHERE tenant_id = 'acade111-0000-4000-8000-000000000001';
DELETE FROM app.usage_rollup WHERE tenant_id = 'acade111-0000-4000-8000-000000000001';
DELETE FROM core.ai_budgets WHERE tenant_id = 'acade111-0000-4000-8000-000000000001';
DELETE FROM core.ai_provider_keys WHERE tenant_id = 'acade111-0000-4000-8000-000000000001';
DELETE FROM core.jury_configs WHERE tenant_id = 'acade111-0000-4000-8000-000000000001';
DELETE FROM core.routing_entries WHERE tenant_id = 'acade111-0000-4000-8000-000000000001';
DELETE FROM core.routing_matrix_versions WHERE tenant_id = 'acade111-0000-4000-8000-000000000001';
DELETE FROM core.evals WHERE tenant_id = 'acade111-0000-4000-8000-000000000001';
DELETE FROM core.autonomy_grants WHERE tenant_id = 'acade111-0000-4000-8000-000000000001';
DELETE FROM core.agents WHERE tenant_id = 'acade111-0000-4000-8000-000000000001';
DELETE FROM core.model_tiers WHERE tenant_id = 'acade111-0000-4000-8000-000000000001';
DELETE FROM core.tier_keys WHERE tenant_id = 'acade111-0000-4000-8000-000000000001';
DELETE FROM core.collections_cases WHERE tenant_id = 'acade111-0000-4000-8000-000000000001';
DELETE FROM core.collection_rules WHERE tenant_id = 'acade111-0000-4000-8000-000000000001';
DELETE FROM core.aging_buckets WHERE tenant_id = 'acade111-0000-4000-8000-000000000001';
DELETE FROM core.invoice_sync_entries WHERE tenant_id = 'acade111-0000-4000-8000-000000000001';
DELETE FROM core.payments WHERE tenant_id = 'acade111-0000-4000-8000-000000000001';
DELETE FROM core.invoice_lines WHERE tenant_id = 'acade111-0000-4000-8000-000000000001';
DELETE FROM core.invoices WHERE tenant_id = 'acade111-0000-4000-8000-000000000001';
DELETE FROM core.hrdc_levy_statements WHERE tenant_id = 'acade111-0000-4000-8000-000000000001';
DELETE FROM core.hrdc_packet_documents WHERE tenant_id = 'acade111-0000-4000-8000-000000000001';
DELETE FROM core.hrdc_packets WHERE tenant_id = 'acade111-0000-4000-8000-000000000001';
DELETE FROM core.hrdc_document_types WHERE tenant_id = 'acade111-0000-4000-8000-000000000001';
DELETE FROM core.rule_change_affected_engagements WHERE tenant_id = 'acade111-0000-4000-8000-000000000001';
DELETE FROM core.rule_changes WHERE tenant_id = 'acade111-0000-4000-8000-000000000001';
DELETE FROM core.rule_change_sets WHERE tenant_id = 'acade111-0000-4000-8000-000000000001';
DELETE FROM core.compliance_version_drifts WHERE tenant_id = 'acade111-0000-4000-8000-000000000001';
DELETE FROM core.compliance_check_results WHERE tenant_id = 'acade111-0000-4000-8000-000000000001';
DELETE FROM core.compliance_rules WHERE tenant_id = 'acade111-0000-4000-8000-000000000001';
DELETE FROM core.certificates WHERE tenant_id = 'acade111-0000-4000-8000-000000000001';
DELETE FROM core.attendance_entries WHERE tenant_id = 'acade111-0000-4000-8000-000000000001';
DELETE FROM core.attendance_days WHERE tenant_id = 'acade111-0000-4000-8000-000000000001';
DELETE FROM core.participants WHERE tenant_id = 'acade111-0000-4000-8000-000000000001';
DELETE FROM core.sessions WHERE tenant_id = 'acade111-0000-4000-8000-000000000001';
DELETE FROM core.engagement_trainers WHERE tenant_id = 'acade111-0000-4000-8000-000000000001';
DELETE FROM core.engagement_checklist_items WHERE tenant_id = 'acade111-0000-4000-8000-000000000001';
DELETE FROM core.engagement_step_states WHERE tenant_id = 'acade111-0000-4000-8000-000000000001';
DELETE FROM core.engagements WHERE tenant_id = 'acade111-0000-4000-8000-000000000001';
DELETE FROM core.rule_set_versions WHERE tenant_id = 'acade111-0000-4000-8000-000000000001';
DELETE FROM core.outbound_messages WHERE tenant_id = 'acade111-0000-4000-8000-000000000001';
DELETE FROM core.follow_ups WHERE tenant_id = 'acade111-0000-4000-8000-000000000001';
DELETE FROM core.portal_comments WHERE tenant_id = 'acade111-0000-4000-8000-000000000001';
DELETE FROM core.portal_acceptances WHERE tenant_id = 'acade111-0000-4000-8000-000000000001';
DELETE FROM core.public_share_tokens WHERE tenant_id = 'acade111-0000-4000-8000-000000000001';
DELETE FROM core.quotation_lines WHERE tenant_id = 'acade111-0000-4000-8000-000000000001';
DELETE FROM core.quotations WHERE tenant_id = 'acade111-0000-4000-8000-000000000001';
DELETE FROM core.proposal_sections WHERE tenant_id = 'acade111-0000-4000-8000-000000000001';
DELETE FROM core.proposals WHERE tenant_id = 'acade111-0000-4000-8000-000000000001';
DELETE FROM core.tna_recommendations WHERE tenant_id = 'acade111-0000-4000-8000-000000000001';
DELETE FROM core.tna_evidence WHERE tenant_id = 'acade111-0000-4000-8000-000000000001';
DELETE FROM core.tna_constraints WHERE tenant_id = 'acade111-0000-4000-8000-000000000001';
DELETE FROM core.tna_gaps WHERE tenant_id = 'acade111-0000-4000-8000-000000000001';
DELETE FROM core.tnas WHERE tenant_id = 'acade111-0000-4000-8000-000000000001';
DELETE FROM core.opportunities WHERE tenant_id = 'acade111-0000-4000-8000-000000000001';
DELETE FROM core.enquiry_extraction_fields WHERE tenant_id = 'acade111-0000-4000-8000-000000000001';
DELETE FROM core.enquiries WHERE tenant_id = 'acade111-0000-4000-8000-000000000001';
DELETE FROM core.rate_card_discount_authorities WHERE tenant_id = 'acade111-0000-4000-8000-000000000001';
DELETE FROM core.rate_card_margin_floors WHERE tenant_id = 'acade111-0000-4000-8000-000000000001';
DELETE FROM core.rate_card_travel WHERE tenant_id = 'acade111-0000-4000-8000-000000000001';
DELETE FROM core.rate_card_venues WHERE tenant_id = 'acade111-0000-4000-8000-000000000001';
DELETE FROM core.rate_card_materials WHERE tenant_id = 'acade111-0000-4000-8000-000000000001';
DELETE FROM core.rate_card_trainer_days WHERE tenant_id = 'acade111-0000-4000-8000-000000000001';
DELETE FROM core.rate_cards WHERE tenant_id = 'acade111-0000-4000-8000-000000000001';
DELETE FROM core.saved_views WHERE tenant_id = 'acade111-0000-4000-8000-000000000001';
DELETE FROM core.templates WHERE tenant_id = 'acade111-0000-4000-8000-000000000001';
DELETE FROM core.organisation_suggestions WHERE tenant_id = 'acade111-0000-4000-8000-000000000001';
DELETE FROM core.contact_consents WHERE tenant_id = 'acade111-0000-4000-8000-000000000001';
DELETE FROM core.contacts WHERE tenant_id = 'acade111-0000-4000-8000-000000000001';
DELETE FROM core.organisation_health_snapshots WHERE tenant_id = 'acade111-0000-4000-8000-000000000001';
DELETE FROM core.organisations WHERE tenant_id = 'acade111-0000-4000-8000-000000000001';
DELETE FROM core.programme_materials WHERE tenant_id = 'acade111-0000-4000-8000-000000000001';
DELETE FROM core.programme_trainers WHERE tenant_id = 'acade111-0000-4000-8000-000000000001';
DELETE FROM core.programme_pricing_tiers WHERE tenant_id = 'acade111-0000-4000-8000-000000000001';
DELETE FROM core.programmes WHERE tenant_id = 'acade111-0000-4000-8000-000000000001';
DELETE FROM core.pipeline_steps WHERE tenant_id = 'acade111-0000-4000-8000-000000000001';
DELETE FROM core.pipelines WHERE tenant_id = 'acade111-0000-4000-8000-000000000001';
DELETE FROM core.check_keys WHERE tenant_id = 'acade111-0000-4000-8000-000000000001';
DELETE FROM core.action_policies WHERE tenant_id = 'acade111-0000-4000-8000-000000000001';
DELETE FROM core.ref_formats WHERE tenant_id = 'acade111-0000-4000-8000-000000000001';
DELETE FROM public.team_members WHERE tenant_id = 'acade111-0000-4000-8000-000000000001';
DELETE FROM public.memberships WHERE tenant_id = 'acade111-0000-4000-8000-000000000001';
DELETE FROM core.trainers WHERE tenant_id = 'acade111-0000-4000-8000-000000000001';
DELETE FROM public.teams WHERE tenant_id = 'acade111-0000-4000-8000-000000000001';
DELETE FROM public.user_profiles WHERE tenant_id = 'acade111-0000-4000-8000-000000000001';
-- The seven humans and the eight agent principals, by id.
DELETE FROM auth.users WHERE id IN (
  'acade111-0001-4000-8000-000000000002',
  'acade111-0001-4000-8000-000000000003',
  'acade111-0001-4000-8000-000000000004',
  'acade111-0001-4000-8000-000000000005',
  'acade111-0001-4000-8000-000000000001',
  'acade111-0001-4000-8000-000000000006',
  'acade111-0001-4000-8000-000000000007',
  '22480065-8fe4-5ca9-b7ba-41102d750d65',
  'c104277c-cedb-5574-96a4-c92699ea4515',
  '3643f0fa-1a31-5a5e-b9ce-b68cbb3d1f3b',
  'c37e813e-e16b-54e9-aaaa-d3dfd8bf77df',
  'fd79eafd-1db7-50da-82e5-c3505ef94a95',
  'c6cccdec-44f9-58e8-ae16-d7763efd7be3',
  '81f09789-93aa-51f4-a114-5d284802c9ae',
  'd1cfaa81-a6b6-55dd-880c-261b1e978865'
);
DELETE FROM public.tenants WHERE id = 'acade111-0000-4000-8000-000000000001';

-- Flush the deferred reconciliation checks before touching these tables:
-- ALTER TABLE refuses a table that has pending trigger events. The flush is
-- also where the header-equals-sum-of-lines checks actually run.
SET CONSTRAINTS core.trg_quotation_reconciled, core.trg_quotation_floor, core.trg_invoice_reconciled, core.trg_credit_note_within_invoice IMMEDIATE;
SET CONSTRAINTS core.trg_quotation_reconciled, core.trg_quotation_floor, core.trg_invoice_reconciled, core.trg_credit_note_within_invoice DEFERRED;

-- Gates restored. test_fixture_world.sql asserts this happened.
ALTER TABLE core.enquiries ENABLE TRIGGER enquiries_state_gate;
ALTER TABLE core.opportunities ENABLE TRIGGER opportunities_state_gate;
ALTER TABLE core.tnas ENABLE TRIGGER tnas_state_gate;
ALTER TABLE core.proposals ENABLE TRIGGER proposals_state_gate;
ALTER TABLE core.quotations ENABLE TRIGGER quotations_state_gate;
ALTER TABLE core.quotations ENABLE TRIGGER trg_quotations_freeze_applied;
ALTER TABLE core.engagements ENABLE TRIGGER engagements_state_gate;
ALTER TABLE core.attendance_days ENABLE TRIGGER attendance_days_state_gate;
ALTER TABLE core.attendance_entries ENABLE TRIGGER trg_attendance_entries_lock;
ALTER TABLE core.compliance_rules ENABLE TRIGGER compliance_rules_state_gate;
ALTER TABLE core.hrdc_packets ENABLE TRIGGER hrdc_packets_state_gate;
ALTER TABLE core.invoices ENABLE TRIGGER invoices_state_gate;
ALTER TABLE core.invoices ENABLE TRIGGER invoices_sync_gate;
ALTER TABLE core.collections_cases ENABLE TRIGGER collections_cases_state_gate;
ALTER TABLE core.events ENABLE TRIGGER events_append_only;
ALTER TABLE app.key_access_audit ENABLE TRIGGER key_access_audit_append_only;
ALTER TABLE core.payments ENABLE TRIGGER trg_a_payments_immutable;
ALTER TABLE core.proposal_sections ENABLE TRIGGER trg_proposal_sections_freeze;
