-- TrainOS fixture world, part 1 — Tenant, principals, reference formats, pipelines, catalogue and parties
--
-- Tenant: akademi-perdana (Akademi Perdana Sdn Bhd), id acade111-0000-4000-8000-000000000001
--
-- Run (all four parts, one transaction, from the repo root):
--   psql "$DATABASE_URL" -1 -v ON_ERROR_STOP=1 \
--     -f supabase/seeds/fixture_world_01_tenant_and_parties.sql \
--     -f supabase/seeds/fixture_world_02_sales_and_money.sql \
--     -f supabase/seeds/fixture_world_03_delivery_compliance_finance.sql \
--     -f supabase/seeds/fixture_world_04_ai_ops_and_agents.sql
--
-- Targets migrations 001-017 (and 018 when it merges): the tenant is
-- provisioned by app.provision_tenant() from 016, so this does NOT run
-- against a database at 013 or earlier.
--
-- Idempotent: every statement is an upsert guarded by an IS DISTINCT FROM
-- comparison, so a second run of an unchanged seed performs zero updates and
-- leaves every updated_at where it was. Iterating a fixture never needs a wipe,
-- with two exceptions named in supabase/seeds/README.md.
--
-- One of the four parts of the TrainOS fixture world. The parts are in
-- foreign-key order and must be run in order:
--
--   1. fixture_world_01_tenant_and_parties.sql
--   2. fixture_world_02_sales_and_money.sql
--   3. fixture_world_03_delivery_compliance_finance.sql
--   4. fixture_world_04_ai_ops_and_agents.sql
--
-- Companion files:
--   fixture_world_wipe.sql         removes every row the four parts write, tenant included
--   test_fixture_world.sql         the pin: counts, landmarks, re-run stability
--
-- Fixed ids. Anchors are hand-picked and carry a version-4 nibble; every other
-- row's id is UUIDv5 over its fixture key in namespace
-- 6ee0a1de-0000-4000-8000-7421a1d05eed, and carries a version-5 nibble.
--
--   tnt_akademi_perdana    acade111-0000-4000-8000-000000000001
--   u_lim                  acade111-0001-4000-8000-000000000001
--   u_amirah               acade111-0001-4000-8000-000000000002
--   u_kelvin               acade111-0001-4000-8000-000000000003
--   u_siti                 acade111-0001-4000-8000-000000000004
--   u_jason                acade111-0001-4000-8000-000000000005
--   u_khairul              acade111-0001-4000-8000-000000000006
--   t_farah                acade111-0001-4000-8000-000000000007
--   org_aurora             acade111-0002-4000-8000-000000000114
--   org_aurora_precision   acade111-0002-4000-8000-000000000115
--   org_kenanga            acade111-0002-4000-8000-000000000121
--   org_meridian           acade111-0002-4000-8000-000000000128
--   org_sutera             acade111-0002-4000-8000-000000000133
--   org_perdana_utilities  acade111-0002-4000-8000-000000000140
--   ent_eng_0259           acade111-0005-4000-8000-000000000259
--
-- Generated by packages/fixtures/scripts/emit-seed.ts — edit the fixtures or the
-- generator, never this file. Regenerate with:
--   npx tsx packages/fixtures/scripts/emit-seed.ts
-- and `--check` fails if the committed SQL and the fixtures have drifted apart.

-- Tenant ──────────────────────────────────────────────────────────────────

-- Tenant, provisioned by 016.
DO $provision$
DECLARE
  v_tenant CONSTANT uuid := 'acade111-0000-4000-8000-000000000001';
  v_id     uuid;
BEGIN
  IF NOT EXISTS (SELECT 1 FROM public.tenants WHERE id = v_tenant) THEN
    v_id := app.provision_tenant(
              'akademi-perdana', 'Akademi Perdana Sdn Bhd', 'Asia/Kuala_Lumpur', v_tenant);
    IF v_id IS DISTINCT FROM v_tenant THEN
      RAISE EXCEPTION
        'fixture_world: app.provision_tenant returned %, not the id it was given. '
        'Every row in this seed carries the fixed id as a literal.', v_id;
    END IF;
  END IF;

  -- The fixture's own detail, and re-runnable in the same sense as every other
  -- statement in this pack: an unchanged fixture updates nothing.
  UPDATE public.tenants
     SET name       = 'Akademi Perdana Sdn Bhd',
         status     = 'ACTIVE',
         timezone   = 'Asia/Kuala_Lumpur',
         locale     = 'en-MY',
         created_at = '2022-01-04T09:00:00+08:00'
   WHERE id = v_tenant
     AND (name, status, timezone, locale, created_at)
         IS DISTINCT FROM ('Akademi Perdana Sdn Bhd', 'ACTIVE', 'Asia/Kuala_Lumpur',
                           'en-MY', '2022-01-04T09:00:00+08:00'::timestamptz);
END
$provision$;

-- Principals ──────────────────────────────────────────────────────────────

-- The seven principals, as auth records.
-- Every tenancy table in `public` has a composite FK into auth.users, so a seed
-- that skips this cannot write a membership, an organisation owner, or a trainer.
-- On a hosted project these rows would come from the auth admin API instead; the
-- columns written here are the ones GoTrue itself fills for a confirmed user.
INSERT INTO auth.users AS target
  (id, aud, role, email, raw_app_meta_data, raw_user_meta_data, created_at)
VALUES
  ('acade111-0001-4000-8000-000000000002', 'authenticated', 'authenticated', 'amirah.yusof@akademiperdana.my', '{"provider":"email","providers":["email"]}'::jsonb, '{"full_name":"Amirah Yusof"}'::jsonb, '2022-01-04T09:00:00+08:00'),
  ('acade111-0001-4000-8000-000000000003', 'authenticated', 'authenticated', 'kelvin.tan@akademiperdana.my', '{"provider":"email","providers":["email"]}'::jsonb, '{"full_name":"Kelvin Tan"}'::jsonb, '2022-01-04T09:00:00+08:00'),
  ('acade111-0001-4000-8000-000000000004', 'authenticated', 'authenticated', 'siti.nordin@akademiperdana.my', '{"provider":"email","providers":["email"]}'::jsonb, '{"full_name":"Siti Nordin"}'::jsonb, '2022-01-04T09:00:00+08:00'),
  ('acade111-0001-4000-8000-000000000005', 'authenticated', 'authenticated', 'jason.lee@akademiperdana.my', '{"provider":"email","providers":["email"]}'::jsonb, '{"full_name":"Jason Lee"}'::jsonb, '2022-01-04T09:00:00+08:00'),
  ('acade111-0001-4000-8000-000000000001', 'authenticated', 'authenticated', 'alex.selvarajah@akademiperdana.my', '{"provider":"email","providers":["email"]}'::jsonb, '{"full_name":"Alex Selvarajah"}'::jsonb, '2022-01-04T09:00:00+08:00'),
  ('acade111-0001-4000-8000-000000000006', 'authenticated', 'authenticated', 'khairul.anwar@akademiperdana.my', '{"provider":"email","providers":["email"]}'::jsonb, '{"full_name":"Khairul Anwar"}'::jsonb, '2022-01-04T09:00:00+08:00'),
  ('acade111-0001-4000-8000-000000000007', 'authenticated', 'authenticated', 'farah.aziz@akademiperdana.my', '{"provider":"email","providers":["email"]}'::jsonb, '{"full_name":"Farah Aziz"}'::jsonb, '2022-01-04T09:00:00+08:00')
ON CONFLICT (id) DO UPDATE SET
  aud = EXCLUDED.aud,
  role = EXCLUDED.role,
  email = EXCLUDED.email,
  raw_app_meta_data = EXCLUDED.raw_app_meta_data,
  raw_user_meta_data = EXCLUDED.raw_user_meta_data
WHERE (target.aud, target.role, target.email, target.raw_app_meta_data, target.raw_user_meta_data)
   IS DISTINCT FROM (EXCLUDED.aud, EXCLUDED.role, EXCLUDED.email, EXCLUDED.raw_app_meta_data, EXCLUDED.raw_user_meta_data);

-- One auth principal per agent, for core.agents.principal_user_id.
-- Derived from the agent, because the fixture world names no service account.
INSERT INTO auth.users AS target
  (id, aud, role, email, raw_app_meta_data, raw_user_meta_data, created_at)
VALUES
  ('22480065-8fe4-5ca9-b7ba-41102d750d65', 'authenticated', 'authenticated', 'agent_lead@agents.akademiperdana.my', '{"provider":"agent","providers":["agent"],"agentId":"agent_lead"}'::jsonb, '{"full_name":"Lead Agent"}'::jsonb, '2022-01-04T09:00:00+08:00'),
  ('c104277c-cedb-5574-96a4-c92699ea4515', 'authenticated', 'authenticated', 'agent_match@agents.akademiperdana.my', '{"provider":"agent","providers":["agent"],"agentId":"agent_match"}'::jsonb, '{"full_name":"Match Agent"}'::jsonb, '2022-01-04T09:00:00+08:00'),
  ('3643f0fa-1a31-5a5e-b9ce-b68cbb3d1f3b', 'authenticated', 'authenticated', 'agent_tna@agents.akademiperdana.my', '{"provider":"agent","providers":["agent"],"agentId":"agent_tna"}'::jsonb, '{"full_name":"TNA Agent"}'::jsonb, '2022-01-04T09:00:00+08:00'),
  ('c37e813e-e16b-54e9-aaaa-d3dfd8bf77df', 'authenticated', 'authenticated', 'agent_proposal@agents.akademiperdana.my', '{"provider":"agent","providers":["agent"],"agentId":"agent_proposal"}'::jsonb, '{"full_name":"Proposal Agent"}'::jsonb, '2022-01-04T09:00:00+08:00'),
  ('fd79eafd-1db7-50da-82e5-c3505ef94a95', 'authenticated', 'authenticated', 'agent_followup@agents.akademiperdana.my', '{"provider":"agent","providers":["agent"],"agentId":"agent_followup"}'::jsonb, '{"full_name":"Follow-up Agent"}'::jsonb, '2022-01-04T09:00:00+08:00'),
  ('c6cccdec-44f9-58e8-ae16-d7763efd7be3', 'authenticated', 'authenticated', 'agent_collections@agents.akademiperdana.my', '{"provider":"agent","providers":["agent"],"agentId":"agent_collections"}'::jsonb, '{"full_name":"Collections Agent"}'::jsonb, '2022-01-04T09:00:00+08:00'),
  ('81f09789-93aa-51f4-a114-5d284802c9ae', 'authenticated', 'authenticated', 'agent_compliance@agents.akademiperdana.my', '{"provider":"agent","providers":["agent"],"agentId":"agent_compliance"}'::jsonb, '{"full_name":"Compliance Agent"}'::jsonb, '2022-01-04T09:00:00+08:00'),
  ('d1cfaa81-a6b6-55dd-880c-261b1e978865', 'authenticated', 'authenticated', 'agent_knowledge@agents.akademiperdana.my', '{"provider":"agent","providers":["agent"],"agentId":"agent_knowledge"}'::jsonb, '{"full_name":"Knowledge Agent"}'::jsonb, '2022-01-04T09:00:00+08:00')
ON CONFLICT (id) DO UPDATE SET
  aud = EXCLUDED.aud,
  role = EXCLUDED.role,
  email = EXCLUDED.email,
  raw_app_meta_data = EXCLUDED.raw_app_meta_data,
  raw_user_meta_data = EXCLUDED.raw_user_meta_data
WHERE (target.aud, target.role, target.email, target.raw_app_meta_data, target.raw_user_meta_data)
   IS DISTINCT FROM (EXCLUDED.aud, EXCLUDED.role, EXCLUDED.email, EXCLUDED.raw_app_meta_data, EXCLUDED.raw_user_meta_data);

INSERT INTO public.user_profiles AS target
  (tenant_id, user_id, display_name, email, locale, timezone, theme, avatar_url, created_at)
VALUES
  ('acade111-0000-4000-8000-000000000001', 'acade111-0001-4000-8000-000000000002', 'Amirah Yusof', 'amirah.yusof@akademiperdana.my', 'en-MY', 'Asia/Kuala_Lumpur', 'LIGHT', NULL, '2022-01-04T09:00:00+08:00'),
  ('acade111-0000-4000-8000-000000000001', 'acade111-0001-4000-8000-000000000003', 'Kelvin Tan', 'kelvin.tan@akademiperdana.my', 'en-MY', 'Asia/Kuala_Lumpur', 'LIGHT', NULL, '2022-01-04T09:00:00+08:00'),
  ('acade111-0000-4000-8000-000000000001', 'acade111-0001-4000-8000-000000000004', 'Siti Nordin', 'siti.nordin@akademiperdana.my', 'en-MY', 'Asia/Kuala_Lumpur', 'LIGHT', NULL, '2022-01-04T09:00:00+08:00'),
  ('acade111-0000-4000-8000-000000000001', 'acade111-0001-4000-8000-000000000005', 'Jason Lee', 'jason.lee@akademiperdana.my', 'en-MY', 'Asia/Kuala_Lumpur', 'LIGHT', NULL, '2022-01-04T09:00:00+08:00'),
  ('acade111-0000-4000-8000-000000000001', 'acade111-0001-4000-8000-000000000001', 'Alex Selvarajah', 'alex.selvarajah@akademiperdana.my', 'en-MY', 'Asia/Kuala_Lumpur', 'DARK', NULL, '2022-01-04T09:00:00+08:00'),
  ('acade111-0000-4000-8000-000000000001', 'acade111-0001-4000-8000-000000000006', 'Khairul Anwar', 'khairul.anwar@akademiperdana.my', 'en-MY', 'Asia/Kuala_Lumpur', 'DARK', NULL, '2022-01-04T09:00:00+08:00'),
  ('acade111-0000-4000-8000-000000000001', 'acade111-0001-4000-8000-000000000007', 'Farah Aziz', 'farah.aziz@akademiperdana.my', 'en-MY', 'Asia/Kuala_Lumpur', 'LIGHT', NULL, '2022-01-04T09:00:00+08:00')
ON CONFLICT (tenant_id, user_id) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  email = EXCLUDED.email,
  locale = EXCLUDED.locale,
  timezone = EXCLUDED.timezone,
  theme = EXCLUDED.theme,
  avatar_url = EXCLUDED.avatar_url
WHERE (target.display_name, target.email, target.locale, target.timezone, target.theme, target.avatar_url)
   IS DISTINCT FROM (EXCLUDED.display_name, EXCLUDED.email, EXCLUDED.locale, EXCLUDED.timezone, EXCLUDED.theme, EXCLUDED.avatar_url);

-- One team: `dataScope.teams = MY_TEAM` has to resolve to a row.
INSERT INTO public.teams AS target
  (id, tenant_id, name, manager_user_id, created_at)
VALUES
  ('4d1338ad-b508-5223-a697-88592c6db773', 'acade111-0000-4000-8000-000000000001', 'Akademi Perdana', 'acade111-0001-4000-8000-000000000003', '2022-01-04T09:00:00+08:00')
ON CONFLICT (id) DO UPDATE SET
  tenant_id = EXCLUDED.tenant_id,
  name = EXCLUDED.name,
  manager_user_id = EXCLUDED.manager_user_id
WHERE (target.tenant_id, target.name, target.manager_user_id)
   IS DISTINCT FROM (EXCLUDED.tenant_id, EXCLUDED.name, EXCLUDED.manager_user_id);

-- Four trainers. TRN-0007 is Farah Aziz, who also holds a TRAINER membership.
--
-- hrd_tdf_valid_to is a FIXTURE CONVENTION, not a fact the fixture world states.
-- 017 requires an expiry wherever hrd_tdf is true, because an accredited trainer
-- with no expiry is the row that keeps getting scheduled after the accreditation
-- lapses. The fixture gives one expiry per trainer -- the TTT certificate's --
-- and the same three trainers hold both accreditations, so the seed reuses it
-- rather than inventing a second date. See T2h, which pins the convention so that
-- real TDF dates arriving in the fixture fail rather than sit unnoticed.
-- hrd_tdf_ref stays NULL: a registry number is the one thing that would be
-- fabricated evidence rather than fixture detail.
INSERT INTO core.trainers AS target
  (id, tenant_id, ref, name, email, phone, user_id, band, day_rate_override_sen, ttt_certified, ttt_ref, ttt_valid_to, hrd_tdf, hrd_tdf_valid_to, hrd_tdf_ref, rating, status, created_at, created_by_kind, created_by_id, created_by_name)
VALUES
  ('0b54f9a4-0d8c-59d9-b39a-1ada4dea58db', 'acade111-0000-4000-8000-000000000001', 'TRN-0007', 'Farah Aziz', 'farah.aziz@akademiperdana.my', NULL, 'acade111-0001-4000-8000-000000000007', 'A', NULL, TRUE, 'TTT-2019-4471', '2027-06-30', TRUE, '2027-06-30', NULL, 4.7, 'ACTIVE', '2022-01-04T09:00:00+08:00', 'HUMAN', 'u_khairul', 'Khairul Anwar'),
  ('1baefe97-f97b-50a1-ba80-55ecfc180eb7', 'acade111-0000-4000-8000-000000000001', 'TRN-0012', 'Daniel Wong', 'daniel.wong@akademiperdana.my', NULL, NULL, 'A', NULL, TRUE, 'TTT-2021-8830', '2028-01-31', TRUE, '2028-01-31', NULL, 4.4, 'ACTIVE', '2022-01-04T09:00:00+08:00', 'HUMAN', 'u_khairul', 'Khairul Anwar'),
  ('ad2d1197-0023-5fe3-a16b-cac09ad90f95', 'acade111-0000-4000-8000-000000000001', 'TRN-0019', 'Lee Chin Hoe', 'lee.chinhoe@akademiperdana.my', NULL, NULL, 'B', NULL, TRUE, 'TTT-2022-1174', '2027-11-30', TRUE, '2027-11-30', NULL, 4.2, 'ACTIVE', '2022-01-04T09:00:00+08:00', 'HUMAN', 'u_khairul', 'Khairul Anwar'),
  ('31bd1a52-678b-57a4-bdde-aefb0db000fc', 'acade111-0000-4000-8000-000000000001', 'TRN-0024', 'Noora Idris', 'noora.idris@akademiperdana.my', NULL, NULL, 'C', NULL, FALSE, NULL, NULL, FALSE, NULL, NULL, 4, 'ACTIVE', '2022-01-04T09:00:00+08:00', 'HUMAN', 'u_khairul', 'Khairul Anwar')
ON CONFLICT (id) DO UPDATE SET
  tenant_id = EXCLUDED.tenant_id,
  name = EXCLUDED.name,
  email = EXCLUDED.email,
  phone = EXCLUDED.phone,
  user_id = EXCLUDED.user_id,
  band = EXCLUDED.band,
  day_rate_override_sen = EXCLUDED.day_rate_override_sen,
  ttt_certified = EXCLUDED.ttt_certified,
  ttt_ref = EXCLUDED.ttt_ref,
  ttt_valid_to = EXCLUDED.ttt_valid_to,
  hrd_tdf = EXCLUDED.hrd_tdf,
  hrd_tdf_valid_to = EXCLUDED.hrd_tdf_valid_to,
  hrd_tdf_ref = EXCLUDED.hrd_tdf_ref,
  rating = EXCLUDED.rating,
  status = EXCLUDED.status,
  created_by_kind = EXCLUDED.created_by_kind,
  created_by_id = EXCLUDED.created_by_id,
  created_by_name = EXCLUDED.created_by_name
WHERE (target.tenant_id, target.name, target.email, target.phone, target.user_id, target.band, target.day_rate_override_sen, target.ttt_certified, target.ttt_ref, target.ttt_valid_to, target.hrd_tdf, target.hrd_tdf_valid_to, target.hrd_tdf_ref, target.rating, target.status, target.created_by_kind, target.created_by_id, target.created_by_name)
   IS DISTINCT FROM (EXCLUDED.tenant_id, EXCLUDED.name, EXCLUDED.email, EXCLUDED.phone, EXCLUDED.user_id, EXCLUDED.band, EXCLUDED.day_rate_override_sen, EXCLUDED.ttt_certified, EXCLUDED.ttt_ref, EXCLUDED.ttt_valid_to, EXCLUDED.hrd_tdf, EXCLUDED.hrd_tdf_valid_to, EXCLUDED.hrd_tdf_ref, EXCLUDED.rating, EXCLUDED.status, EXCLUDED.created_by_kind, EXCLUDED.created_by_id, EXCLUDED.created_by_name);

-- Roles and data scopes, straight off `users[].role` and `users[].dataScope`.
INSERT INTO public.memberships AS target
  (tenant_id, user_id, role, actor_kind, agent_id, primary_team_id, trainer_id, client_scope, team_scope, mfa_required, status, is_default, created_at)
VALUES
  ('acade111-0000-4000-8000-000000000001', 'acade111-0001-4000-8000-000000000002', 'SALES', 'HUMAN', NULL, '4d1338ad-b508-5223-a697-88592c6db773', NULL, 'MY_ACCOUNTS', 'MY_TEAM', FALSE, 'ACTIVE', TRUE, '2022-01-04T09:00:00+08:00'),
  ('acade111-0000-4000-8000-000000000001', 'acade111-0001-4000-8000-000000000003', 'SALES_MANAGER', 'HUMAN', NULL, '4d1338ad-b508-5223-a697-88592c6db773', NULL, 'MY_TEAM', 'MY_TEAM', FALSE, 'ACTIVE', TRUE, '2022-01-04T09:00:00+08:00'),
  ('acade111-0000-4000-8000-000000000001', 'acade111-0001-4000-8000-000000000004', 'OPS', 'HUMAN', NULL, '4d1338ad-b508-5223-a697-88592c6db773', NULL, 'ALL', 'MY_TEAM', FALSE, 'ACTIVE', TRUE, '2022-01-04T09:00:00+08:00'),
  ('acade111-0000-4000-8000-000000000001', 'acade111-0001-4000-8000-000000000005', 'FINANCE', 'HUMAN', NULL, '4d1338ad-b508-5223-a697-88592c6db773', NULL, 'ALL', 'ALL', FALSE, 'ACTIVE', TRUE, '2022-01-04T09:00:00+08:00'),
  ('acade111-0000-4000-8000-000000000001', 'acade111-0001-4000-8000-000000000001', 'MD', 'HUMAN', NULL, '4d1338ad-b508-5223-a697-88592c6db773', NULL, 'ALL', 'ALL', TRUE, 'ACTIVE', TRUE, '2022-01-04T09:00:00+08:00'),
  ('acade111-0000-4000-8000-000000000001', 'acade111-0001-4000-8000-000000000006', 'ADMIN', 'HUMAN', NULL, '4d1338ad-b508-5223-a697-88592c6db773', NULL, 'ALL', 'ALL', TRUE, 'ACTIVE', TRUE, '2022-01-04T09:00:00+08:00'),
  ('acade111-0000-4000-8000-000000000001', 'acade111-0001-4000-8000-000000000007', 'TRAINER', 'HUMAN', NULL, '4d1338ad-b508-5223-a697-88592c6db773', '0b54f9a4-0d8c-59d9-b39a-1ada4dea58db', 'MY_ACCOUNTS', 'MY_TEAM', FALSE, 'ACTIVE', TRUE, '2022-01-04T09:00:00+08:00')
ON CONFLICT (tenant_id, user_id) DO UPDATE SET
  role = EXCLUDED.role,
  actor_kind = EXCLUDED.actor_kind,
  agent_id = EXCLUDED.agent_id,
  primary_team_id = EXCLUDED.primary_team_id,
  trainer_id = EXCLUDED.trainer_id,
  client_scope = EXCLUDED.client_scope,
  team_scope = EXCLUDED.team_scope,
  mfa_required = EXCLUDED.mfa_required,
  status = EXCLUDED.status,
  is_default = EXCLUDED.is_default
WHERE (target.role, target.actor_kind, target.agent_id, target.primary_team_id, target.trainer_id, target.client_scope, target.team_scope, target.mfa_required, target.status, target.is_default)
   IS DISTINCT FROM (EXCLUDED.role, EXCLUDED.actor_kind, EXCLUDED.agent_id, EXCLUDED.primary_team_id, EXCLUDED.trainer_id, EXCLUDED.client_scope, EXCLUDED.team_scope, EXCLUDED.mfa_required, EXCLUDED.status, EXCLUDED.is_default);

INSERT INTO public.team_members AS target
  (tenant_id, team_id, user_id)
VALUES
  ('acade111-0000-4000-8000-000000000001', '4d1338ad-b508-5223-a697-88592c6db773', 'acade111-0001-4000-8000-000000000002'),
  ('acade111-0000-4000-8000-000000000001', '4d1338ad-b508-5223-a697-88592c6db773', 'acade111-0001-4000-8000-000000000003'),
  ('acade111-0000-4000-8000-000000000001', '4d1338ad-b508-5223-a697-88592c6db773', 'acade111-0001-4000-8000-000000000004'),
  ('acade111-0000-4000-8000-000000000001', '4d1338ad-b508-5223-a697-88592c6db773', 'acade111-0001-4000-8000-000000000005'),
  ('acade111-0000-4000-8000-000000000001', '4d1338ad-b508-5223-a697-88592c6db773', 'acade111-0001-4000-8000-000000000001'),
  ('acade111-0000-4000-8000-000000000001', '4d1338ad-b508-5223-a697-88592c6db773', 'acade111-0001-4000-8000-000000000006'),
  ('acade111-0000-4000-8000-000000000001', '4d1338ad-b508-5223-a697-88592c6db773', 'acade111-0001-4000-8000-000000000007')
ON CONFLICT (team_id, user_id) DO UPDATE SET
  tenant_id = EXCLUDED.tenant_id
WHERE target.tenant_id IS DISTINCT FROM EXCLUDED.tenant_id;

-- Pipeline configuration ──────────────────────────────────────────────────

-- Stage names and order are configuration, never hardcoded: this is the row the
-- UI renders from. Ids are md5(tenant_id::text || 'pipeline:' || object)::uuid,
-- the derivation the 018 lane's stage seed computes in SQL, so either pack may
-- write these rows and both produce the same id. See lib/ids.ts.
INSERT INTO core.pipelines AS target
  (id, tenant_id, ref, object, name, is_default, version, status, created_at, created_by_kind, created_by_id, created_by_name)
VALUES
  ('3e97773b-effa-398c-2509-d5a19388c3c3', 'acade111-0000-4000-8000-000000000001', 'PIP-0001', 'ENGAGEMENT', 'Engagement lifecycle', TRUE, 1, 'ACTIVE', '2022-01-04T09:00:00+08:00', 'HUMAN', 'u_khairul', 'Khairul Anwar'),
  ('095ef670-c9a6-9036-477e-4c4668fbced0', 'acade111-0000-4000-8000-000000000001', 'PIP-0002', 'OPPORTUNITY', 'Opportunity lifecycle', TRUE, 1, 'ACTIVE', '2022-01-04T09:00:00+08:00', 'HUMAN', 'u_khairul', 'Khairul Anwar')
ON CONFLICT (id) DO UPDATE SET
  tenant_id = EXCLUDED.tenant_id,
  object = EXCLUDED.object,
  name = EXCLUDED.name,
  is_default = EXCLUDED.is_default,
  version = EXCLUDED.version,
  status = EXCLUDED.status,
  created_by_kind = EXCLUDED.created_by_kind,
  created_by_id = EXCLUDED.created_by_id,
  created_by_name = EXCLUDED.created_by_name
WHERE (target.tenant_id, target.object, target.name, target.is_default, target.version, target.status, target.created_by_kind, target.created_by_id, target.created_by_name)
   IS DISTINCT FROM (EXCLUDED.tenant_id, EXCLUDED.object, EXCLUDED.name, EXCLUDED.is_default, EXCLUDED.version, EXCLUDED.status, EXCLUDED.created_by_kind, EXCLUDED.created_by_id, EXCLUDED.created_by_name);

-- Ids are md5(tenant_id::text || 'pipeline:' || object || ':' || step_key)::uuid.
-- The object is in the name because WON is a stage of BOTH pipelines, and
-- core.pipeline_steps is unique on (tenant_id, pipeline_id, step_key) rather
-- than on step_key alone, so the two rows are legitimate and a shared id would
-- be a primary key violation. See lib/ids.ts.
--
-- `outcome` (WON/LOST on the two terminal opportunity stages) has no column
-- yet -- see the PR's schema-gap list.
INSERT INTO core.pipeline_steps AS target
  (id, tenant_id, pipeline_id, step_key, label, position, terminal, blocking_check_keys, created_at)
VALUES
  ('373f74b3-51ff-99d9-d30d-83c76ec3a56a', 'acade111-0000-4000-8000-000000000001', '3e97773b-effa-398c-2509-d5a19388c3c3', 'WON', 'Won', 1, FALSE, '{}'::text[], '2022-01-04T09:00:00+08:00'),
  ('75e8b03e-3507-886d-73af-3404bacb9ddd', 'acade111-0000-4000-8000-000000000001', '3e97773b-effa-398c-2509-d5a19388c3c3', 'TRAINER_CONFIRMED', 'Trainer confirmed', 2, FALSE, '{}'::text[], '2022-01-04T09:00:00+08:00'),
  ('b527c150-ba17-a790-12fb-acc8afd6665a', 'acade111-0000-4000-8000-000000000001', '3e97773b-effa-398c-2509-d5a19388c3c3', 'SCHEDULED', 'Scheduled', 3, FALSE, '{}'::text[], '2022-01-04T09:00:00+08:00'),
  ('c4eae41d-f4d8-ed21-b47d-38787f8c74ae', 'acade111-0000-4000-8000-000000000001', '3e97773b-effa-398c-2509-d5a19388c3c3', 'REGISTERED', 'Registered', 4, FALSE, '{}'::text[], '2022-01-04T09:00:00+08:00'),
  ('f9bbc905-53fa-da47-0903-f4e9b6b7340a', 'acade111-0000-4000-8000-000000000001', '3e97773b-effa-398c-2509-d5a19388c3c3', 'DELIVERED', 'Delivered', 5, FALSE, '{}'::text[], '2022-01-04T09:00:00+08:00'),
  ('52459c66-b37b-7af8-2706-5c2033c97c0c', 'acade111-0000-4000-8000-000000000001', '3e97773b-effa-398c-2509-d5a19388c3c3', 'ATTENDANCE_LOCKED', 'Attendance locked', 6, FALSE, '{}'::text[], '2022-01-04T09:00:00+08:00'),
  ('37310240-c006-f409-c3d8-554b1c6bdde3', 'acade111-0000-4000-8000-000000000001', '3e97773b-effa-398c-2509-d5a19388c3c3', 'HRDC_CLAIM', 'HRDC claim', 7, FALSE, '{}'::text[], '2022-01-04T09:00:00+08:00'),
  ('0ec4d10c-6f91-bb36-357e-85b4840c417f', 'acade111-0000-4000-8000-000000000001', '3e97773b-effa-398c-2509-d5a19388c3c3', 'INVOICED', 'Invoiced', 8, FALSE, '{}'::text[], '2022-01-04T09:00:00+08:00'),
  ('2eb8e328-57d0-e1a9-2965-02ffa5401866', 'acade111-0000-4000-8000-000000000001', '3e97773b-effa-398c-2509-d5a19388c3c3', 'PAID', 'Paid', 9, TRUE, '{}'::text[], '2022-01-04T09:00:00+08:00'),
  ('f6020e09-abd2-bedb-0582-9e95ec3a79de', 'acade111-0000-4000-8000-000000000001', '095ef670-c9a6-9036-477e-4c4668fbced0', 'NEW', 'New', 1, FALSE, '{}'::text[], '2022-01-04T09:00:00+08:00'),
  ('b2253c79-438d-c8ca-95f8-3fa762b999dc', 'acade111-0000-4000-8000-000000000001', '095ef670-c9a6-9036-477e-4c4668fbced0', 'QUALIFYING', 'Qualifying', 2, FALSE, '{}'::text[], '2022-01-04T09:00:00+08:00'),
  ('69e9ac2a-7ced-3a52-aeec-74659d1b113d', 'acade111-0000-4000-8000-000000000001', '095ef670-c9a6-9036-477e-4c4668fbced0', 'TNA_SENT', 'TNA sent', 3, FALSE, '{}'::text[], '2022-01-04T09:00:00+08:00'),
  ('faa55a15-0102-7d5a-28e9-e829acb8d04c', 'acade111-0000-4000-8000-000000000001', '095ef670-c9a6-9036-477e-4c4668fbced0', 'PROPOSAL_SENT', 'Proposal sent', 4, FALSE, '{}'::text[], '2022-01-04T09:00:00+08:00'),
  ('dd26c806-16ce-adf5-0c67-68eb27db103d', 'acade111-0000-4000-8000-000000000001', '095ef670-c9a6-9036-477e-4c4668fbced0', 'NEGOTIATION', 'Negotiation', 5, FALSE, '{}'::text[], '2022-01-04T09:00:00+08:00'),
  ('361edf63-dc3f-59bd-2a07-27e5bc04489d', 'acade111-0000-4000-8000-000000000001', '095ef670-c9a6-9036-477e-4c4668fbced0', 'WON', 'Won', 6, TRUE, '{}'::text[], '2022-01-04T09:00:00+08:00'),
  ('7e4ce44a-418e-6d95-5882-e7eb8d412d05', 'acade111-0000-4000-8000-000000000001', '095ef670-c9a6-9036-477e-4c4668fbced0', 'LOST', 'Lost', 7, TRUE, '{}'::text[], '2022-01-04T09:00:00+08:00')
ON CONFLICT (tenant_id, pipeline_id, step_key) DO UPDATE SET
  id = EXCLUDED.id,
  label = EXCLUDED.label,
  position = EXCLUDED.position,
  terminal = EXCLUDED.terminal,
  blocking_check_keys = EXCLUDED.blocking_check_keys
WHERE (target.id, target.label, target.position, target.terminal, target.blocking_check_keys)
   IS DISTINCT FROM (EXCLUDED.id, EXCLUDED.label, EXCLUDED.position, EXCLUDED.terminal, EXCLUDED.blocking_check_keys);

-- Catalogue ───────────────────────────────────────────────────────────────

-- Five programmes. PRG-0022 Safety Leadership Essentials is the one whose delivered margin sits below its floor.
INSERT INTO core.programmes AS target
  (id, tenant_id, ref, name, category, days, version, status, hrdc_scheme, hrdc_claimable, list_price_sen, list_price_pax, floor_price_sen, floor_margin_rate, currency, outcomes, deliveries_count, average_evaluation, archived_at, created_at, created_by_kind, created_by_id, created_by_name)
VALUES
  ('24d14893-e990-5f09-92d6-6580a3c684c2', 'acade111-0000-4000-8000-000000000001', 'PRG-0031', 'Leading Through Change', 'LEADERSHIP', 2, 4, 'ACTIVE', 'SBL_KHAS', TRUE, 1850000, 30, 1390000, 0.35, 'MYR', ARRAY['Name the four escalation patterns that stall cross-team work', 'Run a structured de-escalation conversation without losing the decision', 'Agree a shared definition of done between production and quality']::text[], 14, 4.5, NULL, '2023-02-14T09:00:00+08:00', 'HUMAN', 'u_khairul', 'Khairul Anwar'),
  ('e31d7740-5e6a-558d-8a04-2a2a60fd1c21', 'acade111-0000-4000-8000-000000000001', 'PRG-0018', 'Conflict to Collaboration', 'LEADERSHIP', 1, 3, 'ACTIVE', 'SBL_KHAS', TRUE, 980000, 20, 735000, 0.35, 'MYR', ARRAY['Separate the position from the interest in a live dispute', 'Close a disagreement with a written, shared commitment']::text[], 22, 4.6, NULL, '2022-09-05T09:00:00+08:00', 'HUMAN', 'u_khairul', 'Khairul Anwar'),
  ('cd093cf5-d36a-5313-b957-a2df85ee2520', 'acade111-0000-4000-8000-000000000001', 'PRG-0044', 'Data Literacy for Managers', 'ANALYTICS', 2, 2, 'ACTIVE', 'SBL_KHAS', TRUE, 1920000, 25, 1440000, 0.35, 'MYR', ARRAY['Read an operational dashboard without being misled by it', 'Ask for the measure that would change the decision']::text[], 6, 4.3, NULL, '2024-01-22T09:00:00+08:00', 'HUMAN', 'u_khairul', 'Khairul Anwar'),
  ('f5017e9f-cf8c-5888-8fd8-f4e698d06655', 'acade111-0000-4000-8000-000000000001', 'PRG-0022', 'Safety Leadership Essentials', 'SAFETY', 2, 6, 'ACTIVE', 'SBL', TRUE, 1620000, 30, 1215000, 0.35, 'MYR', ARRAY['Stop work without stopping the relationship', 'Run a five-minute pre-shift safety conversation that lands']::text[], 31, 4.4, NULL, '2021-11-30T09:00:00+08:00', 'HUMAN', 'u_khairul', 'Khairul Anwar'),
  ('f5db77a5-b328-56bf-8113-e162c3fbee97', 'acade111-0000-4000-8000-000000000001', 'PRG-0009', 'Sales Excellence for Store Managers', 'SALES', 2, 3, 'ACTIVE', 'SBL_KHAS', TRUE, 2240000, 30, 1680000, 0.35, 'MYR', ARRAY['Coach a floor conversation in under ten minutes', 'Read the weekly mix without the report']::text[], 9, 4.1, NULL, '2023-06-12T09:00:00+08:00', 'HUMAN', 'u_khairul', 'Khairul Anwar')
ON CONFLICT (id) DO UPDATE SET
  tenant_id = EXCLUDED.tenant_id,
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  days = EXCLUDED.days,
  version = EXCLUDED.version,
  status = EXCLUDED.status,
  hrdc_scheme = EXCLUDED.hrdc_scheme,
  hrdc_claimable = EXCLUDED.hrdc_claimable,
  list_price_sen = EXCLUDED.list_price_sen,
  list_price_pax = EXCLUDED.list_price_pax,
  floor_price_sen = EXCLUDED.floor_price_sen,
  floor_margin_rate = EXCLUDED.floor_margin_rate,
  currency = EXCLUDED.currency,
  outcomes = EXCLUDED.outcomes,
  deliveries_count = EXCLUDED.deliveries_count,
  average_evaluation = EXCLUDED.average_evaluation,
  archived_at = EXCLUDED.archived_at,
  created_by_kind = EXCLUDED.created_by_kind,
  created_by_id = EXCLUDED.created_by_id,
  created_by_name = EXCLUDED.created_by_name
WHERE (target.tenant_id, target.name, target.category, target.days, target.version, target.status, target.hrdc_scheme, target.hrdc_claimable, target.list_price_sen, target.list_price_pax, target.floor_price_sen, target.floor_margin_rate, target.currency, target.outcomes, target.deliveries_count, target.average_evaluation, target.archived_at, target.created_by_kind, target.created_by_id, target.created_by_name)
   IS DISTINCT FROM (EXCLUDED.tenant_id, EXCLUDED.name, EXCLUDED.category, EXCLUDED.days, EXCLUDED.version, EXCLUDED.status, EXCLUDED.hrdc_scheme, EXCLUDED.hrdc_claimable, EXCLUDED.list_price_sen, EXCLUDED.list_price_pax, EXCLUDED.floor_price_sen, EXCLUDED.floor_margin_rate, EXCLUDED.currency, EXCLUDED.outcomes, EXCLUDED.deliveries_count, EXCLUDED.average_evaluation, EXCLUDED.archived_at, EXCLUDED.created_by_kind, EXCLUDED.created_by_id, EXCLUDED.created_by_name);

-- A tier carries no floor of its own in the contract; the programme's floor rate applies to the tier price.
INSERT INTO core.programme_pricing_tiers AS target
  (id, tenant_id, programme_id, max_pax, price_sen, floor_price_sen, currency, created_at, created_by_kind, created_by_id, created_by_name)
VALUES
  ('0b282f38-19dd-58b7-a1ab-0ee81f538d50', 'acade111-0000-4000-8000-000000000001', '24d14893-e990-5f09-92d6-6580a3c684c2', 20, 1450000, 942500, 'MYR', '2023-02-14T09:00:00+08:00', 'HUMAN', 'u_khairul', 'Khairul Anwar'),
  ('0c2b097c-def5-510f-a2ce-82a3dc1972f5', 'acade111-0000-4000-8000-000000000001', '24d14893-e990-5f09-92d6-6580a3c684c2', 30, 1850000, 1202500, 'MYR', '2023-02-14T09:00:00+08:00', 'HUMAN', 'u_khairul', 'Khairul Anwar'),
  ('e98992c0-9e60-5f88-a751-e871d6a4fcb4', 'acade111-0000-4000-8000-000000000001', '24d14893-e990-5f09-92d6-6580a3c684c2', 40, 2240000, 1456000, 'MYR', '2023-02-14T09:00:00+08:00', 'HUMAN', 'u_khairul', 'Khairul Anwar'),
  ('66285d88-4876-51dd-b950-8c598cdf99f5', 'acade111-0000-4000-8000-000000000001', 'e31d7740-5e6a-558d-8a04-2a2a60fd1c21', 20, 980000, 637000, 'MYR', '2022-09-05T09:00:00+08:00', 'HUMAN', 'u_khairul', 'Khairul Anwar'),
  ('6fea5e7d-3840-5e3d-9855-e6991d86de3a', 'acade111-0000-4000-8000-000000000001', 'e31d7740-5e6a-558d-8a04-2a2a60fd1c21', 30, 1320000, 858000, 'MYR', '2022-09-05T09:00:00+08:00', 'HUMAN', 'u_khairul', 'Khairul Anwar'),
  ('bc388b09-9f65-5643-99b2-476dc739e467', 'acade111-0000-4000-8000-000000000001', 'cd093cf5-d36a-5313-b957-a2df85ee2520', 25, 1920000, 1248000, 'MYR', '2024-01-22T09:00:00+08:00', 'HUMAN', 'u_khairul', 'Khairul Anwar'),
  ('1db4440a-407a-5546-be63-2f8907a833d3', 'acade111-0000-4000-8000-000000000001', 'cd093cf5-d36a-5313-b957-a2df85ee2520', 40, 2560000, 1664000, 'MYR', '2024-01-22T09:00:00+08:00', 'HUMAN', 'u_khairul', 'Khairul Anwar'),
  ('5c0df7cc-cf40-598c-aad9-6c6dffca707f', 'acade111-0000-4000-8000-000000000001', 'f5017e9f-cf8c-5888-8fd8-f4e698d06655', 30, 1620000, 1053000, 'MYR', '2021-11-30T09:00:00+08:00', 'HUMAN', 'u_khairul', 'Khairul Anwar'),
  ('bb42d420-21c7-5fe7-98a1-e7293193946f', 'acade111-0000-4000-8000-000000000001', 'f5017e9f-cf8c-5888-8fd8-f4e698d06655', 45, 2180000, 1417000, 'MYR', '2021-11-30T09:00:00+08:00', 'HUMAN', 'u_khairul', 'Khairul Anwar'),
  ('f6e93964-7165-5a64-9653-be13d8894b1f', 'acade111-0000-4000-8000-000000000001', 'f5db77a5-b328-56bf-8113-e162c3fbee97', 30, 2240000, 1456000, 'MYR', '2023-06-12T09:00:00+08:00', 'HUMAN', 'u_khairul', 'Khairul Anwar'),
  ('9bb1da02-2444-53cb-832a-23a4574bf378', 'acade111-0000-4000-8000-000000000001', 'f5db77a5-b328-56bf-8113-e162c3fbee97', 50, 3400000, 2210000, 'MYR', '2023-06-12T09:00:00+08:00', 'HUMAN', 'u_khairul', 'Khairul Anwar')
ON CONFLICT (tenant_id, programme_id, max_pax) DO UPDATE SET
  id = EXCLUDED.id,
  price_sen = EXCLUDED.price_sen,
  floor_price_sen = EXCLUDED.floor_price_sen,
  currency = EXCLUDED.currency,
  created_by_kind = EXCLUDED.created_by_kind,
  created_by_id = EXCLUDED.created_by_id,
  created_by_name = EXCLUDED.created_by_name
WHERE (target.id, target.price_sen, target.floor_price_sen, target.currency, target.created_by_kind, target.created_by_id, target.created_by_name)
   IS DISTINCT FROM (EXCLUDED.id, EXCLUDED.price_sen, EXCLUDED.floor_price_sen, EXCLUDED.currency, EXCLUDED.created_by_kind, EXCLUDED.created_by_id, EXCLUDED.created_by_name);

INSERT INTO core.programme_trainers AS target
  (id, tenant_id, programme_id, trainer_id, certified_at, rating_override, created_at, created_by_kind, created_by_id, created_by_name)
VALUES
  ('50da33fb-b8c2-5797-8f32-afe443f62eb9', 'acade111-0000-4000-8000-000000000001', '24d14893-e990-5f09-92d6-6580a3c684c2', '0b54f9a4-0d8c-59d9-b39a-1ada4dea58db', NULL, 4.7, '2023-02-14T09:00:00+08:00', 'HUMAN', 'u_khairul', 'Khairul Anwar'),
  ('d782f483-a628-500a-9c4d-26e588e10cfd', 'acade111-0000-4000-8000-000000000001', '24d14893-e990-5f09-92d6-6580a3c684c2', '1baefe97-f97b-50a1-ba80-55ecfc180eb7', NULL, 4.4, '2023-02-14T09:00:00+08:00', 'HUMAN', 'u_khairul', 'Khairul Anwar'),
  ('0cc9839f-588d-5d02-ba9c-2e593e5a1f12', 'acade111-0000-4000-8000-000000000001', 'e31d7740-5e6a-558d-8a04-2a2a60fd1c21', '0b54f9a4-0d8c-59d9-b39a-1ada4dea58db', NULL, 4.6, '2022-09-05T09:00:00+08:00', 'HUMAN', 'u_khairul', 'Khairul Anwar'),
  ('8700a518-76f4-529c-a388-c9e145f73119', 'acade111-0000-4000-8000-000000000001', 'cd093cf5-d36a-5313-b957-a2df85ee2520', 'ad2d1197-0023-5fe3-a16b-cac09ad90f95', NULL, 4.2, '2024-01-22T09:00:00+08:00', 'HUMAN', 'u_khairul', 'Khairul Anwar'),
  ('8a3587d9-025f-5121-801a-a120ffdaa465', 'acade111-0000-4000-8000-000000000001', 'f5017e9f-cf8c-5888-8fd8-f4e698d06655', '31bd1a52-678b-57a4-bdde-aefb0db000fc', NULL, 4, '2021-11-30T09:00:00+08:00', 'HUMAN', 'u_khairul', 'Khairul Anwar'),
  ('b145a397-98af-501b-8a8d-2990d4bc4448', 'acade111-0000-4000-8000-000000000001', 'f5db77a5-b328-56bf-8113-e162c3fbee97', 'ad2d1197-0023-5fe3-a16b-cac09ad90f95', NULL, 4.2, '2023-06-12T09:00:00+08:00', 'HUMAN', 'u_khairul', 'Khairul Anwar')
ON CONFLICT (tenant_id, programme_id, trainer_id) DO UPDATE SET
  id = EXCLUDED.id,
  certified_at = EXCLUDED.certified_at,
  rating_override = EXCLUDED.rating_override,
  created_by_kind = EXCLUDED.created_by_kind,
  created_by_id = EXCLUDED.created_by_id,
  created_by_name = EXCLUDED.created_by_name
WHERE (target.id, target.certified_at, target.rating_override, target.created_by_kind, target.created_by_id, target.created_by_name)
   IS DISTINCT FROM (EXCLUDED.id, EXCLUDED.certified_at, EXCLUDED.rating_override, EXCLUDED.created_by_kind, EXCLUDED.created_by_id, EXCLUDED.created_by_name);

INSERT INTO core.programme_materials AS target
  (id, tenant_id, programme_id, material_type, version, languages, attachment_id, created_at, created_by_kind, created_by_id, created_by_name)
VALUES
  ('bc3e370a-642d-505a-9f0c-57b17e3cc9fd', 'acade111-0000-4000-8000-000000000001', '24d14893-e990-5f09-92d6-6580a3c684c2', 'WORKBOOK', 4, ARRAY['EN']::char(2)[], NULL, '2023-02-14T09:00:00+08:00', 'HUMAN', 'u_khairul', 'Khairul Anwar'),
  ('e99a541d-f659-534f-9174-5ebf8013b870', 'acade111-0000-4000-8000-000000000001', 'e31d7740-5e6a-558d-8a04-2a2a60fd1c21', 'WORKBOOK', 3, ARRAY['EN', 'MS']::char(2)[], NULL, '2022-09-05T09:00:00+08:00', 'HUMAN', 'u_khairul', 'Khairul Anwar'),
  ('a2d2763e-949d-56be-ae65-d13689168421', 'acade111-0000-4000-8000-000000000001', 'cd093cf5-d36a-5313-b957-a2df85ee2520', 'WORKBOOK', 2, ARRAY['EN']::char(2)[], NULL, '2024-01-22T09:00:00+08:00', 'HUMAN', 'u_khairul', 'Khairul Anwar'),
  ('fc380bf1-7737-5afc-95b4-b137651edb74', 'acade111-0000-4000-8000-000000000001', 'f5017e9f-cf8c-5888-8fd8-f4e698d06655', 'WORKBOOK', 6, ARRAY['EN', 'MS']::char(2)[], NULL, '2021-11-30T09:00:00+08:00', 'HUMAN', 'u_khairul', 'Khairul Anwar'),
  ('dcb4ab35-8491-5fee-8e6e-3158f464f5f8', 'acade111-0000-4000-8000-000000000001', 'f5db77a5-b328-56bf-8113-e162c3fbee97', 'WORKBOOK', 3, ARRAY['EN']::char(2)[], NULL, '2023-06-12T09:00:00+08:00', 'HUMAN', 'u_khairul', 'Khairul Anwar')
ON CONFLICT (tenant_id, programme_id, material_type, version) DO UPDATE SET
  id = EXCLUDED.id,
  languages = EXCLUDED.languages,
  attachment_id = EXCLUDED.attachment_id,
  created_by_kind = EXCLUDED.created_by_kind,
  created_by_id = EXCLUDED.created_by_id,
  created_by_name = EXCLUDED.created_by_name
WHERE (target.id, target.languages, target.attachment_id, target.created_by_kind, target.created_by_id, target.created_by_name)
   IS DISTINCT FROM (EXCLUDED.id, EXCLUDED.languages, EXCLUDED.attachment_id, EXCLUDED.created_by_kind, EXCLUDED.created_by_id, EXCLUDED.created_by_name);

-- Parties ─────────────────────────────────────────────────────────────────

-- Six organisations. ORG-0114 Aurora Manufacturing carries the in-flight deal ENG-0259.
INSERT INTO core.organisations AS target
  (id, tenant_id, ref, name, industry, location, owner_id, status, hrdc_registered, hrdc_employer_code, proposal_count, first_proposal_sent_at, health_score, archived_at, created_at, created_by_kind, created_by_id, created_by_name, tax_identifier_kind, tax_identifier, tin, sst_registration_no, address_line1, address_line2, city, state_code, postcode, country_code)
VALUES
  ('acade111-0002-4000-8000-000000000114', 'acade111-0000-4000-8000-000000000001', 'ORG-0114', 'Aurora Manufacturing Sdn Bhd', 'MANUFACTURING', 'Shah Alam', 'acade111-0001-4000-8000-000000000002', 'ACTIVE_CLIENT', TRUE, 'HRDC-2201-8834', 0, NULL, 74, NULL, '2024-03-04T09:00:00+08:00', 'HUMAN', 'u_amirah', 'Amirah Yusof', NULL, NULL, NULL, NULL, NULL, NULL, 'Shah Alam', NULL, NULL, 'MYS'),
  ('acade111-0002-4000-8000-000000000115', 'acade111-0000-4000-8000-000000000001', 'ORG-0115', 'Aurora Precision Tooling Sdn Bhd', 'MANUFACTURING', 'Klang', 'acade111-0001-4000-8000-000000000002', 'PROSPECT', TRUE, 'HRDC-2204-1190', 0, NULL, 50, NULL, '2026-08-19T11:20:00+08:00', 'HUMAN', 'u_amirah', 'Amirah Yusof', NULL, NULL, NULL, NULL, NULL, NULL, 'Klang', NULL, NULL, 'MYS'),
  ('acade111-0002-4000-8000-000000000121', 'acade111-0000-4000-8000-000000000001', 'ORG-0121', 'Kenanga Retail Group Berhad', 'RETAIL', 'Kuala Lumpur', 'acade111-0001-4000-8000-000000000002', 'ACTIVE_CLIENT', TRUE, 'HRDC-1908-4417', 0, NULL, 81, NULL, '2023-07-11T09:00:00+08:00', 'HUMAN', 'u_amirah', 'Amirah Yusof', NULL, NULL, NULL, NULL, NULL, NULL, 'Kuala Lumpur', NULL, NULL, 'MYS'),
  ('acade111-0002-4000-8000-000000000128', 'acade111-0000-4000-8000-000000000001', 'ORG-0128', 'Meridian Logistics Sdn Bhd', 'LOGISTICS', 'Port Klang', 'acade111-0001-4000-8000-000000000002', 'ACTIVE_CLIENT', TRUE, 'HRDC-2102-6620', 0, NULL, 62, NULL, '2024-11-02T09:00:00+08:00', 'HUMAN', 'u_amirah', 'Amirah Yusof', NULL, NULL, NULL, NULL, NULL, NULL, 'Port Klang', NULL, NULL, 'MYS'),
  ('acade111-0002-4000-8000-000000000133', 'acade111-0000-4000-8000-000000000001', 'ORG-0133', 'Sutera Hospitality Group', 'HOSPITALITY', 'Kuala Lumpur', 'acade111-0001-4000-8000-000000000002', 'DORMANT', TRUE, 'HRDC-2007-3312', 0, NULL, 38, NULL, '2022-05-18T09:00:00+08:00', 'HUMAN', 'u_amirah', 'Amirah Yusof', NULL, NULL, NULL, NULL, NULL, NULL, 'Kuala Lumpur', NULL, NULL, 'MYS'),
  ('acade111-0002-4000-8000-000000000140', 'acade111-0000-4000-8000-000000000001', 'ORG-0140', 'Perdana Utilities Berhad', 'UTILITIES', 'Cyberjaya', 'acade111-0001-4000-8000-000000000002', 'PROSPECT', TRUE, 'HRDC-1806-9021', 0, NULL, 55, NULL, '2026-05-21T09:00:00+08:00', 'HUMAN', 'u_amirah', 'Amirah Yusof', NULL, NULL, NULL, NULL, NULL, NULL, 'Cyberjaya', NULL, NULL, 'MYS')
ON CONFLICT (id) DO UPDATE SET
  tenant_id = EXCLUDED.tenant_id,
  name = EXCLUDED.name,
  industry = EXCLUDED.industry,
  location = EXCLUDED.location,
  owner_id = EXCLUDED.owner_id,
  status = EXCLUDED.status,
  hrdc_registered = EXCLUDED.hrdc_registered,
  hrdc_employer_code = EXCLUDED.hrdc_employer_code,
  proposal_count = EXCLUDED.proposal_count,
  first_proposal_sent_at = EXCLUDED.first_proposal_sent_at,
  health_score = EXCLUDED.health_score,
  archived_at = EXCLUDED.archived_at,
  created_by_kind = EXCLUDED.created_by_kind,
  created_by_id = EXCLUDED.created_by_id,
  created_by_name = EXCLUDED.created_by_name,
  tax_identifier_kind = EXCLUDED.tax_identifier_kind,
  tax_identifier = EXCLUDED.tax_identifier,
  tin = EXCLUDED.tin,
  sst_registration_no = EXCLUDED.sst_registration_no,
  address_line1 = EXCLUDED.address_line1,
  address_line2 = EXCLUDED.address_line2,
  city = EXCLUDED.city,
  state_code = EXCLUDED.state_code,
  postcode = EXCLUDED.postcode,
  country_code = EXCLUDED.country_code
WHERE (target.tenant_id, target.name, target.industry, target.location, target.owner_id, target.status, target.hrdc_registered, target.hrdc_employer_code, target.proposal_count, target.first_proposal_sent_at, target.health_score, target.archived_at, target.created_by_kind, target.created_by_id, target.created_by_name, target.tax_identifier_kind, target.tax_identifier, target.tin, target.sst_registration_no, target.address_line1, target.address_line2, target.city, target.state_code, target.postcode, target.country_code)
   IS DISTINCT FROM (EXCLUDED.tenant_id, EXCLUDED.name, EXCLUDED.industry, EXCLUDED.location, EXCLUDED.owner_id, EXCLUDED.status, EXCLUDED.hrdc_registered, EXCLUDED.hrdc_employer_code, EXCLUDED.proposal_count, EXCLUDED.first_proposal_sent_at, EXCLUDED.health_score, EXCLUDED.archived_at, EXCLUDED.created_by_kind, EXCLUDED.created_by_id, EXCLUDED.created_by_name, EXCLUDED.tax_identifier_kind, EXCLUDED.tax_identifier, EXCLUDED.tin, EXCLUDED.sst_registration_no, EXCLUDED.address_line1, EXCLUDED.address_line2, EXCLUDED.city, EXCLUDED.state_code, EXCLUDED.postcode, EXCLUDED.country_code);

-- One snapshot per scored organisation, at the fixture clock. The account screen reads the latest.
INSERT INTO core.organisation_health_snapshots AS target
  (id, tenant_id, organisation_id, score, components, computed_at, model_version, created_at, created_by_kind, created_by_id, created_by_name)
VALUES
  ('1da5e1b9-6c1a-5ddb-a274-74d431a338aa', 'acade111-0000-4000-8000-000000000001', 'acade111-0002-4000-8000-000000000114', 74, '{"source":"fixture","note":"of 100"}'::jsonb, '2026-11-14T10:32:00+08:00', 'fixture-v1', '2026-11-14T10:32:00+08:00', 'SYSTEM', 'system', NULL),
  ('bad6e9f6-d5a3-528d-82cd-795cbaf9dccf', 'acade111-0000-4000-8000-000000000001', 'acade111-0002-4000-8000-000000000115', 50, '{"source":"fixture","note":"of 100"}'::jsonb, '2026-11-14T10:32:00+08:00', 'fixture-v1', '2026-11-14T10:32:00+08:00', 'SYSTEM', 'system', NULL),
  ('258fbc33-7ef2-5042-84bc-b51577b8ad34', 'acade111-0000-4000-8000-000000000001', 'acade111-0002-4000-8000-000000000121', 81, '{"source":"fixture","note":"of 100"}'::jsonb, '2026-11-14T10:32:00+08:00', 'fixture-v1', '2026-11-14T10:32:00+08:00', 'SYSTEM', 'system', NULL),
  ('217147ae-b64a-5b8c-bd8d-b3de65dfa856', 'acade111-0000-4000-8000-000000000001', 'acade111-0002-4000-8000-000000000128', 62, '{"source":"fixture","note":"of 100"}'::jsonb, '2026-11-14T10:32:00+08:00', 'fixture-v1', '2026-11-14T10:32:00+08:00', 'SYSTEM', 'system', NULL),
  ('c9f09de6-e6c7-5053-a5a0-6a1ae2b5fc9f', 'acade111-0000-4000-8000-000000000001', 'acade111-0002-4000-8000-000000000133', 38, '{"source":"fixture","note":"of 100"}'::jsonb, '2026-11-14T10:32:00+08:00', 'fixture-v1', '2026-11-14T10:32:00+08:00', 'SYSTEM', 'system', NULL),
  ('5bf99d49-a9dd-5cb3-a385-39bae4a4b32c', 'acade111-0000-4000-8000-000000000001', 'acade111-0002-4000-8000-000000000140', 55, '{"source":"fixture","note":"of 100"}'::jsonb, '2026-11-14T10:32:00+08:00', 'fixture-v1', '2026-11-14T10:32:00+08:00', 'SYSTEM', 'system', NULL)
ON CONFLICT (id) DO UPDATE SET
  tenant_id = EXCLUDED.tenant_id,
  organisation_id = EXCLUDED.organisation_id,
  score = EXCLUDED.score,
  components = EXCLUDED.components,
  computed_at = EXCLUDED.computed_at,
  model_version = EXCLUDED.model_version,
  created_by_kind = EXCLUDED.created_by_kind,
  created_by_id = EXCLUDED.created_by_id,
  created_by_name = EXCLUDED.created_by_name
WHERE (target.tenant_id, target.organisation_id, target.score, target.components, target.computed_at, target.model_version, target.created_by_kind, target.created_by_id, target.created_by_name)
   IS DISTINCT FROM (EXCLUDED.tenant_id, EXCLUDED.organisation_id, EXCLUDED.score, EXCLUDED.components, EXCLUDED.computed_at, EXCLUDED.model_version, EXCLUDED.created_by_kind, EXCLUDED.created_by_id, EXCLUDED.created_by_name);

INSERT INTO core.contacts AS target
  (id, tenant_id, ref, organisation_id, name, job_title, email, phone, is_primary, pdpa_flag, redacted_at, created_at, created_by_kind, created_by_id, created_by_name)
VALUES
  ('eab22cf4-2961-5919-b158-75e055bc6a30', 'acade111-0000-4000-8000-000000000001', 'CON-0233', 'acade111-0002-4000-8000-000000000114', 'Nurul Hassan', 'HR Manager', 'nurul.hassan@auroramfg.com.my', '+60123344551', TRUE, NULL, NULL, '2024-03-04T09:12:00+08:00', 'HUMAN', 'u_amirah', 'Amirah Yusof'),
  ('6482fcbb-845d-58d8-bc2b-925db84371df', 'acade111-0000-4000-8000-000000000001', 'CON-0241', 'acade111-0002-4000-8000-000000000114', 'Ravi Subramaniam', 'Plant Director', 'ravi.s@auroramfg.com.my', NULL, FALSE, 'NO_CONSENT', NULL, '2024-06-18T14:00:00+08:00', 'HUMAN', 'u_amirah', 'Amirah Yusof'),
  ('6cfeb215-c79f-5338-939e-40d7531b4f4f', 'acade111-0000-4000-8000-000000000001', 'CON-0250', 'acade111-0002-4000-8000-000000000121', 'Lim Wei Sheng', 'Head of Learning', 'weisheng.lim@kenangaretail.com.my', '+60129900112', TRUE, NULL, NULL, '2023-07-11T09:20:00+08:00', 'HUMAN', 'u_amirah', 'Amirah Yusof'),
  ('92b57985-0ea6-5de6-9b09-b1cdd832512f', 'acade111-0000-4000-8000-000000000001', 'CON-0255', 'acade111-0002-4000-8000-000000000128', 'Faridah Omar', 'HR Business Partner', 'faridah.omar@meridianlog.com.my', '+60127788330', TRUE, NULL, NULL, '2024-11-02T09:30:00+08:00', 'HUMAN', 'u_amirah', 'Amirah Yusof'),
  ('9bbed7be-2325-5a10-a1e6-18e56fb9b071', 'acade111-0000-4000-8000-000000000001', 'CON-0264', 'acade111-0002-4000-8000-000000000133', 'Suresh Kumaran', 'General Manager', 'suresh@suterahospitality.com', NULL, TRUE, NULL, NULL, '2022-05-18T09:40:00+08:00', 'HUMAN', 'u_amirah', 'Amirah Yusof'),
  ('f181430e-87dd-5977-9974-48e41ab3ffff', 'acade111-0000-4000-8000-000000000001', 'CON-0271', 'acade111-0002-4000-8000-000000000140', 'Ganesh Pillai', 'Safety & Training Lead', 'ganesh.pillai@perdanautilities.com.my', '+60133322990', TRUE, NULL, NULL, '2026-05-21T09:15:00+08:00', 'HUMAN', 'u_amirah', 'Amirah Yusof')
ON CONFLICT (id) DO UPDATE SET
  tenant_id = EXCLUDED.tenant_id,
  organisation_id = EXCLUDED.organisation_id,
  name = EXCLUDED.name,
  job_title = EXCLUDED.job_title,
  email = EXCLUDED.email,
  phone = EXCLUDED.phone,
  is_primary = EXCLUDED.is_primary,
  pdpa_flag = EXCLUDED.pdpa_flag,
  redacted_at = EXCLUDED.redacted_at,
  created_by_kind = EXCLUDED.created_by_kind,
  created_by_id = EXCLUDED.created_by_id,
  created_by_name = EXCLUDED.created_by_name
WHERE (target.tenant_id, target.organisation_id, target.name, target.job_title, target.email, target.phone, target.is_primary, target.pdpa_flag, target.redacted_at, target.created_by_kind, target.created_by_id, target.created_by_name)
   IS DISTINCT FROM (EXCLUDED.tenant_id, EXCLUDED.organisation_id, EXCLUDED.name, EXCLUDED.job_title, EXCLUDED.email, EXCLUDED.phone, EXCLUDED.is_primary, EXCLUDED.pdpa_flag, EXCLUDED.redacted_at, EXCLUDED.created_by_kind, EXCLUDED.created_by_id, EXCLUDED.created_by_name);

-- PDPA consent, one row per channel a contact was actually asked about.
INSERT INTO core.contact_consents AS target
  (id, tenant_id, contact_id, channel, granted, recorded_at, purpose, notice_version, source, withdrawn_at, created_at, created_by_kind, created_by_id, created_by_name)
VALUES
  ('8883055a-bdaa-5084-92c3-e04bd20c937c', 'acade111-0000-4000-8000-000000000001', 'eab22cf4-2961-5919-b158-75e055bc6a30', 'EMAIL', TRUE, '2024-03-04T10:12:00+08:00', 'UNSPECIFIED_PRE_017', NULL, 'fixture', NULL, '2024-03-04T10:12:00+08:00', 'HUMAN', 'u_amirah', 'Amirah Yusof'),
  ('1636f80e-cf09-5006-9ff7-9b20e7c59a66', 'acade111-0000-4000-8000-000000000001', 'eab22cf4-2961-5919-b158-75e055bc6a30', 'WHATSAPP', TRUE, '2024-03-04T10:12:00+08:00', 'UNSPECIFIED_PRE_017', NULL, 'fixture', NULL, '2024-03-04T10:12:00+08:00', 'HUMAN', 'u_amirah', 'Amirah Yusof'),
  ('ab176b58-ffdf-5a16-8704-0dcaaa087151', 'acade111-0000-4000-8000-000000000001', '6cfeb215-c79f-5338-939e-40d7531b4f4f', 'EMAIL', TRUE, '2023-07-11T09:20:00+08:00', 'UNSPECIFIED_PRE_017', NULL, 'fixture', NULL, '2023-07-11T09:20:00+08:00', 'HUMAN', 'u_amirah', 'Amirah Yusof'),
  ('4ecba6cf-3594-5ea8-acaa-9130cdfcfae8', 'acade111-0000-4000-8000-000000000001', '92b57985-0ea6-5de6-9b09-b1cdd832512f', 'EMAIL', TRUE, '2024-11-02T09:30:00+08:00', 'UNSPECIFIED_PRE_017', NULL, 'fixture', NULL, '2024-11-02T09:30:00+08:00', 'HUMAN', 'u_amirah', 'Amirah Yusof'),
  ('c9a0ab6c-8557-5af5-862a-d8318ea2ebfa', 'acade111-0000-4000-8000-000000000001', '92b57985-0ea6-5de6-9b09-b1cdd832512f', 'WHATSAPP', TRUE, '2024-11-02T09:30:00+08:00', 'UNSPECIFIED_PRE_017', NULL, 'fixture', NULL, '2024-11-02T09:30:00+08:00', 'HUMAN', 'u_amirah', 'Amirah Yusof'),
  ('eb097823-eb28-5815-a905-0b3229f37c31', 'acade111-0000-4000-8000-000000000001', '9bbed7be-2325-5a10-a1e6-18e56fb9b071', 'EMAIL', TRUE, '2022-05-18T09:40:00+08:00', 'UNSPECIFIED_PRE_017', NULL, 'fixture', NULL, '2022-05-18T09:40:00+08:00', 'HUMAN', 'u_amirah', 'Amirah Yusof'),
  ('8afab56a-06d0-5689-a6fb-69c358e375de', 'acade111-0000-4000-8000-000000000001', 'f181430e-87dd-5977-9974-48e41ab3ffff', 'EMAIL', TRUE, '2026-05-21T09:15:00+08:00', 'UNSPECIFIED_PRE_017', NULL, 'fixture', NULL, '2026-05-21T09:15:00+08:00', 'HUMAN', 'u_amirah', 'Amirah Yusof'),
  ('c3d5c919-9afe-5d77-9320-47d2debc3dd0', 'acade111-0000-4000-8000-000000000001', 'f181430e-87dd-5977-9974-48e41ab3ffff', 'WHATSAPP', TRUE, '2026-05-21T09:15:00+08:00', 'UNSPECIFIED_PRE_017', NULL, 'fixture', NULL, '2026-05-21T09:15:00+08:00', 'HUMAN', 'u_amirah', 'Amirah Yusof')
ON CONFLICT (tenant_id, contact_id, channel, recorded_at) DO UPDATE SET
  id = EXCLUDED.id,
  granted = EXCLUDED.granted,
  purpose = EXCLUDED.purpose,
  notice_version = EXCLUDED.notice_version,
  source = EXCLUDED.source,
  withdrawn_at = EXCLUDED.withdrawn_at,
  created_by_kind = EXCLUDED.created_by_kind,
  created_by_id = EXCLUDED.created_by_id,
  created_by_name = EXCLUDED.created_by_name
WHERE (target.id, target.granted, target.purpose, target.notice_version, target.source, target.withdrawn_at, target.created_by_kind, target.created_by_id, target.created_by_name)
   IS DISTINCT FROM (EXCLUDED.id, EXCLUDED.granted, EXCLUDED.purpose, EXCLUDED.notice_version, EXCLUDED.source, EXCLUDED.withdrawn_at, EXCLUDED.created_by_kind, EXCLUDED.created_by_id, EXCLUDED.created_by_name);

-- Agent-proposed next programmes on the account screen.
INSERT INTO core.organisation_suggestions AS target
  (id, tenant_id, organisation_id, suggestion_type, programme_id, title, rationale, status, dismissed_at, dismissed_by_user_id, created_at, created_by_kind, created_by_id, created_by_name)
VALUES
  ('1e47ebc0-85f2-596c-853d-804926563106', 'acade111-0000-4000-8000-000000000001', 'acade111-0002-4000-8000-000000000114', 'CROSS_SELL', 'e31d7740-5e6a-558d-8a04-2a2a60fd1c21', 'Conflict to Collaboration', 'RM 61,000 unused levy expiring 31 Dec; 42 supervisors have not attended any programme; the programme scored 4.6 with their managers.', 'OPEN', NULL, NULL, '2026-11-14T10:32:00+08:00', 'AGENT', 'agent_knowledge', 'Knowledge agent')
ON CONFLICT (id) DO UPDATE SET
  tenant_id = EXCLUDED.tenant_id,
  organisation_id = EXCLUDED.organisation_id,
  suggestion_type = EXCLUDED.suggestion_type,
  programme_id = EXCLUDED.programme_id,
  title = EXCLUDED.title,
  rationale = EXCLUDED.rationale,
  status = EXCLUDED.status,
  dismissed_at = EXCLUDED.dismissed_at,
  dismissed_by_user_id = EXCLUDED.dismissed_by_user_id,
  created_by_kind = EXCLUDED.created_by_kind,
  created_by_id = EXCLUDED.created_by_id,
  created_by_name = EXCLUDED.created_by_name
WHERE (target.tenant_id, target.organisation_id, target.suggestion_type, target.programme_id, target.title, target.rationale, target.status, target.dismissed_at, target.dismissed_by_user_id, target.created_by_kind, target.created_by_id, target.created_by_name)
   IS DISTINCT FROM (EXCLUDED.tenant_id, EXCLUDED.organisation_id, EXCLUDED.suggestion_type, EXCLUDED.programme_id, EXCLUDED.title, EXCLUDED.rationale, EXCLUDED.status, EXCLUDED.dismissed_at, EXCLUDED.dismissed_by_user_id, EXCLUDED.created_by_kind, EXCLUDED.created_by_id, EXCLUDED.created_by_name);