-- TrainOS fixture world, part 4 — Agents, routing, budgets, runs, approvals and knowledge
--
-- Tenant: akademi-perdana (Akademi Perdana Sdn Bhd), id acade111-0000-4000-8000-000000000001
--
-- Run (all four parts, one transaction, from the repo root):
--   psql "$DATABASE_URL" -1 -v ON_ERROR_STOP=1 \
--     -f supabase/seeds/fixture_world_01_tenant_and_parties.sql \
--     -f supabase/seeds/fixture_world_02_sales_and_money.sql \
--     -f supabase/seeds/fixture_world_03_delivery_compliance_finance.sql \
--     -f supabase/seeds/fixture_world_04_ai_ops_and_agents.sql
--
-- Targets migrations 001-017: the tenant is provisioned by
-- app.provision_tenant() from 016, so this does NOT run against a database at
-- 013 or earlier. 018 adds RPCs, not configuration this seed writes — the
-- pipeline rows below are the seed's own, and no provisioning pack writes
-- stages yet.
--
-- Idempotent: every statement is an upsert guarded by an IS DISTINCT FROM
-- comparison, so a second run of an unchanged seed performs zero updates and
-- leaves every updated_at where it was. Iterating a fixture never needs a wipe,
-- with two exceptions named in supabase/seeds/README.md.
--
-- One of the four parts of the TrainOS fixture world. The parts are in
-- foreign-key order and must be run in order:
--
--   1. fixture_world_01_tenant_and_parties.sql
--   2. fixture_world_02_sales_and_money.sql
--   3. fixture_world_03_delivery_compliance_finance.sql
--   4. fixture_world_04_ai_ops_and_agents.sql
--
-- Companion files:
--   fixture_world_wipe.sql         removes every row the four parts write, tenant included
--   test_fixture_world.sql         the pin: counts, landmarks, re-run stability
--
-- Generated by packages/fixtures/scripts/emit-seed.ts — edit the fixtures or the
-- generator, never this file. Regenerate with:
--   npx tsx packages/fixtures/scripts/emit-seed.ts
-- and `--check` fails if the committed SQL and the fixtures have drifted apart.

-- Model tiers and routing configuration ───────────────────────────────────

-- The nine tier keys. Six other tables have a composite FK into this one, so it
-- loads first. `label` is the key rendered for a human (STRONG_1 → Strong 1);
-- the fixture world names the MODEL behind a tier, never the tier itself.
INSERT INTO core.tier_keys AS target
  (id, tenant_id, tier_key, label, description, position, active, created_at)
VALUES
  ('60e63ee4-93fc-5fd7-804a-9b5b90e9901a', 'acade111-0000-4000-8000-000000000001', 'FAST', 'Fast', NULL, 0, TRUE, '2026-11-14T10:32:00+08:00'),
  ('1935a23a-f41f-5a68-b4a6-d26bb51a81e2', 'acade111-0000-4000-8000-000000000001', 'FAST_UI', 'Fast UI', NULL, 1, TRUE, '2026-11-14T10:32:00+08:00'),
  ('c4f13f45-944d-5ae5-a07e-90730f53d9df', 'acade111-0000-4000-8000-000000000001', 'MID', 'Mid', NULL, 2, TRUE, '2026-11-14T10:32:00+08:00'),
  ('df9a3557-aa68-5ce3-a0f3-913f2fede270', 'acade111-0000-4000-8000-000000000001', 'CHEAP', 'Cheap', NULL, 3, TRUE, '2026-11-14T10:32:00+08:00'),
  ('fede02a7-1778-5188-98b6-5cecfb9a19ee', 'acade111-0000-4000-8000-000000000001', 'STRONG_1', 'Strong 1', NULL, 4, TRUE, '2026-11-14T10:32:00+08:00'),
  ('c1a9f6c4-f08b-51eb-9c86-cc6f6c0271ec', 'acade111-0000-4000-8000-000000000001', 'STRONG_2', 'Strong 2', NULL, 5, TRUE, '2026-11-14T10:32:00+08:00'),
  ('a4803234-9cf3-539f-8136-c47773ebf5ee', 'acade111-0000-4000-8000-000000000001', 'STRONG_3', 'Strong 3', NULL, 6, TRUE, '2026-11-14T10:32:00+08:00'),
  ('f7c68513-5474-5297-88e0-b377968425c4', 'acade111-0000-4000-8000-000000000001', 'DEEP_THINK', 'Deep think', NULL, 7, TRUE, '2026-11-14T10:32:00+08:00'),
  ('f57e4018-2dec-5afb-8e17-03ab9453f269', 'acade111-0000-4000-8000-000000000001', 'SPECIAL', 'Special', NULL, 8, TRUE, '2026-11-14T10:32:00+08:00')
ON CONFLICT (tenant_id, tier_key) DO UPDATE SET
  id = EXCLUDED.id,
  label = EXCLUDED.label,
  description = EXCLUDED.description,
  position = EXCLUDED.position,
  active = EXCLUDED.active
WHERE (target.id, target.label, target.description, target.position, target.active)
   IS DISTINCT FROM (EXCLUDED.id, EXCLUDED.label, EXCLUDED.description, EXCLUDED.position, EXCLUDED.active);

-- The model behind each tier, its routing strategy and its off-peak window.
--
-- `batch_eligible` is derived, not copied: §17 restricts batch-eligible tiers to
-- off-peak hours and makes them queue rather than escalate, so a tier whose
-- `allowedHours` are narrower than the full day IS the batch-eligible one. That
-- picks out MID and CHEAP, which is what ai-ops.ts's own note on MID says.
--
-- SPECIAL's fixture status is PAUSED_BY_CAP and this table has no column for it:
-- `admin_state` is ENABLED/DISABLED and `health` is HEALTHY/DEGRADED. Paused-by-cap
-- is a derived read (spend against `monthly_cap_sen`, which for SPECIAL is exactly
-- at its cap), so the row is stored ENABLED/HEALTHY. See the PR's schema-gap list.
INSERT INTO core.model_tiers AS target
  (id, tenant_id, tier_key, model, provider, routing, fallback_chain, cache_strategy, max_output_tokens, allowed_hours, batch_eligible, admin_state, health, degraded_since, degraded_reason, active_fallback_tier, monthly_cap_sen, currency, created_at)
VALUES
  ('c368d6e1-2158-5c82-9294-48495572e483', 'acade111-0000-4000-8000-000000000001', 'FAST', 'Gemini 3.1 Flash', 'GOOGLE', 'THROUGHPUT', ARRAY['FAST_UI', 'MID']::text[], 'PROMPT_1H', 4096, B'111111111111111111111111', FALSE, 'ENABLED', 'HEALTHY', NULL, NULL, NULL, 8000, 'MYR', '2026-11-14T10:32:00+08:00'),
  ('8b863b34-42bb-5834-a5df-450ea87cf8ae', 'acade111-0000-4000-8000-000000000001', 'FAST_UI', 'Gemini 3.1 Flash Lite', 'GOOGLE', 'THROUGHPUT', ARRAY['FAST']::text[], 'PROMPT_15M', 2048, B'111111111111111111111111', FALSE, 'ENABLED', 'HEALTHY', NULL, NULL, NULL, 3000, 'MYR', '2026-11-14T10:32:00+08:00'),
  ('2af724df-089f-5922-b2db-21e446f15420', 'acade111-0000-4000-8000-000000000001', 'MID', 'DeepSeek V4 Pro', 'DEEPSEEK', 'PRICE', ARRAY['FAST', 'STRONG_1']::text[], 'PROMPT_24H', 8192, B'111111111000110000111111', TRUE, 'ENABLED', 'HEALTHY', NULL, NULL, NULL, 12000, 'MYR', '2026-11-14T10:32:00+08:00'),
  ('3c5c4568-ae59-5cc3-9828-f09c4b4dfb9f', 'acade111-0000-4000-8000-000000000001', 'CHEAP', 'DeepSeek V4 Lite', 'DEEPSEEK', 'PRICE', ARRAY['FAST']::text[], 'PROMPT_24H', 4096, B'111111111000000000111111', TRUE, 'ENABLED', 'HEALTHY', NULL, NULL, NULL, 4000, 'MYR', '2026-11-14T10:32:00+08:00'),
  ('1385815f-4846-58c6-8274-cf6e0cf71338', 'acade111-0000-4000-8000-000000000001', 'STRONG_1', 'Claude Sonnet 5', 'ANTHROPIC', 'FIXED', ARRAY['STRONG_2', 'STRONG_3']::text[], 'CONTEXT_1H', 8192, B'111111111111111111111111', FALSE, 'ENABLED', 'HEALTHY', NULL, NULL, NULL, 15000, 'MYR', '2026-11-14T10:32:00+08:00'),
  ('e49ddac7-e83a-57b0-9ed8-2c07efa7363e', 'acade111-0000-4000-8000-000000000001', 'STRONG_2', 'Gemini 3.1 Pro', 'GOOGLE', 'PRICE', ARRAY['STRONG_3', 'MID']::text[], 'CONTEXT_1H', 8192, B'111111111111111111111111', FALSE, 'ENABLED', 'DEGRADED', '2026-11-14T09:12:00+08:00', 'PROVIDER_5XX', 'DEEP_THINK', 10000, 'MYR', '2026-11-14T10:32:00+08:00'),
  ('76f3f677-fd33-5c00-8c0f-42bb1b8c92e6', 'acade111-0000-4000-8000-000000000001', 'STRONG_3', 'GPT-5.6 Terra', 'OPENAI', 'FIXED', ARRAY['STRONG_1']::text[], 'PROMPT_1H', 8192, B'111111111111111111111111', FALSE, 'ENABLED', 'HEALTHY', NULL, NULL, NULL, 9000, 'MYR', '2026-11-14T10:32:00+08:00'),
  ('922e3939-c38c-54e1-8485-0b9e0674f373', 'acade111-0000-4000-8000-000000000001', 'DEEP_THINK', 'Gemini 3.1 Pro Thinking', 'GOOGLE', 'FIXED', ARRAY['STRONG_1']::text[], 'CONTEXT_1H', 16384, B'111111111111111111111111', FALSE, 'ENABLED', 'HEALTHY', NULL, NULL, NULL, 12000, 'MYR', '2026-11-14T10:32:00+08:00'),
  ('eee74ffb-44d8-53bc-8f85-bf4bf53dc06c', 'acade111-0000-4000-8000-000000000001', 'SPECIAL', 'Claude Opus 5', 'ANTHROPIC', 'FIXED', ARRAY['STRONG_1']::text[], 'CONTEXT_1H', 16384, B'111111111111111111111111', FALSE, 'ENABLED', 'HEALTHY', NULL, NULL, NULL, 20000, 'MYR', '2026-11-14T10:32:00+08:00')
ON CONFLICT (tenant_id, tier_key) DO UPDATE SET
  id = EXCLUDED.id,
  model = EXCLUDED.model,
  provider = EXCLUDED.provider,
  routing = EXCLUDED.routing,
  fallback_chain = EXCLUDED.fallback_chain,
  cache_strategy = EXCLUDED.cache_strategy,
  max_output_tokens = EXCLUDED.max_output_tokens,
  allowed_hours = EXCLUDED.allowed_hours,
  batch_eligible = EXCLUDED.batch_eligible,
  admin_state = EXCLUDED.admin_state,
  health = EXCLUDED.health,
  degraded_since = EXCLUDED.degraded_since,
  degraded_reason = EXCLUDED.degraded_reason,
  active_fallback_tier = EXCLUDED.active_fallback_tier,
  monthly_cap_sen = EXCLUDED.monthly_cap_sen,
  currency = EXCLUDED.currency
WHERE (target.id, target.model, target.provider, target.routing, target.fallback_chain, target.cache_strategy, target.max_output_tokens, target.allowed_hours, target.batch_eligible, target.admin_state, target.health, target.degraded_since, target.degraded_reason, target.active_fallback_tier, target.monthly_cap_sen, target.currency)
   IS DISTINCT FROM (EXCLUDED.id, EXCLUDED.model, EXCLUDED.provider, EXCLUDED.routing, EXCLUDED.fallback_chain, EXCLUDED.cache_strategy, EXCLUDED.max_output_tokens, EXCLUDED.allowed_hours, EXCLUDED.batch_eligible, EXCLUDED.admin_state, EXCLUDED.health, EXCLUDED.degraded_since, EXCLUDED.degraded_reason, EXCLUDED.active_fallback_tier, EXCLUDED.monthly_cap_sen, EXCLUDED.currency);

-- The agent fleet ─────────────────────────────────────────────────────────

-- Eight agents. agent_knowledge is PAUSED on an eval regression and carries the
-- resume condition that would lift it (evalScore ≥ 0.85).
--
-- `costMonth`, `evalScore`, `cacheHitRate30d` and `costPerRun30d` are read-side
-- aggregates with no column here: the first lands in app.usage_rollup, the second
-- in core.evals, and the last two have nowhere to go. See the PR's schema-gap list.
INSERT INTO core.agents AS target
  (id, tenant_id, ref, agent_id, name, status, principal_user_id, orchestrator, scopes, kill_switch, paused_at, paused_reason, paused_by, resume_condition, default_tier, escalation_ladder, jury, last_run_at, created_at)
VALUES
  ('abae3a57-cba3-5099-b69b-bcbedc6c944b', 'acade111-0000-4000-8000-000000000001', 'AGT-001', 'agent_lead', 'Lead Agent', 'ACTIVE', '22480065-8fe4-5ca9-b7ba-41102d750d65', NULL, ARRAY['enquiries', 'contacts']::text[], FALSE, NULL, NULL, NULL, NULL, 'FAST', ARRAY['FAST', 'MID']::text[], '{"mode":"SAMPLE","quorum":2,"of":3,"tiers":["STRONG_1","STRONG_2","STRONG_3"],"sampleRate":0.05}'::jsonb, '2026-11-13T17:41:00+08:00', '2026-01-12T10:00:00+08:00'),
  ('351fe2bd-71d6-5340-bc46-99f6f76356d6', 'acade111-0000-4000-8000-000000000001', 'AGT-002', 'agent_match', 'Match Agent', 'ACTIVE', 'c104277c-cedb-5574-96a4-c92699ea4515', NULL, ARRAY['organisations', 'contacts']::text[], FALSE, NULL, NULL, NULL, NULL, 'CHEAP', ARRAY['CHEAP', 'FAST']::text[], '{"mode":"GATE","quorum":2,"of":3,"tiers":["STRONG_1","STRONG_2","STRONG_3"]}'::jsonb, '2026-11-13T17:41:00+08:00', '2026-01-12T10:00:00+08:00'),
  ('ee27cc82-8c7f-5d8e-a6ee-e82c14c0031b', 'acade111-0000-4000-8000-000000000001', 'AGT-003', 'agent_tna', 'TNA Agent', 'ACTIVE', '3643f0fa-1a31-5a5e-b9ce-b68cbb3d1f3b', NULL, ARRAY['tnas', 'programmes']::text[], FALSE, NULL, NULL, NULL, NULL, 'STRONG_1', ARRAY['STRONG_1', 'DEEP_THINK']::text[], '{"mode":"ESCALATE","quorum":2,"of":3,"tiers":["STRONG_1","STRONG_2","STRONG_3"],"triggers":{"minConfidence":0.7,"maxValueSen":5000000,"firstOfKind":true}}'::jsonb, '2026-11-12T15:33:00+08:00', '2026-01-12T10:00:00+08:00'),
  ('e80740d1-e4c6-5976-93c8-4621a43f0d31', 'acade111-0000-4000-8000-000000000001', 'AGT-004', 'agent_proposal', 'Proposal Agent', 'ACTIVE', 'c37e813e-e16b-54e9-aaaa-d3dfd8bf77df', NULL, ARRAY['proposals', 'quotations']::text[], FALSE, NULL, NULL, NULL, NULL, 'STRONG_1', ARRAY['STRONG_1', 'STRONG_2']::text[], '{"mode":"ESCALATE","quorum":2,"of":3,"tiers":["STRONG_1","STRONG_2","STRONG_3"],"triggers":{"minConfidence":0.7,"maxValueSen":5000000,"firstOfKind":true}}'::jsonb, '2026-11-14T10:30:00+08:00', '2026-01-12T10:00:00+08:00'),
  ('3c281278-6e94-54f1-8e26-3e0cb2455745', 'acade111-0000-4000-8000-000000000001', 'AGT-005', 'agent_followup', 'Follow-up Agent', 'ACTIVE', 'fd79eafd-1db7-50da-82e5-c3505ef94a95', NULL, ARRAY['follow-ups', 'messages']::text[], FALSE, NULL, NULL, NULL, NULL, 'MID', ARRAY['MID', 'STRONG_1']::text[], '{"mode":"SAMPLE","quorum":2,"of":3,"tiers":["STRONG_1","STRONG_2","STRONG_3"],"sampleRate":0.05}'::jsonb, '2026-11-14T07:40:00+08:00', '2026-01-12T10:00:00+08:00'),
  ('4f029e34-1653-5a84-82f1-ba2f267b1979', 'acade111-0000-4000-8000-000000000001', 'AGT-006', 'agent_collections', 'Collections Agent', 'ACTIVE', 'c6cccdec-44f9-58e8-ae16-d7763efd7be3', NULL, ARRAY['invoices', 'receivables']::text[], FALSE, NULL, NULL, NULL, NULL, 'MID', ARRAY['MID', 'STRONG_1']::text[], '{"mode":"SAMPLE","quorum":2,"of":3,"tiers":["STRONG_1","STRONG_2","STRONG_3"],"sampleRate":0.05}'::jsonb, '2026-11-14T08:30:00+08:00', '2026-01-12T10:00:00+08:00'),
  ('8d82175d-cdb5-529a-9908-e397a55af783', 'acade111-0000-4000-8000-000000000001', 'AGT-007', 'agent_compliance', 'Compliance Agent', 'ACTIVE', '81f09789-93aa-51f4-a114-5d284802c9ae', NULL, ARRAY['hrdc', 'compliance', 'knowledge']::text[], FALSE, NULL, NULL, NULL, NULL, 'STRONG_2', ARRAY['STRONG_2', 'SPECIAL']::text[], '{"mode":"ESCALATE","quorum":2,"of":3,"tiers":["STRONG_1","STRONG_2","STRONG_3"],"triggers":{"minConfidence":0.8,"maxValueSen":0,"firstOfKind":true}}'::jsonb, '2026-11-14T10:30:00+08:00', '2026-01-12T10:00:00+08:00'),
  ('baa59ec5-5fec-5b02-a614-347576c53c63', 'acade111-0000-4000-8000-000000000001', 'AGT-008', 'agent_knowledge', 'Knowledge Agent', 'PAUSED', 'd1cfaa81-a6b6-55dd-880c-261b1e978865', NULL, ARRAY['knowledge', 'suggestions']::text[], FALSE, '2026-11-09T00:00:00+08:00', 'EVAL_REGRESSION', NULL, '{"metric":"evalScore","op":"gte","value":0.85}'::jsonb, 'MID', ARRAY['MID', 'STRONG_1']::text[], '{"mode":"GATE","quorum":2,"of":3,"tiers":["STRONG_1","STRONG_2","STRONG_3"]}'::jsonb, '2026-11-08T22:10:00+08:00', '2026-01-12T10:00:00+08:00')
ON CONFLICT (tenant_id, agent_id) DO UPDATE SET
  id = EXCLUDED.id,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  principal_user_id = EXCLUDED.principal_user_id,
  orchestrator = EXCLUDED.orchestrator,
  scopes = EXCLUDED.scopes,
  kill_switch = EXCLUDED.kill_switch,
  paused_at = EXCLUDED.paused_at,
  paused_reason = EXCLUDED.paused_reason,
  paused_by = EXCLUDED.paused_by,
  resume_condition = EXCLUDED.resume_condition,
  default_tier = EXCLUDED.default_tier,
  escalation_ladder = EXCLUDED.escalation_ladder,
  jury = EXCLUDED.jury,
  last_run_at = EXCLUDED.last_run_at
WHERE (target.id, target.name, target.status, target.principal_user_id, target.orchestrator, target.scopes, target.kill_switch, target.paused_at, target.paused_reason, target.paused_by, target.resume_condition, target.default_tier, target.escalation_ladder, target.jury, target.last_run_at)
   IS DISTINCT FROM (EXCLUDED.id, EXCLUDED.name, EXCLUDED.status, EXCLUDED.principal_user_id, EXCLUDED.orchestrator, EXCLUDED.scopes, EXCLUDED.kill_switch, EXCLUDED.paused_at, EXCLUDED.paused_reason, EXCLUDED.paused_by, EXCLUDED.resume_condition, EXCLUDED.default_tier, EXCLUDED.escalation_ladder, EXCLUDED.jury, EXCLUDED.last_run_at);

-- The launch matrix, one row per agent and action type. The autonomy ceiling trigger stays live.
INSERT INTO core.autonomy_grants AS target
  (id, tenant_id, agent_id, action_type, level, approver_role, value_threshold_sen, currency, min_confidence, paused, paused_at, paused_reason, resume_condition, promotion_condition, promoted_from_level, promoted_at, promoted_by, promotion_jury_verdict_id, promotion_blocked_reason, granted_by, granted_at)
VALUES
  ('c56e176d-b274-52bf-9f2f-f411c01ded5b', 'acade111-0000-4000-8000-000000000001', 'agent_lead', 'ENQUIRY_ARCHIVE', 'AUTONOMOUS', NULL, NULL, 'MYR', 0.7, FALSE, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'launch_matrix', '2026-01-12T10:00:00+08:00'),
  ('78240989-7538-51f4-b4a8-53ba080d0d15', 'acade111-0000-4000-8000-000000000001', 'agent_lead', 'OPPORTUNITY_CONVERT', 'ACT_WITH_APPROVAL', NULL, NULL, 'MYR', 0.7, FALSE, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'launch_matrix', '2026-01-12T10:00:00+08:00'),
  ('df4ddf46-ead4-56c0-89b1-35721367082f', 'acade111-0000-4000-8000-000000000001', 'agent_match', 'ENQUIRY_ARCHIVE', 'OBSERVE', NULL, NULL, 'MYR', 0.7, FALSE, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'launch_matrix', '2026-01-12T10:00:00+08:00'),
  ('aac958b4-764b-5239-b0c6-226702a89580', 'acade111-0000-4000-8000-000000000001', 'agent_tna', 'TNA_RECOMMENDATION_ACCEPT', 'SUGGEST', NULL, NULL, 'MYR', 0.7, FALSE, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'launch_matrix', '2026-01-12T10:00:00+08:00'),
  ('8159a2d0-02e1-5920-b15b-083228695afb', 'acade111-0000-4000-8000-000000000001', 'agent_proposal', 'PROPOSAL_SEND', 'ACT_WITH_APPROVAL', 'SALES_MANAGER', NULL, 'MYR', 0.7, FALSE, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'launch_matrix', '2026-01-12T10:00:00+08:00'),
  ('5152e681-8cd8-5359-a069-6ec0704f2bd0', 'acade111-0000-4000-8000-000000000001', 'agent_proposal', 'QUOTATION_APPLY', 'SUGGEST', NULL, NULL, 'MYR', 0.7, FALSE, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'launch_matrix', '2026-01-12T10:00:00+08:00'),
  ('9e0ed318-f7da-534b-8a6d-e92c53320960', 'acade111-0000-4000-8000-000000000001', 'agent_followup', 'FOLLOWUP_SEND', 'SUGGEST', NULL, NULL, 'MYR', 0.7, FALSE, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'launch_matrix', '2026-01-12T10:00:00+08:00'),
  ('4633366d-6b97-5529-8a2c-cf864c2e0ef3', 'acade111-0000-4000-8000-000000000001', 'agent_followup', 'BROADCAST_SEND', 'OBSERVE', NULL, NULL, 'MYR', 0.7, TRUE, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'launch_matrix', '2026-01-12T10:00:00+08:00'),
  ('9023ee2c-91e5-5ff2-9a63-25a10ebb1fd8', 'acade111-0000-4000-8000-000000000001', 'agent_collections', 'REMINDER_SEND', 'ACT_WITH_APPROVAL', 'FINANCE', NULL, 'MYR', 0.7, FALSE, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'launch_matrix', '2026-01-12T10:00:00+08:00'),
  ('f3a1f11b-e003-5222-9650-21b97508c034', 'acade111-0000-4000-8000-000000000001', 'agent_collections', 'INVOICE_CREATE', 'OBSERVE', NULL, NULL, 'MYR', 0.7, FALSE, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'launch_matrix', '2026-01-12T10:00:00+08:00'),
  ('ebcf3328-c310-51c7-b5f0-b84be02d208e', 'acade111-0000-4000-8000-000000000001', 'agent_compliance', 'HRDC_PACKET_MARK_SUBMITTED', 'ACT_WITH_APPROVAL', 'FINANCE', NULL, 'MYR', 0.7, FALSE, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'launch_matrix', '2026-01-12T10:00:00+08:00'),
  ('437bcb0a-8c28-5713-ad4d-e0737a56c49f', 'acade111-0000-4000-8000-000000000001', 'agent_compliance', 'RULE_CHANGE_APPROVE', 'ACT_WITH_APPROVAL', 'FINANCE', NULL, 'MYR', 0.7, FALSE, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'launch_matrix', '2026-01-12T10:00:00+08:00'),
  ('c417c038-d447-571d-ae15-99e40947663e', 'acade111-0000-4000-8000-000000000001', 'agent_knowledge', 'BROADCAST_SEND', 'OBSERVE', NULL, NULL, 'MYR', 0.7, TRUE, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'launch_matrix', '2026-01-12T10:00:00+08:00')
ON CONFLICT (id) DO UPDATE SET
  tenant_id = EXCLUDED.tenant_id,
  agent_id = EXCLUDED.agent_id,
  action_type = EXCLUDED.action_type,
  level = EXCLUDED.level,
  approver_role = EXCLUDED.approver_role,
  value_threshold_sen = EXCLUDED.value_threshold_sen,
  currency = EXCLUDED.currency,
  min_confidence = EXCLUDED.min_confidence,
  paused = EXCLUDED.paused,
  paused_at = EXCLUDED.paused_at,
  paused_reason = EXCLUDED.paused_reason,
  resume_condition = EXCLUDED.resume_condition,
  promotion_condition = EXCLUDED.promotion_condition,
  promoted_from_level = EXCLUDED.promoted_from_level,
  promoted_at = EXCLUDED.promoted_at,
  promoted_by = EXCLUDED.promoted_by,
  promotion_jury_verdict_id = EXCLUDED.promotion_jury_verdict_id,
  promotion_blocked_reason = EXCLUDED.promotion_blocked_reason,
  granted_by = EXCLUDED.granted_by
WHERE (target.tenant_id, target.agent_id, target.action_type, target.level, target.approver_role, target.value_threshold_sen, target.currency, target.min_confidence, target.paused, target.paused_at, target.paused_reason, target.resume_condition, target.promotion_condition, target.promoted_from_level, target.promoted_at, target.promoted_by, target.promotion_jury_verdict_id, target.promotion_blocked_reason, target.granted_by)
   IS DISTINCT FROM (EXCLUDED.tenant_id, EXCLUDED.agent_id, EXCLUDED.action_type, EXCLUDED.level, EXCLUDED.approver_role, EXCLUDED.value_threshold_sen, EXCLUDED.currency, EXCLUDED.min_confidence, EXCLUDED.paused, EXCLUDED.paused_at, EXCLUDED.paused_reason, EXCLUDED.resume_condition, EXCLUDED.promotion_condition, EXCLUDED.promoted_from_level, EXCLUDED.promoted_at, EXCLUDED.promoted_by, EXCLUDED.promotion_jury_verdict_id, EXCLUDED.promotion_blocked_reason, EXCLUDED.granted_by);

-- One rolling eval per agent. `passed` has no fixture value — a score is not a verdict.
INSERT INTO core.evals AS target
  (id, tenant_id, agent_id, action_type, kind, golden_set_version, run_id, score, passed, detail, evaluated_at, created_at)
VALUES
  ('7339689e-c5d7-59b5-b155-7926a65b349d', 'acade111-0000-4000-8000-000000000001', 'agent_lead', NULL, 'LIVE_SAMPLE', NULL, NULL, 0.93, NULL, '{"window":"30d","sampleSize":120,"method":"DETERMINISTIC","origin":"SYSTEM"}'::jsonb, '2026-11-14T00:00:00+08:00', '2026-11-14T00:00:00+08:00'),
  ('448e341b-2e7e-5215-a8ae-89bbfcf74a82', 'acade111-0000-4000-8000-000000000001', 'agent_match', NULL, 'LIVE_SAMPLE', NULL, NULL, 0.95, NULL, '{"window":"30d","sampleSize":120,"method":"DETERMINISTIC","origin":"SYSTEM"}'::jsonb, '2026-11-14T00:00:00+08:00', '2026-11-14T00:00:00+08:00'),
  ('332f701e-1893-5da7-9b9d-cc207cd1ee2b', 'acade111-0000-4000-8000-000000000001', 'agent_tna', NULL, 'LIVE_SAMPLE', NULL, NULL, 0.9, NULL, '{"window":"30d","sampleSize":120,"method":"DETERMINISTIC","origin":"SYSTEM"}'::jsonb, '2026-11-14T00:00:00+08:00', '2026-11-14T00:00:00+08:00'),
  ('9491a3a7-6fd7-504a-a8ac-2e905200b6df', 'acade111-0000-4000-8000-000000000001', 'agent_proposal', NULL, 'LIVE_SAMPLE', NULL, NULL, 0.89, NULL, '{"window":"30d","sampleSize":120,"method":"DETERMINISTIC","origin":"SYSTEM"}'::jsonb, '2026-11-14T00:00:00+08:00', '2026-11-14T00:00:00+08:00'),
  ('8e12508e-15d2-5f4f-b8e6-b004aa42ea22', 'acade111-0000-4000-8000-000000000001', 'agent_followup', NULL, 'LIVE_SAMPLE', NULL, NULL, 0.86, NULL, '{"window":"30d","sampleSize":120,"method":"DETERMINISTIC","origin":"SYSTEM"}'::jsonb, '2026-11-14T00:00:00+08:00', '2026-11-14T00:00:00+08:00'),
  ('b9cae214-dde0-50a8-9a3c-dded6ce8ba8c', 'acade111-0000-4000-8000-000000000001', 'agent_collections', NULL, 'LIVE_SAMPLE', NULL, NULL, 0.88, NULL, '{"window":"30d","sampleSize":120,"method":"DETERMINISTIC","origin":"SYSTEM"}'::jsonb, '2026-11-14T00:00:00+08:00', '2026-11-14T00:00:00+08:00'),
  ('d10ed68d-de63-5bbb-b8ff-39d37fd805fe', 'acade111-0000-4000-8000-000000000001', 'agent_compliance', NULL, 'LIVE_SAMPLE', NULL, NULL, 0.91, NULL, '{"window":"30d","sampleSize":120,"method":"DETERMINISTIC","origin":"SYSTEM"}'::jsonb, '2026-11-14T00:00:00+08:00', '2026-11-14T00:00:00+08:00'),
  ('3b5c4c1c-360c-51be-a3bf-09e0ed3d7e79', 'acade111-0000-4000-8000-000000000001', 'agent_knowledge', NULL, 'LIVE_SAMPLE', NULL, NULL, 0.71, NULL, '{"window":"30d","sampleSize":120,"method":"DETERMINISTIC","origin":"SYSTEM"}'::jsonb, '2026-11-14T00:00:00+08:00', '2026-11-14T00:00:00+08:00')
ON CONFLICT (id) DO UPDATE SET
  detail = EXCLUDED.detail
WHERE target.detail IS DISTINCT FROM EXCLUDED.detail;

-- Routing matrix and juries ───────────────────────────────────────────────

-- The live routing matrix. One open-ended version; the exclusion constraint permits no second.
INSERT INTO core.routing_matrix_versions AS target
  (id, tenant_id, label, effective_from, effective_to, note, created_at)
VALUES
  ('81a35648-6a64-56fa-9e9c-ba98d36722e2', 'acade111-0000-4000-8000-000000000001', 'launch', '2026-01-12T10:00:00+08:00', NULL, 'The assignment matrix M20-S20 renders. Staged edits are proposals and are not applied.', '2026-01-12T10:00:00+08:00')
ON CONFLICT (tenant_id, label) DO UPDATE SET
  id = EXCLUDED.id,
  effective_to = EXCLUDED.effective_to,
  note = EXCLUDED.note
WHERE (target.id, target.effective_to, target.note)
   IS DISTINCT FROM (EXCLUDED.id, EXCLUDED.effective_to, EXCLUDED.note);

-- Eleven of the twelve assignment rows. PROPOSAL_DRAFT is dropped: this table has a
-- foreign key into app.action_types and the catalogue migration 011 provisions has
-- no PROPOSAL_DRAFT key. See the PR's schema-gap list.
INSERT INTO core.routing_entries AS target
  (id, tenant_id, version_id, action_type, tier_key, escalation_ladder, jury, required_for_autonomous, created_at)
VALUES
  ('8ea9bde3-2d7a-5edb-8049-cc416f842089', 'acade111-0000-4000-8000-000000000001', '81a35648-6a64-56fa-9e9c-ba98d36722e2', 'PROPOSAL_SEND', 'STRONG_1', ARRAY['STRONG_1', 'STRONG_2']::text[], '{"mode":"ESCALATE","quorum":2,"of":3,"tiers":["STRONG_1","STRONG_2","STRONG_3"],"triggers":{"minConfidence":0.7,"maxValueSen":5000000,"firstOfKind":true}}'::jsonb, TRUE, '2026-01-12T10:00:00+08:00'),
  ('6033dd16-ce4e-5ce8-8868-b139082b856d', 'acade111-0000-4000-8000-000000000001', '81a35648-6a64-56fa-9e9c-ba98d36722e2', 'OPPORTUNITY_CONVERT', 'FAST', ARRAY['FAST', 'MID']::text[], '{"mode":"SAMPLE","quorum":2,"of":3,"tiers":["STRONG_1","STRONG_2","STRONG_3"],"sampleRate":0.05}'::jsonb, FALSE, '2026-01-12T10:00:00+08:00'),
  ('5c500df0-1055-58b2-a2e9-8db27846e54b', 'acade111-0000-4000-8000-000000000001', '81a35648-6a64-56fa-9e9c-ba98d36722e2', 'ENQUIRY_ARCHIVE', 'CHEAP', ARRAY['CHEAP', 'FAST']::text[], '{"mode":"SAMPLE","quorum":2,"of":3,"tiers":["STRONG_1","STRONG_2","STRONG_3"],"sampleRate":0.05}'::jsonb, TRUE, '2026-01-12T10:00:00+08:00'),
  ('bf5ef2e0-b332-5b30-b633-532d715aaada', 'acade111-0000-4000-8000-000000000001', '81a35648-6a64-56fa-9e9c-ba98d36722e2', 'TNA_RECOMMENDATION_ACCEPT', 'STRONG_1', ARRAY['STRONG_1', 'DEEP_THINK']::text[], '{"mode":"GATE","quorum":2,"of":3,"tiers":["STRONG_1","STRONG_2","STRONG_3"]}'::jsonb, TRUE, '2026-01-12T10:00:00+08:00'),
  ('17352ef0-3b9d-5b67-831d-ebee8e91d089', 'acade111-0000-4000-8000-000000000001', '81a35648-6a64-56fa-9e9c-ba98d36722e2', 'QUOTATION_APPLY', 'MID', ARRAY['MID', 'STRONG_1']::text[], '{"mode":"GATE","quorum":2,"of":3,"tiers":["STRONG_1","STRONG_2","STRONG_3"]}'::jsonb, TRUE, '2026-01-12T10:00:00+08:00'),
  ('9b739efb-6665-5fce-9827-22c61af0d540', 'acade111-0000-4000-8000-000000000001', '81a35648-6a64-56fa-9e9c-ba98d36722e2', 'FOLLOWUP_SEND', 'MID', ARRAY['MID', 'STRONG_1']::text[], '{"mode":"SAMPLE","quorum":2,"of":3,"tiers":["STRONG_1","STRONG_2","STRONG_3"],"sampleRate":0.05}'::jsonb, TRUE, '2026-01-12T10:00:00+08:00'),
  ('09d62a1e-7b2e-569f-b69d-028456f632e3', 'acade111-0000-4000-8000-000000000001', '81a35648-6a64-56fa-9e9c-ba98d36722e2', 'REMINDER_SEND', 'MID', ARRAY['MID', 'STRONG_1']::text[], '{"mode":"SAMPLE","quorum":2,"of":3,"tiers":["STRONG_1","STRONG_2","STRONG_3"],"sampleRate":0.05}'::jsonb, TRUE, '2026-01-12T10:00:00+08:00'),
  ('4a370772-1077-56b4-900b-6d72d41cd8fe', 'acade111-0000-4000-8000-000000000001', '81a35648-6a64-56fa-9e9c-ba98d36722e2', 'INVOICE_CREATE', 'STRONG_1', ARRAY['STRONG_1']::text[], '{"mode":"GATE","quorum":2,"of":3,"tiers":["STRONG_1","STRONG_2","STRONG_3"]}'::jsonb, TRUE, '2026-01-12T10:00:00+08:00'),
  ('fccb6d3c-315a-5836-aaba-30476f1ab3e0', 'acade111-0000-4000-8000-000000000001', '81a35648-6a64-56fa-9e9c-ba98d36722e2', 'HRDC_PACKET_MARK_SUBMITTED', 'STRONG_2', ARRAY['STRONG_2', 'SPECIAL']::text[], '{"mode":"GATE","quorum":2,"of":3,"tiers":["STRONG_1","STRONG_2","STRONG_3"]}'::jsonb, TRUE, '2026-01-12T10:00:00+08:00'),
  ('3dfa08e9-ead7-5d57-8da1-79fe8eac8530', 'acade111-0000-4000-8000-000000000001', '81a35648-6a64-56fa-9e9c-ba98d36722e2', 'RULE_CHANGE_APPROVE', 'SPECIAL', ARRAY['STRONG_2', 'SPECIAL']::text[], '{"mode":"ESCALATE","quorum":2,"of":3,"tiers":["STRONG_1","STRONG_2","STRONG_3"],"triggers":{"minConfidence":0.8,"maxValueSen":0,"firstOfKind":true}}'::jsonb, TRUE, '2026-01-12T10:00:00+08:00'),
  ('e3444688-7707-5286-8e2f-24e043f90104', 'acade111-0000-4000-8000-000000000001', '81a35648-6a64-56fa-9e9c-ba98d36722e2', 'ATTENDANCE_APPROVE', 'FAST', ARRAY['FAST']::text[], '{"mode":"GATE","quorum":2,"of":3,"tiers":["STRONG_1","STRONG_2","STRONG_3"]}'::jsonb, TRUE, '2026-01-12T10:00:00+08:00')
ON CONFLICT (tenant_id, version_id, action_type) DO UPDATE SET
  id = EXCLUDED.id,
  tier_key = EXCLUDED.tier_key,
  escalation_ladder = EXCLUDED.escalation_ladder,
  jury = EXCLUDED.jury,
  required_for_autonomous = EXCLUDED.required_for_autonomous
WHERE (target.id, target.tier_key, target.escalation_ladder, target.jury, target.required_for_autonomous)
   IS DISTINCT FROM (EXCLUDED.id, EXCLUDED.tier_key, EXCLUDED.escalation_ladder, EXCLUDED.jury, EXCLUDED.required_for_autonomous);

-- The routing matrix's jury policy, normalised out of the jsonb for the jury queue to read.
INSERT INTO core.jury_configs AS target
  (id, tenant_id, action_type, mode, quorum, of, tiers, sample_rate, trigger_min_confidence, trigger_max_value_sen, trigger_first_of_kind, active, created_at)
VALUES
  ('112d896a-0034-5143-9190-d46c97277f09', 'acade111-0000-4000-8000-000000000001', 'PROPOSAL_SEND', 'ESCALATE', 2, 3, ARRAY['STRONG_1', 'STRONG_2', 'STRONG_3']::text[], NULL, 0.7, 5000000, TRUE, TRUE, '2026-01-12T10:00:00+08:00'),
  ('c2170d2c-9a21-5140-a7ed-1f46feed755a', 'acade111-0000-4000-8000-000000000001', 'OPPORTUNITY_CONVERT', 'SAMPLE', 2, 3, ARRAY['STRONG_1', 'STRONG_2', 'STRONG_3']::text[], 0.05, NULL, NULL, FALSE, TRUE, '2026-01-12T10:00:00+08:00'),
  ('c3b469de-77e9-51d6-bc18-b21a0530762a', 'acade111-0000-4000-8000-000000000001', 'ENQUIRY_ARCHIVE', 'SAMPLE', 2, 3, ARRAY['STRONG_1', 'STRONG_2', 'STRONG_3']::text[], 0.05, NULL, NULL, FALSE, TRUE, '2026-01-12T10:00:00+08:00'),
  ('673b38db-1c94-5c59-9e55-6583eb42a052', 'acade111-0000-4000-8000-000000000001', 'TNA_RECOMMENDATION_ACCEPT', 'GATE', 2, 3, ARRAY['STRONG_1', 'STRONG_2', 'STRONG_3']::text[], NULL, NULL, NULL, FALSE, TRUE, '2026-01-12T10:00:00+08:00'),
  ('a90b4d02-82ca-53a0-880f-5e5d1861cb2e', 'acade111-0000-4000-8000-000000000001', 'QUOTATION_APPLY', 'GATE', 2, 3, ARRAY['STRONG_1', 'STRONG_2', 'STRONG_3']::text[], NULL, NULL, NULL, FALSE, TRUE, '2026-01-12T10:00:00+08:00'),
  ('9613314d-018e-5463-b58c-b3265ea49730', 'acade111-0000-4000-8000-000000000001', 'FOLLOWUP_SEND', 'SAMPLE', 2, 3, ARRAY['STRONG_1', 'STRONG_2', 'STRONG_3']::text[], 0.05, NULL, NULL, FALSE, TRUE, '2026-01-12T10:00:00+08:00'),
  ('9e051bc1-af19-5470-9a23-3624f4fff4fa', 'acade111-0000-4000-8000-000000000001', 'REMINDER_SEND', 'SAMPLE', 2, 3, ARRAY['STRONG_1', 'STRONG_2', 'STRONG_3']::text[], 0.05, NULL, NULL, FALSE, TRUE, '2026-01-12T10:00:00+08:00'),
  ('a9d63974-5156-5acf-83ca-bea08907317c', 'acade111-0000-4000-8000-000000000001', 'INVOICE_CREATE', 'GATE', 2, 3, ARRAY['STRONG_1', 'STRONG_2', 'STRONG_3']::text[], NULL, NULL, NULL, FALSE, TRUE, '2026-01-12T10:00:00+08:00'),
  ('b37f5e18-536b-5cfd-a2ae-505ba067a7c7', 'acade111-0000-4000-8000-000000000001', 'HRDC_PACKET_MARK_SUBMITTED', 'GATE', 2, 3, ARRAY['STRONG_1', 'STRONG_2', 'STRONG_3']::text[], NULL, NULL, NULL, FALSE, TRUE, '2026-01-12T10:00:00+08:00'),
  ('e1e6588b-0d4b-51ad-9723-ceee4ae1991d', 'acade111-0000-4000-8000-000000000001', 'RULE_CHANGE_APPROVE', 'ESCALATE', 2, 3, ARRAY['STRONG_1', 'STRONG_2', 'STRONG_3']::text[], NULL, 0.8, 0, TRUE, TRUE, '2026-01-12T10:00:00+08:00'),
  ('76c1365b-4d81-569b-a1a9-bbbfb4f23a15', 'acade111-0000-4000-8000-000000000001', 'ATTENDANCE_APPROVE', 'GATE', 2, 3, ARRAY['STRONG_1', 'STRONG_2', 'STRONG_3']::text[], NULL, NULL, NULL, FALSE, TRUE, '2026-01-12T10:00:00+08:00')
ON CONFLICT (tenant_id, action_type) DO UPDATE SET
  id = EXCLUDED.id,
  mode = EXCLUDED.mode,
  quorum = EXCLUDED.quorum,
  of = EXCLUDED.of,
  tiers = EXCLUDED.tiers,
  sample_rate = EXCLUDED.sample_rate,
  trigger_min_confidence = EXCLUDED.trigger_min_confidence,
  trigger_max_value_sen = EXCLUDED.trigger_max_value_sen,
  trigger_first_of_kind = EXCLUDED.trigger_first_of_kind,
  active = EXCLUDED.active
WHERE (target.id, target.mode, target.quorum, target.of, target.tiers, target.sample_rate, target.trigger_min_confidence, target.trigger_max_value_sen, target.trigger_first_of_kind, target.active)
   IS DISTINCT FROM (EXCLUDED.id, EXCLUDED.mode, EXCLUDED.quorum, EXCLUDED.of, EXCLUDED.tiers, EXCLUDED.sample_rate, EXCLUDED.trigger_min_confidence, EXCLUDED.trigger_max_value_sen, EXCLUDED.trigger_first_of_kind, EXCLUDED.active);

-- Provider keys, budgets and usage ────────────────────────────────────────

-- Five provider keys. A masked prefix and a fingerprint, never key material.
-- `key_fingerprint` is SHA-256 of the PUBLIC provider ref, not of any secret.
-- The NOT_SET embeddings slot cannot be stored — see the PR's schema-gap list.
INSERT INTO core.ai_provider_keys AS target
  (id, tenant_id, provider_ref, provider, label, status, masked_key, key_fingerprint, key_ref, scope_tiers, cap_sen, currency, rotation_date, billing_owner, region, last_tested_at, invalid_since, active_fallback_tier, added_by, added_at, last_revealed_at, reveal_count, created_at)
VALUES
  ('f9882525-13a6-5902-8f1e-b3b808274c82', 'acade111-0000-4000-8000-000000000001', 'prv_anthropic', 'ANTHROPIC', 'Anthropic direct', 'INVALID', 'sk-ant-••••••••••••9a41', '\x862c9b16e8d245c2d67de134ff4a648cf749ebc23e4c3bfba6606ebf7aa015cf'::bytea, 'fixture://provider-keys/prv_anthropic', ARRAY['STRONG_1']::text[], 15000, 'MYR', '2027-03-01', 'CLIENT_ACCOUNT', 'US', '2026-11-14T08:40:00+08:00', '2026-11-14T08:40:00+08:00', 'STRONG_2', '{"kind":"HUMAN","id":"u_khairul","name":"Khairul Anwar"}'::jsonb, '2026-01-12T10:00:00+08:00', NULL, 0, '2026-01-12T10:00:00+08:00'),
  ('b8c29f26-b83d-588f-a7a4-5a1c0905b705', 'acade111-0000-4000-8000-000000000001', 'prv_google', 'GOOGLE', 'Google Vertex — asia-southeast1', 'VALID', 'AIza••••••••••••7c22', '\xdf68b48df7ecbfa1630c4949844902ca575b1600e7d0e0985dd42a5411121bbc'::bytea, 'fixture://provider-keys/prv_google', ARRAY['FAST', 'FAST_UI', 'STRONG_2', 'DEEP_THINK']::text[], 18500, 'MYR', '2027-06-30', 'CLIENT_ACCOUNT', 'SG', '2026-11-14T06:00:00+08:00', NULL, NULL, '{"kind":"HUMAN","id":"u_khairul","name":"Khairul Anwar"}'::jsonb, '2026-01-12T10:20:00+08:00', NULL, 0, '2026-01-12T10:20:00+08:00'),
  ('abb31f1f-641b-5421-8228-0ec06d3a3b79', 'acade111-0000-4000-8000-000000000001', 'prv_openai', 'OPENAI', 'OpenAI platform', 'EXPIRING', 'sk-proj-••••••••••••1d08', '\x279d23550d7d476de084d189bcb4ddbe01c045a0af5fad5f6af84904662adbc0'::bytea, 'fixture://provider-keys/prv_openai', ARRAY['STRONG_3']::text[], 9000, 'MYR', '2026-12-01', 'PASS_THROUGH', 'US', '2026-11-13T06:00:00+08:00', NULL, NULL, '{"kind":"HUMAN","id":"u_khairul","name":"Khairul Anwar"}'::jsonb, '2026-02-03T09:00:00+08:00', NULL, 0, '2026-02-03T09:00:00+08:00'),
  ('bd38efeb-8c9b-5047-8cf5-69983d36c41e', 'acade111-0000-4000-8000-000000000001', 'prv_deepseek', 'DEEPSEEK', 'DeepSeek platform', 'VALID', 'sk-ds-••••••••••••4b90', '\x00e3e98ce27940dde52bde7238e770a83ee3bd603e602f5f700919064dcca769'::bytea, 'fixture://provider-keys/prv_deepseek', ARRAY['MID', 'CHEAP']::text[], 16000, 'MYR', '2027-08-15', 'CLIENT_ACCOUNT', 'SG', '2026-11-14T06:00:00+08:00', NULL, NULL, '{"kind":"HUMAN","id":"u_khairul","name":"Khairul Anwar"}'::jsonb, '2026-03-18T14:30:00+08:00', NULL, 0, '2026-03-18T14:30:00+08:00'),
  ('1b77497e-c9ba-5aeb-aad9-e4d3bda31806', 'acade111-0000-4000-8000-000000000001', 'prv_anthropic_batch', 'ANTHROPIC', 'Anthropic batch — SPECIAL tier', 'VALID', 'sk-ant-••••••••••••2e17', '\xac7582cc18a46b06a82077352784a4fa049e9f1f3fdb07162f7832785f793c30'::bytea, 'fixture://provider-keys/prv_anthropic_batch', ARRAY['SPECIAL']::text[], 20000, 'MYR', '2027-03-01', 'CLIENT_ACCOUNT', 'US', '2026-11-14T06:00:00+08:00', NULL, NULL, '{"kind":"HUMAN","id":"u_khairul","name":"Khairul Anwar"}'::jsonb, '2026-05-02T11:00:00+08:00', NULL, 0, '2026-05-02T11:00:00+08:00')
ON CONFLICT (tenant_id, provider_ref) DO UPDATE SET
  id = EXCLUDED.id,
  provider = EXCLUDED.provider,
  label = EXCLUDED.label,
  status = EXCLUDED.status,
  masked_key = EXCLUDED.masked_key,
  key_ref = EXCLUDED.key_ref,
  scope_tiers = EXCLUDED.scope_tiers,
  cap_sen = EXCLUDED.cap_sen,
  currency = EXCLUDED.currency,
  rotation_date = EXCLUDED.rotation_date,
  billing_owner = EXCLUDED.billing_owner,
  region = EXCLUDED.region,
  last_tested_at = EXCLUDED.last_tested_at,
  invalid_since = EXCLUDED.invalid_since,
  active_fallback_tier = EXCLUDED.active_fallback_tier,
  last_revealed_at = EXCLUDED.last_revealed_at,
  reveal_count = EXCLUDED.reveal_count
WHERE (target.id, target.provider, target.label, target.status, target.masked_key, target.key_ref, target.scope_tiers, target.cap_sen, target.currency, target.rotation_date, target.billing_owner, target.region, target.last_tested_at, target.invalid_since, target.active_fallback_tier, target.last_revealed_at, target.reveal_count)
   IS DISTINCT FROM (EXCLUDED.id, EXCLUDED.provider, EXCLUDED.label, EXCLUDED.status, EXCLUDED.masked_key, EXCLUDED.key_ref, EXCLUDED.scope_tiers, EXCLUDED.cap_sen, EXCLUDED.currency, EXCLUDED.rotation_date, EXCLUDED.billing_owner, EXCLUDED.region, EXCLUDED.last_tested_at, EXCLUDED.invalid_since, EXCLUDED.active_fallback_tier, EXCLUDED.last_revealed_at, EXCLUDED.reveal_count);

-- Seven caps. `spend` and `state` are NOT stored: both are reads against
-- app.usage_rollup, and duplicating them here would be a second answer to one
-- question. `near_threshold` keeps the schema default of 0.800 — the fixture
-- publishes the resulting STATE, never the threshold that produced it.
INSERT INTO core.ai_budgets AS target
  (id, tenant_id, scope, key, cap_sen, currency, near_threshold, note, created_at)
VALUES
  ('dc38e74e-238b-571f-8a75-12eac47aa32e', 'acade111-0000-4000-8000-000000000001', 'TIER', 'SPECIAL', 20000, 'MYR', 0.8, NULL, '2026-01-12T10:00:00+08:00'),
  ('7c08dd79-a16d-5ad4-9184-6800da43cc7a', 'acade111-0000-4000-8000-000000000001', 'TIER', 'STRONG_1', 15000, 'MYR', 0.8, NULL, '2026-01-12T10:00:00+08:00'),
  ('486cb309-bf42-5e93-9908-003867110a0e', 'acade111-0000-4000-8000-000000000001', 'TIER', 'MID', 12000, 'MYR', 0.8, NULL, '2026-01-12T10:00:00+08:00'),
  ('2bd58356-3a1c-554f-9b3c-319415bc11a9', 'acade111-0000-4000-8000-000000000001', 'ACTION_TYPE', 'RULE_CHANGE_APPROVE', 6000, 'MYR', 0.8, NULL, '2026-01-12T10:00:00+08:00'),
  ('b07faeb0-4b3d-560d-b386-b805db762d91', 'acade111-0000-4000-8000-000000000001', 'ACTION_TYPE', 'PROPOSAL_DRAFT', 9000, 'MYR', 0.8, NULL, '2026-01-12T10:00:00+08:00'),
  ('6efa0e7d-cca2-5642-ac3d-9b5be3a2163f', 'acade111-0000-4000-8000-000000000001', 'AGENT', 'agent_proposal', 4000, 'MYR', 0.8, NULL, '2026-01-12T10:00:00+08:00'),
  ('bf4694fa-12f4-5c30-89b1-7f0ae9bc6221', 'acade111-0000-4000-8000-000000000001', 'AGENT', 'agent_compliance', 2000, 'MYR', 0.8, NULL, '2026-01-12T10:00:00+08:00')
ON CONFLICT (tenant_id, scope, key) DO UPDATE SET
  id = EXCLUDED.id,
  cap_sen = EXCLUDED.cap_sen,
  currency = EXCLUDED.currency,
  near_threshold = EXCLUDED.near_threshold,
  note = EXCLUDED.note
WHERE (target.id, target.cap_sen, target.currency, target.near_threshold, target.note)
   IS DISTINCT FROM (EXCLUDED.id, EXCLUDED.cap_sen, EXCLUDED.currency, EXCLUDED.near_threshold, EXCLUDED.note);

-- November spend, by tier, by agent and by action type — the three groupings
-- `GET /v1/ai/usage?groupBy=` serves. The fourteen-day series has no table:
-- see USAGE_DAILY in the generator.
INSERT INTO app.usage_rollup AS target
  (id, tenant_id, period, scope, key, spend_sen, currency, tokens_in, tokens_out, runs, cache_saving_sen, computed_at, created_at)
VALUES
  ('543fd763-641f-56ec-bd64-542a13d7250d', 'acade111-0000-4000-8000-000000000001', '2026-11', 'TIER', 'SPECIAL', 20000, 'MYR', 0, 0, 0, 0, '2026-11-14T10:32:00+08:00', '2026-11-14T10:32:00+08:00'),
  ('026dec61-bd95-5054-97fe-2d0afa664091', 'acade111-0000-4000-8000-000000000001', '2026-11', 'TIER', 'STRONG_1', 9600, 'MYR', 0, 0, 0, 0, '2026-11-14T10:32:00+08:00', '2026-11-14T10:32:00+08:00'),
  ('4117b503-790f-5683-8e72-d509a25657dd', 'acade111-0000-4000-8000-000000000001', '2026-11', 'TIER', 'MID', 7300, 'MYR', 0, 0, 0, 0, '2026-11-14T10:32:00+08:00', '2026-11-14T10:32:00+08:00'),
  ('52e74cc8-6def-5a98-a869-0ccf014cf5ab', 'acade111-0000-4000-8000-000000000001', '2026-11', 'TIER', 'STRONG_2', 6400, 'MYR', 0, 0, 0, 0, '2026-11-14T10:32:00+08:00', '2026-11-14T10:32:00+08:00'),
  ('4eb120d2-1c3f-5047-a1ac-924304316599', 'acade111-0000-4000-8000-000000000001', '2026-11', 'TIER', 'DEEP_THINK', 5200, 'MYR', 0, 0, 0, 0, '2026-11-14T10:32:00+08:00', '2026-11-14T10:32:00+08:00'),
  ('4abc9070-872d-5c25-a33d-672d52316cb0', 'acade111-0000-4000-8000-000000000001', '2026-11', 'AGENT', 'agent_tna', 2180, 'MYR', 0, 0, 0, 0, '2026-11-14T10:32:00+08:00', '2026-11-14T10:32:00+08:00'),
  ('c52b8114-79d1-5889-b250-afbaacb0ba55', 'acade111-0000-4000-8000-000000000001', '2026-11', 'AGENT', 'agent_proposal', 1890, 'MYR', 0, 0, 0, 0, '2026-11-14T10:32:00+08:00', '2026-11-14T10:32:00+08:00'),
  ('a2f51d97-0db6-55cc-9e58-9443fa580913', 'acade111-0000-4000-8000-000000000001', '2026-11', 'AGENT', 'agent_lead', 1240, 'MYR', 0, 0, 0, 0, '2026-11-14T10:32:00+08:00', '2026-11-14T10:32:00+08:00'),
  ('a78e83d0-406c-5e80-b856-b899afa799f1', 'acade111-0000-4000-8000-000000000001', '2026-11', 'AGENT', 'agent_compliance', 1180, 'MYR', 0, 0, 0, 0, '2026-11-14T10:32:00+08:00', '2026-11-14T10:32:00+08:00'),
  ('f8b84995-35db-5af7-b77c-1b3411622f0d', 'acade111-0000-4000-8000-000000000001', '2026-11', 'AGENT', 'agent_collections', 980, 'MYR', 0, 0, 0, 0, '2026-11-14T10:32:00+08:00', '2026-11-14T10:32:00+08:00'),
  ('34ed40b5-1371-50cf-8c29-bc28c594d7a6', 'acade111-0000-4000-8000-000000000001', '2026-11', 'ACTION_TYPE', 'RULE_CHANGE_APPROVE', 5880, 'MYR', 0, 0, 0, 0, '2026-11-14T10:32:00+08:00', '2026-11-14T10:32:00+08:00'),
  ('6b90d9f4-ff77-53e2-a37e-c999d3c7f04c', 'acade111-0000-4000-8000-000000000001', '2026-11', 'ACTION_TYPE', 'PROPOSAL_DRAFT', 4200, 'MYR', 0, 0, 0, 0, '2026-11-14T10:32:00+08:00', '2026-11-14T10:32:00+08:00'),
  ('40607937-a441-53e4-be74-836c89cba557', 'acade111-0000-4000-8000-000000000001', '2026-11', 'ACTION_TYPE', 'TNA_RECOMMENDATION_ACCEPT', 2180, 'MYR', 0, 0, 0, 0, '2026-11-14T10:32:00+08:00', '2026-11-14T10:32:00+08:00'),
  ('f890e7c1-c121-580b-95b5-960ed901d01c', 'acade111-0000-4000-8000-000000000001', '2026-11', 'ACTION_TYPE', 'REMINDER_SEND', 980, 'MYR', 0, 0, 0, 0, '2026-11-14T10:32:00+08:00', '2026-11-14T10:32:00+08:00')
ON CONFLICT (tenant_id, period, scope, key) DO UPDATE SET
  id = EXCLUDED.id,
  spend_sen = EXCLUDED.spend_sen,
  currency = EXCLUDED.currency,
  tokens_in = EXCLUDED.tokens_in,
  tokens_out = EXCLUDED.tokens_out,
  runs = EXCLUDED.runs,
  cache_saving_sen = EXCLUDED.cache_saving_sen,
  computed_at = EXCLUDED.computed_at
WHERE (target.id, target.spend_sen, target.currency, target.tokens_in, target.tokens_out, target.runs, target.cache_saving_sen, target.computed_at)
   IS DISTINCT FROM (EXCLUDED.id, EXCLUDED.spend_sen, EXCLUDED.currency, EXCLUDED.tokens_in, EXCLUDED.tokens_out, EXCLUDED.runs, EXCLUDED.cache_saving_sen, EXCLUDED.computed_at);

-- Action envelopes and approvals ──────────────────────────────────────────

-- The envelope behind each pending approval. `target_id` is NULL throughout:
-- every target belongs to slice 2 or slice 3, and `target_ref` is the pointer
-- that does not need them. `approval_request_id` is filled in below, once the
-- approvals exist — the two tables reference each other.
INSERT INTO core.action_requests AS target
  (id, tenant_id, ref, action_type, target_ref, target_entity, target_id, payload, value_sen, currency, requested_by_kind, requested_by_id, requested_by_role, agent_run_id, confidence, reasoning, evidence, context_flags, autonomy_level, granted_level, matched_policy_id, evaluation_trace, status, effects, effects_hash, suggested_draft_id, error_code, error_details, idempotency_key_id, created_at, completed_at)
VALUES
  ('3adc0ba7-ede3-5b18-aafc-b8b8a812dd67', 'acade111-0000-4000-8000-000000000001', 'ACT-2026-0768', 'DISCOUNT_APPROVE', 'QUO-2026-0179', NULL, NULL, '{}'::jsonb, 700000, 'MYR', 'HUMAN', 'u_amirah', 'SALES', NULL, NULL, 'RM 7,000 is below the RM 7,350 floor for 18 pax; policy APV-02 requires a manager decision.', '[{"n":1,"type":"QUOTATION","ref":"QUO-2026-0179","label":"Margin 23% against a 35% floor"},{"n":2,"type":"PROPOSAL","ref":"PRO-2026-0166","label":"Service recovery, 18 pax, 1 day"}]'::jsonb, '{}'::jsonb, NULL, NULL, 'APV-02', '[]'::jsonb, 'QUEUED_FOR_APPROVAL', '[]'::jsonb, NULL, NULL, NULL, NULL, NULL, '2026-11-13T13:00:00+08:00', NULL),
  ('8a4f277f-47c2-579a-adf7-ff6e131d026e', 'acade111-0000-4000-8000-000000000001', 'ACT-2026-0771', 'PROPOSAL_SEND', 'PRO-2026-0184', NULL, NULL, '{}'::jsonb, 1850000, 'MYR', 'AGENT', 'agent_proposal', NULL, 'run_4821', 0.82, 'Value above the RM 15,000 threshold in policy APV-01, and this is the first proposal to this organisation.', '[{"n":1,"type":"EMAIL","ref":"ENQ-2026-0912","label":"Enquiry email, 11 Sep — 30 managers, November, conflict & communication"},{"n":2,"type":"TNA","ref":"TNA-0042","label":"Competency gaps confirmed by Nurul Hassan"},{"n":3,"type":"PROGRAMME","ref":"PRG-0031","label":"Leading Through Change — 2 days, RM 18,500 / 30 pax"},{"n":4,"type":"TRAINER","ref":"TRN-0007","label":"Farah Aziz available 12–13 Nov"},{"n":5,"type":"QUOTATION","ref":"QUO-2026-0184","label":"Margin 41%, above 35% floor"}]'::jsonb, '{}'::jsonb, 'ACT_WITH_APPROVAL', NULL, 'APV-01', '[]'::jsonb, 'QUEUED_FOR_APPROVAL', '[]'::jsonb, NULL, NULL, NULL, NULL, NULL, '2026-09-11T09:14:12+08:00', NULL),
  ('11dcb7db-49a8-5a59-8149-307263ced0ed', 'acade111-0000-4000-8000-000000000001', 'ACT-2026-0772', 'REMINDER_SEND', 'INV-2026-0288', NULL, NULL, '{}'::jsonb, 1240000, 'MYR', 'AGENT', 'agent_collections', NULL, 'run_4926', 0.88, 'Policy FIN-03 routes every collections reminder to a human before it leaves.', '[{"n":1,"type":"INVOICE","ref":"INV-2026-0288","label":"RM 12,400 outstanding, 34 days"},{"n":2,"type":"CONTACT","ref":"CON-0233","label":"Email consent recorded 04 Mar 2024"}]'::jsonb, '{}'::jsonb, 'ACT_WITH_APPROVAL', NULL, 'FIN-03', '[]'::jsonb, 'QUEUED_FOR_APPROVAL', '[]'::jsonb, NULL, NULL, NULL, NULL, NULL, '2026-11-14T08:30:00+08:00', NULL),
  ('4e0dd838-ee03-5b05-972a-e96432cf80ba', 'acade111-0000-4000-8000-000000000001', 'ACT-2026-0773', 'RULE_CHANGE_APPROVE', 'DOC-0219', NULL, NULL, '{}'::jsonb, NULL, NULL, 'AGENT', 'agent_compliance', NULL, 'run_4912', 0.94, 'A new circular supersedes the 3-day public lead time from 1 Jan 2027; four open engagements are affected.', '[{"n":1,"type":"HRDC_STATEMENT","ref":"DOC-0219","label":"Circular 09/2026, section 2.1, page 3"}]'::jsonb, '{}'::jsonb, 'ACT_WITH_APPROVAL', NULL, 'CMP-01', '[]'::jsonb, 'QUEUED_FOR_APPROVAL', '[]'::jsonb, NULL, NULL, NULL, NULL, NULL, '2026-11-14T09:45:00+08:00', NULL),
  ('68af749d-727e-57de-8ead-271e4a2f927b', 'acade111-0000-4000-8000-000000000001', 'ACT-2026-0774', 'ATTENDANCE_APPROVE', 'ENG-0231', NULL, NULL, '{}'::jsonb, NULL, NULL, 'HUMAN', 'u_siti', 'OPS', NULL, NULL, 'Attendance lock is one-way and HRD Corp treats a locked sheet as immutable, so it is never autonomous.', '[{"n":1,"type":"PROGRAMME","ref":"PRG-0031","label":"Two-day programme, AM/PM sessions"},{"n":2,"type":"TRAINER","ref":"TRN-0007","label":"Farah Aziz signed the day-2 declaration"}]'::jsonb, '{}'::jsonb, NULL, NULL, 'OPS-01', '[]'::jsonb, 'QUEUED_FOR_APPROVAL', '[]'::jsonb, NULL, NULL, NULL, NULL, NULL, '2026-11-14T08:02:00+08:00', NULL),
  ('57cfcf82-cdb6-5880-8ca5-ff37bfc2c985', 'acade111-0000-4000-8000-000000000001', 'ACT-2026-0775', 'TRAINER_BOOK', 'ENG-0244', NULL, NULL, '{}'::jsonb, NULL, NULL, 'HUMAN', 'u_amirah', 'SALES', NULL, NULL, 'Trainer booking is a commitment to a client and never starts above act-with-approval.', '[{"n":1,"type":"TRAINER_AVAILABILITY","ref":"TRN-0007","label":"Free 14–15 Jan 2027"}]'::jsonb, '{}'::jsonb, NULL, NULL, 'OPS-03', '[]'::jsonb, 'QUEUED_FOR_APPROVAL', '[]'::jsonb, NULL, NULL, NULL, NULL, NULL, '2026-11-13T12:00:00+08:00', NULL),
  ('1b476a40-b72e-59c3-8429-b9627de4d231', 'acade111-0000-4000-8000-000000000001', 'ACT-2026-0776', 'BUDGET_CAP_RAISE', 'TIER/SPECIAL', NULL, NULL, '{}'::jsonb, 30000, 'MYR', 'HUMAN', 'u_khairul', 'ADMIN', NULL, NULL, 'The SPECIAL tier is paused by cap and rule extraction is queued behind it.', '[{"n":1,"type":"ACTION","ref":"TIER/SPECIAL","label":"Spend RM 200 of a RM 200 cap"}]'::jsonb, '{}'::jsonb, NULL, NULL, 'AI-01', '[]'::jsonb, 'QUEUED_FOR_APPROVAL', '[]'::jsonb, NULL, NULL, NULL, NULL, NULL, '2026-11-14T10:00:00+08:00', NULL)
ON CONFLICT (id) DO UPDATE SET
  tenant_id = EXCLUDED.tenant_id,
  action_type = EXCLUDED.action_type,
  target_ref = EXCLUDED.target_ref,
  target_entity = EXCLUDED.target_entity,
  target_id = EXCLUDED.target_id,
  payload = EXCLUDED.payload,
  value_sen = EXCLUDED.value_sen,
  currency = EXCLUDED.currency,
  requested_by_kind = EXCLUDED.requested_by_kind,
  requested_by_id = EXCLUDED.requested_by_id,
  requested_by_role = EXCLUDED.requested_by_role,
  agent_run_id = EXCLUDED.agent_run_id,
  confidence = EXCLUDED.confidence,
  reasoning = EXCLUDED.reasoning,
  evidence = EXCLUDED.evidence,
  context_flags = EXCLUDED.context_flags,
  autonomy_level = EXCLUDED.autonomy_level,
  granted_level = EXCLUDED.granted_level,
  matched_policy_id = EXCLUDED.matched_policy_id,
  evaluation_trace = EXCLUDED.evaluation_trace,
  status = EXCLUDED.status,
  effects = EXCLUDED.effects,
  effects_hash = EXCLUDED.effects_hash,
  suggested_draft_id = EXCLUDED.suggested_draft_id,
  error_code = EXCLUDED.error_code,
  error_details = EXCLUDED.error_details,
  idempotency_key_id = EXCLUDED.idempotency_key_id,
  completed_at = EXCLUDED.completed_at
WHERE (target.tenant_id, target.action_type, target.target_ref, target.target_entity, target.target_id, target.payload, target.value_sen, target.currency, target.requested_by_kind, target.requested_by_id, target.requested_by_role, target.agent_run_id, target.confidence, target.reasoning, target.evidence, target.context_flags, target.autonomy_level, target.granted_level, target.matched_policy_id, target.evaluation_trace, target.status, target.effects, target.effects_hash, target.suggested_draft_id, target.error_code, target.error_details, target.idempotency_key_id, target.completed_at)
   IS DISTINCT FROM (EXCLUDED.tenant_id, EXCLUDED.action_type, EXCLUDED.target_ref, EXCLUDED.target_entity, EXCLUDED.target_id, EXCLUDED.payload, EXCLUDED.value_sen, EXCLUDED.currency, EXCLUDED.requested_by_kind, EXCLUDED.requested_by_id, EXCLUDED.requested_by_role, EXCLUDED.agent_run_id, EXCLUDED.confidence, EXCLUDED.reasoning, EXCLUDED.evidence, EXCLUDED.context_flags, EXCLUDED.autonomy_level, EXCLUDED.granted_level, EXCLUDED.matched_policy_id, EXCLUDED.evaluation_trace, EXCLUDED.status, EXCLUDED.effects, EXCLUDED.effects_hash, EXCLUDED.suggested_draft_id, EXCLUDED.error_code, EXCLUDED.error_details, EXCLUDED.idempotency_key_id, EXCLUDED.completed_at);

-- Seven pending approvals: 1 breaching, 4 today, 2 this week. `policy_id` is the
-- FIXTURE's policy id, which is not always the provisioned one — see
-- POLICY_DISAGREEMENT in the generator. No decisions: every row is PENDING, so
-- core.approval_decisions has nothing to hold.
INSERT INTO core.approval_requests AS target
  (id, tenant_id, ref, action_request_id, policy_id, action_type, subject, target_ref, value_sen, currency, margin_rate, requested_by_kind, requested_by_id, requested_by_name, agent_run_id, confidence, autonomy, reason, recommendation, evidence, deviations, risk, diff, diff_hash, preview_url, approver_role, assigned_to_id, assigned_to_name, sla_due_at, escalate_at, escalated_at, escalated_to_role, expires_at, breach_notified_at, bulk_approvable, status, decision, decision_note, decided_by_id, decided_by_name, decided_at, created_at)
VALUES
  ('6def4b0b-b49c-5f2f-9854-e63987c4896b', 'acade111-0000-4000-8000-000000000001', 'APV-2026-0768', '3adc0ba7-ede3-5b18-aafc-b8b8a812dd67', 'APV-02', 'DISCOUNT_APPROVE', 'Discount below floor · Sutera Hospitality Group', 'QUO-2026-0179', 700000, 'MYR', 0.23, 'HUMAN', 'u_amirah', 'Amirah Yusof', NULL, NULL, NULL, 'RM 7,000 is below the RM 7,350 floor for 18 pax; policy APV-02 requires a manager decision.', '{"verdict":"REQUEST_CHANGES","rationale":"The account has been dormant since June and the margin at this price is 0.23, well under the 0.35 floor."}'::jsonb, '[{"n":1,"type":"QUOTATION","ref":"QUO-2026-0179","label":"Margin 23% against a 35% floor"},{"n":2,"type":"PROPOSAL","ref":"PRO-2026-0166","label":"Service recovery, 18 pax, 1 day"}]'::jsonb, '["Below the absolute tier floor, not only the margin floor."]'::jsonb, '{"level":"HIGH","note":"Sets a precedent for a dormant account returning at a discount."}'::jsonb, '[{"op":"UPDATE","entity":"Quotation","ref":"QUO-2026-0179","description":"sellPrice RM 9,800 → RM 7,000"},{"op":"UPDATE","entity":"Proposal","ref":"PRO-2026-0166","description":"value RM 9,800 → RM 7,000"}]'::jsonb, '11e13cd6687de5a24a74270ebe855916086bf21bb5c9971cfe97a23191e469f8', NULL, 'SALES_MANAGER', NULL, NULL, '2026-11-13T17:00:00+08:00', '2026-11-13T11:00:00.000Z', NULL, 'MD', '2026-11-14T05:00:00.000Z', NULL, FALSE, 'PENDING', NULL, NULL, NULL, NULL, NULL, '2026-11-13T13:00:00+08:00'),
  ('6fc206d8-3636-5f37-b82f-036df67402fb', 'acade111-0000-4000-8000-000000000001', 'APV-2026-0771', '8a4f277f-47c2-579a-adf7-ff6e131d026e', 'APV-01', 'PROPOSAL_SEND', 'Send proposal · Aurora Manufacturing Sdn Bhd', 'PRO-2026-0184', 1850000, 'MYR', 0.41, 'AGENT', 'agent_proposal', 'Proposal Agent', 'run_4821', 0.82, 'ACT_WITH_APPROVAL', 'Value above the RM 15,000 threshold in policy APV-01, and this is the first proposal to this organisation.', '{"verdict":"SEND_AS_DRAFTED","rationale":"Gap coverage complete, margin above floor, trainer confirmed available.","provenance":{"origin":"AI_GENERATED","confidence":0.82,"agentId":"agent_proposal","runId":"run_4821","tier":"STRONG_1","model":"Claude Sonnet 5","provider":"ANTHROPIC","cacheHitRate":0.41}}'::jsonb, '[{"n":1,"type":"EMAIL","ref":"ENQ-2026-0912","label":"Enquiry email, 11 Sep — 30 managers, November, conflict & communication"},{"n":2,"type":"TNA","ref":"TNA-0042","label":"Competency gaps confirmed by Nurul Hassan"},{"n":3,"type":"PROGRAMME","ref":"PRG-0031","label":"Leading Through Change — 2 days, RM 18,500 / 30 pax"},{"n":4,"type":"TRAINER","ref":"TRN-0007","label":"Farah Aziz available 12–13 Nov"},{"n":5,"type":"QUOTATION","ref":"QUO-2026-0184","label":"Margin 41%, above 35% floor"}]'::jsonb, '["Client requested November specifically.","Only one matched trainer is available in that window."]'::jsonb, '{"level":"MEDIUM","note":"Single trainer dependency — if Farah Aziz withdraws, the November window has no second-choice match at this competency level."}'::jsonb, '[{"op":"UPDATE","entity":"Proposal","ref":"PRO-2026-0184","description":"status DRAFT → SENT"},{"op":"ADD","entity":"Email","description":"To nurul.hassan@auroramfg.com.my with PDF attachment"},{"op":"UPDATE","entity":"Opportunity","ref":"OPP-0512","description":"stage → PROPOSAL_SENT"},{"op":"ADD","entity":"Task","description":"Follow-up for Amirah, due 16 Sep 2026"},{"op":"REMOVE","entity":"Quotation","ref":"QUO-2026-0184","description":"Draft lock released"}]'::jsonb, '083c974a39129db3212440390f631d9ded324d13541f25830701fd9fbaba5a7b', '/v1/proposals/PRO-2026-0184/preview?format=HTML', 'SALES_MANAGER', NULL, NULL, '2026-09-11T13:14:00+08:00', '2026-09-11T07:14:12.000Z', NULL, 'MD', '2026-09-12T01:14:12.000Z', NULL, FALSE, 'PENDING', NULL, NULL, NULL, NULL, NULL, '2026-09-11T09:14:12+08:00'),
  ('de87ef7a-3c43-5823-aa91-96ef04456cc4', 'acade111-0000-4000-8000-000000000001', 'APV-2026-0772', '11dcb7db-49a8-5a59-8149-307263ced0ed', 'FIN-03', 'REMINDER_SEND', 'Send reminder 2 · INV-2026-0288, 34 days overdue', 'INV-2026-0288', 1240000, 'MYR', NULL, 'AGENT', 'agent_collections', 'Collections Agent', 'run_4926', 0.88, 'ACT_WITH_APPROVAL', 'Policy FIN-03 routes every collections reminder to a human before it leaves.', '{"verdict":"SEND_AS_DRAFTED","rationale":"Second reminder is due at 30 days; the contact has email consent on record."}'::jsonb, '[{"n":1,"type":"INVOICE","ref":"INV-2026-0288","label":"RM 12,400 outstanding, 34 days"},{"n":2,"type":"CONTACT","ref":"CON-0233","label":"Email consent recorded 04 Mar 2024"}]'::jsonb, '["The account also has a proposal in flight, so tone is softened."]'::jsonb, '{"level":"LOW","note":"Repeat client with a clean payment history before this invoice."}'::jsonb, '[{"op":"ADD","entity":"Email","description":"Reminder 2 to nurul.hassan@auroramfg.com.my"},{"op":"UPDATE","entity":"Receivable","ref":"INV-2026-0288","description":"stage REMINDER_2 → REMINDER_3 due 25 Nov"}]'::jsonb, '1286e43cbd3540c44feedd38c2eccc0e7a0c5e54a0ca9e758f0459f279028e44', NULL, 'FINANCE', NULL, NULL, '2026-11-14T14:30:00+08:00', '2026-11-14T08:30:00.000Z', NULL, 'MD', '2026-11-15T00:30:00.000Z', NULL, FALSE, 'PENDING', NULL, NULL, NULL, NULL, NULL, '2026-11-14T08:30:00+08:00'),
  ('734f618d-0d29-54d3-8290-acd92e25cc1c', 'acade111-0000-4000-8000-000000000001', 'APV-2026-0773', '4e0dd838-ee03-5b05-972a-e96432cf80ba', 'CMP-01', 'RULE_CHANGE_APPROVE', 'Approve 1 rule change · Circular 09/2026', 'DOC-0219', NULL, NULL, NULL, 'AGENT', 'agent_compliance', 'Compliance Agent', 'run_4912', 0.94, 'ACT_WITH_APPROVAL', 'A new circular supersedes the 3-day public lead time from 1 Jan 2027; four open engagements are affected.', '{"verdict":"APPROVE","rationale":"Extraction confidence 0.94, source span quoted verbatim from section 2.1."}'::jsonb, '[{"n":1,"type":"HRDC_STATEMENT","ref":"DOC-0219","label":"Circular 09/2026, section 2.1, page 3"}]'::jsonb, '["Effective date is the circular''s, not today''s."]'::jsonb, '{"level":"MEDIUM","note":"Two January engagements were scheduled under the old lead time."}'::jsonb, '[{"op":"UPDATE","entity":"ComplianceRule","ref":"HRD-015","description":"status ACTIVE → SUPERSEDED from 2027-01-01"},{"op":"ADD","entity":"ComplianceRule","ref":"HRD-022","description":"Public lead time 14 calendar days"}]'::jsonb, '2cf75c90845d47391a5306300913739afb65333f50fb38e1a8cee32e443c15fe', NULL, 'FINANCE', NULL, NULL, '2026-11-14T18:00:00+08:00', NULL, NULL, NULL, '2026-11-15T01:45:00.000Z', NULL, TRUE, 'PENDING', NULL, NULL, NULL, NULL, NULL, '2026-11-14T09:45:00+08:00'),
  ('d35859db-0af2-517c-8e52-d2a6c7590a3f', 'acade111-0000-4000-8000-000000000001', 'APV-2026-0774', '68af749d-727e-57de-8ead-271e4a2f927b', 'OPS-01', 'ATTENDANCE_APPROVE', 'Lock attendance · ENG-0231 day 2, 28 of 30 present', 'ENG-0231', NULL, NULL, NULL, 'HUMAN', 'u_siti', 'Siti Nordin', NULL, NULL, NULL, 'Attendance lock is one-way and HRD Corp treats a locked sheet as immutable, so it is never autonomous.', '{"verdict":"APPROVE","rationale":"Signatures reconcile at 56 of 56 expected for the present participants."}'::jsonb, '[{"n":1,"type":"PROGRAMME","ref":"PRG-0031","label":"Two-day programme, AM/PM sessions"},{"n":2,"type":"TRAINER","ref":"TRN-0007","label":"Farah Aziz signed the day-2 declaration"}]'::jsonb, '["Two participants absent on medical leave both days."]'::jsonb, '{"level":"LOW","note":"Locking day 2 completes the attendance evidence for the claim packet."}'::jsonb, '[{"op":"UPDATE","entity":"AttendanceSheet","ref":"ENG-0231/day-2","description":"status PENDING_APPROVAL → LOCKED"},{"op":"UPDATE","entity":"Engagement","ref":"ENG-0231","description":"lifecycle ATTENDANCE_LOCKED → DONE"}]'::jsonb, '73a84c10c419b9d8282e9aabec8b1aebaa5ef04317e373bfa4eec121cc9ba333', NULL, 'OPS', NULL, NULL, '2026-11-14T17:00:00+08:00', NULL, NULL, NULL, '2026-11-15T00:02:00.000Z', NULL, TRUE, 'PENDING', NULL, NULL, NULL, NULL, NULL, '2026-11-14T08:02:00+08:00'),
  ('36bd5dcf-55e3-57dd-8aab-208d7c605080', 'acade111-0000-4000-8000-000000000001', 'APV-2026-0775', '57cfcf82-cdb6-5880-8ca5-ff37bfc2c985', 'OPS-03', 'TRAINER_BOOK', 'Confirm trainer · Kenanga Retail, 14–15 Jan 2027', 'ENG-0244', NULL, NULL, NULL, 'HUMAN', 'u_amirah', 'Amirah Yusof', NULL, NULL, NULL, 'Trainer booking is a commitment to a client and never starts above act-with-approval.', '{"verdict":"APPROVE","rationale":"Farah Aziz is free in the window and TTT certification runs to 30 Jun 2027."}'::jsonb, '[{"n":1,"type":"TRAINER_AVAILABILITY","ref":"TRN-0007","label":"Free 14–15 Jan 2027"}]'::jsonb, '[]'::jsonb, '{"level":"LOW","note":"Two months of notice."}'::jsonb, '[{"op":"UPDATE","entity":"Engagement","ref":"ENG-0244","description":"trainer soft-hold → confirmed"}]'::jsonb, 'c27ee239c527da4a9ebc760f28783800efece297ada3d89eaacc509e559ee81d', NULL, 'OPS', NULL, NULL, '2026-11-18T12:00:00+08:00', NULL, NULL, NULL, '2026-11-14T04:00:00.000Z', NULL, TRUE, 'PENDING', NULL, NULL, NULL, NULL, NULL, '2026-11-13T12:00:00+08:00'),
  ('95911a00-9a53-5e61-9b09-6c2bc92832c7', 'acade111-0000-4000-8000-000000000001', 'APV-2026-0776', '1b476a40-b72e-59c3-8429-b9627de4d231', 'AI-01', 'BUDGET_CAP_RAISE', 'Raise SPECIAL tier cap · RM 200 → RM 300', 'TIER/SPECIAL', 30000, 'MYR', NULL, 'HUMAN', 'u_khairul', 'Khairul Anwar', NULL, NULL, NULL, 'The SPECIAL tier is paused by cap and rule extraction is queued behind it.', '{"verdict":"APPROVE","rationale":"Forecast RM 812 against a RM 940 overall cap; the raise stays inside it."}'::jsonb, '[{"n":1,"type":"ACTION","ref":"TIER/SPECIAL","label":"Spend RM 200 of a RM 200 cap"}]'::jsonb, '["Second raise this quarter."]'::jsonb, '{"level":"MEDIUM","note":"Opus-class calls are the most expensive per run."}'::jsonb, '[{"op":"UPDATE","entity":"Budget","ref":"TIER/SPECIAL","description":"cap RM 200 → RM 300"}]'::jsonb, 'b2fdf110035a7cfc77eb932fceee74921154966c91c6590fe89a948ae12bab37', NULL, 'MD', NULL, NULL, '2026-11-17T10:00:00+08:00', NULL, NULL, NULL, '2026-11-15T02:00:00.000Z', NULL, FALSE, 'PENDING', NULL, NULL, NULL, NULL, NULL, '2026-11-14T10:00:00+08:00')
ON CONFLICT (id) DO UPDATE SET
  tenant_id = EXCLUDED.tenant_id,
  action_request_id = EXCLUDED.action_request_id,
  policy_id = EXCLUDED.policy_id,
  action_type = EXCLUDED.action_type,
  subject = EXCLUDED.subject,
  target_ref = EXCLUDED.target_ref,
  value_sen = EXCLUDED.value_sen,
  currency = EXCLUDED.currency,
  margin_rate = EXCLUDED.margin_rate,
  requested_by_kind = EXCLUDED.requested_by_kind,
  requested_by_id = EXCLUDED.requested_by_id,
  requested_by_name = EXCLUDED.requested_by_name,
  agent_run_id = EXCLUDED.agent_run_id,
  confidence = EXCLUDED.confidence,
  autonomy = EXCLUDED.autonomy,
  reason = EXCLUDED.reason,
  recommendation = EXCLUDED.recommendation,
  evidence = EXCLUDED.evidence,
  deviations = EXCLUDED.deviations,
  risk = EXCLUDED.risk,
  diff = EXCLUDED.diff,
  diff_hash = EXCLUDED.diff_hash,
  preview_url = EXCLUDED.preview_url,
  approver_role = EXCLUDED.approver_role,
  assigned_to_id = EXCLUDED.assigned_to_id,
  assigned_to_name = EXCLUDED.assigned_to_name,
  sla_due_at = EXCLUDED.sla_due_at,
  escalate_at = EXCLUDED.escalate_at,
  escalated_at = EXCLUDED.escalated_at,
  escalated_to_role = EXCLUDED.escalated_to_role,
  expires_at = EXCLUDED.expires_at,
  breach_notified_at = EXCLUDED.breach_notified_at,
  bulk_approvable = EXCLUDED.bulk_approvable,
  status = EXCLUDED.status,
  decision = EXCLUDED.decision,
  decision_note = EXCLUDED.decision_note,
  decided_by_id = EXCLUDED.decided_by_id,
  decided_by_name = EXCLUDED.decided_by_name,
  decided_at = EXCLUDED.decided_at
WHERE (target.tenant_id, target.action_request_id, target.policy_id, target.action_type, target.subject, target.target_ref, target.value_sen, target.currency, target.margin_rate, target.requested_by_kind, target.requested_by_id, target.requested_by_name, target.agent_run_id, target.confidence, target.autonomy, target.reason, target.recommendation, target.evidence, target.deviations, target.risk, target.diff, target.diff_hash, target.preview_url, target.approver_role, target.assigned_to_id, target.assigned_to_name, target.sla_due_at, target.escalate_at, target.escalated_at, target.escalated_to_role, target.expires_at, target.breach_notified_at, target.bulk_approvable, target.status, target.decision, target.decision_note, target.decided_by_id, target.decided_by_name, target.decided_at)
   IS DISTINCT FROM (EXCLUDED.tenant_id, EXCLUDED.action_request_id, EXCLUDED.policy_id, EXCLUDED.action_type, EXCLUDED.subject, EXCLUDED.target_ref, EXCLUDED.value_sen, EXCLUDED.currency, EXCLUDED.margin_rate, EXCLUDED.requested_by_kind, EXCLUDED.requested_by_id, EXCLUDED.requested_by_name, EXCLUDED.agent_run_id, EXCLUDED.confidence, EXCLUDED.autonomy, EXCLUDED.reason, EXCLUDED.recommendation, EXCLUDED.evidence, EXCLUDED.deviations, EXCLUDED.risk, EXCLUDED.diff, EXCLUDED.diff_hash, EXCLUDED.preview_url, EXCLUDED.approver_role, EXCLUDED.assigned_to_id, EXCLUDED.assigned_to_name, EXCLUDED.sla_due_at, EXCLUDED.escalate_at, EXCLUDED.escalated_at, EXCLUDED.escalated_to_role, EXCLUDED.expires_at, EXCLUDED.breach_notified_at, EXCLUDED.bulk_approvable, EXCLUDED.status, EXCLUDED.decision, EXCLUDED.decision_note, EXCLUDED.decided_by_id, EXCLUDED.decided_by_name, EXCLUDED.decided_at);

-- Close the loop: each envelope now names the approval it is queued behind.
UPDATE core.action_requests AS target
   SET approval_request_id = pair.approval_request_id
  FROM (VALUES
    ('3adc0ba7-ede3-5b18-aafc-b8b8a812dd67'::uuid, '6def4b0b-b49c-5f2f-9854-e63987c4896b'::uuid),
    ('8a4f277f-47c2-579a-adf7-ff6e131d026e'::uuid, '6fc206d8-3636-5f37-b82f-036df67402fb'::uuid),
    ('11dcb7db-49a8-5a59-8149-307263ced0ed'::uuid, 'de87ef7a-3c43-5823-aa91-96ef04456cc4'::uuid),
    ('4e0dd838-ee03-5b05-972a-e96432cf80ba'::uuid, '734f618d-0d29-54d3-8290-acd92e25cc1c'::uuid),
    ('68af749d-727e-57de-8ead-271e4a2f927b'::uuid, 'd35859db-0af2-517c-8e52-d2a6c7590a3f'::uuid),
    ('57cfcf82-cdb6-5880-8ca5-ff37bfc2c985'::uuid, '36bd5dcf-55e3-57dd-8aab-208d7c605080'::uuid),
    ('1b476a40-b72e-59c3-8429-b9627de4d231'::uuid, '95911a00-9a53-5e61-9b09-6c2bc92832c7'::uuid)
  ) AS pair(action_request_id, approval_request_id)
 WHERE target.tenant_id = 'acade111-0000-4000-8000-000000000001'
   AND target.id = pair.action_request_id
   AND target.approval_request_id IS DISTINCT FROM pair.approval_request_id;

-- Runs ────────────────────────────────────────────────────────────────────

-- Eight runs. run_4821 is the §17 trace in full, halted at send_proposal by APV-01,
-- which is how the trace proves the agent never sent anything; run_4903 is the
-- dead-lettered failure and run_4930 the one that only succeeded after a retry.
--
-- `finished_at` is `started_at` + `durationMs`: the fixture times the run and names
-- its start, and a finish that contradicted the duration would be a third fact.
-- The run-level `halted_by` is the halting STEP's, for the same reason.
INSERT INTO core.runs AS target
  (id, tenant_id, ref, agent_id, orchestrator, trigger, mode, status, outcome, failure, halted_by, model, tiers_used, cache_hit_rate, tokens_in, tokens_out, cost_sen, currency, guardrails, routing_version_id, started_at, finished_at, duration_ms, parent_run_id, replay_of_run_id, correlation_id, action_request_id, acknowledged_at, acknowledged_by, redacted_at, created_at)
VALUES
  ('f4aa02ce-8cb4-5338-8d0f-462148a6a949', 'acade111-0000-4000-8000-000000000001', '#4821', 'agent_proposal', 'proposal_orchestrator', '{"type":"TNA_SIGNED_OFF","ref":"TNA-0042"}'::jsonb, 'LIVE', 'HALTED', 'QUEUED_FOR_APPROVAL', NULL, '{"policyId":"APV-01","approvalRequestRef":"APV-2026-0771","reason":"Value RM 18,500 exceeds RM 15,000"}'::jsonb, 'Claude Sonnet 5', ARRAY['FAST', 'MID', 'STRONG_1']::text[], 0.58, 31204, 7208, 38, 'MYR', ARRAY['APV-01 value threshold', 'No PII in prompt', 'Rate card ≤ 24h old', 'Approved template version', 'Max 8 tool calls']::text[], '81a35648-6a64-56fa-9e9c-ba98d36722e2', '2026-09-11T09:14:02+08:00', '2026-09-11T01:14:16.200Z', 14200, NULL, NULL, '53be8b7b-1cdc-5f36-8a04-f1fc4cc5a553', '8a4f277f-47c2-579a-adf7-ff6e131d026e', NULL, NULL, NULL, '2026-09-11T09:14:02+08:00'),
  ('dbff2c3a-57a9-5a56-8eb6-1b82728e0553', 'acade111-0000-4000-8000-000000000001', '#4788', 'agent_lead', NULL, '{"type":"ENQUIRY_RECEIVED","ref":"ENQ-2026-0912"}'::jsonb, 'LIVE', 'SUCCEEDED', 'CLASSIFIED', NULL, NULL, 'Gemini 3.1 Flash', ARRAY['FAST']::text[], 0.71, 2100, 380, 1, 'MYR', ARRAY['No PII in prompt', 'Max 4 tool calls']::text[], '81a35648-6a64-56fa-9e9c-ba98d36722e2', '2026-09-11T08:52:40+08:00', '2026-09-11T00:52:42.200Z', 2200, NULL, NULL, 'd77ed49d-e1e2-53aa-b678-da1025dda5a0', NULL, NULL, NULL, NULL, '2026-09-11T08:52:40+08:00'),
  ('72a1d1ec-07cb-523d-a4ed-5c1cdd964c03', 'acade111-0000-4000-8000-000000000001', '#4884', 'agent_tna', NULL, '{"type":"TNA_COMPLETED","ref":"TNA-0042"}'::jsonb, 'LIVE', 'SUCCEEDED', 'RECOMMENDATIONS_READY', NULL, NULL, 'Claude Sonnet 5', ARRAY['STRONG_1']::text[], 0.38, 14200, 3100, 12, 'MYR', ARRAY['No PII in prompt', 'Catalogue read-only']::text[], '81a35648-6a64-56fa-9e9c-ba98d36722e2', '2026-09-11T09:12:20+08:00', '2026-09-11T01:12:29.100Z', 9100, NULL, NULL, '5e762d99-abab-55f9-96b4-12bf31a712c4', NULL, NULL, NULL, NULL, '2026-09-11T09:12:20+08:00'),
  ('70d472fe-579b-5a80-bdce-b3e34b0c98bf', 'acade111-0000-4000-8000-000000000001', '#4899', 'agent_followup', NULL, '{"type":"FOLLOW_UP_DUE","ref":"FUP-0311"}'::jsonb, 'LIVE', 'SUCCEEDED', 'SUGGESTED', NULL, NULL, 'DeepSeek V4 Pro', ARRAY['MID']::text[], 0.66, 3900, 620, 3, 'MYR', ARRAY['PDPA consent check', 'Template category locked to UTILITY']::text[], '81a35648-6a64-56fa-9e9c-ba98d36722e2', '2026-09-16T08:01:40+08:00', '2026-09-16T00:01:43.400Z', 3400, NULL, NULL, 'a9455758-39b4-570d-8858-65f743574d7f', NULL, NULL, NULL, NULL, '2026-09-16T08:01:40+08:00'),
  ('60c0f303-02ef-5c7d-a0ee-622202c00bfd', 'acade111-0000-4000-8000-000000000001', '#4912', 'agent_compliance', NULL, '{"type":"SOURCE_CHANGED","ref":"DOC-0219"}'::jsonb, 'LIVE', 'SUCCEEDED', 'RULE_CHANGES_PROPOSED', NULL, NULL, 'Gemini 3.1 Pro', ARRAY['STRONG_2']::text[], 0.57, 42100, 5200, 9, 'MYR', ARRAY['Extraction only — never activates a rule', 'Confidence floor 0.80 for the diff view']::text[], '81a35648-6a64-56fa-9e9c-ba98d36722e2', '2026-11-14T09:40:10+08:00', '2026-11-14T01:40:32.400Z', 22400, NULL, NULL, '7a00f9f3-09f8-5b86-b37f-42f3fd57e25d', '4e0dd838-ee03-5b05-972a-e96432cf80ba', NULL, NULL, NULL, '2026-11-14T09:40:10+08:00'),
  ('684eca68-f00d-5173-a345-33537f6790d1', 'acade111-0000-4000-8000-000000000001', '#4926', 'agent_collections', NULL, '{"type":"RECEIVABLE_AGED","ref":"INV-2026-0288"}'::jsonb, 'LIVE', 'SUCCEEDED', 'QUEUED_FOR_APPROVAL', NULL, NULL, 'DeepSeek V4 Pro', ARRAY['MID']::text[], 0.74, 3100, 540, 2, 'MYR', ARRAY['PDPA consent check', 'FIN-03 approval required']::text[], '81a35648-6a64-56fa-9e9c-ba98d36722e2', '2026-11-14T08:29:30+08:00', '2026-11-14T00:29:32.900Z', 2900, NULL, NULL, 'ac641b1e-8e30-536e-b0ce-a0586cdd144c', '11dcb7db-49a8-5a59-8149-307263ced0ed', NULL, NULL, NULL, '2026-11-14T08:29:30+08:00'),
  ('023f558a-41ad-554f-9dea-df31454de5c6', 'acade111-0000-4000-8000-000000000001', '#4930', 'agent_compliance', NULL, '{"type":"PACKET_ASSEMBLE","ref":"ENG-0231"}'::jsonb, 'LIVE', 'SUCCEEDED', 'PACKET_ASSEMBLED', NULL, NULL, 'Gemini 3.1 Pro', ARRAY['STRONG_2']::text[], 0.61, 20400, 2600, 7, 'MYR', ARRAY['Document store read-only', 'Max 12 tool calls']::text[], '81a35648-6a64-56fa-9e9c-ba98d36722e2', '2026-11-14T10:29:00+08:00', '2026-11-14T02:29:18.700Z', 18700, NULL, NULL, 'ca94af9b-0050-5b8f-a14e-364b9ab3fff8', NULL, NULL, NULL, NULL, '2026-11-14T10:29:00+08:00'),
  ('a2f656be-b8a8-5222-86d3-bc46910b9121', 'acade111-0000-4000-8000-000000000001', '#4903', 'agent_collections', NULL, '{"type":"RECEIVABLE_AGED","ref":"INV-2026-0279"}'::jsonb, 'LIVE', 'FAILED', 'DEAD_LETTERED', '{"code":"WA_TEMPLATE_REJECTED","message":"Template tpl_collections_reminder3_v1 is not approved for the UTILITY category","attempts":3,"retryable":true,"deadLettered":true}'::jsonb, NULL, 'DeepSeek V4 Pro', ARRAY['MID']::text[], 0.4, 5200, 300, 4, 'MYR', ARRAY['PDPA consent check', 'Template category locked to UTILITY']::text[], '81a35648-6a64-56fa-9e9c-ba98d36722e2', '2026-11-12T08:30:00+08:00', '2026-11-12T00:30:41.200Z', 41200, NULL, NULL, '8b603bcb-a4ef-5f9d-a2c4-2e92b8cda3df', NULL, NULL, NULL, NULL, '2026-11-12T08:30:00+08:00')
ON CONFLICT (id) DO UPDATE SET
  tenant_id = EXCLUDED.tenant_id,
  agent_id = EXCLUDED.agent_id,
  orchestrator = EXCLUDED.orchestrator,
  status = EXCLUDED.status,
  outcome = EXCLUDED.outcome,
  failure = EXCLUDED.failure,
  halted_by = EXCLUDED.halted_by,
  model = EXCLUDED.model,
  tiers_used = EXCLUDED.tiers_used,
  cache_hit_rate = EXCLUDED.cache_hit_rate,
  tokens_in = EXCLUDED.tokens_in,
  tokens_out = EXCLUDED.tokens_out,
  cost_sen = EXCLUDED.cost_sen,
  currency = EXCLUDED.currency,
  guardrails = EXCLUDED.guardrails,
  routing_version_id = EXCLUDED.routing_version_id,
  finished_at = EXCLUDED.finished_at,
  duration_ms = EXCLUDED.duration_ms,
  parent_run_id = EXCLUDED.parent_run_id,
  replay_of_run_id = EXCLUDED.replay_of_run_id,
  action_request_id = EXCLUDED.action_request_id,
  acknowledged_at = EXCLUDED.acknowledged_at,
  acknowledged_by = EXCLUDED.acknowledged_by,
  redacted_at = EXCLUDED.redacted_at
WHERE (target.tenant_id, target.agent_id, target.orchestrator, target.status, target.outcome, target.failure, target.halted_by, target.model, target.tiers_used, target.cache_hit_rate, target.tokens_in, target.tokens_out, target.cost_sen, target.currency, target.guardrails, target.routing_version_id, target.finished_at, target.duration_ms, target.parent_run_id, target.replay_of_run_id, target.action_request_id, target.acknowledged_at, target.acknowledged_by, target.redacted_at)
   IS DISTINCT FROM (EXCLUDED.tenant_id, EXCLUDED.agent_id, EXCLUDED.orchestrator, EXCLUDED.status, EXCLUDED.outcome, EXCLUDED.failure, EXCLUDED.halted_by, EXCLUDED.model, EXCLUDED.tiers_used, EXCLUDED.cache_hit_rate, EXCLUDED.tokens_in, EXCLUDED.tokens_out, EXCLUDED.cost_sen, EXCLUDED.currency, EXCLUDED.guardrails, EXCLUDED.routing_version_id, EXCLUDED.finished_at, EXCLUDED.duration_ms, EXCLUDED.parent_run_id, EXCLUDED.replay_of_run_id, EXCLUDED.action_request_id, EXCLUDED.acknowledged_at, EXCLUDED.acknowledged_by, EXCLUDED.redacted_at);

-- The execution tree where the fixture gives one, the tool list where it gives that instead.
INSERT INTO core.run_nodes AS target
  (id, tenant_id, run_id, node_key, parent_node_id, seq, kind, name, tier, model, provider, tokens_in, tokens_out, cache_hit_rate, cost_sen, status, retries, duration_ms, args, result, error, halted_by, started_at, finished_at, created_at)
VALUES
  ('9fca9075-ee37-586a-a134-c48f732aef33', 'acade111-0000-4000-8000-000000000001', 'f4aa02ce-8cb4-5338-8d0f-462148a6a949', 'n0', NULL, 0, 'ORCHESTRATOR', 'Orchestrator', 'MID', 'DeepSeek V4 Pro', 'DEEPSEEK', 6200, 1100, 0.44, 6, 'OK', 0, 2100, NULL, NULL, NULL, NULL, '2026-09-11T09:14:02+08:00', NULL, '2026-09-11T09:14:02+08:00'),
  ('403c9d17-5611-54bf-b519-9e0ff43683d6', 'acade111-0000-4000-8000-000000000001', 'f4aa02ce-8cb4-5338-8d0f-462148a6a949', 'n1', '9fca9075-ee37-586a-a134-c48f732aef33', 1, 'SUB_AGENT', 'Reader', 'FAST', 'Gemini 3.1 Flash', 'GOOGLE', 4100, 600, 0.82, 1, 'OK', 0, 800, NULL, NULL, NULL, NULL, '2026-09-11T09:14:02+08:00', NULL, '2026-09-11T09:14:02+08:00'),
  ('7f5f7053-0fc2-58fe-8216-f9e8abb5c2dc', 'acade111-0000-4000-8000-000000000001', 'f4aa02ce-8cb4-5338-8d0f-462148a6a949', 'n2', '9fca9075-ee37-586a-a134-c48f732aef33', 2, 'SUB_AGENT', 'Matcher', 'MID', 'DeepSeek V4 Pro', 'DEEPSEEK', 5200, 900, 0.61, 4, 'OK', 0, 1900, NULL, NULL, NULL, NULL, '2026-09-11T09:14:02+08:00', NULL, '2026-09-11T09:14:02+08:00'),
  ('9dfd2a8d-7d68-5c0a-8a8f-3c304d50563c', 'acade111-0000-4000-8000-000000000001', 'f4aa02ce-8cb4-5338-8d0f-462148a6a949', 'n3', '9fca9075-ee37-586a-a134-c48f732aef33', 3, 'SUB_AGENT', 'Drafter', 'STRONG_1', 'Claude Sonnet 5', 'ANTHROPIC', 12400, 3800, 0.41, 19, 'RETRIED', 1, 6900, NULL, NULL, NULL, NULL, '2026-09-11T09:14:02+08:00', NULL, '2026-09-11T09:14:02+08:00'),
  ('83648c68-0284-5d9a-8f8d-a5fcafafd702', 'acade111-0000-4000-8000-000000000001', 'f4aa02ce-8cb4-5338-8d0f-462148a6a949', 'n4', '9fca9075-ee37-586a-a134-c48f732aef33', 4, 'SUB_AGENT', 'Verifier', 'STRONG_1', 'Claude Sonnet 5', 'ANTHROPIC', 3300, 800, 0.55, 8, 'OK', 0, 2500, NULL, NULL, NULL, NULL, '2026-09-11T09:14:02+08:00', NULL, '2026-09-11T09:14:02+08:00'),
  ('d2cabc0e-922c-5a95-9669-6b6adfbf270e', 'acade111-0000-4000-8000-000000000001', 'f4aa02ce-8cb4-5338-8d0f-462148a6a949', 'n5', '9fca9075-ee37-586a-a134-c48f732aef33', 5, 'TOOL', 'send_proposal', NULL, NULL, NULL, NULL, NULL, NULL, 0, 'HALTED', 0, 0, NULL, NULL, NULL, '{"policyId":"APV-01","approvalRequestRef":"APV-2026-0771","reason":"Value RM 18,500 exceeds RM 15,000"}'::jsonb, '2026-09-11T09:14:02+08:00', NULL, '2026-09-11T09:14:02+08:00'),
  ('a4c2e70c-344c-5b22-bbb1-7235ce453e69', 'acade111-0000-4000-8000-000000000001', 'dbff2c3a-57a9-5a56-8eb6-1b82728e0553', 'classify_enquiry', NULL, 1, 'TOOL', 'classify_enquiry', NULL, NULL, NULL, NULL, NULL, NULL, 1, 'OK', 0, 1200, '{"ref":"ENQ-2026-0912"}'::jsonb, '{"label":"LEADERSHIP","confidence":0.94}'::jsonb, NULL, NULL, '2026-09-11T08:52:40+08:00', NULL, '2026-09-11T08:52:40+08:00'),
  ('499d98a3-ae4f-57d7-b8b0-170e457e1a8b', 'acade111-0000-4000-8000-000000000001', 'dbff2c3a-57a9-5a56-8eb6-1b82728e0553', 'match_organisation', NULL, 2, 'TOOL', 'match_organisation', NULL, NULL, NULL, NULL, NULL, NULL, 0, 'OK', 0, 400, '{"domain":"auroramfg.com.my"}'::jsonb, '{"ref":"ORG-0114","matchReason":"EXACT_DOMAIN"}'::jsonb, NULL, NULL, '2026-09-11T08:52:40+08:00', NULL, '2026-09-11T08:52:40+08:00'),
  ('8d85e0ab-8f5c-561d-ac24-0f427110b69e', 'acade111-0000-4000-8000-000000000001', '023f558a-41ad-554f-9dea-df31454de5c6', 'list_documents', NULL, 1, 'TOOL', 'list_documents', NULL, NULL, NULL, NULL, NULL, NULL, 0, 'OK', 0, 700, '{"engagementRef":"ENG-0231"}'::jsonb, '{"present":3,"required":5}'::jsonb, NULL, NULL, '2026-11-14T10:29:00+08:00', NULL, '2026-11-14T10:29:00+08:00'),
  ('252b1623-9f99-5e44-92d0-1e1a48c88f81', 'acade111-0000-4000-8000-000000000001', '023f558a-41ad-554f-9dea-df31454de5c6', 'fetch_attendance_export', NULL, 2, 'TOOL', 'fetch_attendance_export', NULL, NULL, NULL, NULL, NULL, NULL, 2, 'RETRIED', 2, 11400, '{"engagementRef":"ENG-0231","day":1}'::jsonb, NULL, '{"attempt":2,"code":"STORAGE_TIMEOUT","message":"Export bundle not ready"}'::jsonb, NULL, '2026-11-14T10:29:00+08:00', NULL, '2026-11-14T10:29:00+08:00'),
  ('a8842a6a-0c01-50c0-a98f-890fe8d7e8c7', 'acade111-0000-4000-8000-000000000001', '023f558a-41ad-554f-9dea-df31454de5c6', 'write_packet', NULL, 3, 'TOOL', 'write_packet', NULL, NULL, NULL, NULL, NULL, NULL, 1, 'OK', 0, 1900, '{"engagementRef":"ENG-0231"}'::jsonb, '{"completeness":0.62}'::jsonb, NULL, NULL, '2026-11-14T10:29:00+08:00', NULL, '2026-11-14T10:29:00+08:00'),
  ('bea643e1-0cee-587d-bbe9-7698afb4c708', 'acade111-0000-4000-8000-000000000001', 'a2f656be-b8a8-5222-86d3-bc46910b9121', 'load_receivable', NULL, 1, 'TOOL', 'load_receivable', NULL, NULL, NULL, NULL, NULL, NULL, 0, 'OK', 0, 600, '{"ref":"INV-2026-0279"}'::jsonb, '{"daysOverdue":46}'::jsonb, NULL, NULL, '2026-11-12T08:30:00+08:00', NULL, '2026-11-12T08:30:00+08:00'),
  ('753a1187-fcae-5712-8256-c313890e471a', 'acade111-0000-4000-8000-000000000001', 'a2f656be-b8a8-5222-86d3-bc46910b9121', 'send_whatsapp_template', NULL, 2, 'TOOL', 'send_whatsapp_template', NULL, NULL, NULL, NULL, NULL, NULL, 4, 'FAILED', 3, 40200, '{"templateId":"tpl_collections_reminder3_v1"}'::jsonb, NULL, '{"attempt":3,"code":"WA_TEMPLATE_REJECTED","message":"Template tpl_collections_reminder3_v1 is not approved for the UTILITY category"}'::jsonb, NULL, '2026-11-12T08:30:00+08:00', NULL, '2026-11-12T08:30:00+08:00')
ON CONFLICT (tenant_id, run_id, node_key) DO UPDATE SET
  id = EXCLUDED.id,
  name = EXCLUDED.name,
  tier = EXCLUDED.tier,
  model = EXCLUDED.model,
  provider = EXCLUDED.provider,
  tokens_in = EXCLUDED.tokens_in,
  tokens_out = EXCLUDED.tokens_out,
  cache_hit_rate = EXCLUDED.cache_hit_rate,
  cost_sen = EXCLUDED.cost_sen,
  status = EXCLUDED.status,
  retries = EXCLUDED.retries,
  duration_ms = EXCLUDED.duration_ms,
  args = EXCLUDED.args,
  result = EXCLUDED.result,
  error = EXCLUDED.error,
  halted_by = EXCLUDED.halted_by,
  finished_at = EXCLUDED.finished_at
WHERE (target.id, target.name, target.tier, target.model, target.provider, target.tokens_in, target.tokens_out, target.cache_hit_rate, target.cost_sen, target.status, target.retries, target.duration_ms, target.args, target.result, target.error, target.halted_by, target.finished_at)
   IS DISTINCT FROM (EXCLUDED.id, EXCLUDED.name, EXCLUDED.tier, EXCLUDED.model, EXCLUDED.provider, EXCLUDED.tokens_in, EXCLUDED.tokens_out, EXCLUDED.cache_hit_rate, EXCLUDED.cost_sen, EXCLUDED.status, EXCLUDED.retries, EXCLUDED.duration_ms, EXCLUDED.args, EXCLUDED.result, EXCLUDED.error, EXCLUDED.halted_by, EXCLUDED.finished_at);

-- run_4821's tool calls and what came back, for replay. Every column is frozen, so this is an append.
INSERT INTO core.run_snapshots AS target
  (id, tenant_id, run_id, tool_name, args_hash, args, response, captured_at, created_at)
VALUES
  ('56910f76-defa-5751-ae94-b18d7c5c3c80', 'acade111-0000-4000-8000-000000000001', 'f4aa02ce-8cb4-5338-8d0f-462148a6a949', 'read_tna', '02e4c0d08a6ee150de0601d2b720f7c2751629061a7cfdf9cdb760c073454695', '{"id":"TNA-0042"}'::jsonb, '{"gaps":3,"audience":30}'::jsonb, '2026-09-11T09:14:02+08:00', '2026-09-11T09:14:02+08:00'),
  ('271b19ba-3e4a-5c51-a233-0e6728b12081', 'acade111-0000-4000-8000-000000000001', 'f4aa02ce-8cb4-5338-8d0f-462148a6a949', 'rank_programmes', '100a5eba329da143f27c40e161e3d2fc638342e441be6dae8464dee4c7b892be', '{"tnaRef":"TNA-0042"}'::jsonb, '{"top":"PRG-0031","fitScore":0.91}'::jsonb, '2026-09-11T09:14:02+08:00', '2026-09-11T09:14:02+08:00'),
  ('048a6222-5c58-58c7-b484-89b05acf133d', 'acade111-0000-4000-8000-000000000001', 'f4aa02ce-8cb4-5338-8d0f-462148a6a949', 'check_trainer_availability', 'a19d2de216578be590ed80f3fdb05fa07fc185792fc94f3b118f5a6a5c87e422', '{"programmeRef":"PRG-0031","window":"2026-11"}'::jsonb, '{"available":["TRN-0007"]}'::jsonb, '2026-09-11T09:14:02+08:00', '2026-09-11T09:14:02+08:00'),
  ('a623df61-313a-566d-abaa-b0330cf09092', 'acade111-0000-4000-8000-000000000001', 'f4aa02ce-8cb4-5338-8d0f-462148a6a949', 'fetch_rate_card', '3f849792db0f9a5f79997512cf8e87f8ec1702ed4cf753bf4ebe5dc02df8a8cc', '{"year":2026}'::jsonb, '{"trainerDay":480000}'::jsonb, '2026-09-11T09:14:02+08:00', '2026-09-11T09:14:02+08:00'),
  ('8389df96-a9c7-5ea7-85fc-47230ba01697', 'acade111-0000-4000-8000-000000000001', 'f4aa02ce-8cb4-5338-8d0f-462148a6a949', 'draft_sections', 'b62f3eb12ee86a07ae5fbb2012fe004e561236ce7512c94b539ba29fdb9ff3e4', '{"templateId":"tpl_proposal_std_v7"}'::jsonb, '{"sections":5,"lowConfidence":1}'::jsonb, '2026-09-11T09:14:02+08:00', '2026-09-11T09:14:02+08:00')
ON CONFLICT (tenant_id, run_id, tool_name, args_hash) DO UPDATE SET
  id = EXCLUDED.id
WHERE target.id IS DISTINCT FROM EXCLUDED.id;

-- run_4821's state card — the goal, the plan and the budget it was working inside when it halted.
INSERT INTO core.run_state_cards AS target
  (id, tenant_id, run_id, version, goal, plan, decisions, constraints, record_pointers, open_questions, budgets, created_at)
VALUES
  ('57ff7bb9-c8a9-5175-a89e-b64ac755607d', 'acade111-0000-4000-8000-000000000001', 'f4aa02ce-8cb4-5338-8d0f-462148a6a949', 1, 'Draft and send a proposal for OPP-0512 within the client''s November window.', '[{"n":1,"label":"Read TNA and org","status":"DONE"},{"n":2,"label":"Rank programmes","status":"DONE"},{"n":3,"label":"Confirm trainer window","status":"DONE"},{"n":4,"label":"Price and draft","status":"DONE"},{"n":5,"label":"Send","status":"HALTED"}]'::jsonb, ARRAY['PRG-0031 over PRG-0018 (0.91 vs 0.78)', 'Farah Aziz — only accredited match in window', 'List price held']::text[], ARRAY['November delivery', 'max 2 days off-floor', 'margin ≥ 0.35', 'HRDC claimable']::text[], ARRAY['TNA-0042', 'PRG-0031', 'TRN-0007', 'QUO-2026-0184', 'PRO-2026-0184']::text[], ARRAY['Section 5 HRDC wording unverified for 2026 (0.41)']::text[], '{"tokens":{"used":38412,"limit":60000},"cost":{"used":38,"limit":120}}'::jsonb, '2026-09-11T09:14:02+08:00')
ON CONFLICT (tenant_id, run_id, version) DO UPDATE SET
  id = EXCLUDED.id,
  goal = EXCLUDED.goal,
  plan = EXCLUDED.plan,
  decisions = EXCLUDED.decisions,
  constraints = EXCLUDED.constraints,
  record_pointers = EXCLUDED.record_pointers,
  open_questions = EXCLUDED.open_questions,
  budgets = EXCLUDED.budgets
WHERE (target.id, target.goal, target.plan, target.decisions, target.constraints, target.record_pointers, target.open_questions, target.budgets)
   IS DISTINCT FROM (EXCLUDED.id, EXCLUDED.goal, EXCLUDED.plan, EXCLUDED.decisions, EXCLUDED.constraints, EXCLUDED.record_pointers, EXCLUDED.open_questions, EXCLUDED.budgets);

-- Escalation, truncation, jury, checkpoint and the policy halt, in time order.
INSERT INTO core.run_events AS target
  (id, tenant_id, run_id, seq, type, node_key, detail, at, created_at)
VALUES
  ('95d20c6a-b66d-59fd-9544-6ca211ccd091', 'acade111-0000-4000-8000-000000000001', 'f4aa02ce-8cb4-5338-8d0f-462148a6a949', 0, 'ESCALATION', 'n2', '{"from":"FAST","to":"MID","confidence":0.62,"threshold":0.75,"node":"n2"}'::jsonb, '2026-09-11T09:14:04+08:00', '2026-09-11T09:14:04+08:00'),
  ('ea257141-3525-53f6-a820-86a3a9bac9a9', 'acade111-0000-4000-8000-000000000001', 'f4aa02ce-8cb4-5338-8d0f-462148a6a949', 1, 'TRUNCATION', NULL, '{"tool":"fetch_rate_card","storedTokens":3400,"fetchMoreAvailable":true}'::jsonb, '2026-09-11T09:14:08+08:00', '2026-09-11T09:14:08+08:00'),
  ('52be7035-a111-5262-91de-8f0db27810a2', 'acade111-0000-4000-8000-000000000001', 'f4aa02ce-8cb4-5338-8d0f-462148a6a949', 2, 'JURY', NULL, '{"mode":"ESCALATE","quorum":2,"of":3,"votes":[{"tier":"STRONG_1","model":"Claude Sonnet 5","agrees":true},{"tier":"STRONG_2","model":"Gemini 3.1 Pro","agrees":true},{"tier":"STRONG_3","model":"GPT-5.6 Terra","agrees":false,"dissent":"Prefers waiting for Daniel Wong in December"}]}'::jsonb, '2026-09-11T09:14:11+08:00', '2026-09-11T09:14:11+08:00'),
  ('884c4da0-a156-53f0-9f00-7c2f06fe82c5', 'acade111-0000-4000-8000-000000000001', 'f4aa02ce-8cb4-5338-8d0f-462148a6a949', 3, 'CHECKPOINT', NULL, '{"step":4,"replayable":true}'::jsonb, '2026-09-11T09:14:12+08:00', '2026-09-11T09:14:12+08:00'),
  ('733b55d4-d295-5f7c-a39b-e4cbe6e6d278', 'acade111-0000-4000-8000-000000000001', 'f4aa02ce-8cb4-5338-8d0f-462148a6a949', 4, 'POLICY_HALT', NULL, '{"policyId":"APV-01","approvalRequestRef":"APV-2026-0771"}'::jsonb, '2026-09-11T09:14:14+08:00', '2026-09-11T09:14:14+08:00'),
  ('bd935609-8fd3-59a9-ac25-6f8d7345a8f5', 'acade111-0000-4000-8000-000000000001', '023f558a-41ad-554f-9dea-df31454de5c6', 0, 'CHECKPOINT', NULL, '{"step":2,"replayable":true}'::jsonb, '2026-11-14T10:29:40+08:00', '2026-11-14T10:29:40+08:00')
ON CONFLICT (tenant_id, run_id, seq) DO NOTHING;

-- run_4821's replayable checkpoint at step 4, against version 1 of its state card.
INSERT INTO core.run_checkpoints AS target
  (id, tenant_id, run_id, step, node_key, state_card_version, cursor, replayable, created_at)
VALUES
  ('658af53d-6b86-5762-bda2-3470219150ee', 'acade111-0000-4000-8000-000000000001', 'f4aa02ce-8cb4-5338-8d0f-462148a6a949', 4, NULL, 1, '{"nodeKey":null,"step":4}'::jsonb, TRUE, '2026-09-11T09:14:12+08:00')
ON CONFLICT (tenant_id, run_id, step) DO UPDATE SET
  id = EXCLUDED.id,
  replayable = EXCLUDED.replayable
WHERE (target.id, target.replayable)
   IS DISTINCT FROM (EXCLUDED.id, EXCLUDED.replayable);

-- Knowledge ───────────────────────────────────────────────────────────────

-- Six sources: one changed and quarantined, one still embedding, one whose fetch
-- has been failing since 07 Nov. `chunk_count` is the fixture's count; the chunks
-- themselves are not in the fixture world and are not invented here.
INSERT INTO core.knowledge_sources AS target
  (id, tenant_id, ref, name, source_type, version, uri, attachment_id, ingested_at, chunk_count, embedding_status, last_checked_at, monitor_status, content_hash, retrieval_scopes, quarantined, archived_at, created_at, created_by_kind, created_by_id, created_by_name)
VALUES
  ('b2b0a5ac-8793-5323-aa61-54f1f80740d2', 'acade111-0000-4000-8000-000000000001', 'SRC-0219', 'Circular 09/2026', 'HRDC_CIRCULAR', 'v1', NULL, NULL, '2026-11-14T09:40:00+08:00', 142, 'INDEXED', '2026-11-14T09:40:00+08:00', 'CHANGED_REVIEW_PENDING', 'sha256:9f2c4a17d8b3e0596c71f2a4d8e0b13c7a95f2e6d40b81c93a5e7f02d6c4b8a1', ARRAY['COMPLIANCE', 'CLIENT_FACING']::core.retrieval_scope[], TRUE, NULL, '2026-11-14T09:40:00+08:00', 'SYSTEM', 'sys_scheduler', 'Scheduler'),
  ('7512bcaa-e24b-536b-807b-b3bad52bd2bb', 'acade111-0000-4000-8000-000000000001', 'SRC-0188', 'Circular 04/2026', 'HRDC_CIRCULAR', 'v2', NULL, NULL, '2026-06-18T08:00:00+08:00', 118, 'INDEXED', '2026-11-10T02:00:00+08:00', 'WATCHING', 'sha256:41b8e7c2905da6f31e8407b5c2d9f6083a1e47b29c05d8f1a6b3e920c74d5f88', ARRAY['COMPLIANCE']::core.retrieval_scope[], FALSE, NULL, '2026-06-18T08:00:00+08:00', 'SYSTEM', 'sys_scheduler', 'Scheduler'),
  ('d44170ac-2a03-5a59-a1c2-60011b147c5c', 'acade111-0000-4000-8000-000000000001', 'SRC-0170', 'Allowable Cost Matrix 2026', 'HRDC_CIRCULAR', 'v1', NULL, NULL, '2026-02-14T08:00:00+08:00', 64, 'INDEXED', '2026-11-10T02:00:00+08:00', 'WATCHING', 'sha256:7d20af9163c4e8b05f72a1d9038e6c45b28f01a7d6e39c840b15f7a2e93c6d04', ARRAY['COMPLIANCE']::core.retrieval_scope[], FALSE, NULL, '2026-02-14T08:00:00+08:00', 'SYSTEM', 'sys_scheduler', 'Scheduler'),
  ('b6ec8a56-a958-56d7-b7b1-6b2c235eede3', 'acade111-0000-4000-8000-000000000001', 'SRC-0155', 'HRD Corp trainer guidelines', 'HRDC_CIRCULAR', 'v3', NULL, NULL, '2026-11-13T21:00:00+08:00', 0, 'PENDING', '2026-11-13T21:00:00+08:00', 'WATCHING', 'sha256:0c6f38b91da24e7503c8b1f6a90d47e25b83f1c04a7d69e820b53f1c9a6e70d2', ARRAY['COMPLIANCE']::core.retrieval_scope[], FALSE, NULL, '2026-11-13T21:00:00+08:00', 'SYSTEM', 'sys_scheduler', 'Scheduler'),
  ('6fffac27-c596-505e-bb58-fda60272c25d', 'acade111-0000-4000-8000-000000000001', 'SRC-0203', 'eTRIS submission help centre', 'HRDC_CIRCULAR', 'v1', NULL, NULL, '2026-08-02T08:00:00+08:00', 87, 'FAILED', '2026-11-07T02:00:00+08:00', 'FAILED', 'sha256:b419d7e0532c86af1b04e93d72c5a608f1d47b2e90c36a5f8b2140e7c93d6a5b', ARRAY['COMPLIANCE']::core.retrieval_scope[], FALSE, NULL, '2026-08-02T08:00:00+08:00', 'SYSTEM', 'sys_scheduler', 'Scheduler'),
  ('c9470281-bd8e-527d-9b80-7701a5ab98d8', 'acade111-0000-4000-8000-000000000001', 'SRC-0240', 'Akademi Perdana delivery SOP', 'HRDC_CIRCULAR', 'v5', NULL, NULL, '2026-09-30T08:00:00+08:00', 203, 'INDEXED', '2026-11-10T02:00:00+08:00', 'MANUAL', 'sha256:e582c10b7f439a6d25e08c1b47f2903da6b58e2c7104f3b9a8d62e5017c4b930', ARRAY['COMPLIANCE']::core.retrieval_scope[], FALSE, NULL, '2026-09-30T08:00:00+08:00', 'SYSTEM', 'sys_scheduler', 'Scheduler')
ON CONFLICT (id) DO UPDATE SET
  tenant_id = EXCLUDED.tenant_id,
  name = EXCLUDED.name,
  source_type = EXCLUDED.source_type,
  version = EXCLUDED.version,
  uri = EXCLUDED.uri,
  attachment_id = EXCLUDED.attachment_id,
  ingested_at = EXCLUDED.ingested_at,
  chunk_count = EXCLUDED.chunk_count,
  embedding_status = EXCLUDED.embedding_status,
  last_checked_at = EXCLUDED.last_checked_at,
  monitor_status = EXCLUDED.monitor_status,
  content_hash = EXCLUDED.content_hash,
  retrieval_scopes = EXCLUDED.retrieval_scopes,
  quarantined = EXCLUDED.quarantined,
  archived_at = EXCLUDED.archived_at,
  created_by_kind = EXCLUDED.created_by_kind,
  created_by_id = EXCLUDED.created_by_id,
  created_by_name = EXCLUDED.created_by_name
WHERE (target.tenant_id, target.name, target.source_type, target.version, target.uri, target.attachment_id, target.ingested_at, target.chunk_count, target.embedding_status, target.last_checked_at, target.monitor_status, target.content_hash, target.retrieval_scopes, target.quarantined, target.archived_at, target.created_by_kind, target.created_by_id, target.created_by_name)
   IS DISTINCT FROM (EXCLUDED.tenant_id, EXCLUDED.name, EXCLUDED.source_type, EXCLUDED.version, EXCLUDED.uri, EXCLUDED.attachment_id, EXCLUDED.ingested_at, EXCLUDED.chunk_count, EXCLUDED.embedding_status, EXCLUDED.last_checked_at, EXCLUDED.monitor_status, EXCLUDED.content_hash, EXCLUDED.retrieval_scopes, EXCLUDED.quarantined, EXCLUDED.archived_at, EXCLUDED.created_by_kind, EXCLUDED.created_by_id, EXCLUDED.created_by_name);

-- Metrics and hours saved ─────────────────────────────────────────────────

-- Every metric cell is self-describing and carries its own drill route — this is the row it reads.
INSERT INTO core.metric_definitions AS target
  (id, tenant_id, metric_key, label, scope, value_kind, formula, is_estimate, drill_to_template, sql_source, compare_period, created_at)
VALUES
  ('55490cb7-5bab-563f-82de-35b198dbadf7', 'acade111-0000-4000-8000-000000000001', 'OPEN_PIPELINE', 'Open pipeline', 'TENANT', 'MONEY', NULL, FALSE, '/v1/opportunities?filter[stage][in]=QUALIFYING,PROPOSAL_SENT,NEGOTIATION', NULL, NULL, '2026-11-14T10:32:00+08:00'),
  ('e5645067-6c8f-59f7-b78e-f900a190f873', 'acade111-0000-4000-8000-000000000001', 'AR_OVERDUE', 'AR overdue', 'TENANT', 'MONEY', NULL, FALSE, '/v1/receivables?filter[daysOverdue][gte]=1', NULL, '2026-10', '2026-11-14T10:32:00+08:00'),
  ('a3fc9d61-4b84-5516-b0f3-cb9f3cb6407e', 'acade111-0000-4000-8000-000000000001', 'PROPOSALS_SENT', 'Proposals sent', 'TENANT', 'COUNT', NULL, FALSE, '/v1/reports/proposals-vs-won?months=6', NULL, '2026-Q3', '2026-11-14T10:32:00+08:00'),
  ('b64fcf94-e7ab-5555-bec4-cec34dc67183', 'acade111-0000-4000-8000-000000000001', 'CLAIM_VALUE_AT_RISK', 'Claim value at risk', 'TENANT', 'MONEY', NULL, FALSE, '/v1/hrdc/deadlines?filter[status][eq]=AT_RISK', NULL, '2026-10', '2026-11-14T10:32:00+08:00'),
  ('f901c950-acaa-556f-9bf7-1473ae2b83c6', 'acade111-0000-4000-8000-000000000001', 'ADMIN_HOURS_SAVED', 'Admin hours saved', 'TENANT', 'DURATION', 'Σ max(0, baselineMinutes − humanMinutes) ÷ 60 × haircut', TRUE, '/v1/reports/hours-saved?period=2026-11', NULL, NULL, '2026-11-14T10:32:00+08:00'),
  ('4f49aabb-acc9-5dc3-9ecf-da4f9450c252', 'acade111-0000-4000-8000-000000000001', 'HEALTH_SCORE', 'Health score', 'ORGANISATION', 'COUNT', NULL, FALSE, '/v1/organisations/ORG-0114/relations', NULL, '2026-10', '2026-11-14T10:32:00+08:00'),
  ('2a14938c-48cd-5b31-bc60-c92ca5ebb99e', 'acade111-0000-4000-8000-000000000001', 'LIFETIME_VALUE', 'Lifetime value', 'ORGANISATION', 'MONEY', NULL, FALSE, '/v1/invoices?filter[organisationRef][eq]=ORG-0114&filter[status][eq]=PAID', NULL, NULL, '2026-11-14T10:32:00+08:00')
ON CONFLICT (tenant_id, metric_key, scope) DO UPDATE SET
  id = EXCLUDED.id,
  label = EXCLUDED.label,
  value_kind = EXCLUDED.value_kind,
  formula = EXCLUDED.formula,
  is_estimate = EXCLUDED.is_estimate,
  drill_to_template = EXCLUDED.drill_to_template,
  sql_source = EXCLUDED.sql_source,
  compare_period = EXCLUDED.compare_period
WHERE (target.id, target.label, target.value_kind, target.formula, target.is_estimate, target.drill_to_template, target.sql_source, target.compare_period)
   IS DISTINCT FROM (EXCLUDED.id, EXCLUDED.label, EXCLUDED.value_kind, EXCLUDED.formula, EXCLUDED.is_estimate, EXCLUDED.drill_to_template, EXCLUDED.sql_source, EXCLUDED.compare_period);

-- Illustrative until measured, with the 0.7 haircut DECISIONS §4 requires.
INSERT INTO core.hours_saved_baseline_tables AS target
  (id, tenant_id, version, basis, haircut, effective_from, signed_off_by_user_id, signed_off_at, created_at)
VALUES
  ('0112c62f-476d-5b77-83ff-51d3c9e7d50c', 'acade111-0000-4000-8000-000000000001', 'baseline-v0-illustrative', 'ILLUSTRATIVE', 0.7, '2026-11-01', NULL, NULL, '2026-11-14T10:32:00+08:00')
ON CONFLICT (tenant_id, version) DO UPDATE SET
  id = EXCLUDED.id,
  basis = EXCLUDED.basis,
  haircut = EXCLUDED.haircut,
  effective_from = EXCLUDED.effective_from,
  signed_off_by_user_id = EXCLUDED.signed_off_by_user_id,
  signed_off_at = EXCLUDED.signed_off_at
WHERE (target.id, target.basis, target.haircut, target.effective_from, target.signed_off_by_user_id, target.signed_off_at)
   IS DISTINCT FROM (EXCLUDED.id, EXCLUDED.basis, EXCLUDED.haircut, EXCLUDED.effective_from, EXCLUDED.signed_off_by_user_id, EXCLUDED.signed_off_at);

-- Four of the report's five action types. PROPOSAL_DRAFT is dropped for the same
-- reason as its routing row: app.action_types has no key for it.
INSERT INTO core.hours_saved_baselines AS target
  (id, tenant_id, baseline_table_id, action_type, baseline_minutes, sample_size, credited, created_at)
VALUES
  ('9c67000b-4f2a-5b61-ae78-a436300ae186', 'acade111-0000-4000-8000-000000000001', '0112c62f-476d-5b77-83ff-51d3c9e7d50c', 'ENQUIRY_ARCHIVE', 6, NULL, TRUE, '2026-11-14T10:32:00+08:00'),
  ('839b3078-8b44-597e-99ef-4302c3f104ba', 'acade111-0000-4000-8000-000000000001', '0112c62f-476d-5b77-83ff-51d3c9e7d50c', 'OPPORTUNITY_CONVERT', 18, NULL, TRUE, '2026-11-14T10:32:00+08:00'),
  ('2afe7fef-490c-5e87-90d8-44a550483e45', 'acade111-0000-4000-8000-000000000001', '0112c62f-476d-5b77-83ff-51d3c9e7d50c', 'HRDC_PACKET_MARK_SUBMITTED', 60, NULL, TRUE, '2026-11-14T10:32:00+08:00'),
  ('d6a9b141-3152-5aff-a34a-cfc312d6feef', 'acade111-0000-4000-8000-000000000001', '0112c62f-476d-5b77-83ff-51d3c9e7d50c', 'REMINDER_SEND', 12, NULL, TRUE, '2026-11-14T10:32:00+08:00')
ON CONFLICT (tenant_id, baseline_table_id, action_type) DO UPDATE SET
  id = EXCLUDED.id,
  baseline_minutes = EXCLUDED.baseline_minutes,
  sample_size = EXCLUDED.sample_size,
  credited = EXCLUDED.credited
WHERE (target.id, target.baseline_minutes, target.sample_size, target.credited)
   IS DISTINCT FROM (EXCLUDED.id, EXCLUDED.baseline_minutes, EXCLUDED.sample_size, EXCLUDED.credited);