-- TrainOS fixture world, part 2 — Enquiries, TNAs, proposals, quotations and the client portal
--
-- Tenant: akademi-perdana (Akademi Perdana Sdn Bhd), id acade111-0000-4000-8000-000000000001
--
-- Run (all four parts, one transaction, from the repo root):
--   psql "$DATABASE_URL" -1 -v ON_ERROR_STOP=1 \
--     -f supabase/seeds/fixture_world_01_tenant_and_parties.sql \
--     -f supabase/seeds/fixture_world_02_sales_and_money.sql \
--     -f supabase/seeds/fixture_world_03_delivery_compliance_finance.sql \
--     -f supabase/seeds/fixture_world_04_ai_ops_and_agents.sql
--
-- Targets migrations 001-017: the tenant is provisioned by
-- app.provision_tenant() from 016, so this does NOT run against a database at
-- 013 or earlier. 018 adds RPCs, not configuration this seed writes — the
-- pipeline rows below are the seed's own, and no provisioning pack writes
-- stages yet.
--
-- Idempotent: every statement is an upsert guarded by an IS DISTINCT FROM
-- comparison, so a second run of an unchanged seed performs zero updates and
-- leaves every updated_at where it was. Iterating a fixture never needs a wipe,
-- with two exceptions named in supabase/seeds/README.md.
--
-- One of the four parts of the TrainOS fixture world. The parts are in
-- foreign-key order and must be run in order:
--
--   1. fixture_world_01_tenant_and_parties.sql
--   2. fixture_world_02_sales_and_money.sql
--   3. fixture_world_03_delivery_compliance_finance.sql
--   4. fixture_world_04_ai_ops_and_agents.sql
--
-- Companion files:
--   fixture_world_wipe.sql         removes every row the four parts write, tenant included
--   test_fixture_world.sql         the pin: counts, landmarks, re-run stability
--
-- Generated by packages/fixtures/scripts/emit-seed.ts — edit the fixtures or the
-- generator, never this file. Regenerate with:
--   npx tsx packages/fixtures/scripts/emit-seed.ts
-- and `--check` fails if the committed SQL and the fixtures have drifted apart.

-- Suspend the gates for this load; restored at the foot of this file.
ALTER TABLE core.enquiries DISABLE TRIGGER enquiries_state_gate;
ALTER TABLE core.opportunities DISABLE TRIGGER opportunities_state_gate;
ALTER TABLE core.tnas DISABLE TRIGGER tnas_state_gate;
ALTER TABLE core.proposals DISABLE TRIGGER proposals_state_gate;
ALTER TABLE core.quotations DISABLE TRIGGER quotations_state_gate;
ALTER TABLE core.quotations DISABLE TRIGGER trg_quotations_freeze_applied;

-- Templates and saved views ───────────────────────────────────────────────

-- Every document and message template the fixture world names. Nothing is hardcoded in the frontend.
INSERT INTO core.templates AS target
  (id, tenant_id, ref, template_type, version, label, merge_fields, status, category, rate_per_message_sen, approved_provider_ref, created_at, created_by_kind, created_by_id, created_by_name)
VALUES
  ('7d213d10-459a-5a6e-afa2-7f0fe56ed425', 'acade111-0000-4000-8000-000000000001', 'TPL-0001', 'PROPOSAL', 7, 'Standard proposal', ARRAY['client.name', 'contact.name', 'programme.title', 'engagement.dates', 'investment.total']::text[], 'ACTIVE', NULL, NULL, NULL, '2022-01-04T09:00:00+08:00', 'HUMAN', 'u_khairul', 'Khairul Anwar'),
  ('52931813-af6d-59d5-bdcb-dc61b85d4704', 'acade111-0000-4000-8000-000000000001', 'TPL-0002', 'EMAIL', 3, 'Proposal covering email', ARRAY['contact.name', 'proposal.ref', 'investment.total']::text[], 'ACTIVE', NULL, NULL, NULL, '2022-01-04T09:00:00+08:00', 'HUMAN', 'u_khairul', 'Khairul Anwar'),
  ('1a2269f6-0d80-5b3f-b6f5-d2701f86ba40', 'acade111-0000-4000-8000-000000000001', 'TPL-0003', 'WHATSAPP', 2, 'Proposal follow-up', ARRAY['contact.name', 'proposal.sentAt']::text[], 'ACTIVE', 'UTILITY', 6, NULL, '2022-01-04T09:00:00+08:00', 'HUMAN', 'u_khairul', 'Khairul Anwar'),
  ('6677eec2-f7a0-5438-9e07-0a4f2e3916c9', 'acade111-0000-4000-8000-000000000001', 'TPL-0004', 'WHATSAPP', 1, 'Programme announcement', ARRAY['contact.name', 'programme.title']::text[], 'ACTIVE', 'MARKETING', 35, NULL, '2022-01-04T09:00:00+08:00', 'HUMAN', 'u_khairul', 'Khairul Anwar'),
  ('4948bac3-232c-50f7-b60b-3cddcd82d8a1', 'acade111-0000-4000-8000-000000000001', 'TPL-0005', 'TNA_QUESTIONNAIRE', 3, 'Standard needs analysis', ARRAY['client.name', 'contact.name']::text[], 'ACTIVE', NULL, NULL, NULL, '2022-01-04T09:00:00+08:00', 'HUMAN', 'u_khairul', 'Khairul Anwar'),
  ('71be0419-d4e1-5b62-b09b-b479f37a7ca5', 'acade111-0000-4000-8000-000000000001', 'TPL-0006', 'QUOTATION', 4, 'Standard quotation', ARRAY['client.name', 'programme.title', 'investment.total', 'rateCard.version']::text[], 'ACTIVE', NULL, NULL, NULL, '2022-01-04T09:00:00+08:00', 'HUMAN', 'u_khairul', 'Khairul Anwar'),
  ('3ec10ecc-28c2-50c2-ac32-b69d3070adb2', 'acade111-0000-4000-8000-000000000001', 'TPL-0007', 'INVOICE', 2, 'Tax invoice', ARRAY['client.name', 'engagement.dates', 'invoice.total']::text[], 'ACTIVE', NULL, NULL, NULL, '2022-01-04T09:00:00+08:00', 'HUMAN', 'u_khairul', 'Khairul Anwar'),
  ('75543d3d-e8a4-5504-976f-6a0a6113c81a', 'acade111-0000-4000-8000-000000000001', 'TPL-0008', 'CERTIFICATE', 5, 'Certificate of attendance', ARRAY['participant.name', 'programme.title', 'engagement.dates', 'trainer.name']::text[], 'ACTIVE', NULL, NULL, NULL, '2022-01-04T09:00:00+08:00', 'HUMAN', 'u_khairul', 'Khairul Anwar'),
  ('e45009b5-0f7a-5a82-be72-683419acc52b', 'acade111-0000-4000-8000-000000000001', 'TPL-0009', 'EVALUATION', 3, 'Post-programme evaluation', ARRAY['programme.title', 'trainer.name']::text[], 'ACTIVE', NULL, NULL, NULL, '2022-01-04T09:00:00+08:00', 'HUMAN', 'u_khairul', 'Khairul Anwar'),
  ('a2fbcded-a5a1-526e-ace6-bf6eb044ac87', 'acade111-0000-4000-8000-000000000001', 'TPL-0010', 'HRDC_PACKET', 2, 'eTRIS claim bundle', ARRAY['employerCode', 'grant.reference', 'engagement.dates']::text[], 'ACTIVE', NULL, NULL, NULL, '2022-01-04T09:00:00+08:00', 'HUMAN', 'u_khairul', 'Khairul Anwar'),
  ('ba71de36-31c8-5caa-9bc9-3581a668b77c', 'acade111-0000-4000-8000-000000000001', 'TPL-0011', 'EMAIL', 4, 'Follow-up email', ARRAY['contact.name', 'proposal.ref']::text[], 'ACTIVE', NULL, NULL, NULL, '2022-01-04T09:00:00+08:00', 'HUMAN', 'u_khairul', 'Khairul Anwar'),
  ('833b9384-44f5-563a-b867-d37fe9dbdeaa', 'acade111-0000-4000-8000-000000000001', 'TPL-0012', 'EMAIL', 2, 'Collections reminder 1', ARRAY['contact.name', 'invoice.ref', 'invoice.outstanding', 'invoice.dueAt']::text[], 'ACTIVE', NULL, NULL, NULL, '2022-01-04T09:00:00+08:00', 'HUMAN', 'u_khairul', 'Khairul Anwar'),
  ('d30c12cb-557c-5134-a625-6249777c6d99', 'acade111-0000-4000-8000-000000000001', 'TPL-0013', 'EMAIL', 2, 'Collections reminder 2', ARRAY['contact.name', 'invoice.ref', 'invoice.outstanding', 'invoice.daysOverdue']::text[], 'ACTIVE', NULL, NULL, NULL, '2022-01-04T09:00:00+08:00', 'HUMAN', 'u_khairul', 'Khairul Anwar'),
  ('9bdd64a1-3817-5c9d-84be-513dd0ee9e60', 'acade111-0000-4000-8000-000000000001', 'TPL-0014', 'WHATSAPP', 1, 'Collections reminder 3', ARRAY['contact.name', 'invoice.ref']::text[], 'ACTIVE', 'UTILITY', 6, NULL, '2022-01-04T09:00:00+08:00', 'HUMAN', 'u_khairul', 'Khairul Anwar')
ON CONFLICT (tenant_id, template_type, label, version) DO UPDATE SET
  id = EXCLUDED.id,
  merge_fields = EXCLUDED.merge_fields,
  status = EXCLUDED.status,
  category = EXCLUDED.category,
  rate_per_message_sen = EXCLUDED.rate_per_message_sen,
  approved_provider_ref = EXCLUDED.approved_provider_ref,
  created_by_kind = EXCLUDED.created_by_kind,
  created_by_id = EXCLUDED.created_by_id,
  created_by_name = EXCLUDED.created_by_name
WHERE (target.id, target.merge_fields, target.status, target.category, target.rate_per_message_sen, target.approved_provider_ref, target.created_by_kind, target.created_by_id, target.created_by_name)
   IS DISTINCT FROM (EXCLUDED.id, EXCLUDED.merge_fields, EXCLUDED.status, EXCLUDED.category, EXCLUDED.rate_per_message_sen, EXCLUDED.approved_provider_ref, EXCLUDED.created_by_kind, EXCLUDED.created_by_id, EXCLUDED.created_by_name);

-- The pill tab groups on the lead, enquiry and approval lists.
INSERT INTO core.saved_views AS target
  (id, tenant_id, ref, object, label, filters, columns, is_default, owner_id, visibility, deleted_at, created_at, created_by_kind, created_by_id, created_by_name)
VALUES
  ('b4e55bbf-3020-5544-8080-d96f7241f650', 'acade111-0000-4000-8000-000000000001', 'SVW-0001', 'LEAD', 'My open leads', '[{"field":"owner.id","op":"eq","value":"u_amirah"}]'::jsonb, ARRAY['contact', 'organisation', 'stage', 'owner', 'value', 'createdAt', 'score']::text[], TRUE, 'acade111-0001-4000-8000-000000000006', 'TENANT', NULL, '2022-01-04T09:00:00+08:00', 'HUMAN', 'u_khairul', 'Khairul Anwar'),
  ('9ba1a525-9ba3-57ae-8f62-9c3d44811202', 'acade111-0000-4000-8000-000000000001', 'SVW-0002', 'ENQUIRY', 'Unassigned', '[{"field":"status","op":"eq","value":"OPEN"}]'::jsonb, ARRAY['channel', 'from.name', 'subject', 'classification.label', 'estimatedValue', 'receivedAt']::text[], TRUE, 'acade111-0001-4000-8000-000000000006', 'TENANT', NULL, '2022-01-04T09:00:00+08:00', 'HUMAN', 'u_khairul', 'Khairul Anwar'),
  ('a78c97b5-add6-59bf-8ec9-a22a3c39fd4b', 'acade111-0000-4000-8000-000000000001', 'SVW-0003', 'ENQUIRY', 'Needs human review', '[{"field":"classification.needsHumanReview","op":"eq","value":true}]'::jsonb, ARRAY['channel', 'from.name', 'subject', 'classification.label', 'receivedAt']::text[], FALSE, 'acade111-0001-4000-8000-000000000006', 'TENANT', NULL, '2022-01-04T09:00:00+08:00', 'HUMAN', 'u_khairul', 'Khairul Anwar'),
  ('49791b1f-26e9-5310-9e26-4db0578646a9', 'acade111-0000-4000-8000-000000000001', 'SVW-0004', 'ENQUIRY', 'WhatsApp', '[{"field":"channel","op":"eq","value":"WHATSAPP"}]'::jsonb, ARRAY['from.name', 'subject', 'classification.label', 'receivedAt']::text[], FALSE, 'acade111-0001-4000-8000-000000000006', 'TENANT', NULL, '2022-01-04T09:00:00+08:00', 'HUMAN', 'u_khairul', 'Khairul Anwar'),
  ('ca90c89c-ddda-57ac-8aa6-32663a050ea9', 'acade111-0000-4000-8000-000000000001', 'SVW-0005', 'APPROVAL', 'Awaiting me', '[{"field":"status","op":"eq","value":"PENDING"}]'::jsonb, ARRAY['subject', 'actionType', 'value', 'requestedBy.name', 'slaDueAt', 'urgencyGroup']::text[], TRUE, 'acade111-0001-4000-8000-000000000006', 'TENANT', NULL, '2022-01-04T09:00:00+08:00', 'HUMAN', 'u_khairul', 'Khairul Anwar'),
  ('3610267a-520e-56d8-bd12-91b62c84eef2', 'acade111-0000-4000-8000-000000000001', 'SVW-0006', 'APPROVAL', 'Money-moving', '[{"field":"bulkApprovable","op":"eq","value":false}]'::jsonb, ARRAY['subject', 'actionType', 'value', 'slaDueAt']::text[], FALSE, 'acade111-0001-4000-8000-000000000006', 'TENANT', NULL, '2022-01-04T09:00:00+08:00', 'HUMAN', 'u_khairul', 'Khairul Anwar')
ON CONFLICT (tenant_id, ref) DO UPDATE SET
  id = EXCLUDED.id,
  object = EXCLUDED.object,
  label = EXCLUDED.label,
  filters = EXCLUDED.filters,
  columns = EXCLUDED.columns,
  is_default = EXCLUDED.is_default,
  owner_id = EXCLUDED.owner_id,
  visibility = EXCLUDED.visibility,
  deleted_at = EXCLUDED.deleted_at,
  created_by_kind = EXCLUDED.created_by_kind,
  created_by_id = EXCLUDED.created_by_id,
  created_by_name = EXCLUDED.created_by_name
WHERE (target.id, target.object, target.label, target.filters, target.columns, target.is_default, target.owner_id, target.visibility, target.deleted_at, target.created_by_kind, target.created_by_id, target.created_by_name)
   IS DISTINCT FROM (EXCLUDED.id, EXCLUDED.object, EXCLUDED.label, EXCLUDED.filters, EXCLUDED.columns, EXCLUDED.is_default, EXCLUDED.owner_id, EXCLUDED.visibility, EXCLUDED.deleted_at, EXCLUDED.created_by_kind, EXCLUDED.created_by_id, EXCLUDED.created_by_name);

-- Rate card ───────────────────────────────────────────────────────────────

-- One rate card, effective from 2026-01-01 with no end. Every fixture quotation prices from it.
INSERT INTO core.rate_cards AS target
  (id, tenant_id, version, currency, status, effective_from, effective_to, created_at, created_by_kind, created_by_id, created_by_name)
VALUES
  ('2d9d4fa8-edc5-53d4-9c98-fe6cc7192179', 'acade111-0000-4000-8000-000000000001', 'v0-placeholder', 'MYR', 'ACTIVE', '2026-01-01', NULL, '2026-01-01T00:00:00+08:00', 'HUMAN', 'u_jason', 'Jason Lee')
ON CONFLICT (tenant_id, version) DO UPDATE SET
  id = EXCLUDED.id,
  currency = EXCLUDED.currency,
  status = EXCLUDED.status,
  effective_from = EXCLUDED.effective_from,
  effective_to = EXCLUDED.effective_to,
  created_by_kind = EXCLUDED.created_by_kind,
  created_by_id = EXCLUDED.created_by_id,
  created_by_name = EXCLUDED.created_by_name
WHERE (target.id, target.currency, target.status, target.effective_from, target.effective_to, target.created_by_kind, target.created_by_id, target.created_by_name)
   IS DISTINCT FROM (EXCLUDED.id, EXCLUDED.currency, EXCLUDED.status, EXCLUDED.effective_from, EXCLUDED.effective_to, EXCLUDED.created_by_kind, EXCLUDED.created_by_id, EXCLUDED.created_by_name);

INSERT INTO core.rate_card_trainer_days AS target
  (id, tenant_id, rate_card_id, band, trainer_id, day_rate_sen, created_at)
VALUES
  ('9764db28-0e6a-55c8-b5a9-9b7eaf8694a3', 'acade111-0000-4000-8000-000000000001', '2d9d4fa8-edc5-53d4-9c98-fe6cc7192179', 'A', NULL, 480000, '2026-01-01T00:00:00+08:00'),
  ('eb2e89a1-b4ec-5bb3-9dba-24012b94dabc', 'acade111-0000-4000-8000-000000000001', '2d9d4fa8-edc5-53d4-9c98-fe6cc7192179', 'A', '0b54f9a4-0d8c-59d9-b39a-1ada4dea58db', 480000, '2026-01-01T00:00:00+08:00'),
  ('23798884-9951-5d9e-ab1d-84da54f88d77', 'acade111-0000-4000-8000-000000000001', '2d9d4fa8-edc5-53d4-9c98-fe6cc7192179', 'B', NULL, 360000, '2026-01-01T00:00:00+08:00'),
  ('0986f60b-2a3a-519c-9327-24c782f6cc19', 'acade111-0000-4000-8000-000000000001', '2d9d4fa8-edc5-53d4-9c98-fe6cc7192179', 'C', NULL, 280000, '2026-01-01T00:00:00+08:00')
ON CONFLICT (id) DO UPDATE SET
  tenant_id = EXCLUDED.tenant_id,
  rate_card_id = EXCLUDED.rate_card_id,
  band = EXCLUDED.band,
  trainer_id = EXCLUDED.trainer_id,
  day_rate_sen = EXCLUDED.day_rate_sen
WHERE (target.tenant_id, target.rate_card_id, target.band, target.trainer_id, target.day_rate_sen)
   IS DISTINCT FROM (EXCLUDED.tenant_id, EXCLUDED.rate_card_id, EXCLUDED.band, EXCLUDED.trainer_id, EXCLUDED.day_rate_sen);

INSERT INTO core.rate_card_materials AS target
  (id, tenant_id, rate_card_id, programme_type, per_pax_sen, created_at)
VALUES
  ('14202f88-d745-5a0a-9ffa-3ce445ce66a4', 'acade111-0000-4000-8000-000000000001', '2d9d4fa8-edc5-53d4-9c98-fe6cc7192179', 'LEADERSHIP', 4000, '2026-01-01T00:00:00+08:00'),
  ('50804006-7c7b-5cb5-9ac2-5014e8d25abb', 'acade111-0000-4000-8000-000000000001', '2d9d4fa8-edc5-53d4-9c98-fe6cc7192179', 'ANALYTICS', 5500, '2026-01-01T00:00:00+08:00'),
  ('8774f554-64c8-5bff-ad6e-b7dd8a2b1b49', 'acade111-0000-4000-8000-000000000001', '2d9d4fa8-edc5-53d4-9c98-fe6cc7192179', 'SAFETY', 3500, '2026-01-01T00:00:00+08:00'),
  ('a0b4e428-a5cd-50bf-a0ff-52cc5404a4d3', 'acade111-0000-4000-8000-000000000001', '2d9d4fa8-edc5-53d4-9c98-fe6cc7192179', 'SALES', 4500, '2026-01-01T00:00:00+08:00')
ON CONFLICT (tenant_id, rate_card_id, programme_type) DO UPDATE SET
  id = EXCLUDED.id,
  per_pax_sen = EXCLUDED.per_pax_sen
WHERE (target.id, target.per_pax_sen)
   IS DISTINCT FROM (EXCLUDED.id, EXCLUDED.per_pax_sen);

-- EXTERNAL carries no rate in the fixture world — it is priced per booking, and NULL says so.
INSERT INTO core.rate_card_venues AS target
  (id, tenant_id, rate_card_id, mode, day_rate_sen, created_at)
VALUES
  ('84fbb676-0f81-518a-99e7-e3f2b984e8ab', 'acade111-0000-4000-8000-000000000001', '2d9d4fa8-edc5-53d4-9c98-fe6cc7192179', 'CLIENT_SITE', 0, '2026-01-01T00:00:00+08:00'),
  ('f03c2ca9-f333-5b0a-99bf-a02ede523121', 'acade111-0000-4000-8000-000000000001', '2d9d4fa8-edc5-53d4-9c98-fe6cc7192179', 'OWN_VENUE', 90000, '2026-01-01T00:00:00+08:00'),
  ('0526a02b-8f16-571a-85cd-9934dce6ab61', 'acade111-0000-4000-8000-000000000001', '2d9d4fa8-edc5-53d4-9c98-fe6cc7192179', 'EXTERNAL', NULL, '2026-01-01T00:00:00+08:00')
ON CONFLICT (tenant_id, rate_card_id, mode) DO UPDATE SET
  id = EXCLUDED.id,
  day_rate_sen = EXCLUDED.day_rate_sen
WHERE (target.id, target.day_rate_sen)
   IS DISTINCT FROM (EXCLUDED.id, EXCLUDED.day_rate_sen);

INSERT INTO core.rate_card_travel AS target
  (id, tenant_id, rate_card_id, region, per_trip_sen, created_at)
VALUES
  ('86e060dc-4618-5abf-b2be-c34ec1e1365a', 'acade111-0000-4000-8000-000000000001', '2d9d4fa8-edc5-53d4-9c98-fe6cc7192179', 'KLANG_VALLEY', 30000, '2026-01-01T00:00:00+08:00'),
  ('63fe4e45-e1cb-51c8-bcd2-49c100cf0257', 'acade111-0000-4000-8000-000000000001', '2d9d4fa8-edc5-53d4-9c98-fe6cc7192179', 'PENINSULAR', 85000, '2026-01-01T00:00:00+08:00'),
  ('ef1e1c65-97fd-538b-9206-f030c5c60217', 'acade111-0000-4000-8000-000000000001', '2d9d4fa8-edc5-53d4-9c98-fe6cc7192179', 'EAST_MALAYSIA', 190000, '2026-01-01T00:00:00+08:00')
ON CONFLICT (tenant_id, rate_card_id, region) DO UPDATE SET
  id = EXCLUDED.id,
  per_trip_sen = EXCLUDED.per_trip_sen
WHERE (target.id, target.per_trip_sen)
   IS DISTINCT FROM (EXCLUDED.id, EXCLUDED.per_trip_sen);

-- The 0.35 floor every quotation in the fixture world is measured against.
INSERT INTO core.rate_card_margin_floors AS target
  (id, tenant_id, rate_card_id, programme_type, floor_pct, created_at)
VALUES
  ('e9788f27-9ab2-5b1d-8588-303dd19792c7', 'acade111-0000-4000-8000-000000000001', '2d9d4fa8-edc5-53d4-9c98-fe6cc7192179', 'LEADERSHIP', 0.35, '2026-01-01T00:00:00+08:00'),
  ('813c7fae-f00a-5137-aa0b-a5ad5f727285', 'acade111-0000-4000-8000-000000000001', '2d9d4fa8-edc5-53d4-9c98-fe6cc7192179', 'ANALYTICS', 0.35, '2026-01-01T00:00:00+08:00'),
  ('b6ebda4d-1076-5a90-ad2b-4894da9ef0a4', 'acade111-0000-4000-8000-000000000001', '2d9d4fa8-edc5-53d4-9c98-fe6cc7192179', 'SAFETY', 0.35, '2026-01-01T00:00:00+08:00'),
  ('145c1f6d-879c-56ac-ada7-64c3d7ddf4b4', 'acade111-0000-4000-8000-000000000001', '2d9d4fa8-edc5-53d4-9c98-fe6cc7192179', 'SALES', 0.35, '2026-01-01T00:00:00+08:00')
ON CONFLICT (tenant_id, rate_card_id, programme_type) DO UPDATE SET
  id = EXCLUDED.id,
  floor_pct = EXCLUDED.floor_pct
WHERE (target.id, target.floor_pct)
   IS DISTINCT FROM (EXCLUDED.id, EXCLUDED.floor_pct);

-- How far below list each role may go before APV-02 is required.
INSERT INTO core.rate_card_discount_authorities AS target
  (id, tenant_id, rate_card_id, role, max_pct, created_at)
VALUES
  ('06d9ba24-2a4e-5c75-a7c4-4786ca955615', 'acade111-0000-4000-8000-000000000001', '2d9d4fa8-edc5-53d4-9c98-fe6cc7192179', 'SALES', 0.05, '2026-01-01T00:00:00+08:00'),
  ('6de1919d-659f-53f4-b6a8-dd7fd1cc1f91', 'acade111-0000-4000-8000-000000000001', '2d9d4fa8-edc5-53d4-9c98-fe6cc7192179', 'SALES_MANAGER', 0.15, '2026-01-01T00:00:00+08:00'),
  ('a08b1e95-bea0-5968-9ec6-278bdf4e4187', 'acade111-0000-4000-8000-000000000001', '2d9d4fa8-edc5-53d4-9c98-fe6cc7192179', 'MD', 0.3, '2026-01-01T00:00:00+08:00')
ON CONFLICT (tenant_id, rate_card_id, role) DO UPDATE SET
  id = EXCLUDED.id,
  max_pct = EXCLUDED.max_pct
WHERE (target.id, target.max_pct)
   IS DISTINCT FROM (EXCLUDED.id, EXCLUDED.max_pct);

-- Enquiries ───────────────────────────────────────────────────────────────

-- The 18-row inbox. ENQ-2026-0912 is the leadership email the demo starts on;
-- ENQ-2026-0931 is the 0.41-confidence WhatsApp row the CHECK forbids archiving.
INSERT INTO core.enquiries AS target
  (id, tenant_id, ref, channel, status, received_at, from_name, from_email, from_phone, subject, preview, body, classification_label, classification_confidence, needs_human_review, estimated_value_sen, currency, matched_organisation_id, matched_contact_id, match_reason, assigned_to_user_id, external_message_id, created_at, created_by_kind, created_by_id, created_by_name)
VALUES
  ('a9bdaa83-d84e-5937-94b0-a6cfd50bdbb6', 'acade111-0000-4000-8000-000000000001', 'ENQ-2026-0912', 'EMAIL', 'CONVERTED', '2026-09-11T08:52:04+08:00', 'Nurul Hassan', 'nurul.hassan@auroramfg.com.my', NULL, 'Leadership training for 30 managers', 'Hi, we''re looking for leadership training for approximately 30 managers…', 'Hi, we''re looking for leadership training for approximately 30 managers, preferably in November, focused on conflict management and communication.', 'LEADERSHIP', 0.94, FALSE, 1850000, 'MYR', 'acade111-0002-4000-8000-000000000114', NULL, 'EXACT_DOMAIN', 'acade111-0001-4000-8000-000000000002', NULL, '2026-09-11T08:52:04+08:00', 'SYSTEM', 'ingest_email', 'Email ingest'),
  ('4277a6db-2cf9-5af9-b505-655ada6da987', 'acade111-0000-4000-8000-000000000001', 'ENQ-2026-0931', 'WHATSAPP', 'OPEN', '2026-11-13T17:41:00+08:00', '+60 12-778 3410', NULL, '+60127783410', 'training?', 'hi do you all do the safety one ah', 'hi do you all do the safety one ah', 'UNCLEAR', 0.41, TRUE, NULL, 'MYR', NULL, NULL, NULL, NULL, NULL, '2026-11-13T17:41:00+08:00', 'SYSTEM', 'ingest_email', 'Email ingest'),
  ('aa7c0cae-d46a-53f3-bb72-c3f889c8070b', 'acade111-0000-4000-8000-000000000001', 'ENQ-2026-0918', 'EMAIL', 'ARCHIVED', '2026-11-12T07:04:00+08:00', 'Conference Alerts', 'noreply@conferencealerts.example', NULL, 'Your invitation: ASEAN L&D Summit 2027', 'Register now for early-bird rates on the region''s largest L&D gathering…', 'Register now for early-bird rates on the region''s largest L&D gathering. Group discounts available.', 'NOT_AN_ENQUIRY', 0.96, FALSE, NULL, 'MYR', NULL, NULL, NULL, NULL, NULL, '2026-11-12T07:04:00+08:00', 'SYSTEM', 'ingest_email', 'Email ingest'),
  ('a0036932-46ad-5865-8d0d-7faba4e119c4', 'acade111-0000-4000-8000-000000000001', 'ENQ-2026-0929', 'EMAIL', 'ASSIGNED', '2026-11-13T09:12:00+08:00', 'Lim Wei Sheng', 'weisheng.lim@kenangaretail.com.my', NULL, 'Sales excellence programme for store managers', 'We would like to run a sales excellence programme for 48 store managers in Q1…', 'We would like to run a sales excellence programme for 48 store managers in Q1 2027, across Klang Valley and Johor.', 'SALES_EXCELLENCE', 0.92, FALSE, 6720000, 'MYR', 'acade111-0002-4000-8000-000000000121', NULL, 'EXACT_DOMAIN', 'acade111-0001-4000-8000-000000000002', NULL, '2026-11-13T09:12:00+08:00', 'SYSTEM', 'ingest_email', 'Email ingest'),
  ('46cddeb0-c6eb-5a1a-be10-d308449b6180', 'acade111-0000-4000-8000-000000000001', 'ENQ-2026-0927', 'WEB_FORM', 'ASSIGNED', '2026-11-12T15:33:00+08:00', 'Faridah Omar', 'faridah.omar@meridianlog.com.my', '+60127788330', 'Data literacy refresher', 'Following last year''s cohort, we want a refresher for the planning team…', 'Following last year''s cohort, we want a refresher for the planning team — about 22 people, ideally December.', 'DATA_LITERACY', 0.88, FALSE, 4200000, 'MYR', 'acade111-0002-4000-8000-000000000128', NULL, 'EXACT_DOMAIN', 'acade111-0001-4000-8000-000000000002', NULL, '2026-11-12T15:33:00+08:00', 'SYSTEM', 'ingest_email', 'Email ingest'),
  ('e1ac420a-1d1b-5159-bea0-949cbe18c583', 'acade111-0000-4000-8000-000000000001', 'ENQ-2026-0925', 'PHONE', 'OPEN', '2026-11-12T11:02:00+08:00', 'Ganesh Pillai', 'ganesh.pillai@perdanautilities.com.my', '+60133322990', 'Safety leadership — substation teams', 'Called to ask about safety leadership for substation supervisors…', 'Called to ask about safety leadership for substation supervisors. Around 35 people, wants HRD Corp claimable.', 'SAFETY', 0.86, FALSE, 2730000, 'MYR', 'acade111-0002-4000-8000-000000000140', NULL, 'MANUAL', NULL, NULL, '2026-11-12T11:02:00+08:00', 'SYSTEM', 'ingest_email', 'Email ingest'),
  ('4a58d9cf-6346-5d90-9443-ee8c214f1f05', 'acade111-0000-4000-8000-000000000001', 'ENQ-2026-0923', 'EMAIL', 'OPEN', '2026-11-11T16:20:00+08:00', 'Suresh Kumaran', 'suresh@suterahospitality.com', NULL, 'Re-opening conversation on service recovery', 'We paused last year but would like to revisit service recovery training…', 'We paused last year but would like to revisit service recovery training for front office, maybe 18 people.', 'SERVICE', 0.79, FALSE, 980000, 'MYR', 'acade111-0002-4000-8000-000000000133', NULL, 'FUZZY_NAME', NULL, NULL, '2026-11-11T16:20:00+08:00', 'SYSTEM', 'ingest_email', 'Email ingest'),
  ('e7a7358d-8be1-5615-9e93-f33a75eb182a', 'acade111-0000-4000-8000-000000000001', 'ENQ-2026-0921', 'WHATSAPP', 'OPEN', '2026-11-11T10:05:00+08:00', '+60 19-220 8871', NULL, '+60192208871', 'Quotation request', 'Good morning, can I get a quote for a 1-day communication workshop…', 'Good morning, can I get a quote for a 1-day communication workshop for 25 staff in Penang?', 'COMMUNICATION', 0.83, FALSE, 890000, 'MYR', NULL, NULL, NULL, NULL, NULL, '2026-11-11T10:05:00+08:00', 'SYSTEM', 'ingest_email', 'Email ingest'),
  ('ce4a4c82-ad4f-54d3-860a-a61f562539b4', 'acade111-0000-4000-8000-000000000001', 'ENQ-2026-0919', 'EMAIL', 'ASSIGNED', '2026-11-10T14:48:00+08:00', 'Procurement — Nusantara Foods', 'procurement@nusantarafoods.example', NULL, 'RFQ: supervisory skills, 2 cohorts', 'Please find attached our RFQ for supervisory skills training, two cohorts…', 'Please find attached our RFQ for supervisory skills training, two cohorts of 25, delivery by March 2027.', 'SUPERVISORY', 0.9, FALSE, 3600000, 'MYR', NULL, NULL, NULL, 'acade111-0001-4000-8000-000000000002', NULL, '2026-11-10T14:48:00+08:00', 'SYSTEM', 'ingest_email', 'Email ingest'),
  ('8009600f-90e0-55ef-885b-4b5c1db047c6', 'acade111-0000-4000-8000-000000000001', 'ENQ-2026-0917', 'WEB_FORM', 'OPEN', '2026-11-10T09:31:00+08:00', 'Adeline Chong', 'adeline.chong@brightpath.example', NULL, 'Coaching for new team leads', 'We have 12 newly promoted team leads and no structured coaching…', 'We have 12 newly promoted team leads and no structured coaching. What do you recommend?', 'COACHING', 0.81, FALSE, 1200000, 'MYR', NULL, NULL, NULL, NULL, NULL, '2026-11-10T09:31:00+08:00', 'SYSTEM', 'ingest_email', 'Email ingest'),
  ('7f84cd63-2db2-554f-8ad5-e13406312c43', 'acade111-0000-4000-8000-000000000001', 'ENQ-2026-0915', 'EMAIL', 'NOT_AN_ENQUIRY', '2026-11-09T18:02:00+08:00', 'Zul from PrintWorks', 'sales@printworks.example', NULL, 'Corporate gifts and lanyards', 'We supply lanyards, notebooks and corporate gifts at wholesale rates…', 'We supply lanyards, notebooks and corporate gifts at wholesale rates. Can we be your vendor?', 'VENDOR_PITCH', 0.94, FALSE, NULL, 'MYR', NULL, NULL, NULL, NULL, NULL, '2026-11-09T18:02:00+08:00', 'SYSTEM', 'ingest_email', 'Email ingest'),
  ('ff4def71-551f-5bc7-a4d3-451afe973b3f', 'acade111-0000-4000-8000-000000000001', 'ENQ-2026-0913', 'EMAIL', 'OPEN', '2026-11-09T11:14:00+08:00', 'Hasnah Ibrahim', 'hasnah@tenagaklang.example', NULL, 'Change management for engineering', 'Our engineering division is restructuring and needs change management support…', 'Our engineering division is restructuring and needs change management support for about 40 engineers.', 'LEADERSHIP', 0.87, FALSE, 2450000, 'MYR', NULL, NULL, NULL, NULL, NULL, '2026-11-09T11:14:00+08:00', 'SYSTEM', 'ingest_email', 'Email ingest'),
  ('f6a430bc-c8bf-572d-935d-4fcfe659a7b3', 'acade111-0000-4000-8000-000000000001', 'ENQ-2026-0911', 'PHONE', 'ASSIGNED', '2026-11-08T15:55:00+08:00', 'Rahim Yaakob', NULL, '+60195512004', 'Follow-up on last year''s proposal', 'Asked whether the 2025 proposal pricing still stands for a January intake…', 'Asked whether the 2025 proposal pricing still stands for a January intake.', 'PRICING_QUERY', 0.72, FALSE, NULL, 'MYR', NULL, NULL, NULL, 'acade111-0001-4000-8000-000000000002', NULL, '2026-11-08T15:55:00+08:00', 'SYSTEM', 'ingest_email', 'Email ingest'),
  ('b227c47c-1d1e-5a12-a3d7-07ea3c540578', 'acade111-0000-4000-8000-000000000001', 'ENQ-2026-0909', 'WHATSAPP', 'OPEN', '2026-11-08T08:22:00+08:00', '+60 13-901 5566', NULL, '+60139015566', 'HRDC claimable?', 'Is your leadership programme claimable under SBL-Khas?', 'Is your leadership programme claimable under SBL-Khas?', 'HRDC_QUERY', 0.89, FALSE, NULL, 'MYR', NULL, NULL, NULL, NULL, NULL, '2026-11-08T08:22:00+08:00', 'SYSTEM', 'ingest_email', 'Email ingest'),
  ('0e2b71a8-67d5-5214-969f-79eb3c77e828', 'acade111-0000-4000-8000-000000000001', 'ENQ-2026-0907', 'EMAIL', 'CONVERTED', '2026-11-06T10:40:00+08:00', 'Faridah Omar', 'faridah.omar@meridianlog.com.my', NULL, 'Confirming the December cohort', 'Confirming we want to proceed with the December cohort as discussed…', 'Confirming we want to proceed with the December cohort as discussed.', 'DATA_LITERACY', 0.93, FALSE, 4200000, 'MYR', 'acade111-0002-4000-8000-000000000128', NULL, 'EXACT_DOMAIN', 'acade111-0001-4000-8000-000000000002', NULL, '2026-11-06T10:40:00+08:00', 'SYSTEM', 'ingest_email', 'Email ingest'),
  ('079b6950-0f80-5d52-838d-a253069e07cb', 'acade111-0000-4000-8000-000000000001', 'ENQ-2026-0905', 'WEB_FORM', 'OPEN', '2026-11-05T13:18:00+08:00', 'Tan Mei Ling', 'meiling.tan@sinarcapital.example', NULL, 'Presentation skills, mid-level', 'Looking for a half-day presentation skills session for 30 analysts…', 'Looking for a half-day presentation skills session for 30 analysts, ideally on site.', 'COMMUNICATION', 0.85, FALSE, 760000, 'MYR', NULL, NULL, NULL, NULL, NULL, '2026-11-05T13:18:00+08:00', 'SYSTEM', 'ingest_email', 'Email ingest'),
  ('fe8e8b42-f936-5d1c-b3b0-c3d65be04ddd', 'acade111-0000-4000-8000-000000000001', 'ENQ-2026-0903', 'EMAIL', 'ARCHIVED', '2026-11-04T09:02:00+08:00', 'Careers Portal', 'careers@jobstack.example', NULL, 'Trainer application — Ismail bin Othman', 'A candidate has applied to your trainer pool listing…', 'A candidate has applied to your trainer pool listing. Review the application in the portal.', 'NOT_AN_ENQUIRY', 0.95, FALSE, NULL, 'MYR', NULL, NULL, NULL, NULL, NULL, '2026-11-04T09:02:00+08:00', 'SYSTEM', 'ingest_email', 'Email ingest'),
  ('d3598b57-7003-5b04-93fa-b15be92b6468', 'acade111-0000-4000-8000-000000000001', 'ENQ-2026-0901', 'EMAIL', 'OPEN', '2026-11-03T16:45:00+08:00', 'Yusof Karim', 'yusof.karim@bandarhealth.example', NULL, 'Conflict management for clinical leads', 'Our clinical leads need conflict management; about 20 people, flexible dates…', 'Our clinical leads need conflict management; about 20 people, flexible dates in the first half of 2027.', 'LEADERSHIP', 0.9, FALSE, 1450000, 'MYR', NULL, NULL, NULL, NULL, NULL, '2026-11-03T16:45:00+08:00', 'SYSTEM', 'ingest_email', 'Email ingest')
ON CONFLICT (tenant_id, ref) DO UPDATE SET
  id = EXCLUDED.id,
  channel = EXCLUDED.channel,
  status = EXCLUDED.status,
  received_at = EXCLUDED.received_at,
  from_name = EXCLUDED.from_name,
  from_email = EXCLUDED.from_email,
  from_phone = EXCLUDED.from_phone,
  subject = EXCLUDED.subject,
  preview = EXCLUDED.preview,
  body = EXCLUDED.body,
  classification_label = EXCLUDED.classification_label,
  classification_confidence = EXCLUDED.classification_confidence,
  needs_human_review = EXCLUDED.needs_human_review,
  estimated_value_sen = EXCLUDED.estimated_value_sen,
  currency = EXCLUDED.currency,
  matched_organisation_id = EXCLUDED.matched_organisation_id,
  matched_contact_id = EXCLUDED.matched_contact_id,
  match_reason = EXCLUDED.match_reason,
  assigned_to_user_id = EXCLUDED.assigned_to_user_id,
  external_message_id = EXCLUDED.external_message_id,
  created_by_kind = EXCLUDED.created_by_kind,
  created_by_id = EXCLUDED.created_by_id,
  created_by_name = EXCLUDED.created_by_name
WHERE (target.id, target.channel, target.status, target.received_at, target.from_name, target.from_email, target.from_phone, target.subject, target.preview, target.body, target.classification_label, target.classification_confidence, target.needs_human_review, target.estimated_value_sen, target.currency, target.matched_organisation_id, target.matched_contact_id, target.match_reason, target.assigned_to_user_id, target.external_message_id, target.created_by_kind, target.created_by_id, target.created_by_name)
   IS DISTINCT FROM (EXCLUDED.id, EXCLUDED.channel, EXCLUDED.status, EXCLUDED.received_at, EXCLUDED.from_name, EXCLUDED.from_email, EXCLUDED.from_phone, EXCLUDED.subject, EXCLUDED.preview, EXCLUDED.body, EXCLUDED.classification_label, EXCLUDED.classification_confidence, EXCLUDED.needs_human_review, EXCLUDED.estimated_value_sen, EXCLUDED.currency, EXCLUDED.matched_organisation_id, EXCLUDED.matched_contact_id, EXCLUDED.match_reason, EXCLUDED.assigned_to_user_id, EXCLUDED.external_message_id, EXCLUDED.created_by_kind, EXCLUDED.created_by_id, EXCLUDED.created_by_name);

INSERT INTO core.enquiry_extraction_fields AS target
  (id, tenant_id, enquiry_id, field_key, value, created_at, created_by_kind, created_by_id, created_by_name)
VALUES
  ('752262fb-a733-5268-90c0-e1b2202abbdc', 'acade111-0000-4000-8000-000000000001', 'a9bdaa83-d84e-5937-94b0-a6cfd50bdbb6', 'topic', 'Conflict & communication', '2026-09-11T08:52:04+08:00', 'AGENT', 'agent_lead', 'Lead Agent'),
  ('98eb08b3-52f3-5e57-9999-ab822ede7a2b', 'acade111-0000-4000-8000-000000000001', 'a9bdaa83-d84e-5937-94b0-a6cfd50bdbb6', 'audience', '30 line managers', '2026-09-11T08:52:04+08:00', 'AGENT', 'agent_lead', 'Lead Agent'),
  ('c44a6147-ee61-5fe1-bddc-c2e0b8131ccf', 'acade111-0000-4000-8000-000000000001', 'a9bdaa83-d84e-5937-94b0-a6cfd50bdbb6', 'timing', '2026-11', '2026-09-11T08:52:04+08:00', 'AGENT', 'agent_lead', 'Lead Agent'),
  ('5dac650b-8772-5523-b907-6d82043937fc', 'acade111-0000-4000-8000-000000000001', 'a9bdaa83-d84e-5937-94b0-a6cfd50bdbb6', 'budget', NULL, '2026-09-11T08:52:04+08:00', 'AGENT', 'agent_lead', 'Lead Agent'),
  ('4c12fa1e-4425-5ba9-bcb9-1af5b693830a', 'acade111-0000-4000-8000-000000000001', '4277a6db-2cf9-5af9-b505-655ada6da987', 'topic', NULL, '2026-11-13T17:41:00+08:00', 'AGENT', 'agent_lead', 'Lead Agent'),
  ('2299dcc6-4817-59b0-adb3-1a3157935651', 'acade111-0000-4000-8000-000000000001', '4277a6db-2cf9-5af9-b505-655ada6da987', 'audience', NULL, '2026-11-13T17:41:00+08:00', 'AGENT', 'agent_lead', 'Lead Agent'),
  ('5076ec62-48c9-59c1-b9d5-d11647292e6d', 'acade111-0000-4000-8000-000000000001', '4277a6db-2cf9-5af9-b505-655ada6da987', 'timing', NULL, '2026-11-13T17:41:00+08:00', 'AGENT', 'agent_lead', 'Lead Agent'),
  ('d4859b61-2d5b-5859-9409-2683a1ca518b', 'acade111-0000-4000-8000-000000000001', '4277a6db-2cf9-5af9-b505-655ada6da987', 'budget', NULL, '2026-11-13T17:41:00+08:00', 'AGENT', 'agent_lead', 'Lead Agent'),
  ('7e594b5f-38a7-5a45-a833-8ad831f0233c', 'acade111-0000-4000-8000-000000000001', 'aa7c0cae-d46a-53f3-bb72-c3f889c8070b', 'topic', NULL, '2026-11-12T07:04:00+08:00', 'AGENT', 'agent_lead', 'Lead Agent'),
  ('e2e5ec5a-67f0-5e45-b2b1-ff38053b1106', 'acade111-0000-4000-8000-000000000001', 'aa7c0cae-d46a-53f3-bb72-c3f889c8070b', 'audience', NULL, '2026-11-12T07:04:00+08:00', 'AGENT', 'agent_lead', 'Lead Agent'),
  ('7506485e-9108-579e-99b2-ea35c03113ad', 'acade111-0000-4000-8000-000000000001', 'aa7c0cae-d46a-53f3-bb72-c3f889c8070b', 'timing', NULL, '2026-11-12T07:04:00+08:00', 'AGENT', 'agent_lead', 'Lead Agent'),
  ('e5170644-e8e5-5f89-b7e6-67db3b7b70cb', 'acade111-0000-4000-8000-000000000001', 'aa7c0cae-d46a-53f3-bb72-c3f889c8070b', 'budget', NULL, '2026-11-12T07:04:00+08:00', 'AGENT', 'agent_lead', 'Lead Agent'),
  ('71228240-a6ef-5465-88cd-3144cf2a4fcb', 'acade111-0000-4000-8000-000000000001', 'a0036932-46ad-5865-8d0d-7faba4e119c4', 'topic', 'Sales excellence', '2026-11-13T09:12:00+08:00', 'AGENT', 'agent_lead', 'Lead Agent'),
  ('d7ec98b7-b80d-5b51-81b7-b5cf42b14efb', 'acade111-0000-4000-8000-000000000001', 'a0036932-46ad-5865-8d0d-7faba4e119c4', 'audience', '48 store managers', '2026-11-13T09:12:00+08:00', 'AGENT', 'agent_lead', 'Lead Agent'),
  ('3f388390-f65c-5740-b90e-c5bf1f5fbcb8', 'acade111-0000-4000-8000-000000000001', 'a0036932-46ad-5865-8d0d-7faba4e119c4', 'timing', '2027-01', '2026-11-13T09:12:00+08:00', 'AGENT', 'agent_lead', 'Lead Agent'),
  ('55cabc06-e44b-5cb0-9684-e6c5d8499c9b', 'acade111-0000-4000-8000-000000000001', 'a0036932-46ad-5865-8d0d-7faba4e119c4', 'budget', NULL, '2026-11-13T09:12:00+08:00', 'AGENT', 'agent_lead', 'Lead Agent'),
  ('93755c51-bbbd-54c6-b205-6f409719daba', 'acade111-0000-4000-8000-000000000001', '46cddeb0-c6eb-5a1a-be10-d308449b6180', 'topic', 'Data literacy', '2026-11-12T15:33:00+08:00', 'AGENT', 'agent_lead', 'Lead Agent'),
  ('61fe8eb3-8097-5b74-bf39-59b570ea05f5', 'acade111-0000-4000-8000-000000000001', '46cddeb0-c6eb-5a1a-be10-d308449b6180', 'audience', '22 planners', '2026-11-12T15:33:00+08:00', 'AGENT', 'agent_lead', 'Lead Agent'),
  ('3779980f-514b-5232-a92f-b9bbea44a660', 'acade111-0000-4000-8000-000000000001', '46cddeb0-c6eb-5a1a-be10-d308449b6180', 'timing', '2026-12', '2026-11-12T15:33:00+08:00', 'AGENT', 'agent_lead', 'Lead Agent'),
  ('2cd6754b-9784-51f5-81dc-5b2f3521664c', 'acade111-0000-4000-8000-000000000001', '46cddeb0-c6eb-5a1a-be10-d308449b6180', 'budget', NULL, '2026-11-12T15:33:00+08:00', 'AGENT', 'agent_lead', 'Lead Agent'),
  ('d65aefb8-ca17-59b3-bebc-f2d5d4ede997', 'acade111-0000-4000-8000-000000000001', 'e1ac420a-1d1b-5159-bea0-949cbe18c583', 'topic', 'Safety leadership', '2026-11-12T11:02:00+08:00', 'AGENT', 'agent_lead', 'Lead Agent'),
  ('32331220-a963-51df-bd09-cea8d7d0223d', 'acade111-0000-4000-8000-000000000001', 'e1ac420a-1d1b-5159-bea0-949cbe18c583', 'audience', '35 supervisors', '2026-11-12T11:02:00+08:00', 'AGENT', 'agent_lead', 'Lead Agent'),
  ('e22297fb-d331-5e6e-a8ea-a5a29d48971a', 'acade111-0000-4000-8000-000000000001', 'e1ac420a-1d1b-5159-bea0-949cbe18c583', 'timing', '2027-02', '2026-11-12T11:02:00+08:00', 'AGENT', 'agent_lead', 'Lead Agent'),
  ('10429dab-fbd2-5e53-ba35-f89995115ef3', 'acade111-0000-4000-8000-000000000001', 'e1ac420a-1d1b-5159-bea0-949cbe18c583', 'budget', NULL, '2026-11-12T11:02:00+08:00', 'AGENT', 'agent_lead', 'Lead Agent'),
  ('f3181170-6352-58fb-98b5-aa5023f98dd3', 'acade111-0000-4000-8000-000000000001', '4a58d9cf-6346-5d90-9443-ee8c214f1f05', 'topic', 'Service recovery', '2026-11-11T16:20:00+08:00', 'AGENT', 'agent_lead', 'Lead Agent'),
  ('b527382f-e3e2-5973-986b-d40b8b1ffc64', 'acade111-0000-4000-8000-000000000001', '4a58d9cf-6346-5d90-9443-ee8c214f1f05', 'audience', '18 front office', '2026-11-11T16:20:00+08:00', 'AGENT', 'agent_lead', 'Lead Agent'),
  ('551d06ba-bc19-58a1-addf-3227c2554edd', 'acade111-0000-4000-8000-000000000001', '4a58d9cf-6346-5d90-9443-ee8c214f1f05', 'timing', NULL, '2026-11-11T16:20:00+08:00', 'AGENT', 'agent_lead', 'Lead Agent'),
  ('e88c53fe-0d3f-5b85-b4af-a1f25ad5d571', 'acade111-0000-4000-8000-000000000001', '4a58d9cf-6346-5d90-9443-ee8c214f1f05', 'budget', NULL, '2026-11-11T16:20:00+08:00', 'AGENT', 'agent_lead', 'Lead Agent'),
  ('7b512793-9096-56e9-9839-460a2c369613', 'acade111-0000-4000-8000-000000000001', 'e7a7358d-8be1-5615-9e93-f33a75eb182a', 'topic', 'Communication', '2026-11-11T10:05:00+08:00', 'AGENT', 'agent_lead', 'Lead Agent'),
  ('8041272b-31f1-5904-a7df-396610a12b99', 'acade111-0000-4000-8000-000000000001', 'e7a7358d-8be1-5615-9e93-f33a75eb182a', 'audience', '25 staff', '2026-11-11T10:05:00+08:00', 'AGENT', 'agent_lead', 'Lead Agent'),
  ('a5a54c7e-21ce-5e49-9685-83d58359ecb3', 'acade111-0000-4000-8000-000000000001', 'e7a7358d-8be1-5615-9e93-f33a75eb182a', 'timing', NULL, '2026-11-11T10:05:00+08:00', 'AGENT', 'agent_lead', 'Lead Agent'),
  ('eb049c1e-ed74-5c1e-95dc-d4138c47ae9c', 'acade111-0000-4000-8000-000000000001', 'e7a7358d-8be1-5615-9e93-f33a75eb182a', 'budget', NULL, '2026-11-11T10:05:00+08:00', 'AGENT', 'agent_lead', 'Lead Agent'),
  ('3e5d0d33-c053-5e98-945a-1a8fe69060d6', 'acade111-0000-4000-8000-000000000001', 'ce4a4c82-ad4f-54d3-860a-a61f562539b4', 'topic', 'Supervisory skills', '2026-11-10T14:48:00+08:00', 'AGENT', 'agent_lead', 'Lead Agent'),
  ('959e8082-ab30-5213-ab18-326ae4b7800a', 'acade111-0000-4000-8000-000000000001', 'ce4a4c82-ad4f-54d3-860a-a61f562539b4', 'audience', '2 cohorts of 25', '2026-11-10T14:48:00+08:00', 'AGENT', 'agent_lead', 'Lead Agent'),
  ('aca30413-7419-5e26-8b82-8cc1ea68eb48', 'acade111-0000-4000-8000-000000000001', 'ce4a4c82-ad4f-54d3-860a-a61f562539b4', 'timing', '2027-03', '2026-11-10T14:48:00+08:00', 'AGENT', 'agent_lead', 'Lead Agent'),
  ('53f9ce6c-b7f1-5ebf-a472-52ea762616dc', 'acade111-0000-4000-8000-000000000001', 'ce4a4c82-ad4f-54d3-860a-a61f562539b4', 'budget', NULL, '2026-11-10T14:48:00+08:00', 'AGENT', 'agent_lead', 'Lead Agent'),
  ('56dad961-bbe8-56c5-a435-51e8606e5963', 'acade111-0000-4000-8000-000000000001', '8009600f-90e0-55ef-885b-4b5c1db047c6', 'topic', 'Coaching', '2026-11-10T09:31:00+08:00', 'AGENT', 'agent_lead', 'Lead Agent'),
  ('eb0762f8-a6e9-574e-a5d7-c63b7da63d44', 'acade111-0000-4000-8000-000000000001', '8009600f-90e0-55ef-885b-4b5c1db047c6', 'audience', '12 team leads', '2026-11-10T09:31:00+08:00', 'AGENT', 'agent_lead', 'Lead Agent'),
  ('e7892afc-087e-5d10-864f-3842c9c528a6', 'acade111-0000-4000-8000-000000000001', '8009600f-90e0-55ef-885b-4b5c1db047c6', 'timing', NULL, '2026-11-10T09:31:00+08:00', 'AGENT', 'agent_lead', 'Lead Agent'),
  ('c8d6416e-79a5-5639-a533-0beb4f9cb015', 'acade111-0000-4000-8000-000000000001', '8009600f-90e0-55ef-885b-4b5c1db047c6', 'budget', NULL, '2026-11-10T09:31:00+08:00', 'AGENT', 'agent_lead', 'Lead Agent'),
  ('f2f8f9b1-e008-58b7-9c98-0b0bba5a9c72', 'acade111-0000-4000-8000-000000000001', '7f84cd63-2db2-554f-8ad5-e13406312c43', 'topic', NULL, '2026-11-09T18:02:00+08:00', 'AGENT', 'agent_lead', 'Lead Agent'),
  ('2250c78a-c1bc-531d-9a7a-e9f978cd6ffe', 'acade111-0000-4000-8000-000000000001', '7f84cd63-2db2-554f-8ad5-e13406312c43', 'audience', NULL, '2026-11-09T18:02:00+08:00', 'AGENT', 'agent_lead', 'Lead Agent'),
  ('67d5581a-e98e-54c3-bc6f-2dbda9ed3601', 'acade111-0000-4000-8000-000000000001', '7f84cd63-2db2-554f-8ad5-e13406312c43', 'timing', NULL, '2026-11-09T18:02:00+08:00', 'AGENT', 'agent_lead', 'Lead Agent'),
  ('b830b9ae-4c13-5ad3-8689-75491715eeef', 'acade111-0000-4000-8000-000000000001', '7f84cd63-2db2-554f-8ad5-e13406312c43', 'budget', NULL, '2026-11-09T18:02:00+08:00', 'AGENT', 'agent_lead', 'Lead Agent'),
  ('7d37c17d-1d4e-503b-8b0d-17101bfd93ef', 'acade111-0000-4000-8000-000000000001', 'ff4def71-551f-5bc7-a4d3-451afe973b3f', 'topic', 'Change management', '2026-11-09T11:14:00+08:00', 'AGENT', 'agent_lead', 'Lead Agent'),
  ('5a3ece5c-95c1-5e46-b8ee-c28d03b32a76', 'acade111-0000-4000-8000-000000000001', 'ff4def71-551f-5bc7-a4d3-451afe973b3f', 'audience', '40 engineers', '2026-11-09T11:14:00+08:00', 'AGENT', 'agent_lead', 'Lead Agent'),
  ('17504c19-3dc5-57c5-be1f-cccf5b41fdde', 'acade111-0000-4000-8000-000000000001', 'ff4def71-551f-5bc7-a4d3-451afe973b3f', 'timing', '2027-01', '2026-11-09T11:14:00+08:00', 'AGENT', 'agent_lead', 'Lead Agent'),
  ('e328e9d5-5f45-597b-a57d-5fd2ce2f7438', 'acade111-0000-4000-8000-000000000001', 'ff4def71-551f-5bc7-a4d3-451afe973b3f', 'budget', NULL, '2026-11-09T11:14:00+08:00', 'AGENT', 'agent_lead', 'Lead Agent'),
  ('165d0b0f-04cf-52b2-b59a-befcd11cd1d0', 'acade111-0000-4000-8000-000000000001', 'f6a430bc-c8bf-572d-935d-4fcfe659a7b3', 'topic', 'Pricing query', '2026-11-08T15:55:00+08:00', 'AGENT', 'agent_lead', 'Lead Agent'),
  ('7ee320d0-5cf0-5669-a23f-a796fdb91914', 'acade111-0000-4000-8000-000000000001', 'f6a430bc-c8bf-572d-935d-4fcfe659a7b3', 'audience', NULL, '2026-11-08T15:55:00+08:00', 'AGENT', 'agent_lead', 'Lead Agent')
ON CONFLICT (tenant_id, enquiry_id, field_key) DO UPDATE SET
  id = EXCLUDED.id,
  value = EXCLUDED.value,
  created_by_kind = EXCLUDED.created_by_kind,
  created_by_id = EXCLUDED.created_by_id,
  created_by_name = EXCLUDED.created_by_name
WHERE (target.id, target.value, target.created_by_kind, target.created_by_id, target.created_by_name)
   IS DISTINCT FROM (EXCLUDED.id, EXCLUDED.value, EXCLUDED.created_by_kind, EXCLUDED.created_by_id, EXCLUDED.created_by_name);

INSERT INTO core.enquiry_extraction_fields AS target
  (id, tenant_id, enquiry_id, field_key, value, created_at, created_by_kind, created_by_id, created_by_name)
VALUES
  ('f35272a2-3ea9-5702-ba3c-5be0d943fde6', 'acade111-0000-4000-8000-000000000001', 'f6a430bc-c8bf-572d-935d-4fcfe659a7b3', 'timing', '2027-01', '2026-11-08T15:55:00+08:00', 'AGENT', 'agent_lead', 'Lead Agent'),
  ('79514dd1-2317-56a7-a4b8-f1201d6f218d', 'acade111-0000-4000-8000-000000000001', 'f6a430bc-c8bf-572d-935d-4fcfe659a7b3', 'budget', NULL, '2026-11-08T15:55:00+08:00', 'AGENT', 'agent_lead', 'Lead Agent'),
  ('dae58534-7c2c-581e-862f-78fc145374d0', 'acade111-0000-4000-8000-000000000001', 'b227c47c-1d1e-5a12-a3d7-07ea3c540578', 'topic', 'HRD Corp eligibility', '2026-11-08T08:22:00+08:00', 'AGENT', 'agent_lead', 'Lead Agent'),
  ('5dc44ed5-c968-54ca-b59c-91b284f33d89', 'acade111-0000-4000-8000-000000000001', 'b227c47c-1d1e-5a12-a3d7-07ea3c540578', 'audience', NULL, '2026-11-08T08:22:00+08:00', 'AGENT', 'agent_lead', 'Lead Agent'),
  ('12d1b92f-01b8-5cdc-84ed-2ad44e078371', 'acade111-0000-4000-8000-000000000001', 'b227c47c-1d1e-5a12-a3d7-07ea3c540578', 'timing', NULL, '2026-11-08T08:22:00+08:00', 'AGENT', 'agent_lead', 'Lead Agent'),
  ('b0038ecf-00d4-58a3-8746-b0168b710808', 'acade111-0000-4000-8000-000000000001', 'b227c47c-1d1e-5a12-a3d7-07ea3c540578', 'budget', NULL, '2026-11-08T08:22:00+08:00', 'AGENT', 'agent_lead', 'Lead Agent'),
  ('8abddfac-7996-5d6b-bf16-fe65dbaf5441', 'acade111-0000-4000-8000-000000000001', '0e2b71a8-67d5-5214-969f-79eb3c77e828', 'topic', 'Data literacy', '2026-11-06T10:40:00+08:00', 'AGENT', 'agent_lead', 'Lead Agent'),
  ('5bee4fd4-a0e8-553c-a05d-53e204c77957', 'acade111-0000-4000-8000-000000000001', '0e2b71a8-67d5-5214-969f-79eb3c77e828', 'audience', '22 planners', '2026-11-06T10:40:00+08:00', 'AGENT', 'agent_lead', 'Lead Agent'),
  ('b388d566-8363-5b06-a3c5-80c072f318e9', 'acade111-0000-4000-8000-000000000001', '0e2b71a8-67d5-5214-969f-79eb3c77e828', 'timing', '2026-12', '2026-11-06T10:40:00+08:00', 'AGENT', 'agent_lead', 'Lead Agent'),
  ('a12e240b-b111-5bec-b6fc-4286219e95b6', 'acade111-0000-4000-8000-000000000001', '0e2b71a8-67d5-5214-969f-79eb3c77e828', 'budget', NULL, '2026-11-06T10:40:00+08:00', 'AGENT', 'agent_lead', 'Lead Agent'),
  ('262ed79a-5e0a-5e81-a1fa-ef2b59689d06', 'acade111-0000-4000-8000-000000000001', '079b6950-0f80-5d52-838d-a253069e07cb', 'topic', 'Presentation skills', '2026-11-05T13:18:00+08:00', 'AGENT', 'agent_lead', 'Lead Agent'),
  ('da0e8da7-04e6-50f8-99bc-7d370122e8bb', 'acade111-0000-4000-8000-000000000001', '079b6950-0f80-5d52-838d-a253069e07cb', 'audience', '30 analysts', '2026-11-05T13:18:00+08:00', 'AGENT', 'agent_lead', 'Lead Agent'),
  ('8f44fde9-fbdf-5a85-8543-842794c42f87', 'acade111-0000-4000-8000-000000000001', '079b6950-0f80-5d52-838d-a253069e07cb', 'timing', '2026-12', '2026-11-05T13:18:00+08:00', 'AGENT', 'agent_lead', 'Lead Agent'),
  ('004d89bf-72a3-5fee-8704-ae806a4eabcd', 'acade111-0000-4000-8000-000000000001', '079b6950-0f80-5d52-838d-a253069e07cb', 'budget', NULL, '2026-11-05T13:18:00+08:00', 'AGENT', 'agent_lead', 'Lead Agent'),
  ('32a8b19b-f592-595a-9d42-70e17cfb4b8f', 'acade111-0000-4000-8000-000000000001', 'fe8e8b42-f936-5d1c-b3b0-c3d65be04ddd', 'topic', NULL, '2026-11-04T09:02:00+08:00', 'AGENT', 'agent_lead', 'Lead Agent'),
  ('a84e62c8-8088-5bfc-a4e1-0c7c9975a44d', 'acade111-0000-4000-8000-000000000001', 'fe8e8b42-f936-5d1c-b3b0-c3d65be04ddd', 'audience', NULL, '2026-11-04T09:02:00+08:00', 'AGENT', 'agent_lead', 'Lead Agent'),
  ('9b69ab2b-427e-526e-b341-28f1f5871257', 'acade111-0000-4000-8000-000000000001', 'fe8e8b42-f936-5d1c-b3b0-c3d65be04ddd', 'timing', NULL, '2026-11-04T09:02:00+08:00', 'AGENT', 'agent_lead', 'Lead Agent'),
  ('b44ba9b1-c9f7-5477-8e74-3929e2e24aee', 'acade111-0000-4000-8000-000000000001', 'fe8e8b42-f936-5d1c-b3b0-c3d65be04ddd', 'budget', NULL, '2026-11-04T09:02:00+08:00', 'AGENT', 'agent_lead', 'Lead Agent'),
  ('d402ce98-7b7f-5f3b-b1fb-2c42cb11a219', 'acade111-0000-4000-8000-000000000001', 'd3598b57-7003-5b04-93fa-b15be92b6468', 'topic', 'Conflict management', '2026-11-03T16:45:00+08:00', 'AGENT', 'agent_lead', 'Lead Agent'),
  ('49300d30-22d9-5de6-84d8-e00fab0bed03', 'acade111-0000-4000-8000-000000000001', 'd3598b57-7003-5b04-93fa-b15be92b6468', 'audience', '20 clinical leads', '2026-11-03T16:45:00+08:00', 'AGENT', 'agent_lead', 'Lead Agent'),
  ('224ba19e-438c-50c4-aa40-bc27ae2a5740', 'acade111-0000-4000-8000-000000000001', 'd3598b57-7003-5b04-93fa-b15be92b6468', 'timing', '2027-H1', '2026-11-03T16:45:00+08:00', 'AGENT', 'agent_lead', 'Lead Agent'),
  ('7395e45a-0931-51d3-a455-c510c6e0c8eb', 'acade111-0000-4000-8000-000000000001', 'd3598b57-7003-5b04-93fa-b15be92b6468', 'budget', NULL, '2026-11-03T16:45:00+08:00', 'AGENT', 'agent_lead', 'Lead Agent')
ON CONFLICT (tenant_id, enquiry_id, field_key) DO UPDATE SET
  id = EXCLUDED.id,
  value = EXCLUDED.value,
  created_by_kind = EXCLUDED.created_by_kind,
  created_by_id = EXCLUDED.created_by_id,
  created_by_name = EXCLUDED.created_by_name
WHERE (target.id, target.value, target.created_by_kind, target.created_by_id, target.created_by_name)
   IS DISTINCT FROM (EXCLUDED.id, EXCLUDED.value, EXCLUDED.created_by_kind, EXCLUDED.created_by_id, EXCLUDED.created_by_name);

-- Opportunities ───────────────────────────────────────────────────────────

-- Five deals, one per active organisation. OPP-0512 is WON and is what ENG-0231 was raised from.
INSERT INTO core.opportunities AS target
  (id, tenant_id, ref, organisation_id, primary_contact_id, source_enquiry_id, owner_id, stage, value_sen, currency, probability, stage_changed_at, lost_reason, created_at, created_by_kind, created_by_id, created_by_name)
VALUES
  ('aea5f8fb-e55e-53c4-a39e-a0e757a264f2', 'acade111-0000-4000-8000-000000000001', 'OPP-0512', 'acade111-0002-4000-8000-000000000114', NULL, 'a9bdaa83-d84e-5937-94b0-a6cfd50bdbb6', 'acade111-0001-4000-8000-000000000002', 'WON', 1850000, 'MYR', 1, '2026-09-15T10:24:00+08:00', NULL, '2026-09-11T09:05:31+08:00', 'HUMAN', 'u_amirah', 'Amirah Yusof'),
  ('03c7d215-c0e7-5c30-86ca-e4135686eadc', 'acade111-0000-4000-8000-000000000001', 'OPP-0498', 'acade111-0002-4000-8000-000000000121', NULL, NULL, 'acade111-0001-4000-8000-000000000002', 'QUALIFYING', 6720000, 'MYR', 0.3, '2026-11-06T16:12:00+08:00', NULL, '2026-10-28T10:00:00+08:00', 'HUMAN', 'u_amirah', 'Amirah Yusof'),
  ('7b861609-d23f-524f-91bb-dce8ed800041', 'acade111-0000-4000-8000-000000000001', 'OPP-0505', 'acade111-0002-4000-8000-000000000128', NULL, NULL, 'acade111-0001-4000-8000-000000000002', 'PROPOSAL_SENT', 4200000, 'MYR', 0.6, '2026-11-10T09:40:00+08:00', NULL, '2026-10-14T09:00:00+08:00', 'HUMAN', 'u_amirah', 'Amirah Yusof'),
  ('7ef89ddd-84b4-5400-800d-32b86060f8f8', 'acade111-0000-4000-8000-000000000001', 'OPP-0470', 'acade111-0002-4000-8000-000000000133', NULL, NULL, 'acade111-0001-4000-8000-000000000002', 'LOST', 980000, 'MYR', 0, '2026-06-30T15:00:00+08:00', 'Opportunity lost on price', '2026-05-06T09:00:00+08:00', 'HUMAN', 'u_amirah', 'Amirah Yusof'),
  ('ffdf3c79-2696-5cc9-aa34-d97a7eeb97d5', 'acade111-0000-4000-8000-000000000001', 'OPP-0521', 'acade111-0002-4000-8000-000000000140', NULL, NULL, 'acade111-0001-4000-8000-000000000002', 'NEGOTIATION', 2730000, 'MYR', 0.75, '2026-11-02T11:30:00+08:00', NULL, '2026-09-30T09:00:00+08:00', 'HUMAN', 'u_amirah', 'Amirah Yusof')
ON CONFLICT (tenant_id, ref) DO UPDATE SET
  id = EXCLUDED.id,
  organisation_id = EXCLUDED.organisation_id,
  primary_contact_id = EXCLUDED.primary_contact_id,
  source_enquiry_id = EXCLUDED.source_enquiry_id,
  owner_id = EXCLUDED.owner_id,
  stage = EXCLUDED.stage,
  value_sen = EXCLUDED.value_sen,
  currency = EXCLUDED.currency,
  probability = EXCLUDED.probability,
  stage_changed_at = EXCLUDED.stage_changed_at,
  lost_reason = EXCLUDED.lost_reason,
  created_by_kind = EXCLUDED.created_by_kind,
  created_by_id = EXCLUDED.created_by_id,
  created_by_name = EXCLUDED.created_by_name
WHERE (target.id, target.organisation_id, target.primary_contact_id, target.source_enquiry_id, target.owner_id, target.stage, target.value_sen, target.currency, target.probability, target.stage_changed_at, target.lost_reason, target.created_by_kind, target.created_by_id, target.created_by_name)
   IS DISTINCT FROM (EXCLUDED.id, EXCLUDED.organisation_id, EXCLUDED.primary_contact_id, EXCLUDED.source_enquiry_id, EXCLUDED.owner_id, EXCLUDED.stage, EXCLUDED.value_sen, EXCLUDED.currency, EXCLUDED.probability, EXCLUDED.stage_changed_at, EXCLUDED.lost_reason, EXCLUDED.created_by_kind, EXCLUDED.created_by_id, EXCLUDED.created_by_name);

-- Needs analysis ──────────────────────────────────────────────────────────

-- TNA-0042's budget is NULL because the client stated none — not zero, and the screen must render the absence.
INSERT INTO core.tnas AS target
  (id, tenant_id, ref, opportunity_id, questionnaire_template_id, status, sent_at, completed_at, completed_by_kind, completed_by_id, completed_by_name, audience_headcount, audience_level, audience_sites, audience_language, budget_sen, currency, reopened_at, created_at, created_by_kind, created_by_id, created_by_name)
VALUES
  ('06a2b9fc-d8de-562b-a80f-77c6fc1ee306', 'acade111-0000-4000-8000-000000000001', 'TNA-0042', 'aea5f8fb-e55e-53c4-a39e-a0e757a264f2', NULL, 'COMPLETE', NULL, '2026-09-11T09:10:00+08:00', 'CLIENT', 'c_nurul', 'Nurul Hassan', 30, 'LINE_MANAGER', ARRAY['Shah Alam', 'Klang']::text[], 'EN', NULL, 'MYR', NULL, '2026-09-11T09:05:31+08:00', 'HUMAN', 'u_amirah', 'Amirah Yusof'),
  ('cb7b6d19-0e58-5ff2-b70b-442feb943486', 'acade111-0000-4000-8000-000000000001', 'TNA-0051', '7b861609-d23f-524f-91bb-dce8ed800041', NULL, 'COMPLETE', NULL, '2026-10-20T11:00:00+08:00', 'CLIENT', 'c_faridah', 'Faridah Omar', 22, 'PLANNER', ARRAY['Port Klang']::text[], 'EN', 4200000, 'MYR', NULL, '2026-10-14T09:20:00+08:00', 'HUMAN', 'u_amirah', 'Amirah Yusof'),
  ('9c54b90f-bd36-5ffd-a131-753af5a328bb', 'acade111-0000-4000-8000-000000000001', 'TNA-0054', '03c7d215-c0e7-5c30-86ca-e4135686eadc', NULL, 'SENT', NULL, NULL, NULL, NULL, NULL, 48, 'STORE_MANAGER', ARRAY['Klang Valley', 'Johor']::text[], 'EN', NULL, 'MYR', NULL, '2026-10-30T09:00:00+08:00', 'HUMAN', 'u_amirah', 'Amirah Yusof')
ON CONFLICT (tenant_id, ref) DO UPDATE SET
  id = EXCLUDED.id,
  opportunity_id = EXCLUDED.opportunity_id,
  questionnaire_template_id = EXCLUDED.questionnaire_template_id,
  status = EXCLUDED.status,
  sent_at = EXCLUDED.sent_at,
  completed_at = EXCLUDED.completed_at,
  completed_by_kind = EXCLUDED.completed_by_kind,
  completed_by_id = EXCLUDED.completed_by_id,
  completed_by_name = EXCLUDED.completed_by_name,
  audience_headcount = EXCLUDED.audience_headcount,
  audience_level = EXCLUDED.audience_level,
  audience_sites = EXCLUDED.audience_sites,
  audience_language = EXCLUDED.audience_language,
  budget_sen = EXCLUDED.budget_sen,
  currency = EXCLUDED.currency,
  reopened_at = EXCLUDED.reopened_at,
  created_by_kind = EXCLUDED.created_by_kind,
  created_by_id = EXCLUDED.created_by_id,
  created_by_name = EXCLUDED.created_by_name
WHERE (target.id, target.opportunity_id, target.questionnaire_template_id, target.status, target.sent_at, target.completed_at, target.completed_by_kind, target.completed_by_id, target.completed_by_name, target.audience_headcount, target.audience_level, target.audience_sites, target.audience_language, target.budget_sen, target.currency, target.reopened_at, target.created_by_kind, target.created_by_id, target.created_by_name)
   IS DISTINCT FROM (EXCLUDED.id, EXCLUDED.opportunity_id, EXCLUDED.questionnaire_template_id, EXCLUDED.status, EXCLUDED.sent_at, EXCLUDED.completed_at, EXCLUDED.completed_by_kind, EXCLUDED.completed_by_id, EXCLUDED.completed_by_name, EXCLUDED.audience_headcount, EXCLUDED.audience_level, EXCLUDED.audience_sites, EXCLUDED.audience_language, EXCLUDED.budget_sen, EXCLUDED.currency, EXCLUDED.reopened_at, EXCLUDED.created_by_kind, EXCLUDED.created_by_id, EXCLUDED.created_by_name);

-- Gaps keep their questionnaire evidence refs (Q4, Q7…) — the TNA screen cites them beside each gap.
INSERT INTO core.tna_gaps AS target
  (id, tenant_id, tna_id, name, description, priority, evidence_refs, created_at, created_by_kind, created_by_id, created_by_name)
VALUES
  ('ecfcf48d-99ba-5e62-b8ee-ce8db1f97d09', 'acade111-0000-4000-8000-000000000001', '06a2b9fc-d8de-562b-a80f-77c6fc1ee306', 'Conflict resolution', 'Production vs quality escalations', 'HIGH', ARRAY['Q4', 'Q7']::text[], '2026-09-11T09:05:31+08:00', 'AGENT', 'agent_tna', 'TNA Agent'),
  ('c13bc3b9-43a5-5736-ae9b-56194449ddec', 'acade111-0000-4000-8000-000000000001', '06a2b9fc-d8de-562b-a80f-77c6fc1ee306', 'Cross-functional communication', 'Shift handover loses the decision, not the data', 'HIGH', ARRAY['Q4', 'Q9', 'Q11']::text[], '2026-09-11T09:05:31+08:00', 'AGENT', 'agent_tna', 'TNA Agent'),
  ('6528c47f-d9da-514f-9a6d-8eaf17bb45d8', 'acade111-0000-4000-8000-000000000001', '06a2b9fc-d8de-562b-a80f-77c6fc1ee306', 'Giving corrective feedback', 'Supervisors escalate rather than address on the floor', 'MEDIUM', ARRAY['Q12']::text[], '2026-09-11T09:05:31+08:00', 'AGENT', 'agent_tna', 'TNA Agent'),
  ('05d22f32-af4a-53f0-bfb1-38e42399a6dd', 'acade111-0000-4000-8000-000000000001', 'cb7b6d19-0e58-5ff2-b70b-442feb943486', 'Interpreting operational dashboards', 'Planners act on the headline, not the distribution', 'HIGH', ARRAY['Q2', 'Q5']::text[], '2026-10-14T09:20:00+08:00', 'AGENT', 'agent_tna', 'TNA Agent')
ON CONFLICT (id) DO UPDATE SET
  tenant_id = EXCLUDED.tenant_id,
  tna_id = EXCLUDED.tna_id,
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  priority = EXCLUDED.priority,
  evidence_refs = EXCLUDED.evidence_refs,
  created_by_kind = EXCLUDED.created_by_kind,
  created_by_id = EXCLUDED.created_by_id,
  created_by_name = EXCLUDED.created_by_name
WHERE (target.tenant_id, target.tna_id, target.name, target.description, target.priority, target.evidence_refs, target.created_by_kind, target.created_by_id, target.created_by_name)
   IS DISTINCT FROM (EXCLUDED.tenant_id, EXCLUDED.tna_id, EXCLUDED.name, EXCLUDED.description, EXCLUDED.priority, EXCLUDED.evidence_refs, EXCLUDED.created_by_kind, EXCLUDED.created_by_id, EXCLUDED.created_by_name);

INSERT INTO core.tna_constraints AS target
  (id, tenant_id, tna_id, code, label, severity, created_at, created_by_kind, created_by_id, created_by_name)
VALUES
  ('14385f19-4a29-57a9-82f2-2081c8804539', 'acade111-0000-4000-8000-000000000001', '06a2b9fc-d8de-562b-a80f-77c6fc1ee306', 'DELIVERY_WINDOW', 'November 2026', 'WARN', '2026-09-11T09:05:31+08:00', 'HUMAN', 'u_amirah', 'Amirah Yusof'),
  ('970906c5-cfc5-5daa-82ab-84b64c7f9e4b', 'acade111-0000-4000-8000-000000000001', '06a2b9fc-d8de-562b-a80f-77c6fc1ee306', 'MAX_DAYS_OFF_FLOOR', 'Max 2 days', NULL, '2026-09-11T09:05:31+08:00', 'HUMAN', 'u_amirah', 'Amirah Yusof'),
  ('f2166408-2cf9-5bb1-ab18-058610773aa5', 'acade111-0000-4000-8000-000000000001', '06a2b9fc-d8de-562b-a80f-77c6fc1ee306', 'HRDC_CLAIMABLE_REQUIRED', 'Must be claimable', NULL, '2026-09-11T09:05:31+08:00', 'HUMAN', 'u_amirah', 'Amirah Yusof'),
  ('d08f5eff-b92c-57ee-b881-d1dc80bf5714', 'acade111-0000-4000-8000-000000000001', 'cb7b6d19-0e58-5ff2-b70b-442feb943486', 'DELIVERY_WINDOW', 'December 2026', NULL, '2026-10-14T09:20:00+08:00', 'HUMAN', 'u_amirah', 'Amirah Yusof'),
  ('3dfd43d6-d7fb-5e81-8182-b8c962c93163', 'acade111-0000-4000-8000-000000000001', '9c54b90f-bd36-5ffd-a131-753af5a328bb', 'DELIVERY_WINDOW', 'Q1 2027', NULL, '2026-10-30T09:00:00+08:00', 'HUMAN', 'u_amirah', 'Amirah Yusof')
ON CONFLICT (tenant_id, tna_id, code) DO UPDATE SET
  id = EXCLUDED.id,
  label = EXCLUDED.label,
  severity = EXCLUDED.severity,
  created_by_kind = EXCLUDED.created_by_kind,
  created_by_id = EXCLUDED.created_by_id,
  created_by_name = EXCLUDED.created_by_name
WHERE (target.id, target.label, target.severity, target.created_by_kind, target.created_by_id, target.created_by_name)
   IS DISTINCT FROM (EXCLUDED.id, EXCLUDED.label, EXCLUDED.severity, EXCLUDED.created_by_kind, EXCLUDED.created_by_id, EXCLUDED.created_by_name);

-- What the analysis read. `source_ref` is the fixture's own citation string, verbatim.
INSERT INTO core.tna_evidence AS target
  (id, tenant_id, tna_id, source_type, source_ref, excerpt, created_at, created_by_kind, created_by_id, created_by_name)
VALUES
  ('cf322fd9-d78e-5110-95d3-5aafbf53d98f', 'acade111-0000-4000-8000-000000000001', '06a2b9fc-d8de-562b-a80f-77c6fc1ee306', 'EMAIL', 'ENQ-2026-0912', NULL, '2026-09-11T09:05:31+08:00', 'AGENT', 'agent_tna', 'TNA Agent'),
  ('a052ebae-61dd-5ae0-98fc-91fd202441f8', 'acade111-0000-4000-8000-000000000001', '06a2b9fc-d8de-562b-a80f-77c6fc1ee306', 'QUESTIONNAIRE', 'TNA-0042/responses', NULL, '2026-09-11T09:05:31+08:00', 'AGENT', 'agent_tna', 'TNA Agent'),
  ('c398ba8f-8a0a-55d6-b50a-8d0c6e63d74d', 'acade111-0000-4000-8000-000000000001', '06a2b9fc-d8de-562b-a80f-77c6fc1ee306', 'HISTORY', 'ORG-0114/2024-2025', NULL, '2026-09-11T09:05:31+08:00', 'AGENT', 'agent_tna', 'TNA Agent'),
  ('917928ea-0eef-58b9-a620-3c24ef177665', 'acade111-0000-4000-8000-000000000001', '06a2b9fc-d8de-562b-a80f-77c6fc1ee306', 'CATALOGUE', 'PRG-*/nov-availability', NULL, '2026-09-11T09:05:31+08:00', 'AGENT', 'agent_tna', 'TNA Agent'),
  ('af597120-b42f-54ad-a011-5693830a074b', 'acade111-0000-4000-8000-000000000001', 'cb7b6d19-0e58-5ff2-b70b-442feb943486', 'QUESTIONNAIRE', 'TNA-0051/responses', NULL, '2026-10-14T09:20:00+08:00', 'AGENT', 'agent_tna', 'TNA Agent')
ON CONFLICT (id) DO UPDATE SET
  tenant_id = EXCLUDED.tenant_id,
  tna_id = EXCLUDED.tna_id,
  source_type = EXCLUDED.source_type,
  source_ref = EXCLUDED.source_ref,
  excerpt = EXCLUDED.excerpt,
  created_by_kind = EXCLUDED.created_by_kind,
  created_by_id = EXCLUDED.created_by_id,
  created_by_name = EXCLUDED.created_by_name
WHERE (target.tenant_id, target.tna_id, target.source_type, target.source_ref, target.excerpt, target.created_by_kind, target.created_by_id, target.created_by_name)
   IS DISTINCT FROM (EXCLUDED.tenant_id, EXCLUDED.tna_id, EXCLUDED.source_type, EXCLUDED.source_ref, EXCLUDED.excerpt, EXCLUDED.created_by_kind, EXCLUDED.created_by_id, EXCLUDED.created_by_name);

INSERT INTO core.tna_recommendations AS target
  (id, tenant_id, tna_id, programme_id, fit_score, rationale, price_indication_sen, currency, rank, scoring_model_version, scoring_weights, accepted_at, created_at, created_by_kind, created_by_id, created_by_name)
VALUES
  ('9f790a39-496f-5c83-a28a-7e23460a1677', 'acade111-0000-4000-8000-000000000001', '06a2b9fc-d8de-562b-a80f-77c6fc1ee306', '24d14893-e990-5f09-92d6-6580a3c684c2', 0.91, 'Covers both high-priority gaps; Farah Aziz free 12–13 Nov.', 1850000, 'MYR', 1, 'fit-v3', '{"gapCoverage":0.5,"audienceFit":0.2,"windowFit":0.2,"trainerAvailability":0.1}'::jsonb, NULL, '2026-09-11T09:13:10+08:00', 'AGENT', 'agent_tna', 'TNA Agent'),
  ('c1db77bc-8405-5633-96c4-e8afdb417857', 'acade111-0000-4000-8000-000000000001', '06a2b9fc-d8de-562b-a80f-77c6fc1ee306', 'e31d7740-5e6a-558d-8a04-2a2a60fd1c21', 0.78, 'Covers conflict only; no communication module.', 980000, 'MYR', 2, 'fit-v3', '{"gapCoverage":0.5,"audienceFit":0.2,"windowFit":0.2,"trainerAvailability":0.1}'::jsonb, NULL, '2026-09-11T09:13:10+08:00', 'AGENT', 'agent_tna', 'TNA Agent'),
  ('e647f716-7937-5dc4-8b61-94597e0899d2', 'acade111-0000-4000-8000-000000000001', '06a2b9fc-d8de-562b-a80f-77c6fc1ee306', 'cd093cf5-d36a-5313-b957-a2df85ee2520', 0.22, 'No gap match; listed for completeness.', NULL, 'MYR', 3, 'fit-v3', '{"gapCoverage":0.5,"audienceFit":0.2,"windowFit":0.2,"trainerAvailability":0.1}'::jsonb, NULL, '2026-09-11T09:13:10+08:00', 'AGENT', 'agent_tna', 'TNA Agent'),
  ('2cb3648d-acf1-563f-862d-7b3d755bdef9', 'acade111-0000-4000-8000-000000000001', 'cb7b6d19-0e58-5ff2-b70b-442feb943486', 'cd093cf5-d36a-5313-b957-a2df85ee2520', 0.94, 'Direct gap match; repeat cohort from October.', 1920000, 'MYR', 1, 'fit-v3', '{"gapCoverage":0.5,"audienceFit":0.2,"windowFit":0.2,"trainerAvailability":0.1}'::jsonb, NULL, '2026-10-20T11:04:00+08:00', 'AGENT', 'agent_tna', 'TNA Agent')
ON CONFLICT (tenant_id, tna_id, programme_id) DO UPDATE SET
  id = EXCLUDED.id,
  fit_score = EXCLUDED.fit_score,
  rationale = EXCLUDED.rationale,
  price_indication_sen = EXCLUDED.price_indication_sen,
  currency = EXCLUDED.currency,
  rank = EXCLUDED.rank,
  scoring_model_version = EXCLUDED.scoring_model_version,
  scoring_weights = EXCLUDED.scoring_weights,
  accepted_at = EXCLUDED.accepted_at,
  created_by_kind = EXCLUDED.created_by_kind,
  created_by_id = EXCLUDED.created_by_id,
  created_by_name = EXCLUDED.created_by_name
WHERE (target.id, target.fit_score, target.rationale, target.price_indication_sen, target.currency, target.rank, target.scoring_model_version, target.scoring_weights, target.accepted_at, target.created_by_kind, target.created_by_id, target.created_by_name)
   IS DISTINCT FROM (EXCLUDED.id, EXCLUDED.fit_score, EXCLUDED.rationale, EXCLUDED.price_indication_sen, EXCLUDED.currency, EXCLUDED.rank, EXCLUDED.scoring_model_version, EXCLUDED.scoring_weights, EXCLUDED.accepted_at, EXCLUDED.created_by_kind, EXCLUDED.created_by_id, EXCLUDED.created_by_name);

-- Proposals ───────────────────────────────────────────────────────────────

-- PRO-2026-0184 is DRAFT internally while its portal page reads ACCEPTED — both states are in the pack, on purpose.
INSERT INTO core.proposals AS target
  (id, tenant_id, ref, opportunity_id, organisation_id, template_id, programme_id, run_id, status, value_sen, currency, margin_rate, sent_at, first_viewed_at, accepted_at, lost_at, created_at, created_by_kind, created_by_id, created_by_name)
VALUES
  ('a4bdb4e8-35f3-5ed3-a0e1-710b3f0e9bdc', 'acade111-0000-4000-8000-000000000001', 'PRO-2026-0184', 'aea5f8fb-e55e-53c4-a39e-a0e757a264f2', 'acade111-0002-4000-8000-000000000114', '7d213d10-459a-5a6e-afa2-7f0fe56ed425', NULL, NULL, 'DRAFT', 1850000, 'MYR', 0.41, NULL, NULL, NULL, NULL, '2026-09-11T09:14:02+08:00', 'AGENT', 'agent_proposal', 'Proposal Agent'),
  ('7cf72341-2af7-5fdc-b4c6-eb39c44dd9b5', 'acade111-0000-4000-8000-000000000001', 'PRO-2026-0191', '7b861609-d23f-524f-91bb-dce8ed800041', 'acade111-0002-4000-8000-000000000128', '7d213d10-459a-5a6e-afa2-7f0fe56ed425', NULL, NULL, 'VIEWED', 1920000, 'MYR', 0.43, NULL, NULL, NULL, NULL, '2026-10-21T10:00:00+08:00', 'AGENT', 'agent_proposal', 'Proposal Agent'),
  ('058ae894-1152-5fb9-8bfc-4e5d5a35655e', 'acade111-0000-4000-8000-000000000001', 'PRO-2026-0166', '7ef89ddd-84b4-5400-800d-32b86060f8f8', 'acade111-0002-4000-8000-000000000133', '7d213d10-459a-5a6e-afa2-7f0fe56ed425', NULL, NULL, 'LOST', 980000, 'MYR', 0.39, NULL, NULL, NULL, '2026-06-30T15:00:00+08:00', '2026-05-20T10:00:00+08:00', 'HUMAN', 'u_amirah', 'Amirah Yusof')
ON CONFLICT (tenant_id, ref) DO UPDATE SET
  id = EXCLUDED.id,
  opportunity_id = EXCLUDED.opportunity_id,
  organisation_id = EXCLUDED.organisation_id,
  template_id = EXCLUDED.template_id,
  programme_id = EXCLUDED.programme_id,
  run_id = EXCLUDED.run_id,
  status = EXCLUDED.status,
  value_sen = EXCLUDED.value_sen,
  currency = EXCLUDED.currency,
  margin_rate = EXCLUDED.margin_rate,
  sent_at = EXCLUDED.sent_at,
  first_viewed_at = EXCLUDED.first_viewed_at,
  accepted_at = EXCLUDED.accepted_at,
  lost_at = EXCLUDED.lost_at,
  created_by_kind = EXCLUDED.created_by_kind,
  created_by_id = EXCLUDED.created_by_id,
  created_by_name = EXCLUDED.created_by_name
WHERE (target.id, target.opportunity_id, target.organisation_id, target.template_id, target.programme_id, target.run_id, target.status, target.value_sen, target.currency, target.margin_rate, target.sent_at, target.first_viewed_at, target.accepted_at, target.lost_at, target.created_by_kind, target.created_by_id, target.created_by_name)
   IS DISTINCT FROM (EXCLUDED.id, EXCLUDED.opportunity_id, EXCLUDED.organisation_id, EXCLUDED.template_id, EXCLUDED.programme_id, EXCLUDED.run_id, EXCLUDED.status, EXCLUDED.value_sen, EXCLUDED.currency, EXCLUDED.margin_rate, EXCLUDED.sent_at, EXCLUDED.first_viewed_at, EXCLUDED.accepted_at, EXCLUDED.lost_at, EXCLUDED.created_by_kind, EXCLUDED.created_by_id, EXCLUDED.created_by_name);

INSERT INTO core.proposal_sections AS target
  (id, tenant_id, proposal_id, n, title, body, merge_fields_used, needs_review, created_at, created_by_kind, created_by_id, created_by_name)
VALUES
  ('bb70a947-6a05-56f8-ab22-b7880da51bdc', 'acade111-0000-4000-8000-000000000001', 'a4bdb4e8-35f3-5ed3-a0e1-710b3f0e9bdc', 1, 'Understanding your needs', 'Aurora Manufacturing''s 30 line managers report friction between production and quality teams…', ARRAY['contact.name']::text[], FALSE, '2026-09-11T09:14:02+08:00', 'AGENT', 'agent_proposal', 'Proposal Agent'),
  ('394e2c34-cb72-5fbc-b5e1-0038aca62fc9', 'acade111-0000-4000-8000-000000000001', 'a4bdb4e8-35f3-5ed3-a0e1-710b3f0e9bdc', 2, 'Recommended programme', 'Leading Through Change is a two-day facilitated programme for up to 30 participants…', ARRAY['programme.title', 'engagement.dates']::text[], FALSE, '2026-09-11T09:14:02+08:00', 'AGENT', 'agent_proposal', 'Proposal Agent'),
  ('db75b202-cde5-5ffa-a3b8-6c75fef9bb49', 'acade111-0000-4000-8000-000000000001', 'a4bdb4e8-35f3-5ed3-a0e1-710b3f0e9bdc', 3, 'Delivery plan', 'Two consecutive days on site at Aurora HQ Shah Alam, 12 and 13 November 2026…', NULL, FALSE, '2026-09-11T09:14:02+08:00', 'AGENT', 'agent_proposal', 'Proposal Agent'),
  ('b628f75a-ce51-54f7-bfa8-fb412d2b28bf', 'acade111-0000-4000-8000-000000000001', 'a4bdb4e8-35f3-5ed3-a0e1-710b3f0e9bdc', 4, 'Investment', 'RM 18,500 for up to 30 participants, inclusive of materials and trainer travel.', ARRAY['investment.total']::text[], FALSE, '2026-09-11T09:14:02+08:00', 'AGENT', 'agent_proposal', 'Proposal Agent'),
  ('8ff9147f-f4f4-5bf7-8869-98bce70c62b5', 'acade111-0000-4000-8000-000000000001', 'a4bdb4e8-35f3-5ed3-a0e1-710b3f0e9bdc', 5, 'HRDC claim guidance', 'This programme is claimable under SBL-Khas subject to prior grant approval…', NULL, TRUE, '2026-09-11T09:14:02+08:00', 'AGENT', 'agent_proposal', 'Proposal Agent'),
  ('623601b6-42cf-5f78-a5c6-b00b65a279ac', 'acade111-0000-4000-8000-000000000001', '7cf72341-2af7-5fdc-b4c6-eb39c44dd9b5', 1, 'Understanding your needs', 'Meridian''s planning team needs to read the distribution, not the headline…', NULL, FALSE, '2026-10-21T10:00:00+08:00', 'AGENT', 'agent_proposal', 'Proposal Agent'),
  ('e39dd313-6bdb-5b0e-bd8a-70d463555d24', 'acade111-0000-4000-8000-000000000001', '7cf72341-2af7-5fdc-b4c6-eb39c44dd9b5', 2, 'Recommended programme', 'Data Literacy for Managers, two days, December 2026.', NULL, FALSE, '2026-10-21T10:00:00+08:00', 'AGENT', 'agent_proposal', 'Proposal Agent'),
  ('ec8964f9-a0df-59c2-ace1-39b6739eb2e3', 'acade111-0000-4000-8000-000000000001', '058ae894-1152-5fb9-8bfc-4e5d5a35655e', 1, 'Understanding your needs', 'Front office service recovery…', NULL, FALSE, '2026-05-20T10:00:00+08:00', 'HUMAN', 'u_amirah', 'Amirah Yusof')
ON CONFLICT (tenant_id, proposal_id, n) DO UPDATE SET
  id = EXCLUDED.id,
  title = EXCLUDED.title,
  body = EXCLUDED.body,
  merge_fields_used = EXCLUDED.merge_fields_used,
  needs_review = EXCLUDED.needs_review,
  created_by_kind = EXCLUDED.created_by_kind,
  created_by_id = EXCLUDED.created_by_id,
  created_by_name = EXCLUDED.created_by_name
WHERE (target.id, target.title, target.body, target.merge_fields_used, target.needs_review, target.created_by_kind, target.created_by_id, target.created_by_name)
   IS DISTINCT FROM (EXCLUDED.id, EXCLUDED.title, EXCLUDED.body, EXCLUDED.merge_fields_used, EXCLUDED.needs_review, EXCLUDED.created_by_kind, EXCLUDED.created_by_id, EXCLUDED.created_by_name);

-- Quotations ──────────────────────────────────────────────────────────────

-- Three costings. QUO-2026-0184's margin floor binds; QUO-2026-0179's catalogue floor does.
-- sell_price_sen and direct_cost_sen are written as the fixture states them and are then
-- recomputed from the lines by trg_quotation_lines_recalc; the deferred reconciliation
-- trigger fails this file at COMMIT if the two ever disagree.
INSERT INTO core.quotations AS target
  (id, tenant_id, ref, proposal_id, supersedes_quotation_id, version, rate_card_id, pax, sell_price_sen, direct_cost_sen, currency, programme_floor_price_sen, floor_margin_rate, commission_rate, commission_payable_on, discount_approval_id, invoice_id, status, created_at, created_by_kind, created_by_id, created_by_name)
VALUES
  ('8af3f0db-3802-5d75-b1da-babf6ad367d4', 'acade111-0000-4000-8000-000000000001', 'QUO-2026-0184', 'a4bdb4e8-35f3-5ed3-a0e1-710b3f0e9bdc', NULL, 1, '2d9d4fa8-edc5-53d4-9c98-fe6cc7192179', 30, 1850000, 1140000, 'MYR', 1390000, 0.35, 0.08, 'COLLECTION', NULL, NULL, 'DRAFT', '2026-09-11T09:14:20+08:00', 'HUMAN', 'u_amirah', 'Amirah Yusof'),
  ('fab18728-b6fc-5584-8bf3-110e8a99fa11', 'acade111-0000-4000-8000-000000000001', 'QUO-2026-0179', '058ae894-1152-5fb9-8bfc-4e5d5a35655e', NULL, 1, '2d9d4fa8-edc5-53d4-9c98-fe6cc7192179', 18, 980000, 382000, 'MYR', 735000, 0.35, 0.08, 'COLLECTION', NULL, NULL, 'APPLIED', '2026-05-20T10:10:00+08:00', 'HUMAN', 'u_amirah', 'Amirah Yusof'),
  ('0feb4cbd-54ef-5433-807e-399d9ad1188d', 'acade111-0000-4000-8000-000000000001', 'QUO-2026-0191', '7cf72341-2af7-5fdc-b4c6-eb39c44dd9b5', NULL, 1, '2d9d4fa8-edc5-53d4-9c98-fe6cc7192179', 22, 1920000, 991000, 'MYR', 1440000, 0.35, 0.08, 'COLLECTION', NULL, NULL, 'APPLIED', '2026-10-21T10:05:00+08:00', 'HUMAN', 'u_amirah', 'Amirah Yusof')
ON CONFLICT (tenant_id, ref) DO UPDATE SET
  id = EXCLUDED.id,
  proposal_id = EXCLUDED.proposal_id,
  supersedes_quotation_id = EXCLUDED.supersedes_quotation_id,
  version = EXCLUDED.version,
  rate_card_id = EXCLUDED.rate_card_id,
  pax = EXCLUDED.pax,
  sell_price_sen = EXCLUDED.sell_price_sen,
  direct_cost_sen = EXCLUDED.direct_cost_sen,
  currency = EXCLUDED.currency,
  programme_floor_price_sen = EXCLUDED.programme_floor_price_sen,
  floor_margin_rate = EXCLUDED.floor_margin_rate,
  commission_rate = EXCLUDED.commission_rate,
  commission_payable_on = EXCLUDED.commission_payable_on,
  discount_approval_id = EXCLUDED.discount_approval_id,
  invoice_id = EXCLUDED.invoice_id,
  status = EXCLUDED.status,
  created_by_kind = EXCLUDED.created_by_kind,
  created_by_id = EXCLUDED.created_by_id,
  created_by_name = EXCLUDED.created_by_name
WHERE (target.id, target.proposal_id, target.supersedes_quotation_id, target.version, target.rate_card_id, target.pax, target.sell_price_sen, target.direct_cost_sen, target.currency, target.programme_floor_price_sen, target.floor_margin_rate, target.commission_rate, target.commission_payable_on, target.discount_approval_id, target.invoice_id, target.status, target.created_by_kind, target.created_by_id, target.created_by_name)
   IS DISTINCT FROM (EXCLUDED.id, EXCLUDED.proposal_id, EXCLUDED.supersedes_quotation_id, EXCLUDED.version, EXCLUDED.rate_card_id, EXCLUDED.pax, EXCLUDED.sell_price_sen, EXCLUDED.direct_cost_sen, EXCLUDED.currency, EXCLUDED.programme_floor_price_sen, EXCLUDED.floor_margin_rate, EXCLUDED.commission_rate, EXCLUDED.commission_payable_on, EXCLUDED.discount_approval_id, EXCLUDED.invoice_id, EXCLUDED.status, EXCLUDED.created_by_kind, EXCLUDED.created_by_id, EXCLUDED.created_by_name);

-- `total_sen` is generated — app.round_half_up_sen(unit_price × qty) — so the §18 rounding rule is the database's, not the fixture's.
INSERT INTO core.quotation_lines AS target
  (id, tenant_id, quotation_id, n, item, detail, basis, qty, unit, unit_price_sen, currency, is_cost, created_at)
VALUES
  ('1f1dc55e-a393-5312-b97e-5f39672a25f4', 'acade111-0000-4000-8000-000000000001', '8af3f0db-3802-5d75-b1da-babf6ad367d4', 1, 'TRAINER_FEE', 'Farah Aziz · TTT certified', 'PER_DAY', 2, 'DAY', 480000, 'MYR', TRUE, '2026-09-11T09:14:20+08:00'),
  ('f764a95e-bd4e-5d28-a22e-e135902ffc6e', 'acade111-0000-4000-8000-000000000001', '8af3f0db-3802-5d75-b1da-babf6ad367d4', 2, 'VENUE', 'Client site · Aurora HQ Shah Alam', 'PER_UNIT', 0, NULL, 0, 'MYR', TRUE, '2026-09-11T09:14:20+08:00'),
  ('4bee5f34-2d28-5f7a-bb88-eaadfe50a12e', 'acade111-0000-4000-8000-000000000001', '8af3f0db-3802-5d75-b1da-babf6ad367d4', 3, 'MATERIALS', NULL, 'PER_UNIT', 30, NULL, 4000, 'MYR', TRUE, '2026-09-11T09:14:20+08:00'),
  ('1ce0abbe-0c61-5ffe-87ac-cccd342fa4a4', 'acade111-0000-4000-8000-000000000001', '8af3f0db-3802-5d75-b1da-babf6ad367d4', 4, 'TRAVEL', NULL, 'PER_UNIT', 2, NULL, 30000, 'MYR', TRUE, '2026-09-11T09:14:20+08:00'),
  ('3107b980-2b5f-57ab-a8d1-6325f807a875', 'acade111-0000-4000-8000-000000000001', '8af3f0db-3802-5d75-b1da-babf6ad367d4', 5, 'SELL_PRICE', 'Quoted price to the client', 'PACKAGE', 1, NULL, 1850000, 'MYR', FALSE, '2026-09-11T09:14:20+08:00'),
  ('5c256664-53ba-560d-a410-d49c502031f3', 'acade111-0000-4000-8000-000000000001', 'fab18728-b6fc-5584-8bf3-110e8a99fa11', 1, 'TRAINER_FEE', 'Farah Aziz · 1 day', 'PER_DAY', 1, 'DAY', 280000, 'MYR', TRUE, '2026-05-20T10:10:00+08:00'),
  ('56746831-5d3a-50e9-8ed4-e026695a6ed7', 'acade111-0000-4000-8000-000000000001', 'fab18728-b6fc-5584-8bf3-110e8a99fa11', 2, 'VENUE', 'Client site · Sutera Bukit Bintang', 'PER_UNIT', 0, NULL, 0, 'MYR', TRUE, '2026-05-20T10:10:00+08:00'),
  ('152ef02a-2391-586a-990d-388154847691', 'acade111-0000-4000-8000-000000000001', 'fab18728-b6fc-5584-8bf3-110e8a99fa11', 3, 'MATERIALS', NULL, 'PER_UNIT', 18, NULL, 4000, 'MYR', TRUE, '2026-05-20T10:10:00+08:00'),
  ('01ffca15-46e5-5746-ae57-ab90d66cd313', 'acade111-0000-4000-8000-000000000001', 'fab18728-b6fc-5584-8bf3-110e8a99fa11', 4, 'TRAVEL', NULL, 'PER_UNIT', 1, 'TRIP', 30000, 'MYR', TRUE, '2026-05-20T10:10:00+08:00'),
  ('91ec6cfb-39f8-507c-9ccc-629c284b4689', 'acade111-0000-4000-8000-000000000001', 'fab18728-b6fc-5584-8bf3-110e8a99fa11', 5, 'SELL_PRICE', 'Quoted price to the client', 'PACKAGE', 1, NULL, 980000, 'MYR', FALSE, '2026-05-20T10:10:00+08:00'),
  ('82fae214-0aad-567c-9b51-7c6e6f0d5789', 'acade111-0000-4000-8000-000000000001', '0feb4cbd-54ef-5433-807e-399d9ad1188d', 1, 'TRAINER_FEE', 'Lee Chin Hoe · 2 days', 'PER_DAY', 2, 'DAY', 360000, 'MYR', TRUE, '2026-10-21T10:05:00+08:00'),
  ('9a364fa5-0d80-5d90-8dec-1e10e0ba0007', 'acade111-0000-4000-8000-000000000001', '0feb4cbd-54ef-5433-807e-399d9ad1188d', 2, 'VENUE', 'Own venue · Akademi Perdana', 'PER_UNIT', 1, NULL, 90000, 'MYR', TRUE, '2026-10-21T10:05:00+08:00'),
  ('e4ff42b4-56be-58e5-b536-7ca988b2646e', 'acade111-0000-4000-8000-000000000001', '0feb4cbd-54ef-5433-807e-399d9ad1188d', 3, 'MATERIALS', NULL, 'PER_UNIT', 22, NULL, 5500, 'MYR', TRUE, '2026-10-21T10:05:00+08:00'),
  ('2ff597d4-122f-52c7-b993-e01e5b119ad6', 'acade111-0000-4000-8000-000000000001', '0feb4cbd-54ef-5433-807e-399d9ad1188d', 4, 'TRAVEL', NULL, 'PER_UNIT', 2, NULL, 30000, 'MYR', TRUE, '2026-10-21T10:05:00+08:00'),
  ('d9464579-7ba1-5a4d-8178-286788ee8ca8', 'acade111-0000-4000-8000-000000000001', '0feb4cbd-54ef-5433-807e-399d9ad1188d', 5, 'SELL_PRICE', 'Quoted price to the client', 'PACKAGE', 1, NULL, 1920000, 'MYR', FALSE, '2026-10-21T10:05:00+08:00')
ON CONFLICT (tenant_id, quotation_id, n) DO UPDATE SET
  id = EXCLUDED.id,
  item = EXCLUDED.item,
  detail = EXCLUDED.detail,
  basis = EXCLUDED.basis,
  qty = EXCLUDED.qty,
  unit = EXCLUDED.unit,
  unit_price_sen = EXCLUDED.unit_price_sen,
  currency = EXCLUDED.currency,
  is_cost = EXCLUDED.is_cost
WHERE (target.id, target.item, target.detail, target.basis, target.qty, target.unit, target.unit_price_sen, target.currency, target.is_cost)
   IS DISTINCT FROM (EXCLUDED.id, EXCLUDED.item, EXCLUDED.detail, EXCLUDED.basis, EXCLUDED.qty, EXCLUDED.unit, EXCLUDED.unit_price_sen, EXCLUDED.currency, EXCLUDED.is_cost);

-- Client portal ───────────────────────────────────────────────────────────

-- The two links a client opens. `issued_at` is the portal page's own `issuedAt`;
-- `expires_at` is the column's 30-day default written out, so the emitted SQL is a
-- literal rather than a `now()` that differs on every machine that loads it.
INSERT INTO core.public_share_tokens AS target
  (id, tenant_id, target_kind, proposal_id, tna_id, token_hash, issued_at, expires_at, revoked_at, last_accessed_at, access_count, created_at, created_by_kind, created_by_id, created_by_name)
VALUES
  ('86a2a6ef-691e-58cf-bf21-d5d9b7584e2b', 'acade111-0000-4000-8000-000000000001', 'PROPOSAL', 'a4bdb4e8-35f3-5ed3-a0e1-710b3f0e9bdc', NULL, '\x82fbde83d458cac99588da126b11bd88368eb8035d51af4ba43513889dc16c87'::bytea, '2026-09-11T00:00:00+08:00', '2026-10-10T16:00:00.000Z', NULL, NULL, 0, '2026-09-11T00:00:00+08:00', 'HUMAN', 'u_amirah', 'Amirah Yusof'),
  ('da981a80-6429-5675-beaf-7ca24c94fd0c', 'acade111-0000-4000-8000-000000000001', 'PROPOSAL', '7cf72341-2af7-5fdc-b4c6-eb39c44dd9b5', NULL, '\x886303b0b74ee7d66baae4ce65b55ef2c7f70e88c760faea6635fa13bdd57931'::bytea, '2026-10-21T00:00:00+08:00', '2026-11-19T16:00:00.000Z', NULL, NULL, 0, '2026-10-21T00:00:00+08:00', 'HUMAN', 'u_amirah', 'Amirah Yusof')
ON CONFLICT (id) DO UPDATE SET
  tenant_id = EXCLUDED.tenant_id,
  target_kind = EXCLUDED.target_kind,
  proposal_id = EXCLUDED.proposal_id,
  tna_id = EXCLUDED.tna_id,
  token_hash = EXCLUDED.token_hash,
  issued_at = EXCLUDED.issued_at,
  expires_at = EXCLUDED.expires_at,
  revoked_at = EXCLUDED.revoked_at,
  last_accessed_at = EXCLUDED.last_accessed_at,
  access_count = EXCLUDED.access_count,
  created_by_kind = EXCLUDED.created_by_kind,
  created_by_id = EXCLUDED.created_by_id,
  created_by_name = EXCLUDED.created_by_name
WHERE (target.tenant_id, target.target_kind, target.proposal_id, target.tna_id, target.token_hash, target.issued_at, target.expires_at, target.revoked_at, target.last_accessed_at, target.access_count, target.created_by_kind, target.created_by_id, target.created_by_name)
   IS DISTINCT FROM (EXCLUDED.tenant_id, EXCLUDED.target_kind, EXCLUDED.proposal_id, EXCLUDED.tna_id, EXCLUDED.token_hash, EXCLUDED.issued_at, EXCLUDED.expires_at, EXCLUDED.revoked_at, EXCLUDED.last_accessed_at, EXCLUDED.access_count, EXCLUDED.created_by_kind, EXCLUDED.created_by_id, EXCLUDED.created_by_name);

INSERT INTO core.portal_acceptances AS target
  (id, tenant_id, proposal_id, accepted_by_name, accepted_by_role, accepted_at, signature_id, engagement_id, share_token_id, created_at, created_by_kind, created_by_id, created_by_name)
VALUES
  ('751161e5-73dc-5b0b-b4ef-b1df537e14b4', 'acade111-0000-4000-8000-000000000001', 'a4bdb4e8-35f3-5ed3-a0e1-710b3f0e9bdc', 'Nurul Hassan', 'HR Manager', '2026-09-15T10:24:00+08:00', NULL, NULL, '86a2a6ef-691e-58cf-bf21-d5d9b7584e2b', '2026-09-15T10:24:00+08:00', 'CLIENT', 'portal', 'Nurul Hassan')
ON CONFLICT (tenant_id, proposal_id) DO UPDATE SET
  id = EXCLUDED.id,
  accepted_by_name = EXCLUDED.accepted_by_name,
  accepted_by_role = EXCLUDED.accepted_by_role,
  accepted_at = EXCLUDED.accepted_at,
  signature_id = EXCLUDED.signature_id,
  engagement_id = EXCLUDED.engagement_id,
  share_token_id = EXCLUDED.share_token_id,
  created_by_kind = EXCLUDED.created_by_kind,
  created_by_id = EXCLUDED.created_by_id,
  created_by_name = EXCLUDED.created_by_name
WHERE (target.id, target.accepted_by_name, target.accepted_by_role, target.accepted_at, target.signature_id, target.engagement_id, target.share_token_id, target.created_by_kind, target.created_by_id, target.created_by_name)
   IS DISTINCT FROM (EXCLUDED.id, EXCLUDED.accepted_by_name, EXCLUDED.accepted_by_role, EXCLUDED.accepted_at, EXCLUDED.signature_id, EXCLUDED.engagement_id, EXCLUDED.share_token_id, EXCLUDED.created_by_kind, EXCLUDED.created_by_id, EXCLUDED.created_by_name);

INSERT INTO core.portal_comments AS target
  (id, tenant_id, proposal_id, contact_id, author_name, author_kind, body, posted_at, created_at, created_by_kind, created_by_id, created_by_name)
VALUES
  ('aa3d3997-e1ef-587c-9b1d-576ed47172cb', 'acade111-0000-4000-8000-000000000001', 'a4bdb4e8-35f3-5ed3-a0e1-710b3f0e9bdc', NULL, 'Nurul Hassan', 'CLIENT', 'Can we confirm the November dates before we take this to the plant director?', '2026-09-12T14:02:00+08:00', '2026-09-12T14:02:00+08:00', 'CLIENT', 'portal', 'Nurul Hassan'),
  ('83e7935c-7fe4-5729-bfa8-a805f07e6ca2', 'acade111-0000-4000-8000-000000000001', 'a4bdb4e8-35f3-5ed3-a0e1-710b3f0e9bdc', NULL, 'Amirah Yusof', 'HUMAN', 'Yes — 12 and 13 November are held for you until Friday.', '2026-09-12T16:20:00+08:00', '2026-09-12T16:20:00+08:00', 'HUMAN', 'portal', 'Amirah Yusof')
ON CONFLICT (id) DO UPDATE SET
  tenant_id = EXCLUDED.tenant_id,
  proposal_id = EXCLUDED.proposal_id,
  contact_id = EXCLUDED.contact_id,
  author_name = EXCLUDED.author_name,
  author_kind = EXCLUDED.author_kind,
  body = EXCLUDED.body,
  posted_at = EXCLUDED.posted_at,
  created_by_kind = EXCLUDED.created_by_kind,
  created_by_id = EXCLUDED.created_by_id,
  created_by_name = EXCLUDED.created_by_name
WHERE (target.tenant_id, target.proposal_id, target.contact_id, target.author_name, target.author_kind, target.body, target.posted_at, target.created_by_kind, target.created_by_id, target.created_by_name)
   IS DISTINCT FROM (EXCLUDED.tenant_id, EXCLUDED.proposal_id, EXCLUDED.contact_id, EXCLUDED.author_name, EXCLUDED.author_kind, EXCLUDED.body, EXCLUDED.posted_at, EXCLUDED.created_by_kind, EXCLUDED.created_by_id, EXCLUDED.created_by_name);

-- Follow-up queue ─────────────────────────────────────────────────────────

-- Nine rows. FUP-0304 and FUP-0307 are the two OVERDUE ones the queue renders in danger.
INSERT INTO core.follow_ups AS target
  (id, tenant_id, ref, organisation_id, contact_id, proposal_id, invoice_id, reason, due_date, status, autonomy, owner_id, created_at, created_by_kind, created_by_id, created_by_name)
VALUES
  ('00633a2e-2a31-5a60-8513-1e3b6ab1190d', 'acade111-0000-4000-8000-000000000001', 'FUP-0311', 'acade111-0002-4000-8000-000000000114', 'eab22cf4-2961-5919-b158-75e055bc6a30', NULL, NULL, 'PRO-2026-0184 sent 11 Sep · not opened since 13 Sep', '2026-09-16', 'DUE', 'SUGGEST', 'acade111-0001-4000-8000-000000000002', '2026-11-14T10:32:00+08:00', 'AGENT', 'agent_followup', 'Follow-up Agent'),
  ('c16da2ab-4baa-5081-a436-bae6afe04890', 'acade111-0000-4000-8000-000000000001', 'FUP-0304', 'acade111-0002-4000-8000-000000000121', '6cfeb215-c79f-5338-939e-40d7531b4f4f', NULL, NULL, 'Discovery call requested 28 Oct · no reply to two emails', '2026-11-10', 'OVERDUE', 'SUGGEST', 'acade111-0001-4000-8000-000000000002', '2026-11-14T10:32:00+08:00', 'AGENT', 'agent_followup', 'Follow-up Agent'),
  ('40223db7-0134-5526-8749-c0c17ed6b9b3', 'acade111-0000-4000-8000-000000000001', 'FUP-0307', 'acade111-0002-4000-8000-000000000128', '92b57985-0ea6-5de6-9b09-b1cdd832512f', NULL, NULL, 'Proposal viewed 06 Nov · decision promised by 11 Nov', '2026-11-11', 'OVERDUE', 'SUGGEST', 'acade111-0001-4000-8000-000000000002', '2026-11-14T10:32:00+08:00', 'AGENT', 'agent_followup', 'Follow-up Agent'),
  ('f3d6ac4c-a9fe-5f83-9644-ff4b9e2fd149', 'acade111-0000-4000-8000-000000000001', 'FUP-0309', 'acade111-0002-4000-8000-000000000140', 'f181430e-87dd-5977-9974-48e41ab3ffff', NULL, NULL, 'Negotiation stalled on start date · last contact 02 Nov', '2026-11-14', 'DUE', 'SUGGEST', 'acade111-0001-4000-8000-000000000002', '2026-11-14T10:32:00+08:00', 'AGENT', 'agent_followup', 'Follow-up Agent'),
  ('56ae055f-29d8-5fcc-94c2-28fd9ea85ed2', 'acade111-0000-4000-8000-000000000001', 'FUP-0312', 'acade111-0002-4000-8000-000000000133', '9bbed7be-2325-5a10-a1e6-18e56fb9b071', NULL, NULL, 'Re-opened conversation 11 Nov · send catalogue', '2026-11-14', 'DUE', 'SUGGEST', 'acade111-0001-4000-8000-000000000002', '2026-11-14T10:32:00+08:00', 'AGENT', 'agent_followup', 'Follow-up Agent'),
  ('d247b593-3fa1-5f17-90c2-14f597575d63', 'acade111-0000-4000-8000-000000000001', 'FUP-0314', 'acade111-0002-4000-8000-000000000114', '6482fcbb-845d-58d8-bc2b-925db84371df', NULL, NULL, 'Named on the delivery brief · no PDPA consent recorded', '2026-11-18', 'DUE', 'OBSERVE', 'acade111-0001-4000-8000-000000000002', '2026-11-14T10:32:00+08:00', 'AGENT', 'agent_followup', 'Follow-up Agent'),
  ('7b6e7418-a8b3-50e9-a2a6-81d441534580', 'acade111-0000-4000-8000-000000000001', 'FUP-0316', 'acade111-0002-4000-8000-000000000121', '6cfeb215-c79f-5338-939e-40d7531b4f4f', NULL, NULL, 'Levy statement requested · chase before year end', '2026-11-21', 'DUE', 'SUGGEST', 'acade111-0001-4000-8000-000000000002', '2026-11-14T10:32:00+08:00', 'AGENT', 'agent_followup', 'Follow-up Agent'),
  ('4186938f-5bb3-5b9e-aa2a-94cb3e81f933', 'acade111-0000-4000-8000-000000000001', 'FUP-0318', 'acade111-0002-4000-8000-000000000128', '92b57985-0ea6-5de6-9b09-b1cdd832512f', NULL, NULL, 'December cohort confirmed 06 Nov · send joining instructions', '2026-11-25', 'SENT', 'SUGGEST', 'acade111-0001-4000-8000-000000000002', '2026-11-14T10:32:00+08:00', 'AGENT', 'agent_followup', 'Follow-up Agent'),
  ('b0c1625b-e0cf-5ca5-bdd2-a0eaf5a5777b', 'acade111-0000-4000-8000-000000000001', 'FUP-0320', 'acade111-0002-4000-8000-000000000140', 'f181430e-87dd-5977-9974-48e41ab3ffff', NULL, NULL, 'Safety brief shared 02 Nov · no response needed yet', '2026-12-02', 'DISMISSED', 'OBSERVE', 'acade111-0001-4000-8000-000000000002', '2026-11-14T10:32:00+08:00', 'AGENT', 'agent_followup', 'Follow-up Agent')
ON CONFLICT (tenant_id, ref) DO UPDATE SET
  id = EXCLUDED.id,
  organisation_id = EXCLUDED.organisation_id,
  contact_id = EXCLUDED.contact_id,
  proposal_id = EXCLUDED.proposal_id,
  invoice_id = EXCLUDED.invoice_id,
  reason = EXCLUDED.reason,
  due_date = EXCLUDED.due_date,
  status = EXCLUDED.status,
  autonomy = EXCLUDED.autonomy,
  owner_id = EXCLUDED.owner_id,
  created_by_kind = EXCLUDED.created_by_kind,
  created_by_id = EXCLUDED.created_by_id,
  created_by_name = EXCLUDED.created_by_name
WHERE (target.id, target.organisation_id, target.contact_id, target.proposal_id, target.invoice_id, target.reason, target.due_date, target.status, target.autonomy, target.owner_id, target.created_by_kind, target.created_by_id, target.created_by_name)
   IS DISTINCT FROM (EXCLUDED.id, EXCLUDED.organisation_id, EXCLUDED.contact_id, EXCLUDED.proposal_id, EXCLUDED.invoice_id, EXCLUDED.reason, EXCLUDED.due_date, EXCLUDED.status, EXCLUDED.autonomy, EXCLUDED.owner_id, EXCLUDED.created_by_kind, EXCLUDED.created_by_id, EXCLUDED.created_by_name);

-- Drafted follow-ups, costed at the BSP rate the draft quotes. None has been sent.
INSERT INTO core.outbound_messages AS target
  (id, tenant_id, ref, purpose, channel, template_id, category, contact_id, to_address, follow_up_id, invoice_id, engagement_id, body, status, sent_at, rate_per_message_sen, rate_per_message_exact, estimated_cost_sen, actual_cost_sen, currency, message_rate_id, consent_id, provider_message_id, created_at, created_by_kind, created_by_id, created_by_name)
VALUES
  ('fccbba7c-063b-5b01-8e7b-a901c2cfea51', 'acade111-0000-4000-8000-000000000001', 'MSG-2026-0001', 'FOLLOWUP', 'WHATSAPP', '1a2269f6-0d80-5b3f-b6f5-d2701f86ba40', 'UTILITY', 'eab22cf4-2961-5919-b158-75e055bc6a30', '+60123344551', '00633a2e-2a31-5a60-8513-1e3b6ab1190d', NULL, NULL, 'Hi Puan Nurul, following up on the leadership proposal we sent on 11 September…', 'DRAFT', NULL, 6, '0.0564', 6, NULL, 'MYR', NULL, NULL, NULL, '2026-09-16T08:02:00+08:00', 'AGENT', 'agent_followup', 'Follow-up Agent'),
  ('779025aa-4446-57b0-8de7-1a257ce3d942', 'acade111-0000-4000-8000-000000000001', 'MSG-2026-0002', 'FOLLOWUP', 'EMAIL', 'ba71de36-31c8-5caa-9bc9-3581a668b77c', 'UTILITY', 'eab22cf4-2961-5919-b158-75e055bc6a30', 'nurul.hassan@auroramfg.com.my', '00633a2e-2a31-5a60-8513-1e3b6ab1190d', NULL, NULL, 'Dear Puan Nurul,

Following up on the leadership proposal we sent on 11 September…', 'DRAFT', NULL, 0, NULL, 0, NULL, 'MYR', NULL, NULL, NULL, '2026-09-16T08:02:00+08:00', 'AGENT', 'agent_followup', 'Follow-up Agent'),
  ('ca68a4fa-d951-574e-bea8-aec86e06c49b', 'acade111-0000-4000-8000-000000000001', 'MSG-2026-0003', 'FOLLOWUP', 'EMAIL', 'ba71de36-31c8-5caa-9bc9-3581a668b77c', 'UTILITY', '6cfeb215-c79f-5338-939e-40d7531b4f4f', 'weisheng.lim@kenangaretail.com.my', 'c16da2ab-4baa-5081-a436-bae6afe04890', NULL, NULL, 'Dear Wei Sheng,

Checking in on the discovery call we discussed on 28 October…', 'DRAFT', NULL, 0, NULL, 0, NULL, 'MYR', NULL, NULL, NULL, '2026-11-14T07:40:00+08:00', 'AGENT', 'agent_followup', 'Follow-up Agent')
ON CONFLICT (tenant_id, ref) DO UPDATE SET
  id = EXCLUDED.id,
  purpose = EXCLUDED.purpose,
  channel = EXCLUDED.channel,
  template_id = EXCLUDED.template_id,
  category = EXCLUDED.category,
  contact_id = EXCLUDED.contact_id,
  to_address = EXCLUDED.to_address,
  follow_up_id = EXCLUDED.follow_up_id,
  invoice_id = EXCLUDED.invoice_id,
  engagement_id = EXCLUDED.engagement_id,
  body = EXCLUDED.body,
  status = EXCLUDED.status,
  sent_at = EXCLUDED.sent_at,
  rate_per_message_sen = EXCLUDED.rate_per_message_sen,
  rate_per_message_exact = EXCLUDED.rate_per_message_exact,
  estimated_cost_sen = EXCLUDED.estimated_cost_sen,
  actual_cost_sen = EXCLUDED.actual_cost_sen,
  currency = EXCLUDED.currency,
  message_rate_id = EXCLUDED.message_rate_id,
  consent_id = EXCLUDED.consent_id,
  provider_message_id = EXCLUDED.provider_message_id,
  created_by_kind = EXCLUDED.created_by_kind,
  created_by_id = EXCLUDED.created_by_id,
  created_by_name = EXCLUDED.created_by_name
WHERE (target.id, target.purpose, target.channel, target.template_id, target.category, target.contact_id, target.to_address, target.follow_up_id, target.invoice_id, target.engagement_id, target.body, target.status, target.sent_at, target.rate_per_message_sen, target.rate_per_message_exact, target.estimated_cost_sen, target.actual_cost_sen, target.currency, target.message_rate_id, target.consent_id, target.provider_message_id, target.created_by_kind, target.created_by_id, target.created_by_name)
   IS DISTINCT FROM (EXCLUDED.id, EXCLUDED.purpose, EXCLUDED.channel, EXCLUDED.template_id, EXCLUDED.category, EXCLUDED.contact_id, EXCLUDED.to_address, EXCLUDED.follow_up_id, EXCLUDED.invoice_id, EXCLUDED.engagement_id, EXCLUDED.body, EXCLUDED.status, EXCLUDED.sent_at, EXCLUDED.rate_per_message_sen, EXCLUDED.rate_per_message_exact, EXCLUDED.estimated_cost_sen, EXCLUDED.actual_cost_sen, EXCLUDED.currency, EXCLUDED.message_rate_id, EXCLUDED.consent_id, EXCLUDED.provider_message_id, EXCLUDED.created_by_kind, EXCLUDED.created_by_id, EXCLUDED.created_by_name);
-- Flush the deferred reconciliation checks before touching these tables:
-- ALTER TABLE refuses a table that has pending trigger events. The flush is
-- also where the header-equals-sum-of-lines checks actually run.
SET CONSTRAINTS core.trg_quotation_reconciled, core.trg_quotation_floor, core.trg_invoice_reconciled, core.trg_credit_note_within_invoice IMMEDIATE;
SET CONSTRAINTS core.trg_quotation_reconciled, core.trg_quotation_floor, core.trg_invoice_reconciled, core.trg_credit_note_within_invoice DEFERRED;

-- Gates restored. test_fixture_world.sql asserts this happened.
ALTER TABLE core.enquiries ENABLE TRIGGER enquiries_state_gate;
ALTER TABLE core.opportunities ENABLE TRIGGER opportunities_state_gate;
ALTER TABLE core.tnas ENABLE TRIGGER tnas_state_gate;
ALTER TABLE core.proposals ENABLE TRIGGER proposals_state_gate;
ALTER TABLE core.quotations ENABLE TRIGGER quotations_state_gate;
ALTER TABLE core.quotations ENABLE TRIGGER trg_quotations_freeze_applied;
