import type { Config } from "tailwindcss";
import tailwindcssAnimate from "tailwindcss-animate";

/**
 * Every colour resolves to a CSS custom property defined in
 * `src/styles/tokens.css`. Nothing here carries a literal colour: a theme swap
 * is a token swap and touches no Tailwind config and no component.
 *
 * The `<alpha-value>` placeholder is what makes `bg-ai-tint/60` work, which is
 * why tokens are stored as `R G B` channel triplets rather than hex.
 */
const token = (name: string) => `rgb(var(--${name}) / <alpha-value>)`;

export default {
  darkMode: ["class", '[data-theme="dark"]'],
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "1rem",
      screens: {
        sm: "640px",
        md: "768px",
        lg: "1024px",
        xl: "1280px",
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        sans: ['var(--font-sans, "Inter", system-ui, sans-serif)'],
        mono: ['var(--font-mono, "JetBrains Mono", ui-monospace, monospace)'],
      },
      colors: {
        /* Surfaces */
        canvas: token("canvas"),
        sidebar: token("sidebar"),
        card: {
          DEFAULT: token("card"),
          foreground: token("ink"),
        },
        surface: {
          DEFAULT: token("surface"),
          hover: token("surface-hover"),
        },

        /* Lines */
        border: token("border"),
        divider: token("divider"),
        "border-strong": token("border-strong"),
        connector: token("connector"),

        /* Text */
        ink: {
          DEFAULT: token("ink"),
          secondary: token("ink-secondary"),
          muted: token("ink-muted"),
          disabled: token("ink-disabled"),
        },

        /* The one accent */
        primary: {
          DEFAULT: token("primary"),
          hover: token("primary-hover"),
          border: token("primary-border"),
          // shadcn primitives say `text-primary-foreground`; TrainOS code says
          // `text-on-primary`. Same token, so a CLI-generated primitive is
          // correct with no edit and no second colour enters the repo.
          foreground: token("on-primary"),
        },
        "on-primary": token("on-primary"),

        /* AI surfaces — tint only, never a solid fill */
        "ai-tint": token("ai-tint"),
        "ai-tint-2": token("ai-tint-2"),

        /* Status — chips only */
        success: {
          DEFAULT: token("success"),
          fill: token("success-fill"),
          border: token("success-border"),
        },
        warning: {
          DEFAULT: token("warning"),
          fill: token("warning-fill"),
          border: token("warning-border"),
        },
        danger: {
          DEFAULT: token("danger"),
          fill: token("danger-fill"),
          border: token("danger-border"),
        },
        info: {
          DEFAULT: token("info"),
          fill: token("info-fill"),
          border: token("info-border"),
        },

        /* Identity */
        avatar: token("avatar-surface"),

        /* shadcn/ui aliases onto the SAME tokens — one palette, two vocabularies.
           A shadcn primitive generated by the CLI styles itself correctly with
           no edit, and no second colour system enters the repo. */
        background: token("canvas"),
        foreground: token("ink"),
        input: token("border"),
        ring: token("primary"),
        muted: {
          DEFAULT: token("surface"),
          foreground: token("ink-muted"),
        },
        accent: {
          DEFAULT: token("ai-tint-2"),
          foreground: token("primary-hover"),
        },
        popover: {
          DEFAULT: token("card"),
          foreground: token("ink"),
        },
        destructive: {
          DEFAULT: token("danger"),
          foreground: token("on-primary"),
        },
        secondary: {
          DEFAULT: token("surface"),
          foreground: token("ink-secondary"),
        },
      },
      borderRadius: {
        control: "var(--radius-control)",
        card: "var(--radius-card)",
        "card-lg": "var(--radius-card-lg)",
        modal: "var(--radius-modal)",
        pill: "var(--radius-pill)",
        lg: "var(--radius-card)",
        md: "var(--radius-control)",
        sm: "calc(var(--radius-control) - 4px)",
      },
      boxShadow: {
        card: "var(--shadow-card)",
        raised: "var(--shadow-raised)",
      },
      spacing: {
        sidebar: "var(--shell-sidebar-width)",
        rail: "var(--shell-rail-width)",
        topbar: "var(--shell-topbar-height)",
        inset: "var(--shell-content-inset)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [tailwindcssAnimate],
} satisfies Config;
