import { writeFileSync } from "node:fs";
import { TRANSITIONS } from "../src/server/fsm/transitions";
import { FIN_LABEL, FIN_STAGES, OPS_LABEL, OPS_STAGES } from "../src/server/domain/stages";
import { GUARDED_REASONS } from "../src/server/fsm/guards";

/**
 * Renders docs/STATE_MACHINES.md from the transition table. The document is
 * generated, never hand-edited: the table is the state machine, and a test
 * already pins it to the database copy.
 */
function mermaid(machine: "OPERATIONAL" | "FINANCIAL"): string {
  const edges = TRANSITIONS.filter((t) => t.machine === machine);
  const lines = ["stateDiagram-v2", `  [*] --> ${machine === "OPERATIONAL" ? "DRAFT" : "ESTIMATE"}`];
  const seen = new Set<string>();
  for (const e of edges) {
    const key = `${e.from}->${e.to}`;
    const reasons = edges.filter((x) => x.from === e.from && x.to === e.to).map((x) => x.reason);
    if (seen.has(key)) continue;
    seen.add(key);
    lines.push(`  ${e.from} --> ${e.to}: ${reasons.join(" / ")}`);
  }
  return lines.join("\n");
}

function table(machine: "OPERATIONAL" | "FINANCIAL"): string {
  const rows = TRANSITIONS.filter((t) => t.machine === machine).map(
    (t) => `| \`${t.from}\` | \`${t.to}\` | \`${t.reason}\` | ${t.actors.join(", ")} | ${GUARDED_REASONS.includes(t.reason) ? "yes" : "**missing**"} | ${t.description} |`,
  );
  return ["| From | To | Reason code | Allowed actors | L0 guard | Meaning |", "|---|---|---|---|---|---|", ...rows].join("\n");
}

const doc = `# State machines

> Generated by \`npm run docs:fsm\` from \`src/server/fsm/transitions.ts\`. Do not edit by hand.
> The same table is seeded into \`tpms.fsm_transitions\` and enforced by the \`packages_before_update\`
> trigger on every UPDATE; \`tests/integration/fsm-parity.test.ts\` asserts the two copies are equal.

No transition accepts an \`AGENT\` actor: agents propose (drafts, quotations, decisions); a named
\`USER\` or the \`SYSTEM\` rule engine moves a package. Every move writes a SHA-256 hash-chained row to
\`tpms.audit_ledger\` with the actor, the reason code and a field-level diff.

## Operational lifecycle

Stages: ${OPS_STAGES.map((s) => `\`${s}\` (${OPS_LABEL[s]})`).join(", ")}.

\`\`\`mermaid
${mermaid("OPERATIONAL")}
\`\`\`

${table("OPERATIONAL")}

## Financial & claim lifecycle

Stages: ${FIN_STAGES.map((s) => `\`${s}\` (${FIN_LABEL[s]})`).join(", ")}.

\`\`\`mermaid
${mermaid("FINANCIAL")}
\`\`\`

${table("FINANCIAL")}

## Coupling between the machines

| When the operational machine enters | The financial machine | Reactions enqueued (same transaction) |
|---|---|---|
| \`QUOTED\` | — | \`commercial.dispatch_quotation\` |
| \`GRANT_PENDING\` (client accepted) | \`ESTIMATE → GRANT_RESERVED\` | \`grant.compile_dossier\` |
| \`GRANT_APPROVED\` | — | \`viability.t14_check\` due at start − 14 days (MYT) |
| \`READY_FOR_EVENT\` | — | \`delivery.issue_magic_links\`, \`delivery.start\` at 07:00 on day 1 |
| \`DELIVERY_COMPLETED\` | \`GRANT_RESERVED / UPFRONT_CLAIM_SUBMITTED → CLAIM_NOT_READY\` | \`certificates.issue\`, \`retention.schedule\` |
| \`CANCELLED\` | \`→ VOIDED\` (if not yet claimed) | — |

| When the financial machine enters | Reactions |
|---|---|
| \`CLAIM_NOT_READY\` | \`claims.collate\` (verifies evidence, drafts the invoice, compiles the claim pack) |
| \`REMITTED\` | \`finance.draft_payment_vouchers\` (pay-when-paid: PVs cannot be PAID before this stage) |
`;

writeFileSync("docs/STATE_MACHINES.md", doc);
console.log(`docs/STATE_MACHINES.md written (${TRANSITIONS.length} transitions)`);
