/**
 * The contract every seed slice implements.
 *
 * One slice is one emitted `.sql` file. Slices are ordered, and the order is
 * the foreign-key order: a slice may reference anything an earlier slice wrote
 * and nothing a later one will.
 */

export interface Slice {
  /** Emitted file name, without a directory. */
  readonly file: string;
  /** One line for the file's own header and for the runner's table of contents. */
  readonly title: string;
  /**
   * Every table this slice writes, in the order it writes them. The wipe file
   * is generated by walking all slices' tables in reverse, so a table missing
   * here is a table the wipe will leave behind.
   */
  readonly tables: readonly string[];
  /**
   * Triggers suspended for the duration of this file, as `schema.table:trigger`.
   *
   * The state gates (`app.enforce_state_transition`) are the reason this exists.
   * A gate admits exactly one status on INSERT — `core.state_transitions` holds
   * a `(new) -> OPEN`-shaped edge per entity — and every later status is
   * reachable only by an UPDATE that an `EXECUTING`/`EXECUTED`
   * `core.action_requests` row targeting that exact row authorises. A fixture
   * world whose engagements are DELIVERED and whose invoices are PAID cannot be
   * expressed through that door without inventing hundreds of action requests
   * that are not part of the fixture world and would themselves be wrong.
   *
   * So the seed suspends the gates, writes the terminal states directly, and
   * restores them in the same file. It never suspends a foreign key, a CHECK,
   * or the recalculation triggers that derive invoice and quotation totals from
   * their lines — those stay live, and the seed is a real test of them.
   * `supabase/seeds/test_fixture_world.sql` asserts every trigger in `core`,
   * `app` and `public` is enabled again when the seed finishes.
   */
  readonly suspendTriggers?: readonly string[];
  /** The statements, already formatted. */
  emit(): string;
}

/**
 * The four DEFERRABLE INITIALLY DEFERRED constraint triggers in the schema.
 *
 * They are the reason the restore block is not just a list of ALTERs. Writing a
 * quotation or an invoice queues their events until COMMIT, and
 * `ALTER TABLE … ENABLE TRIGGER` on a table with pending trigger events fails
 * outright: `cannot ALTER TABLE "invoices" because it has pending trigger
 * events`. Flushing them to IMMEDIATE runs the checks — which is what proves the
 * headers reconcile against their lines — and putting them straight back to
 * DEFERRED leaves the transaction as the next slice expects to find it, since a
 * later slice writes its own header before its own lines.
 *
 * Named rather than `ALL`, because `SET CONSTRAINTS ALL DEFERRED` would also
 * defer every DEFERRABLE INITIALLY IMMEDIATE constraint, which is a different
 * promise from the one being restored.
 */
const DEFERRED_CONSTRAINTS = [
  "core.trg_quotation_reconciled",
  "core.trg_quotation_floor",
  "core.trg_invoice_reconciled",
  "core.trg_credit_note_within_invoice",
].join(", ");

export const suspendSql = (triggers: readonly string[], mode: "DISABLE" | "ENABLE"): string => {
  if (triggers.length === 0) return "";
  const lines = triggers.map((entry) => {
    const [table, trigger] = entry.split(":");
    if (!table || !trigger) throw new Error(`bad trigger spec: ${entry}`);
    return `ALTER TABLE ${table} ${mode} TRIGGER ${trigger};`;
  });

  if (mode === "DISABLE") {
    return `-- Suspend the gates for this load; restored at the foot of this file.\n${lines.join("\n")}`;
  }

  return [
    "-- Flush the deferred reconciliation checks before touching these tables:",
    "-- ALTER TABLE refuses a table that has pending trigger events. The flush is",
    "-- also where the header-equals-sum-of-lines checks actually run.",
    `SET CONSTRAINTS ${DEFERRED_CONSTRAINTS} IMMEDIATE;`,
    `SET CONSTRAINTS ${DEFERRED_CONSTRAINTS} DEFERRED;`,
    "",
    "-- Gates restored. test_fixture_world.sql asserts this happened.",
    ...lines,
  ].join("\n");
};
