/**
 * Emits `supabase/seeds/fixture_world*.sql` from `@trainos/fixtures`.
 *
 *     npm run seed:emit -w packages/fixtures
 *
 * The emitted SQL is committed alongside this script and is what a human runs.
 * The generator exists so the 136 participants, the 78 certificates and the
 * 14-day usage series stay in step with the fixture world rather than drifting
 * from a transcription of it; CI re-runs this and fails if the committed SQL
 * differs (`--check`).
 */

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import * as fx from "../src/data/index.ts";
import { ANCHORS, NAMESPACE, TENANT_UUID, uuidFor } from "./lib/ids.ts";
import { suspendSql, type Slice } from "./lib/slice.ts";
import { agentPrincipalKey, slice01, TENANT_SLUG } from "./slices/01-tenant-and-parties.ts";
import { slice02 } from "./slices/02-sales-and-money.ts";
import { slice03 } from "./slices/03-delivery-compliance-finance.ts";
import { slice04 } from "./slices/04-ai-ops-and-agents.ts";

const HERE = dirname(fileURLToPath(import.meta.url));
const SEEDS_DIR = resolve(HERE, "../../../supabase/seeds");
const WIPE = "fixture_world_wipe.sql";

const SLICES: readonly Slice[] = [slice01, slice02, slice03, slice04];

/**
 * The run command.
 *
 * Four files, one transaction, no runner. There is no `fixture_world.sql` that
 * `\\ir`s the parts, because `npm run lint:sql` parses everything under
 * `supabase/seeds/` through the real Postgres grammar and a psql meta-command is
 * a syntax error to it — which is the whole point of that gate. A file in this
 * tree is a claim that it runs; `\\i` and `\\set` make that claim false for
 * everything except psql.
 *
 * `-1` wraps all four in one transaction, which is what the deferred
 * reconciliation checks and the cross-slice foreign keys need.
 */
const SEED_FILES = [
  "fixture_world_01_tenant_and_parties.sql",
  "fixture_world_02_sales_and_money.sql",
  "fixture_world_03_delivery_compliance_finance.sql",
  "fixture_world_04_ai_ops_and_agents.sql",
] as const;

const RUN_COMMAND = [
  'psql "$DATABASE_URL" -1 -v ON_ERROR_STOP=1 \\',
  ...SEED_FILES.map(
    (name, index) =>
      `  -f supabase/seeds/${name}${index === SEED_FILES.length - 1 ? "" : " \\"}`,
  ),
];

const GENERATED_BY =
  "Generated by packages/fixtures/scripts/emit-seed.ts — edit the fixtures or the\n" +
  "-- generator, never this file. Regenerate with:\n" +
  "--   npx tsx packages/fixtures/scripts/emit-seed.ts\n" +
  "-- and `--check` fails if the committed SQL and the fixtures have drifted apart.";

/**
 * The shared header. Every emitted file carries it, because a reviewer opening
 * one part should not have to find another to learn what tenant it lands in or
 * how it is meant to be run.
 */
const header = (title: string, extra: string[] = []): string =>
  [
    `-- ${title}`,
    "--",
    `-- Tenant: ${TENANT_SLUG} (Akademi Perdana Sdn Bhd), id ${TENANT_UUID}`,
    "--",
    "-- Run (all four parts, one transaction, from the repo root):",
    ...RUN_COMMAND.map((line) => `--   ${line}`),
    "--",
    "-- Targets migrations 001-017 (and 018 when it merges). It provisions through",
    "-- 016's own seeders, so it does NOT run against a database at 013 or earlier.",
    "--",
    "-- Idempotent: every statement is an upsert guarded by an IS DISTINCT FROM",
    "-- comparison, so a second run of an unchanged seed performs zero updates and",
    "-- leaves every updated_at where it was. Iterating a fixture never needs a wipe.",
    "--",
    ...extra.flatMap((line) => (line === "" ? ["--"] : [`-- ${line}`])),
    ...(extra.length ? ["--"] : []),
    `-- ${GENERATED_BY}`,
    "",
  ].join("\n");

const anchorTable = (): string[] => {
  const width = Math.max(...Object.keys(ANCHORS).map((k) => k.length));
  return [
    "Fixed ids. Anchors are hand-picked and carry a version-4 nibble; every other",
    "row's id is UUIDv5 over its fixture key in namespace",
    `${NAMESPACE}, and carries a version-5 nibble.`,
    "",
    ...Object.entries(ANCHORS).map(([key, value]) => `  ${key.padEnd(width)}  ${value}`),
  ];
};

const PART_OF = [
  "One of the four parts of the TrainOS fixture world. The parts are in",
  "foreign-key order and must be run in order:",
  "",
  ...SEED_FILES.map((name, index) => `  ${index + 1}. ${name}`),
  "",
  "Companion files:",
  `  ${WIPE}         removes every row the four parts write, tenant included`,
  "  test_fixture_world.sql         the pin: counts, landmarks, re-run stability",
];

const sliceFile = (slice: Slice, index: number): string => {
  const suspend = slice.suspendTriggers ?? [];
  const extra = index === 0 ? [...PART_OF, "", ...anchorTable()] : PART_OF;
  return [
    header(`TrainOS fixture world, part ${index + 1} — ${slice.title}`, extra),
    suspend.length ? `${suspendSql(suspend, "DISABLE")}\n` : "",
    slice.emit(),
    "",
    suspend.length ? `${suspendSql(suspend, "ENABLE")}\n` : "",
  ]
    .filter(Boolean)
    .join("\n");
};

/**
 * The wipe.
 *
 * Every table any slice writes, in exactly the reverse of the order they were
 * written, scoped to the one tenant. The state gates and the append-only guards
 * refuse deletes as readily as they refuse writes, so the wipe suspends the same
 * triggers the slices do, plus the append-only ones that only a delete trips.
 */
const DELETE_ONLY_TRIGGERS: readonly string[] = [
  "core.events:events_append_only",
  "app.key_access_audit:key_access_audit_append_only",
  "core.payments:trg_a_payments_immutable",
  "core.attendance_entries:trg_attendance_entries_lock",
  "core.proposal_sections:trg_proposal_sections_freeze",
];

/**
 * Every `auth.users` id the seed writes: the seven humans, and one service
 * principal per agent. Derived from the same fixtures and the same key function
 * slice 1 derives them from, so the wipe cannot fall behind the seed.
 */
const seededAuthUserIds = (): string[] => [
  ...fx.users.map((user) => uuidFor(user.id)),
  ...fx.agents.map((agent) => uuidFor(agentPrincipalKey(agent.id))),
];

/**
 * Back-pointers the wipe has to cut before it can delete anything.
 *
 * `core.action_requests` and `core.approval_requests` reference each other:
 * an action names the approval it is waiting on, and the approval names the
 * action it will run. `approval_request_id` is the nullable half, so there is
 * no delete order that satisfies both — reverse dependency order or any other.
 * Cutting the nullable side first turns the cycle into a chain.
 */
const UNLINK_BEFORE_DELETE: readonly [table: string, column: string][] = [
  ["core.action_requests", "approval_request_id"],
];

const wipeFile = (): string => {
  const tables: string[] = [];
  for (const slice of SLICES) tables.push(...slice.tables);
  const ordered = [...new Set(tables)].reverse();
  const suspend = [
    ...new Set([...SLICES.flatMap((s) => s.suspendTriggers ?? []), ...DELETE_ONLY_TRIGGERS]),
  ];

  const deletes = ordered.map((table) => {
    if (table === "public.tenants") return `DELETE FROM public.tenants WHERE id = '${TENANT_UUID}';`;
    if (table === "auth.users")
      return [
        "-- The seven humans and the eight agent principals, by id.",
        "DELETE FROM auth.users WHERE id IN (",
        seededAuthUserIds()
          .map((id, index, all) => `  '${id}'${index === all.length - 1 ? "" : ","}`)
          .join("\n"),
        ");",
      ].join("\n");
    return `DELETE FROM ${table} WHERE tenant_id = '${TENANT_UUID}';`;
  });

  return [
    header("Wipe the TrainOS fixture world", [
      "Removes every row the four fixture_world parts write, in reverse dependency",
      "order, for the one tenant. Reset, not rollback: re-running the seed afterwards",
      "rebuilds the world from scratch with the same ids.",
      "",
      "Normal iteration does NOT need this. The seed upserts; wipe only when you want",
      "to prove the seed builds from nothing, or to hand the database back empty.",
      "",
      "Run:",
      `  psql "$DATABASE_URL" -1 -v ON_ERROR_STOP=1 -f supabase/seeds/${WIPE}`,
    ]),
    suspendSql(suspend, "DISABLE"),
    "",
    "-- Cut the mutual references first; see UNLINK_BEFORE_DELETE in the generator.",
    UNLINK_BEFORE_DELETE.map(
      ([table, column]) =>
        `UPDATE ${table} SET ${column} = NULL\n WHERE tenant_id = '${TENANT_UUID}' AND ${column} IS NOT NULL;`,
    ).join("\n"),
    "",
    deletes.join("\n"),
    "",
    suspendSql(suspend, "ENABLE"),
    "",
  ].join("\n");
};

const files = (): Record<string, string> => {
  const out: Record<string, string> = { [WIPE]: wipeFile() };
  SLICES.forEach((slice, index) => {
    out[slice.file] = sliceFile(slice, index);
  });
  return out;
};

const main = (): void => {
  const check = process.argv.includes("--check");
  // `--only <substring>` writes just the matching files. Only useful while
  // authoring one slice; CI and the committed output always emit the full set.
  const onlyFlag = process.argv.indexOf("--only");
  const only = onlyFlag === -1 ? null : process.argv[onlyFlag + 1];

  mkdirSync(SEEDS_DIR, { recursive: true });
  const emitted = files();
  let drifted = 0;

  for (const [name, content] of Object.entries(emitted)) {
    if (only && !name.includes(only)) continue;
    const path = join(SEEDS_DIR, name);
    if (check) {
      let current = "";
      try {
        current = readFileSync(path, "utf8");
      } catch {
        current = "";
      }
      if (current !== content) {
        drifted += 1;
        console.error(`drift: ${name} differs from what the fixtures emit`);
      }
      continue;
    }
    writeFileSync(path, content, "utf8");
    console.log(`${name}  ${content.split("\n").length} lines`);
  }

  if (check) {
    if (drifted > 0) {
      console.error(`\n${drifted} file(s) out of date. Run: npm run seed:emit -w packages/fixtures`);
      process.exit(1);
    }
    console.log("seeds match the fixtures");
  }
};

main();
