-- ============================================================================
-- Migration 003: enum types — the closed catalogues the API contract froze,
-- generated FROM the contract package so the two cannot disagree.
-- ============================================================================
--
-- FEATURE. Doc 01's Conventions section makes a deliberate split:
--
--   Closed catalogues (§12 and §17 of the contract) become native Postgres
--   enums. They are frozen by the contract, so the cost of ALTER TYPE never
--   arrives; they generate real union types in Supabase's TypeScript output,
--   which is the entire point of having a contract package; and they are four
--   bytes on disk in a model with a great many status columns.
--
--   Open, config-driven sets become `text` with a foreign key to a reference
--   table. Never `text + CHECK`. The project rule is that stage names and order
--   render from configuration, never hardcoded — a CHECK constraint is code, a
--   reference table is data: editable by an admin screen, joinable for labels
--   and ordering, and still enforced by an FK. Those sets are `action_type`,
--   the lifecycle step key, the compliance check key, `hrdc_document_type`,
--   the metric key, the tier key, the template type and the TNA constraint code.
--   They arrive in 004 as tables, not here as types.
--
-- WHY THIS IS GENERATED AND NOT TRANSCRIBED
--
-- Sixty-nine types and roughly two hundred and eighty values. Transcribing that
-- by hand produces a typo in a value nobody notices until a row will not insert
-- in staging, and the failure is silent at authoring time because a misspelt
-- enum label is perfectly valid SQL. Sixty-two of the sixty-nine are therefore
-- generated by reading `packages/contract/src/enums.ts` and emitting one
-- CREATE TYPE per `as const` array, so the database and the TypeScript contract
-- are the same list by construction rather than by review. Each carries a
-- COMMENT naming the exact constant it came from, so the provenance survives
-- into `psql \dT+`.
--
-- The remaining seven are named by doc 01 with inline values but are absent
-- from the package. They are listed separately below, each with the doc section
-- it came from, and they are the ones to re-check when the package catches up.
-- ⚠ `travel_region` is the weakest: doc 01 names the type but gives no values,
-- so the three below are taken from DECISIONS §5's rate-card travel bands
-- (Klang Valley / peninsular / East Malaysia). Flagged in the report.
--
-- ⚠ CONFLICT C3, resolved. Doc 03 §1 states its own convention: "check
-- constraints in place of enum types so that adding a value is a migration on
-- one line rather than a type rewrite", and writes every `app.*` gate table
-- that way. Doc 01 makes the opposite choice, with reasons, for the domain.
-- These are not in conflict: each document is describing the tables it owns.
-- The gate tables in 011 use `text` + CHECK exactly as doc 03 writes them; the
-- domain tables use these enums. The asymmetry is deliberate and is recorded
-- here so a later reader does not "unify" it in one direction and break the
-- other lane's stated design.
--
-- ⚠ `app_role` and `actor_kind` are NOT created here. Doc 02 §1.2 creates them
-- in `app`, and doc 02 outranks doc 01 on identity. A domain column typed
-- `actor_kind` therefore uses `app.actor_kind`. Recorded as conflict C2.
--
-- SPINE: none touched. Types only; no table, no function, no policy.
--
-- ── AUTHORIZATION ─────────────────────────────────────────────────────────
--   Types are not privileged objects. USAGE on a type is granted to PUBLIC by
--   default and there is nothing sensitive in a label. What matters is that
--   `core` itself is reachable, which 001 arranged, and that PUBLIC holds no
--   CREATE there, which 001 also arranged and test_001 T4b asserts.
--
-- ── THE 7-POINT RPC CONTRACT CHECK, worked ───────────────────────────────
--   1. Envelope: no RPC. 2. Unwrap: no jsonb crosses the boundary.
--   3. RpcMap: none — but this migration is the one place the SQL side and
--      `packages/contract/src/enums.ts` MUST stay in lockstep, and it is
--      generated from that file precisely so they do. test_003 re-derives the
--      comparison at run time rather than trusting the generation.
--   4. Call sites: every domain table in 004-013 types a column with one of
--      these. Zero today is expected.
--   5. Casts: none. 6. Reload/restore: no behaviour. 7. Public routes: none.
--
-- ⚠ OPERATIONAL NOTE THAT OUTLIVES THIS MIGRATION. A Postgres enum value can be
-- ADDED (`ALTER TYPE ... ADD VALUE`) but not removed or reordered, and before
-- PostgreSQL 12 ADD VALUE could not run inside a transaction at all. Adding a
-- value is therefore cheap and removing one is a table rewrite. That asymmetry
-- is the reason only CLOSED catalogues are enums: if a set is going to lose a
-- member, it should have been a reference table.
--
-- Rollback: rollbacks/003_enum_types_rollback.sql
-- ============================================================================

BEGIN;

SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '120s';

-- ─── Enums generated from packages/contract/src/enums.ts ───────────────────

DO $$ BEGIN
  CREATE TYPE core.absence_reason AS ENUM ('MEDICAL_LEAVE', 'WORK_CONFLICT', 'NO_SHOW', 'OTHER');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
COMMENT ON TYPE core.absence_reason IS 'Generated from packages/contract/src/enums.ts :: ABSENCE_REASONS (4 values).';

DO $$ BEGIN
  CREATE TYPE core.action_status AS ENUM ('EXECUTED', 'QUEUED_FOR_APPROVAL', 'SUGGESTED', 'REJECTED');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
COMMENT ON TYPE core.action_status IS 'Generated from packages/contract/src/enums.ts :: ACTION_STATUSES (4 values).';

DO $$ BEGIN
  CREATE TYPE core.agent_status AS ENUM ('ACTIVE', 'PAUSED', 'RETIRED');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
COMMENT ON TYPE core.agent_status IS 'Generated from packages/contract/src/enums.ts :: AGENT_STATUSES (3 values).';

DO $$ BEGIN
  CREATE TYPE core.ai_provider AS ENUM ('ANTHROPIC', 'GOOGLE', 'OPENAI', 'DEEPSEEK');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
COMMENT ON TYPE core.ai_provider IS 'Generated from packages/contract/src/enums.ts :: AI_PROVIDERS (4 values).';

DO $$ BEGIN
  CREATE TYPE core.approval_decision AS ENUM ('APPROVE', 'REQUEST_CHANGES', 'REJECT');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
COMMENT ON TYPE core.approval_decision IS 'Generated from packages/contract/src/enums.ts :: APPROVAL_DECISIONS (3 values).';

DO $$ BEGIN
  CREATE TYPE core.approval_status AS ENUM ('PENDING', 'APPROVED', 'CHANGES_REQUESTED', 'REJECTED', 'EXPIRED');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
COMMENT ON TYPE core.approval_status IS 'Generated from packages/contract/src/enums.ts :: APPROVAL_STATUSES (5 values).';

DO $$ BEGIN
  CREATE TYPE core.attendance_status AS ENUM ('OPEN', 'PENDING_APPROVAL', 'LOCKED');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
COMMENT ON TYPE core.attendance_status IS 'Generated from packages/contract/src/enums.ts :: ATTENDANCE_STATUSES (3 values).';

DO $$ BEGIN
  CREATE TYPE core.autonomy_level AS ENUM ('OBSERVE', 'SUGGEST', 'ACT_WITH_APPROVAL', 'AUTONOMOUS');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
COMMENT ON TYPE core.autonomy_level IS 'Generated from packages/contract/src/enums.ts :: AUTONOMY_LEVELS (4 values).';

DO $$ BEGIN
  CREATE TYPE core.badge_severity AS ENUM ('DEFAULT', 'ALERT');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
COMMENT ON TYPE core.badge_severity IS 'Generated from packages/contract/src/enums.ts :: BADGE_SEVERITIES (2 values).';

DO $$ BEGIN
  CREATE TYPE core.billing_owner AS ENUM ('CLIENT_ACCOUNT', 'PASS_THROUGH');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
COMMENT ON TYPE core.billing_owner IS 'Generated from packages/contract/src/enums.ts :: BILLING_OWNERS (2 values).';

DO $$ BEGIN
  CREATE TYPE core.budget_scope AS ENUM ('TIER', 'AGENT', 'ACTION_TYPE');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
COMMENT ON TYPE core.budget_scope IS 'Generated from packages/contract/src/enums.ts :: BUDGET_SCOPES (3 values).';

DO $$ BEGIN
  CREATE TYPE core.budget_state AS ENUM ('WITHIN', 'NEAR', 'PAUSED');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
COMMENT ON TYPE core.budget_state IS 'Generated from packages/contract/src/enums.ts :: BUDGET_STATES (3 values).';

DO $$ BEGIN
  CREATE TYPE core.cache_strategy AS ENUM ('NONE', 'PROMPT_15M', 'PROMPT_1H', 'PROMPT_24H', 'CONTEXT_1H');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
COMMENT ON TYPE core.cache_strategy IS 'Generated from packages/contract/src/enums.ts :: CACHE_STRATEGIES (5 values).';

DO $$ BEGIN
  CREATE TYPE core.capture_method AS ENUM ('QR', 'SIGNATURE', 'MANUAL');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
COMMENT ON TYPE core.capture_method IS 'Generated from packages/contract/src/enums.ts :: CAPTURE_METHODS (3 values).';

DO $$ BEGIN
  CREATE TYPE core.check_state AS ENUM ('PASS', 'WARN', 'FAIL', 'NOT_APPLICABLE');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
COMMENT ON TYPE core.check_state IS 'Generated from packages/contract/src/enums.ts :: CHECK_STATES (4 values).';

DO $$ BEGIN
  CREATE TYPE core.collection_stage AS ENUM ('REMINDER_1', 'REMINDER_2', 'REMINDER_3', 'HUMAN_CALL', 'TRADING_HOLD');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
COMMENT ON TYPE core.collection_stage IS 'Generated from packages/contract/src/enums.ts :: COLLECTION_STAGES (5 values).';

DO $$ BEGIN
  CREATE TYPE core.delta_direction AS ENUM ('UP', 'DOWN', 'FLAT');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
COMMENT ON TYPE core.delta_direction IS 'Generated from packages/contract/src/enums.ts :: DELTA_DIRECTIONS (3 values).';

DO $$ BEGIN
  CREATE TYPE core.diff_op AS ENUM ('ADD', 'UPDATE', 'REMOVE');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
COMMENT ON TYPE core.diff_op IS 'Generated from packages/contract/src/enums.ts :: DIFF_OPS (3 values).';

DO $$ BEGIN
  CREATE TYPE core.document_presence AS ENUM ('PRESENT', 'MISSING');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
COMMENT ON TYPE core.document_presence IS 'Generated from packages/contract/src/enums.ts :: DOCUMENT_PRESENCE (2 values).';

DO $$ BEGIN
  CREATE TYPE core.embedding_status AS ENUM ('INDEXED', 'PENDING', 'FAILED');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
COMMENT ON TYPE core.embedding_status IS 'Generated from packages/contract/src/enums.ts :: EMBEDDING_STATUSES (3 values).';

DO $$ BEGIN
  CREATE TYPE core.engagement_status AS ENUM ('PROPOSED', 'CONFIRMED', 'SCHEDULED', 'IN_DELIVERY', 'DELIVERED', 'CLOSED', 'CANCELLED');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
COMMENT ON TYPE core.engagement_status IS 'Generated from packages/contract/src/enums.ts :: ENGAGEMENT_STATUSES (7 values).';

DO $$ BEGIN
  CREATE TYPE core.enquiry_channel AS ENUM ('EMAIL', 'WHATSAPP', 'WEB_FORM', 'PHONE');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
COMMENT ON TYPE core.enquiry_channel IS 'Generated from packages/contract/src/enums.ts :: ENQUIRY_CHANNELS (4 values).';

DO $$ BEGIN
  CREATE TYPE core.enquiry_status AS ENUM ('OPEN', 'ASSIGNED', 'CONVERTED', 'ARCHIVED', 'NOT_AN_ENQUIRY');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
COMMENT ON TYPE core.enquiry_status IS 'Generated from packages/contract/src/enums.ts :: ENQUIRY_STATUSES (5 values).';

DO $$ BEGIN
  CREATE TYPE core.evidence_type AS ENUM ('EMAIL', 'TNA', 'PROGRAMME', 'TRAINER', 'TRAINER_AVAILABILITY', 'QUOTATION', 'QUESTIONNAIRE', 'HISTORY', 'CATALOGUE', 'HRDC_STATEMENT', 'PARTICIPANT_QUERY', 'ORGANISATION', 'CONTACT', 'INVOICE', 'PROPOSAL', 'ACTION');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
COMMENT ON TYPE core.evidence_type IS 'Generated from packages/contract/src/enums.ts :: EVIDENCE_TYPES (16 values).';

DO $$ BEGIN
  CREATE TYPE core.filter_op AS ENUM ('eq', 'in', 'gte', 'lte', 'contains', 'between');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
COMMENT ON TYPE core.filter_op IS 'Generated from packages/contract/src/enums.ts :: FILTER_OPS (6 values).';

DO $$ BEGIN
  CREATE TYPE core.filter_source AS ENUM ('REQUEST', 'VIEW');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
COMMENT ON TYPE core.filter_source IS 'Generated from packages/contract/src/enums.ts :: FILTER_SOURCES (2 values).';

DO $$ BEGIN
  CREATE TYPE core.gap_priority AS ENUM ('HIGH', 'MEDIUM', 'LOW');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
COMMENT ON TYPE core.gap_priority IS 'Generated from packages/contract/src/enums.ts :: GAP_PRIORITIES (3 values).';

DO $$ BEGIN
  CREATE TYPE core.hours_saved_basis AS ENUM ('MEASURED', 'ILLUSTRATIVE');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
COMMENT ON TYPE core.hours_saved_basis IS 'Generated from packages/contract/src/enums.ts :: HOURS_SAVED_BASES (2 values).';

DO $$ BEGIN
  CREATE TYPE core.hrdc_packet_panel_state AS ENUM ('ON_TRACK', 'DEADLINE_AT_RISK', 'BLOCKED', 'SUBMITTED');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
COMMENT ON TYPE core.hrdc_packet_panel_state IS 'Generated from packages/contract/src/enums.ts :: HRDC_PACKET_PANEL_STATES (4 values).';

DO $$ BEGIN
  CREATE TYPE core.hrdc_scheme AS ENUM ('SBL_KHAS', 'SBL', 'HRDC_PLACEMENT');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
COMMENT ON TYPE core.hrdc_scheme IS 'Generated from packages/contract/src/enums.ts :: HRDC_SCHEMES (3 values).';

DO $$ BEGIN
  CREATE TYPE core.invoice_status AS ENUM ('DRAFT', 'SENT', 'PARTIALLY_PAID', 'PAID', 'OVERDUE', 'VOID');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
COMMENT ON TYPE core.invoice_status IS 'Generated from packages/contract/src/enums.ts :: INVOICE_STATUSES (6 values).';

DO $$ BEGIN
  CREATE TYPE core.jury_mode AS ENUM ('GATE', 'SAMPLE', 'ESCALATE');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
COMMENT ON TYPE core.jury_mode IS 'Generated from packages/contract/src/enums.ts :: JURY_MODES (3 values).';

DO $$ BEGIN
  CREATE TYPE core.knowledge_source_type AS ENUM ('HRDC_CIRCULAR');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
COMMENT ON TYPE core.knowledge_source_type IS 'Generated from packages/contract/src/enums.ts :: KNOWLEDGE_SOURCE_TYPES (1 values).';

DO $$ BEGIN
  CREATE TYPE core.lifecycle_state AS ENUM ('DONE', 'CURRENT', 'PENDING', 'BLOCKED', 'SKIPPED', 'FAILED');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
COMMENT ON TYPE core.lifecycle_state IS 'Generated from packages/contract/src/enums.ts :: LIFECYCLE_STATES (6 values).';

DO $$ BEGIN
  CREATE TYPE core.message_category AS ENUM ('MARKETING', 'UTILITY', 'SERVICE');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
COMMENT ON TYPE core.message_category IS 'Generated from packages/contract/src/enums.ts :: MESSAGE_CATEGORIES (3 values).';

DO $$ BEGIN
  CREATE TYPE core.monitor_status AS ENUM ('WATCHING', 'CHANGED_REVIEW_PENDING', 'FAILED', 'MANUAL');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
COMMENT ON TYPE core.monitor_status IS 'Generated from packages/contract/src/enums.ts :: MONITOR_STATUSES (4 values).';

DO $$ BEGIN
  CREATE TYPE core.opportunity_stage AS ENUM ('NEW', 'QUALIFYING', 'TNA_SENT', 'PROPOSAL_SENT', 'NEGOTIATION', 'WON', 'LOST');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
COMMENT ON TYPE core.opportunity_stage IS 'Generated from packages/contract/src/enums.ts :: OPPORTUNITY_STAGES (7 values).';

DO $$ BEGIN
  CREATE TYPE core.organisation_match_reason AS ENUM ('EXACT_DOMAIN', 'FUZZY_NAME', 'MANUAL');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
COMMENT ON TYPE core.organisation_match_reason IS 'Generated from packages/contract/src/enums.ts :: ORGANISATION_MATCH_REASONS (3 values).';

DO $$ BEGIN
  CREATE TYPE core.organisation_status AS ENUM ('PROSPECT', 'ACTIVE_CLIENT', 'DORMANT');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
COMMENT ON TYPE core.organisation_status IS 'Generated from packages/contract/src/enums.ts :: ORGANISATION_STATUSES (3 values).';

DO $$ BEGIN
  CREATE TYPE core.packet_status AS ENUM ('DRAFT', 'READY', 'SUBMITTED', 'PAID', 'REJECTED');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
COMMENT ON TYPE core.packet_status IS 'Generated from packages/contract/src/enums.ts :: PACKET_STATUSES (5 values).';

DO $$ BEGIN
  CREATE TYPE core.proposal_status AS ENUM ('DRAFT', 'AWAITING_APPROVAL', 'SENT', 'VIEWED', 'ACCEPTED', 'LOST');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
COMMENT ON TYPE core.proposal_status IS 'Generated from packages/contract/src/enums.ts :: PROPOSAL_STATUSES (6 values).';

DO $$ BEGIN
  CREATE TYPE core.provenance_origin AS ENUM ('HUMAN', 'SYSTEM', 'AI_SUGGESTED', 'AI_GENERATED', 'AI_EXECUTED');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
COMMENT ON TYPE core.provenance_origin IS 'Generated from packages/contract/src/enums.ts :: PROVENANCE_ORIGINS (5 values).';

DO $$ BEGIN
  CREATE TYPE core.provider_key_status AS ENUM ('NOT_SET', 'VALID', 'INVALID', 'EXPIRING');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
COMMENT ON TYPE core.provider_key_status IS 'Generated from packages/contract/src/enums.ts :: PROVIDER_KEY_STATUSES (4 values).';

DO $$ BEGIN
  CREATE TYPE core.retrieval_scope AS ENUM ('COMPLIANCE', 'CLIENT_FACING');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
COMMENT ON TYPE core.retrieval_scope IS 'Generated from packages/contract/src/enums.ts :: RETRIEVAL_SCOPES (2 values).';

DO $$ BEGIN
  CREATE TYPE core.risk_level AS ENUM ('LOW', 'MEDIUM', 'HIGH');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
COMMENT ON TYPE core.risk_level IS 'Generated from packages/contract/src/enums.ts :: RISK_LEVELS (3 values).';

DO $$ BEGIN
  CREATE TYPE core.routing_strategy AS ENUM ('THROUGHPUT', 'PRICE', 'FIXED');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
COMMENT ON TYPE core.routing_strategy IS 'Generated from packages/contract/src/enums.ts :: ROUTING_STRATEGIES (3 values).';

DO $$ BEGIN
  CREATE TYPE core.rule_change_op AS ENUM ('ADD', 'MODIFY', 'SUPERSEDE');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
COMMENT ON TYPE core.rule_change_op IS 'Generated from packages/contract/src/enums.ts :: RULE_CHANGE_OPS (3 values).';

DO $$ BEGIN
  CREATE TYPE core.rule_resolution_basis AS ENUM ('GRANT_SUBMITTED', 'CLAIM_SUBMITTED');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
COMMENT ON TYPE core.rule_resolution_basis IS 'Generated from packages/contract/src/enums.ts :: RULE_RESOLUTION_BASES (2 values).';

DO $$ BEGIN
  CREATE TYPE core.rule_status AS ENUM ('PROPOSED', 'ACTIVE', 'SUPERSEDED');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
COMMENT ON TYPE core.rule_status IS 'Generated from packages/contract/src/enums.ts :: RULE_STATUSES (3 values).';

DO $$ BEGIN
  CREATE TYPE core.run_event_type AS ENUM ('ESCALATION', 'JURY', 'TRUNCATION', 'HANDOFF', 'CHECKPOINT', 'POLICY_HALT', 'CACHE_HIT', 'BUDGET_EXCEEDED');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
COMMENT ON TYPE core.run_event_type IS 'Generated from packages/contract/src/enums.ts :: RUN_EVENT_TYPES (8 values).';

DO $$ BEGIN
  CREATE TYPE core.run_status AS ENUM ('RUNNING', 'SUCCEEDED', 'FAILED', 'HALTED');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
COMMENT ON TYPE core.run_status IS 'Generated from packages/contract/src/enums.ts :: RUN_STATUSES (4 values).';

DO $$ BEGIN
  CREATE TYPE core.run_step_status AS ENUM ('OK', 'RETRIED', 'FAILED', 'HALTED');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
COMMENT ON TYPE core.run_step_status IS 'Generated from packages/contract/src/enums.ts :: RUN_STEP_STATUSES (4 values).';

DO $$ BEGIN
  CREATE TYPE core.saved_view_object AS ENUM ('LEAD', 'ENQUIRY', 'APPROVAL');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
COMMENT ON TYPE core.saved_view_object IS 'Generated from packages/contract/src/enums.ts :: SAVED_VIEW_OBJECTS (3 values).';

DO $$ BEGIN
  CREATE TYPE core.severity AS ENUM ('INFO', 'WARN', 'DANGER', 'ALERT');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
COMMENT ON TYPE core.severity IS 'Generated from packages/contract/src/enums.ts :: SEVERITIES (4 values).';

DO $$ BEGIN
  CREATE TYPE core.sync_state AS ENUM ('NOT_SENT', 'SENT', 'VALIDATED', 'ERROR');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
COMMENT ON TYPE core.sync_state IS 'Generated from packages/contract/src/enums.ts :: SYNC_STATES (4 values).';

DO $$ BEGIN
  CREATE TYPE core.template_type AS ENUM ('PROPOSAL', 'QUOTATION', 'CERTIFICATE', 'EMAIL', 'WHATSAPP', 'INVOICE', 'TNA_QUESTIONNAIRE', 'EVALUATION', 'HRDC_PACKET');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
COMMENT ON TYPE core.template_type IS 'Generated from packages/contract/src/enums.ts :: TEMPLATE_TYPES (9 values).';

DO $$ BEGIN
  CREATE TYPE core.theme AS ENUM ('LIGHT', 'DARK', 'SYSTEM');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
COMMENT ON TYPE core.theme IS 'Generated from packages/contract/src/enums.ts :: THEMES (3 values).';

DO $$ BEGIN
  CREATE TYPE core.tier_status AS ENUM ('HEALTHY', 'DEGRADED', 'PAUSED_BY_CAP', 'DISABLED');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
COMMENT ON TYPE core.tier_status IS 'Generated from packages/contract/src/enums.ts :: TIER_STATUSES (4 values).';

DO $$ BEGIN
  CREATE TYPE core.tna_status AS ENUM ('DRAFT', 'SENT', 'COMPLETE', 'REOPENED');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
COMMENT ON TYPE core.tna_status IS 'Generated from packages/contract/src/enums.ts :: TNA_STATUSES (4 values).';

DO $$ BEGIN
  CREATE TYPE core.trace_node_kind AS ENUM ('ORCHESTRATOR', 'SUB_AGENT', 'TOOL');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
COMMENT ON TYPE core.trace_node_kind IS 'Generated from packages/contract/src/enums.ts :: TRACE_NODE_KINDS (3 values).';

DO $$ BEGIN
  CREATE TYPE core.urgency_group AS ENUM ('BREACHING', 'TODAY', 'THIS_WEEK', 'LATER');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
COMMENT ON TYPE core.urgency_group IS 'Generated from packages/contract/src/enums.ts :: URGENCY_GROUPS (4 values).';

DO $$ BEGIN
  CREATE TYPE core.usage_group_by AS ENUM ('TIER', 'AGENT', 'ACTION_TYPE');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
COMMENT ON TYPE core.usage_group_by IS 'Generated from packages/contract/src/enums.ts :: USAGE_GROUP_BY (3 values).';

-- ─── Enums the contract package does not carry ─────────────────────────────

DO $$ BEGIN
  CREATE TYPE core.attendance_half AS ENUM ('AM', 'PM');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
COMMENT ON TYPE core.attendance_half IS 'Not in the contract package. Source: doc 01 §3.2 attendance_entries.half.';

DO $$ BEGIN
  CREATE TYPE core.booking_state AS ENUM ('SOFT_HOLD', 'CONFIRMED', 'RELEASED', 'CANCELLED');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
COMMENT ON TYPE core.booking_state IS 'Not in the contract package. Source: doc 01 §3.2 trainer_bookings.state.';

DO $$ BEGIN
  CREATE TYPE core.follow_up_status AS ENUM ('DUE', 'OVERDUE', 'SENT', 'DISMISSED');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
COMMENT ON TYPE core.follow_up_status IS 'Not in the contract package. Source: doc 01 §3.1 follow_ups.status.';

DO $$ BEGIN
  CREATE TYPE core.trainer_band AS ENUM ('A', 'B', 'C');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
COMMENT ON TYPE core.trainer_band IS 'Not in the contract package. Source: doc 01 §3.2 trainers.band, DECISIONS §5.';

DO $$ BEGIN
  CREATE TYPE core.travel_region AS ENUM ('KLANG_VALLEY', 'PENINSULAR', 'EAST_MALAYSIA');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
COMMENT ON TYPE core.travel_region IS 'Not in the contract package. Source: doc 01 §Conventions; values from DECISIONS §5 rate-card travel bands.';

DO $$ BEGIN
  CREATE TYPE core.venue_mode AS ENUM ('CLIENT_SITE', 'OWN_VENUE', 'EXTERNAL');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
COMMENT ON TYPE core.venue_mode IS 'Not in the contract package. Source: doc 01 §3.2 engagements.venue_mode, DECISIONS §5.';

DO $$ BEGIN
  CREATE TYPE core.view_visibility AS ENUM ('PRIVATE', 'TEAM', 'TENANT');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
COMMENT ON TYPE core.view_visibility IS 'Not in the contract package. Source: doc 01 §4.4 / doc 02 §4.4 saved_views.visibility.';

-- ─── Verify ─────────────────────────────────────────────────────────────────

DO $verify$
DECLARE
  v_types  int;
  v_labels int;
  v_bad    text;
BEGIN
  SELECT count(*) INTO v_types
  FROM pg_catalog.pg_type t
  JOIN pg_catalog.pg_namespace n ON n.oid = t.typnamespace
  WHERE n.nspname = 'core' AND t.typtype = 'e';
  IF v_types <> 69 THEN
    RAISE EXCEPTION '003 verify: expected 69 enum types in core, found %', v_types;
  END IF;

  SELECT count(*) INTO v_labels
  FROM pg_catalog.pg_enum e
  JOIN pg_catalog.pg_type t ON t.oid = e.enumtypid
  JOIN pg_catalog.pg_namespace n ON n.oid = t.typnamespace
  WHERE n.nspname = 'core';
  IF v_labels < 200 THEN
    RAISE EXCEPTION '003 verify: only % enum labels in core; expected ~280', v_labels;
  END IF;

  -- Every type carries the COMMENT that records where its values came from. An
  -- uncommented type is one somebody added by hand, which is exactly the case
  -- this migration exists to prevent.
  SELECT string_agg(t.typname, ', ') INTO v_bad
  FROM pg_catalog.pg_type t
  JOIN pg_catalog.pg_namespace n ON n.oid = t.typnamespace
  WHERE n.nspname = 'core' AND t.typtype = 'e'
    AND obj_description(t.oid, 'pg_type') IS NULL;
  IF v_bad IS NOT NULL THEN
    RAISE EXCEPTION '003 verify: enum type(s) with no provenance comment: %', v_bad;
  END IF;

  -- The two identity types must NOT have been duplicated into core. Two
  -- `actor_kind` types, one in app and one in core, is the divergence that ends
  -- with a column typed against the wrong one and a cast that silently works.
  IF EXISTS (
    SELECT 1 FROM pg_catalog.pg_type t
    JOIN pg_catalog.pg_namespace n ON n.oid = t.typnamespace
    WHERE n.nspname = 'core' AND t.typname IN ('actor_kind','app_role')
  ) THEN
    RAISE EXCEPTION
      '003 verify: actor_kind or app_role was created in core. Doc 02 owns both '
      'and creates them in app; a second copy is a silent mistyping waiting to happen.';
  END IF;

  RAISE NOTICE '003 verify: OK - % enum types, % labels, all commented.', v_types, v_labels;
END;
$verify$;

COMMIT;
